src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Exclude_from_Auto_Invoicing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If you do not want an invoice or credit note automatically created for this Account check this box</description>
        <inlineHelpText>If you do not want an invoice or credit note automatically created for this Account check this box</inlineHelpText>
        <label>Exclude from Auto Invoicing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Available_For_Invoice__c</fullName>
        <description>If latest Invoice in Blank or latest invoice is populated but credited the opp can be invoiced</description>
        <formula>IF( 
   OR(
       ISBLANK(Latest_Invoice__c),
       Latest_Invoice__r.Is_Credited_In_Full__c = true,
       AND(
           TEXT(Latest_Invoice__r.c2g__InvoiceStatus__c) = &apos;Discarded&apos;,
           TEXT( Latest_Invoice__r.c2g__InvoiceStatus__c) &lt;&gt; &apos;In Progress&apos;,
           TEXT( Latest_Invoice__r.c2g__InvoiceStatus__c) &lt;&gt; &apos;Complete&apos;
       )
   ),
   TRUE, 
   FALSE
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available For Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_from_Auto_Invoicing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Exclude this Opportunity from being processed using Auto Invoicing</description>
        <label>Exclude from Auto Invoicing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Finance_to_Invoice_Opp__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used to identify if opp needs to be invoiced or not. This is used in combination with the invoice date to inform the &quot;Invoice Status&quot; field.</inlineHelpText>
        <label>Finance to Invoice Opp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The company on which this opportunity will be invoiced.</inlineHelpText>
        <label>Invoice Company</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not an active company.</errorMessage>
            <filterItems>
                <field>c2g__codaCompany__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>c2g__codaCompany__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <formula>IF( Finance_Written_Off__c = True, &apos;Written Off&apos;,
   IF( Finance_to_Credit_Opp__c = True, &apos;To Be Credited&apos;,
      IF( 
         OR( 
            AND(Finance_to_Invoice_Opp__c = True,  ISBLANK(Date_to_be_Invoiced__c)) , 
            AND(Finance_to_Invoice_Opp__c = True,  Date_to_be_Invoiced__c &lt;=  TODAY())
         ),&apos;To Be Invoiced&apos;,
         
         IF( AND(CreatedBy.Alias = &apos;Website&apos;, !ISBLANK(Latest_Invoice__r.Website_Order_Id__c)), &apos;N/A&apos;,
            IF( Using_one_to_one_invoicing__c = &apos;Yes&apos;,
               

               IF( AND(Latest_Invoice__r.Is_Credited_In_Full__c = True,!ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)) ,&apos;Credited&apos;,
                  IF( AND( Latest_Invoice__r.c2g__OutstandingValue__c = 0, !ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)) , &apos;Paid&apos;,
                     IF( AND(Latest_Invoice__r.c2g__OutstandingValue__c &gt; 0, Latest_Invoice__r.c2g__OutstandingValue__c &lt; Latest_Invoice__r.c2g__InvoiceTotal__c, !ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)), &apos;Part Paid&apos;,
                        IF(  AND(Latest_Invoice__r.c2g__OutstandingValue__c =  Latest_Invoice__r.c2g__InvoiceTotal__c, !ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)), &apos;Invoiced&apos;,
                           &apos;No Action&apos;
                        )
                     )
                  )
               )



            ,&apos;N/A&apos;
            )
         ) 
      )
   )
)</formula>
        <inlineHelpText>Determines the current status of the opportunity based on the one to one invoicing model.</inlineHelpText>
        <label>Invoice Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_C_Price_Variation_Products__c</fullName>
        <label>T/C Price Variation Products</label>
        <summaryFilterItems>
            <field>OpportunityLineItem.T_C_Price_Variation__c</field>
            <operation>equals</operation>
            <value>TRUE</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>T_C_Variation_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>T/C Variation Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Using_one_to_one_invoicing__c</fullName>
        <formula>IF( 
   AND(
      CreatedDate &gt;= $Setup.Feature_Settings__c.One_to_One_Invoicing_Start_Date__c, 
      Use_part_invoicing__c = False
   ),
   &apos;Yes&apos;,
   &apos;No&apos;
)</formula>
        <label>Using one to one invoicing</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_Order_Id__c</fullName>
        <description>The unique identifier for the order in the website this may not be unique within Salesforce as an order on the website may match multiple orders in Salesforce.</description>
        <inlineHelpText>The unique identifier for the order in the website this may not be unique within Salesforce as an order on the website may match multiple orders in Salesforce.</inlineHelpText>
        <label>Website Order Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Subscription</fullName>
        <active>true</active>
        <businessProcess>BSC Sales Process</businessProcess>
        <description>Opportunity for Membership and other Subscription Product Sales</description>
        <label>Subscription</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AutoInvoiceBatch.cls
/*

VS : This batch is called from AutoInvoiceSchedule
     On start of the batch, check is done for the invCompany(in constructor) is passed from AutoInvoiceSchedule and AutoInvCreditMatchBatch. 
     If the invCompany is Complywise Ltd
        for the scheduled user we change the current FF company to Complywise using  AutoSwitchFFCompany.switchFFCompany(userinfo.getUserId(), 'FF British Safety Council');
     
     the oppId in the constructor is only used for test purpose.
     
     Only 10 invoices are generated based on the query (if the oppId is not passed). 

     calls AutoInvoiceHelper.bulkCreateInvoiceFromOpps to bulk generate invoices.
     
     if invoices are created calls the AutoGenerateFinancialTransactions to generate financial lines for reporting purposes
     else calls the credit notes batch (AutoCreditBatch)
     
*/

global class AutoInvoiceBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    id opportunityId; 
 
    global string invoiceCompany;
    global set<id> invoices;
    
    global AutoInvoiceBatch(id oppId, string invCompany){
        opportunityId = oppId;
        invoiceCompany = invCompany;
    }
    
    public class invoiceException extends Exception{}
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        system.debug('auto Invoice Batch Started');
        
        datetime oppsLastModified = datetime.now();
        
        if (invoiceCompany == 'Complywise Ltd')
            AutoSwitchFFCompany.switchFFCompany(userinfo.getUserId(), 'FF British Safety Council');
        
        if (AutoInvoiceSettings.autoInvoiceDelay > 0)
            oppsLastModified = oppsLastModified.addHours(AutoInvoiceSettings.autoInvoiceDelay * -1);
         
        system.debug('finding opps that were modified before ' + oppsLastModified);
        
        if (opportunityId == null)
            return Database.getQueryLocator([Select o.Id, 
                                                    LastModifiedDate, 
                                                    (select id from c2g__Invoices__r where is_credited_in_full__c=false and c2g__InvoiceStatus__c in ('Complete','InProgress') order by lastmodifieddate desc),
                                                    T_C_Variation_Approved__c,
                                                    T_C_Price_Variation_Products__c,
                                                    StageName,
                                                    Owner.Email
                                               From Opportunity o 
                                              where Finance_to_Invoice_Opp__c = true
                                                and StageName = 'Booking Received'
                                                and Invoice_Status__c = 'To Be Invoiced'    
                                                and Type not in ('Subscription Renewal')  
                                                and Using_one_to_one_invoicing__c = 'Yes' 
                                                and Amount > 0
                                                and Available_For_Invoice__c = true
                                                and Exclude_from_Auto_Invoicing__c = false
                                                and Website_Order_Id__c = null 
                                                and Invoice_Company__r.Name = :invoiceCompany
                                                and lastmodifieddate < :oppsLastModified
                                              limit 10]);
        //and Account.billingCountry in ('United Kingdom','England' ,'Wales' , 'Northern Ireland' , 'Scotland' , 'UK') 
        else
            return Database.getQueryLocator([Select o.Id, 
                                                    LastModifiedDate, 
                                                    (select id from c2g__Invoices__r order by lastmodifieddate desc) ,
                                                    T_C_Variation_Approved__c,
                                                    T_C_Price_Variation_Products__c,
                                                    StageName,
                                                    Owner.Email
                                               From Opportunity o 
                                              where Finance_to_Invoice_Opp__c = true
                                                and Website_Order_Id__c = null
                                                and id = :opportunityId 
                                              limit 1]);            
        
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        list<string> info = new list<string>();
        info.add(AutoInvoiceSettings.emailNotificationTo);
        
        
        list<Id> oppIds = new List<id>();
        list<Opportunity> oppToUpdate = new list<opportunity>();
        
        for (opportunity opp : (list<Opportunity>)scope){
            oppIds.add(opp.id);
        }

        try{
            AutoInvoiceHelper.sendMail('Started Invoice Generation', 'Opps to be invoiced: ' + scope , info);
            list<Id> invs = AutoInvoiceHelper.bulkCreateInvoiceFromOpps(oppIds, AutoInvoiceSettings.autoPostInvoices, invoiceCompany);
            invoices = new set<id>(invs);
            
            system.debug('Opps to be invoiced: ' + oppIds); 
            update oppToUpdate;
            
            AutoInvoiceHelper.sendMail('Finished Invoice Generation', 'Invoices created: ' + string.valueof(invs), info);
        } catch(Exception e) {
            AutoInvoiceHelper.sendMail('AI Invoice Generation Error', e.getMessage() + ' ' + e.getCause() + ' ' + e.getStackTraceString(), info);
            //throw new invoiceException(e.getMessage());
        }
        
        
    }
    
    global void finish(Database.BatchableContext BC){
        system.debug('invoices: ' + invoices);
        
        if (invoices == null || invoices.Size() == 0){
            system.debug('executing credit note batch for BSC..');
            AutoCreditBatch acb = new AutoCreditBatch(null, invoiceCompany);
            database.executeBatch(acb);
        } else {
            AutoGenerateFinancialTransactions aft = new AutoGenerateFinancialTransactions(invoices, invoiceCompany);
            database.executeBatch(aft,1);
        }
    }
}