src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the Account is Active or Inactive i.e. does the Organisation exist.</description>
        <inlineHelpText>Indicates whether the Account is Active or Inactive i.e. does the Organisation exist.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>c2g__CODADimension4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dimension 4</label>
        <referenceTo>c2g__codaDimension4__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Audit</fullName>
        <active>true</active>
        <businessProcess>BSC Sales Process</businessProcess>
        <description>Opportunity to manage sale of an Audit</description>
        <label>Audit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Length__c</fullName>
        <description>The length of a Product in Days where that product has a duration</description>
        <inlineHelpText>Default Length in Days</inlineHelpText>
        <label>Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Dimension_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is for finance and pulls in the event reference</description>
        <inlineHelpText>This is for finance and pulls in the event reference</inlineHelpText>
        <label>Dimension 4</label>
        <referenceTo>c2g__codaDimension4__c</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date when Special Event ends.</description>
        <inlineHelpText>Date when Special Event ends.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Shows the stage of the event, which is a dependant pick list of the status field</description>
        <inlineHelpText>Shows the stage of the event, which is a dependant pick list of the status field</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when Special Event starts.</description>
        <inlineHelpText>Date when Special Event starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Determines the type of event from a picklist</description>
        <inlineHelpText>Determine the type of event from the picklist</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NVQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <recordTypes>
        <fullName>Audit</fullName>
        <active>true</active>
        <description>Audit or Advisory Session</description>
        <label>Audit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related to the original account booking the event booking.</description>
        <inlineHelpText>Related to the original account booking the event booking</inlineHelpText>
        <label>Booking Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>R00N50000001mIaxEAE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Defines the event booking type whether primary or additional etc</description>
        <inlineHelpText>Defines the event booking type whether primary or additional etc</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional - On the Day</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestBscEvent.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestBscEvent {

	private static Account account;
	private static Opportunity opportunity;
	
	static void InsertAccount()
	{
		account = new Account(
			name = 'testAcount');
		insert account;
		
		System.debug('** inserted account: ' + account.Id);
	}
	
	static void InsertOpportunity()
	{
		opportunity = new Opportunity(
			Name = 'testOpportunity',
			AccountId = account.Id,
			StageName = 'Qualifying',
			CloseDate = Date.today());
		insert opportunity;
		
		System.debug('** inserted opp: ' + opportunity.Id);
	}

    static testMethod void testNewProduct() {
        InsertAccount();
        InsertOpportunity();
        
		// Create a product for the Event.
		Product2 product = new Product2(
			name = 'GHI');
		insert product;        
        
        Special_Event_Booking__c[] bookings = new Special_Event_Booking__c[3];
		
		for (Integer i = 0; i < 3; i++)
		{
			Special_Event__c specialEvent = new Special_Event__c(
				Opportunity__c = opportunity.Id,
				Name = 'Test Event',
				product__c = product.id,
				Type__c = 'In-Company Training',
				Status__c = 'Anything but Confirmed',
				Stage__c = 'Anything but Provisional',
				StartDate__c = Date.today(),
				EndDate__c = Date.today().addDays(5));

			insert specialEvent;

			c2g__codaDimension4__c dim4 = new c2g__codaDimension4__c();
			try
			{
			   dim4 = [Select d.id, d.name From c2g__codaDimension4__c d Where d.name = :specialEvent.Name][0];
			}
			catch(Exception e)
			{
				system.debug('Cannnot locate the dimension record');
			}
			System.assertEquals(specialEvent.Dimension_4__r.Name, dim4.id);
		}
    }
    
    static testMethod void testExistingProduct() {
        InsertAccount();
        InsertOpportunity();
 		RecordType recType = [Select r.Id From RecordType r where r.sObjectType = 'Special_Event__c' and r.name = 'In-Company Event' and isactive=true][0];
		// Test with an existing product
		// Creating a Special Event Booking
		// Update the status of the event to Confirmed to see if the 
		// Special Event Booking are updated accordingly
		Product2 productExist = [Select p.ProductCode, p.Name, p.Length__c, p.Id 
		                    From Product2 p
                            where length__c = 1
                            limit 1 ][0];
		
        CurrencyType curr = [Select id, isocode From CurrencyType][0];
		Special_Event__c specialEvent = new Special_Event__c(
			Opportunity__c = opportunity.Id,
			Name = 'Test Event',
			product__c = productExist.id,
			//Type__c = 'In-Company Training',
			RecordTypeId = recType.Id,
			Status__c = 'Allocating',
			Stage__c = 'Provisional',
			StartDate__c = Date.today(),
			EndDate__c = Date.today().addDays(5),
			CurrencyIsoCode = curr.isocode);
	
		insert specialEvent;

		c2g__codaDimension4__c dim4 = new c2g__codaDimension4__c();
		try
		{
			 dim4 = [Select d.id, d.name From c2g__codaDimension4__c d Where d.name = :specialEvent.Name][0];
		}
		catch(Exception e)
		{
			system.debug('Cannnot locate the dimension record');
		}
		System.assertEquals(specialEvent.Dimension_4__r.Name, dim4.id);
		//Account acc = [Select id From Account Where active__c = true][0];
		Account acc = new Account(
			Name = 'Test Account XXX',
			active__c = true
			);
				
		Special_Event_Booking__c specialEventBooking = new Special_Event_Booking__c(
		company__c=acc.Id, opportunity__c=opportunity.Id, status__c='Provisional',
		currencyisocode=curr.isocode,special_event__c=specialEvent.Id);
		test.startTest();
		insert specialEventBooking;
		test.stopTest();
		
		// Now update the Event status to confirmed to fire the after update trigger
		// Test when Status changes to Confirmed
		specialEvent.Status__c = 'Confirmed';
		specialEvent.Stage__c = 'Confirmed';
		update specialEvent;
		
		// The after update trigger should have fired
		List<Special_Event_Booking__c> seb = [Select id, status__c
		from Special_Event_Booking__c where id = :specialEventBooking.id];
		for (Special_Event_Booking__c se:seb)
		{
			System.assertEquals('Confirmed', se.status__c);
		}
				
		// Test when Status changes to Allocating
		specialEvent.Status__c = 'Allocating';
		specialEvent.Stage__c = 'Provisional';
		update specialEvent;
		// The after update trigger should have fired
		List<Special_Event_Booking__c> seb1 = [Select id, status__c
		from Special_Event_Booking__c where id = :specialEventBooking.id];
		for (Special_Event_Booking__c s: seb1)
		{
			System.assertEquals('Provisional', s.status__c);	
		}
		
    }
    
    static testMethod void testAuditOutcome() {
        InsertAccount();
        InsertOpportunity();
 		RecordType recType = [Select r.Id From RecordType r where r.sObjectType = 'Special_Event__c' and r.name = 'Audit' and isactive=true][0];
		// Test with an existing product
		// Creating a Special Event Booking
		// Update the status of the event to Confirmed to see if the 
		// Special Event Booking are updated accordingly
		Product2 productExist = [Select p.ProductCode, p.Name, p.Length__c, p.Id 
		                    From Product2 p
                            where length__c = 1
                            limit 1 ][0];
		
        CurrencyType curr = [Select id, isocode From CurrencyType][0];
		Special_Event__c specialEvent = new Special_Event__c(
			Opportunity__c = opportunity.Id,
			Name = 'Test Event 1',
			product__c = productExist.id,
			Type__c = 'Audit',
			RecordTypeId = recType.Id,
			Status__c = 'Allocating',
			Stage__c = 'Provisional',
			StartDate__c = Date.today(),
			EndDate__c = Date.today().addDays(5),
			CurrencyIsoCode = curr.isocode);
	
		insert specialEvent;

		c2g__codaDimension4__c dim4 = new c2g__codaDimension4__c();
		try
		{
			 dim4 = [Select d.id, d.name From c2g__codaDimension4__c d Where d.name = :specialEvent.Name][0];
		}
		catch(Exception e)
		{
			system.debug('Cannnot locate the dimension record');
		}
		// Test to see if the trigger has fired properly
		System.assertEquals(specialEvent.Dimension_4__r.Name, dim4.id);
		//Account acc = [Select id From Account Where active__c = true][0];
		Account acc = new Account(
			Name = 'Test Account XXX',
			active__c = true
			);
		
		Special_Event_Booking__c specialEventBooking = new Special_Event_Booking__c(
		company__c=acc.Id, opportunity__c=opportunity.Id, status__c='Provisional',
		currencyisocode=curr.isocode,special_event__c=specialEvent.Id);
		test.startTest();
		insert specialEventBooking;
		test.stopTest();
		
		// Now update the Event status to confirmed to fire the after update trigger
		// Test when Status changes to Confirmed
		specialEvent.Status__c = 'Confirmed';
		specialEvent.Stage__c = 'Confirmed';
		update specialEvent;
		
		// The after update trigger should have fired
		List<Special_Event_Booking__c> seb = [Select id, status__c
		from Special_Event_Booking__c where id = :specialEventBooking.id];
		for (Special_Event_Booking__c se:seb)
		{
			// Checking whether the trigger has fired properly
			System.assertEquals('Confirmed', se.status__c);
		}
				
		// Test when Status changes to Allocating
		specialEvent.Status__c = 'Allocating';
		specialEvent.Stage__c = 'Provisional';
		update specialEvent;
		// The after update trigger should have fired
		List<Special_Event_Booking__c> seb1 = [Select id, status__c
		from Special_Event_Booking__c where id = :specialEventBooking.id];
		for (Special_Event_Booking__c s: seb1)
		{
			// Checking whether the trigger has fired properly
			System.assertEquals('Provisional', s.status__c);	
		}
		
    }    
}