src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employees_Group__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Employees (Group)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Employees__c</fullName>
        <inlineHelpText>Number of employees in this and child accounts (updates automatically)</inlineHelpText>
        <label>Hierarchy Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Trigger_Flags__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Trigger Status Flags, globally disables trigger methods</description>
    <fields>
        <fullName>Account_Assignment_Deactivated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Deactivates account assignment triggers when checked.</description>
        <inlineHelpText>Deactivates account assignment triggers when checked.</inlineHelpText>
        <label>Account Assignment Deactivated</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Trigger Flags</label>
</CustomObject>

src/objects/Area__c.object
<CustomObject>
    <description>Object to associate Accounts with Territories</description>
    <label>Area</label>
    <nameField>
        <displayFormat>AREA-{0000000}</displayFormat>
        <label>Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BatchUpdateAccountArea.cls
global class BatchUpdateAccountArea implements Database.Batchable<sObject>
// Case 0001359 and Case 0001254
// New Class to Update Area on Account object
{
    global final String Query;
    public List<Integer> maxLevel = new List<Integer>();
    public static boolean isTest = false;
    
    global BatchUpdateAccountArea(Integer size)
    {
        if (isTest)
            Query = 'SELECT Id, Hierarchy_Employees__c, ParentId, NumberOfEmployees FROM Account WHERE ParentId != null LIMIT ' + size;
        else
        {
            // Query = 'SELECT Id, Hierarchy_Employees__c, ParentId, NumberOfEmployees FROM Account order by name' + ' LIMIT ' + size;
            Query = 'SELECT Id, Hierarchy_Employees__c, ParentId, NumberOfEmployees FROM Account order by name';
        }
            
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Account> scope)
    {
        System.debug('Disabling AccountReAssignment');
        //ApexCodePatrol.disable('AccountReAssignment');
        Account_Trigger_Flags__c settingsTrig =Account_Trigger_Flags__c.getInstance('Deactivated');
        if (Test.isRunningTest() == false){
            settingsTrig.Account_Assignment_Deactivated__c = true;
            update settingsTrig;
        }
        
        List<Account> accArea = new List<Account>();
        // System.Debug('*********************batchAccounts:'+batchAccounts.size());
        for (Account a: scope)
        {
            System.Debug('*********************batchAccounts Account:'+a);
            Account accUpdate =new Account(id=a.Id, Area__c=null);
            // Case 1359 and 1254
            if (a.parentId == null&&( (a.Hierarchy_Employees__c==null&&a.NumberOfEmployees!=null)||(a.Hierarchy_Employees__c<>a.NumberOfEmployees)))
            {
                System.Debug('*********************batchAccounts Updating employees Hierarchy:'+a.NumberOfEmployees);
                accUpdate.Hierarchy_Employees__c = a.NumberOfEmployees;
                accUpdate.Employees_Group__c = accUpdate.Hierarchy_Employees__c;
            }
        
            accArea.add(accUpdate);
        }
        update accArea;

        set<id>accountIds = new set<id>();
        for(Account a : scope)
        {
            /*Boolean result;
            result = accountIds.contains(a.Id);
            if (!result)
            {
                try
                {*/
                    accountIds.add(a.Id);
                /*}
                catch (exception e)
                {
                    continue;
                }
            }*/                    
        }
        if(accountIds.size() > 0){
            AccountAssignmentHelper.calculateOwnersBatch(accountIds);
        }
        System.debug('Enabling AccountReAssignment');
        //ApexCodePatrol.enable('AccountReAssignment');
        if (Test.isRunningTest() == false){
            settingsTrig.Account_Assignment_Deactivated__c = false;
            update settingsTrig;    
        }
    }
    
    
    global void finish(Database.BatchableContext BC)
    {
        AsyncApexJob a = [
            SELECT
                Id,
                Status,
                NumberOfErrors,
                JobItemsProcessed,
                TotalJobItems,
                CreatedBy.Email
            FROM
                AsyncApexJob
            WHERE
                Id = : BC.getJobId()];
                
        String message = 'The batch Apex job processed ' + a.TotalJobItems + ' batches with '+
            a.NumberOfErrors + ' failures.';
        
        // Send an email to the Apex job's submitter notifying of job completion.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        // Email the current user regarding the completion of the process
        user getCurrentUser = [Select u.email from user u where u.id = :UserInfo.getUserId()];
        // system.debug(getCurrentUser.email);
        // String[] toAddresses = new String[] {a.CreatedBy.Email, getCurrentUser.email};
        String[] toAddresses = new String[] {a.CreatedBy.Email, 'it.helpdesk@britsafe.org'};
        mail.setToAddresses(toAddresses);
        mail.setSubject('BatchUpdateAccountArea ' + a.Status);
        mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems + ' batches with '+ a.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
    public static testMethod void tests()
    {
        Account ultParentAcc = new Account (
            Name = 'Ultimate Parent Acc',
            Phone = '000001'
            );
        insert ultParentAcc;
        
        Account acc = new Account (
            Name = 'Test Acc',
            Phone = '00000',
            ParentId = ultParentAcc.Id
            );
        insert acc;
        
        Account acc1 = new Account (
            Name = 'Test Acc test',
            Phone = '00003420',
            ParentId = ultParentAcc.Id
            );
        insert acc1;
        
        
        Test.startTest();
        BatchUpdateAccountArea.isTest = true;
        BatchUpdateAccountArea batch = new BatchUpdateAccountArea(1);       
        Database.executeBatch(batch, 100);
        Test.stopTest();
    }  
}