src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Venue__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Can this Account be used as a venue?</description>
        <inlineHelpText>Can this Account be used as a venue?</inlineHelpText>
        <label>Venue?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Number_of_Delegates__c</fullName>
        <description>Copied from Lead - the number of delegates the customers wishes to book on the course</description>
        <inlineHelpText>Copied from Lead - the number of delegates the customers wishes to book on the course</inlineHelpText>
        <label>Number of Delegates</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Audit</fullName>
        <active>true</active>
        <businessProcess>BSC Sales Process</businessProcess>
        <description>Opportunity to manage sale of an Audit</description>
        <label>Audit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>In_Company_Number_of_Days__c</fullName>
        <inlineHelpText>Number of Days</inlineHelpText>
        <label>In Co: No. of Days</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Delegates__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of Delegates for In-Company Courses</description>
        <inlineHelpText>In-Company Training Courses Only</inlineHelpText>
        <label>IC Training: No. of Delegates</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Event_Record_Type__c</fullName>
        <label>Event Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>No_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When a product has no timed event this should be true, in order to pull the products through on the booking form.</description>
        <label>No Event</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Latest_Start_Date__c</fullName>
        <description>Field populated when provisional events are created from the opportunity</description>
        <inlineHelpText>Field populated when provisional events are created from the opportunity and is selected when using the request event wizard on the opportunity</inlineHelpText>
        <label>Latest Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when Special Event starts.</description>
        <inlineHelpText>Date when Special Event starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transferred_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populates automatically with the originating Event when an In-Company Event / Audit is transferred</description>
        <inlineHelpText>Populates automatically with the originating Event when an In-Company Event / Audit is transferred</inlineHelpText>
        <label>Transferred From</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>Originating Events</relationshipLabel>
        <relationshipName>BSC_Events1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Determines the type of event from a picklist</description>
        <inlineHelpText>Determine the type of event from the picklist</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NVQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Venue in which the event is being held</description>
        <inlineHelpText>Select the event venue. For an In-company event held on company premises, select the account</inlineHelpText>
        <label>Venue</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Venue</value>
            </filterItems>
            <infoMessage>Search is limited to venues. Select &quot;Show all results&quot; to expand search to all organisations (for In-Company Events)</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events (Held in this Venue)</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <recordTypes>
        <fullName>Audit</fullName>
        <active>true</active>
        <description>Audit or Advisory Session</description>
        <label>Audit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Event_Type__c</fullName>
        <formula>Special_Event__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transferred_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be populated with the previous field if a booking is transferred</description>
        <inlineHelpText>This field will be populated with the previous field if a booking is transferred</inlineHelpText>
        <label>Transferred From</label>
        <referenceTo>Special_Event_Booking__c</referenceTo>
        <relationshipLabel>Previous Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Defines the event booking type whether primary or additional etc</description>
        <inlineHelpText>Defines the event booking type whether primary or additional etc</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional - On the Day</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit__c.object
<CustomObject>
    <description>Object to manage Units of an event, e.g. sessions or components</description>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>Related event</description>
        <inlineHelpText>Related event</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Units</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the Unit venue (if different from the Event venue)</description>
        <inlineHelpText>Select the Unit venue (if different from the Event venue)</inlineHelpText>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Units (Held in this Venue)</relationshipLabel>
        <relationshipName>BSC_Event_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Unit</label>
    <nameField>
        <label>Event Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Event Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event Unit (Session or component)</description>
    <fields>
        <fullName>Event_Booking__c</fullName>
        <description>Lookup to the related event booking</description>
        <inlineHelpText>Lookup to the related event booking</inlineHelpText>
        <label>Event Booking</label>
        <referenceTo>Special_Event_Booking__c</referenceTo>
        <relationshipLabel>BSC Event Unit Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Unit_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related event unit</description>
        <inlineHelpText>Lookup to the related event unit</inlineHelpText>
        <label>Event Unit</label>
        <referenceTo>Special_Event_Unit__c</referenceTo>
        <relationshipLabel>BSC Event Unit Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Unit_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Unit Booking</label>
    <nameField>
        <displayFormat>EUB-{0000000}</displayFormat>
        <label>Event Unit Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Unit Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/tncRequestEvent.cls
public class tncRequestEvent{
	public Opportunity oppy                 {get; private set;}
    public List<myProduct> theProducts      {get; set;}
    public id theProductId                  {get; set;}
    public id oplId                         {get; set;}
    
    private Map<Id, list<decimal>> productCosts;
    private String recordTypeId;
    private Map<Id,Id> oppLineItemsProdMapping;
    //private map<string,string> oplEventMap;
    
    list<EventOplLink> eventopl;
    public boolean processComplete	{get; set;}
    
    
    public tncRequestEvent(ApexPages.StandardController con)
    {
        processComplete = false;
        oppLineItemsProdMapping =  new Map<Id,Id>();
        oppy = (Opportunity)con.getRecord();
        theProducts = new List<myProduct>();
        productCosts = new Map<Id, list<decimal>>();
        
        string[] oplEvent = System.currentPageReference().getParameters().get('opl').split(',',0);
        list<string> opls = new list<string>();
        //oplEventMap = new map<string,string>();
        
        eventopl = new list<EventOplLink>();
        
        for (string s : oplEvent){
            opls.add(s.split(':')[0]);
            //oplEventMap.put(s.split(':')[0], s.split(':')[1]);
            
            EventOplLink link = new EventOplLink();
            link.oplId = Id.Valueof(s.split(':')[0]);
            link.EventId = Id.Valueof(s.split(':')[1]);
            link.hasRow = false;
            eventopl.add(link);
        }

        system.debug('opl: ' + opls);
        system.debug('oplEvent: ' + oplEvent);
        system.debug('eventopl: ' + eventopl);
        //system.debug('oplEventMap: ' + oplEventMap);
        
        oppy = [
            SELECT
                id,
                name,
                AccountId,
                Account.RecordType.Name,
                CloseDate,
                CurrencyIsoCode, // Case 0001747
               (
                    SELECT
                        id,
                        contactId
                    FROM
                        OpportunityContactRoles
                    WHERE
                        isPrimary=true
                ),
                (
                    SELECT
                        Id,
                        TotalPrice,
                        UnitPrice,
                        PricebookEntry.Product2Id,
                        Number_of_Delegates__c, 
                    	quantity,
                    	In_Company_Number_of_Days__c
                    FROM
                        OpportunityLineItems o
                    WHERE
                        PricebookEntry.Product2.No_Event__c = False and Id in :opls
                )
            FROM
                Opportunity
            WHERE
                id =: oppy.Id];
        
        list<Id> productIds = new list<Id>();
        for(OpportunityLineItem o : oppy.OpportunityLineItems)
        {
            productIds.add(o.PricebookEntry.Product2Id);
        }
        
        map<id,Product2> products = new map<id,product2>( [ SELECT id, name, Family, Event_Record_Type__c, Event_Type__c FROM Product2 WHERE id in :productIds order by name]);
        
        for(OpportunityLineItem o : oppy.OpportunityLineItems)
        {
            list<decimal> ds = new List<decimal>();
            ds.add(o.UnitPrice);
            ds.add(o.Number_Of_Delegates__c < 1 ? 1 : o.Number_Of_Delegates__c );
            productCosts.put(o.PricebookEntry.Product2Id, ds);
            oppLineItemsProdMapping.put(o.PricebookEntry.Product2Id,o.Id);
            myProduct product = new myProduct(products.get(o.PricebookEntry.Product2Id),ds);
            product.oppLineItemId  = o.Id;
            product.oliQty = o.Quantity;
            product.oliNoOfDays = o.In_Company_Number_of_Days__c;
            product.oliUnitPrice = o.UnitPrice;
            product.oliDelegates = o.Number_of_Delegates__c;
            theProducts.add(product);
        }

        system.debug('theProducts '+ theProducts);
    }
    
    public void addRow()
    {
        system.debug('oplid: ' + oplid);
        for(myProduct p : theProducts)
        {
            if(p.oppLineItemId == oplId )
            {
                Id transferredFrom = null;//oplEventMap.get(oplId)
                decimal numOfOPL = 0;
                for (EventOplLink link : eventopl){
                    if (link.oplId == p.oppLineItemId && link.hasRow == false){
                        transferredFrom = link.eventId;
                        link.hasRow = true;
                        break;
                    }
                }
                
                system.debug('eventopl: ' + eventopl);
                system.debug('transferredFrom: ' + transferredFrom);
                
                for (EventOplLink link : eventopl){
                    if (link.oplId == p.oppLineItemId){
                        numOfOPL++;
                    }
                }

                if (p.theEvents.size() <  numOfOpl){
                    
                    p.theEvents.add(new Special_Event__c(Venue__c = oppy.Account.RecordType.Name== 'Venue' ? oppy.AccountId :null,
                                                         Transferred_From__c = transferredFrom));
                } else {
                    ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Cannot add more rows for product ' + p.me.Name));
                }
                break;
            }
        }
    }
    
    public PageReference save()
    {
        List<RecordType> rts = [SELECT id, name FROM RecordType WHERE SObjectType = 'Special_Event__c'];
        Id recordTypeId;
        List<Special_Event__c> events;
        List<Special_Event_Booking__c> bookings = new List<Special_Event_Booking__c>();
        // Case 0001747
        List<Special_Event_Unit__c> units = new List<Special_Event_Unit__c>();
        List<Special_Event_Unit_Booking__c> unitBookings = new List<Special_Event_Unit_Booking__c>(); 
        Id rtsId;
        Id rtsAuditId; // Case 00001850
        for (RecordType rt: rts)
        {
            if (rt.name == 'In-Company Event')
                rtsId = rt.id;
            else // Case 00001850 - added Audit Record Type
                if (rt.name == 'Audit')
                    rtsAuditId = rt.id;
        }
        // End of Case 0001747
        for(myProduct p : theProducts)
        {
            events = new List<Special_Event__c>();
            recordTypeId = null;
            if(p.createable)
            {               
                for(RecordType rt : rts)
                {
                    if(rt.name == p.me.Event_Record_Type__c){
                        recordTypeId = rt.Id;
                    }
                }               
                
                for(Special_Event__c e : p.theEvents)
                {
                    if(e.StartDate__c != null && e.Latest_Start_Date__c != null)
                    {
                        e.RecordTypeId = recordTypeId;
                        e.type__c = p.me.Event_Type__c;
                        e.Opportunity__c = oppy.Id;
                        e.Status__c = 'Requested';
                        e.Stage__c = 'Provisional';
                        e.Product__c = p.myId;
                        events.add(e);
                    }
                }
            
                if(events.size() > 0)
                {
                    try
                    {
                        insert events;
                        
                        map<id,id> transferto = new map<id,id>();

                        boolean primaryBooking = true;
                        for(Special_Event__c e : events)
                        {
                            if (transferto.containsKey(e.Transferred_From__c) == false){
                                transferTo.put(e.Transferred_From__c, e.Id);
                            }
                            
                            if (e.RecordTypeId==rtsId||e.RecordTypeId==rtsAuditId)
                            {
                                OpportunityLineItem opl = [Select ol.In_Company_Number_of_Days__c From OpportunityLineItem ol Where Id = :p.oppLineItemId ][0];
                                
                                Date usableStartDate = e.StartDate__c;
                                Integer duration;
                                if (opl.In_Company_Number_of_Days__c==null)
                                {
                                    duration = 0;
                                }
                                else
                                {
                                    duration = opl.In_Company_Number_of_Days__c.Round().intValue();
                                }
                                System.debug('Duration: '+ duration);
                                if (duration==0)
                                {
                                    duration = 1;
                                }
                                System.debug('Duration before run: '+ duration);
                                for (Integer i=0;i<duration;i++)
                                {
                                    System.debug('looping creating the event unit: '+ i);
                                    Datetime startDate = datetime.newInstance(usableStartDate.year(), usableStartDate.month(), usableStartDate.day(), 9, 0, 0);
                                    Datetime endDate = datetime.newInstance(usableStartDate.year(), usableStartDate.month(), usableStartDate.day(), 17, 0, 0);
                                    Boolean primaryUnit;
                                    if(i==0)
                                    {
                                        primaryUnit=True;
                                    }
                                    else
                                    {
                                        primaryUnit=False;
                                    }
                                    Special_Event_Unit__c unit = new Special_Event_Unit__c(
                                                                    name = 'Day '+(i+1),
                                                                    primary_c__c = primaryUnit,
                                                                    unit_start_time__c = startDate,
                                                                    unit_end_time__c = endDate,
                                                                    venue__c = e.Venue__c,
                                                                    Special_Event__c= e.id,
                                                                    CurrencyIsoCode = oppy.CurrencyIsoCode);
                                    units.add(unit);
                                    usableStartDate=usableStartDate.addDays(1);                                 
                                }
                                if(e.RecordTypeId==rtsAuditId)
                                    e.Audit_Number_of_Days__c=duration;
                                
                            }

                            primaryBooking = true;
                            Special_Event_Booking__c booking = new Special_Event_Booking__c(
                                Opportunity__c = oppy.Id,
                                Special_Event__c = e.Id,
                                Status__c='Provisional',
                                Type__c = 'In-Company Primary',
                                Contact__c = oppy.OpportunityContactRoles[0].contactid,
                                Company__c = oppy.AccountId,
                                Primary_Booking__c = primaryBooking,
                                Booking_Fee__c = primaryBooking ? p.cost : 0.0);
                                
                            primaryBooking = false;

                            booking.OPL_ID__c = p.oppLineItemId;
                            bookings.add(booking);                          
                        
                            if(p.numberOfDelegates > 1)
                            {
                                for(integer i = 1; i < p.numberOfDelegates; i++)
                                {
                                    Special_Event_Booking__c bookingAdditional = new Special_Event_Booking__c(
                                        Opportunity__c = oppy.Id,
                                        Status__c='Provisional',
                                        Type__c = 'In-Company Additional',
                                        Special_Event__c = e.Id,
                                        Company__c = oppy.AccountId,
                                        Booking_Fee__c = 0.0);
                                    if(!oppLineItemsProdMapping.isEmpty())
                                    {
                                        if(oppLineItemsProdMapping.containsKey(p.myId))
                                            bookingAdditional.OPL_ID__c  = p.oppLineItemId;
                                    }
                                    bookings.add(bookingAdditional);
                                }
                            }
                        }
                        
                        list<Special_Event__c> mainEvents = [select id from Special_Event__c where id in :transferTo.keySet()];
                        for (Special_Event__c evt : mainEvents){
                            evt.Transferred_To__c = transferTo.get(evt.id);
                        }
                        update mainEvents;
                        
                        update events;
                        processComplete = true;
                    }
                    catch(System.Exception ex)
                    {
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,ex.getMessage()));
                        return null;
                    }
                }
            }
        }
        try
        {
            if(bookings.size() > 0)
                insert bookings;
        }
        catch(System.Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,ex.getMessage()));
            return null;
        }   
        
        // Case 0001747
        try
        {
            if(units.size() > 0)
                insert units;

        }
        catch(System.Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,ex.getMessage()));
            return null;
        }
        
        for (Special_Event_Booking__c e: bookings)
        {
            Integer i = 0;
            System.debug('Looping Event Booking: ');
            // Case 00001851
            for (Special_Event_Unit__c u:[Select Id From Special_Event_Unit__c Where Special_Event__c=:e.Special_Event__c])
            {
                System.debug('Looping special Event unit to create special event Unit Booking: '+u.id);
                Special_Event_Unit_Booking__c unitBooking = new Special_Event_Unit_Booking__c(currencyIsoCode=oppy.CurrencyIsoCode,
                                                                                            attended__c = false,
                                                                                            event_unit__c = u.Id,
                                                                                            contact__c = e.contact__c,
                                                                                            event_booking__c=e.id);
                unitBookings.add(unitBooking);
                i++;
            }
        }
        
        try
        {
            if(unitBookings.size() > 0)
                insert unitBookings;

        }
        catch(System.Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,ex.getMessage()));
            return null;
        }
        
        // End Case 0001747             
        //return new PageReference('/'+oppy.id);

        return null;
    }
    
    public PageReference returnToOpp(){
        return new PageReference('/'+oppy.id);      
    }
    
    public PageReference transferMore(){
        return new PageReference('/apex/tncInCompanyTransfer?oppId='+oppy.id);      
    }
    
    public PageReference confirmPendingTransfer(){
        return new PageReference('/apex/tncConfirmTransfer?oppId='+oppy.id);      
    }
    
    public class EventOplLink{
        
        public Id eventId     {get;set;}
        public Id oplId       {get;set;}
        public boolean hasRow {get;set;}
        
    }
    
    public class myProduct
    {
        public List<Special_Event__c> theEvents{get; set;}
        public Product2 me{get; set;}
        public Id myId{get; private set;}
        private decimal cost;
        private decimal numberOfDelegates;
        public boolean createable{get; private set;}
        
        public Id oppLineItemId {get; set;}
        public decimal oliQty {get; set;}
        public decimal oliNoOfDays {get; set;}
        public decimal oliUnitPrice {get; set;}
        public decimal oliDelegates {get; set;}
        public string linebreak {get; set;}
        
        public myProduct(Product2 me, List<decimal> ds)
        {
            this.linebreak = '\n';
            this.me = me;
            this.myId = me.Id;
            this.cost = ds[0];
            this.numberOfDelegates = ds[1];
            if(numberOfDelegates == null || numberOfDelegates < 1)
                numberOfDelegates = 1;
            theEvents = new List<Special_Event__c>();
            if(me.Family == 'Audit' || me.Family == 'In-Company Training' || me.Family == 'Advisory'){
                createable = true;
            }else{
                createable = false;
            }
        }
    }
}