src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the Account is Active or Inactive i.e. does the Organisation exist.</description>
        <inlineHelpText>Indicates whether the Account is Active or Inactive i.e. does the Organisation exist.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tick if the Account is a current member.</description>
        <inlineHelpText>Tick if the Account is a current member.</inlineHelpText>
        <label>Member</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the Contact is Active or Inactive i.e. does the contact exist at the Organisation</description>
        <inlineHelpText>Indicates whether the Contact is Active or Inactive i.e. does the contact exist at the Organisation</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>Subscription</fullName>
        <active>true</active>
        <description>Record type for Memberships and other Subscription Products</description>
        <label>Subscription</label>
    </recordTypes>
</CustomObject>

src/objects/Site_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product associated to this site product</description>
        <formula>Subscription_Line__r.Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Product associated to this site product</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Line__c</fullName>
        <description>Master Detail</description>
        <inlineHelpText>Subscription line associated with the site product</inlineHelpText>
        <label>Subscription Line</label>
        <referenceTo>Subscription_Line__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subscription site associated to this site product</description>
        <inlineHelpText>Lookup to Subscription Site</inlineHelpText>
        <label>Subscription Site</label>
        <referenceTo>Subscription_Site__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <description>Master detail</description>
        <inlineHelpText>Subscription associated with this site product</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site Product</label>
    <nameField>
        <displayFormat>SP-{0000000}</displayFormat>
        <label>Site Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to manage subscriptions (Memberships, Complywise Subscriptions and other ongoing product deliveries)</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The primary contact for this subscription</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Product__c</fullName>
        <description>Total number of Site products on the subscription</description>
        <inlineHelpText>Total number of Site products on the subscription</inlineHelpText>
        <label>Site Products</label>
        <summaryForeignKey>Site_Product__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending - Not Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Not Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Renewing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Cancelling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapsing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapse Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Manual Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Line__c</fullName>
        <description>The total number of subscription lines on the subscription</description>
        <inlineHelpText>The total number of subscription lines on the subscription.</inlineHelpText>
        <label>Subscription Lines</label>
        <summaryForeignKey>Subscription_Line__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Sub Ref: Current Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Line__c.object
<CustomObject>
    <description>Object to manage products / elements of a subscription</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Available__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Available</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Subscription Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription_Site__c.object
<CustomObject>
    <description>Object to manage delivery of subscriptions to multiple sites</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if a site is currently active</description>
        <inlineHelpText>Indicates if a site is currently active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Site_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Multi_Site_Subscription_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Multi_Site_Subscription_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Site_Product_Codes__c</fullName>
        <label>Subscription Site Product Codes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Site Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Site Subsidiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription Site</label>
    <nameField>
        <displayFormat>SS-{0000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SSCeationController.cls
public with sharing class SSCeationController
{  
  Public Subscription_Site__c SubscriptionSite {get; set; }
  public String    SubscriptionId        { get; set; }
  Public List<Subscription_Line__c> SubscriptionLines {get; set; }
  Public List<Subscription_Line__c> SubscriptionLines4Display {get; set; }
  Public List<Site_Product__c > SiteProducts {get; set; }
  Public List<Products2Add> Products2AddInfo {get; set; }
  Public List<AccountContact> AccountContacts {get; set; }
  Public  List<Contact> contact2Add;
  //public String[] SiteTypeCriteria { get; set; }
     
  public Integer pageNum { get; private set; }
  private final Integer maxPages = 3;
       
      //public SSCeationController ( ApexPages.StandardController stdController )
      public SSCeationController ( )
      {
        //this.SubscriptionSite =(Subscription_Site__c ) stdController.getrecord();
        this.SubscriptionSite =new Subscription_Site__c();

/*      SiteTypeCriteria = new String[] {};
        // Select all types as default
        for (SelectOption so : getSiteTypePicklistOptions())
        {
            SiteTypeCriteria.add(so.getValue());
        }
*/      

        if( System.currentPageReference().getParameters().get( 'SCid' ) != null )
        {
            this.SubscriptionId=System.currentPageReference().getParameters().get( 'SCid' );
        } 
            SubscriptionLines =[Select  Quantity__c,Quantity_Available__c, Product__c,Product__R.Id,Product__R.Name,Product__R.ProductCode,Subscription__c  From Subscription_Line__c  where         Subscription__c=:this.SubscriptionId];
           
           Products2AddInfo= new List<Products2Add>();
           SubscriptionLines4Display= new List<Subscription_Line__c>();
           if(SubscriptionLines.size()>0)
           {     
               for (Subscription_Line__c SL: SubscriptionLines)
               {
                  Products2Add NewProducts2Add=new Products2Add();
                  Subscription_Line__c SLNew= new Subscription_Line__c();
                  SLNew.Quantity__c= 0;//SL.Quantity__c;
                  SLNew.Quantity_Available__c=SL.Quantity_Available__c;
                  SLNew.Product__c=SL.Product__c;
                  NewProducts2Add.record=SLNew;
                  NewProducts2Add.recordRef=SL;
                  NewProducts2Add.ProductName=SL.Product__R.Name;
                  NewProducts2Add.ProductCode=SL.Product__R.ProductCode;                         
                  Products2AddInfo.add(NewProducts2Add);     
               }           
           }                          
        pageNum=1;    
      }
                                                                             
    Private boolean GetContactsforAccount()
    {                  
         boolean AtLeastOnePositiveQuantity=false;       
         for(Products2Add SLine :Products2AddInfo)
         {
            if(SLine.record.Quantity__c>SLine.record.Quantity_Available__c)
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Quantity can not be greater than total quantity available for a product'));
                return false; 
            }      
            if(SLine.record.Quantity__c > 0.0)
            {
                AtLeastOnePositiveQuantity=true;
            }
         }
         
         if(AtLeastOnePositiveQuantity==false)
         {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Please enter quantity of Product'));
                return false;        
         }
         
        if (SubscriptionSite.Site_Account__c==null)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Please select an Account for the subscription site'));
            return false;
        }
                 
        AccountContacts= new List<AccountContact>();
            for (Contact NewContact : [Select LastName, Id, FirstName From Contact   where  AccountId=:SubscriptionSite.Site_Account__c])
            {
                AccountContacts.add(new AccountContact(NewContact));
            }       
    
        return true;    
    }     
               
    public void next()
    {  
        if (pageNum < maxPages) pageNum++;
         
        if (pageNum == 2)  
        {  
            GetContactsforAccount();
        }     
        else if (pageNum == 3)  
        {
            //Boolean success = generateBSCEventUnits();
            //if (!success) pageNum--;
        }                   
    }         
           
    public PageReference savesite()
    {  
	    Integer CntContacts=0;
	    PageReference PageRef;
	    Boolean CallFinal=true;
	    contact2Add=new  List<Contact>();
	    for(AccountContact ActContact:AccountContacts)
	    {
	        if(ActContact.selected == true)
	        {  
	            CntContacts=CntContacts+1;
	            contact2Add.add(ActContact.record);         
	        }
	    }
	    //Case 1447
	    if (CntContacts>0&&SubscriptionSite.Site_Contact__c!=null)
	    {
	            CallFinal=false;
	            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Select only one contact from either Subscription site or Additional Subscription site '));
	            return null;            	
	    }
	    //End of Case 1447  
	               
	    if(CntContacts>1)
	    {
	            CallFinal=false;
	            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Select only one contact '));
	            return null;        
	    }
	    
	    // Case 1447
	    if(CntContacts==0&&SubscriptionSite.Site_Contact__c==null)
	    {
	            CallFinal=false;
	            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Select main contact '));
	            return null;        
	    }       
	                        
	    //Create Subscription Site First
	    SubscriptionSite.Subscription__c=SubscriptionLines[0].Subscription__c;
	    SubscriptionSite.Site_Account__c=SubscriptionSite.Site_Account__c;
	    SubscriptionSite.Active__c=true;
	    // Case 1447
	    if (SubscriptionSite.Site_Contact__c==null)
	    {
	    	SubscriptionSite.Site_Contact__c=contact2Add[0].id;
	    }
	    // End of Case 1447
	    string StrProductCodes='';
	    for(Products2Add SLine :Products2AddInfo)
	    {
	    	if(SLine.record.Quantity__c>0)
	        {
	        	StrProductCodes=StrProductCodes + ';' + SLine.ProductCode;
	        }    
	    }    
	    StrProductCodes=StrProductCodes.substring(1,StrProductCodes.length());
	    SubscriptionSite.Subscription_Site_Product_Codes__c=StrProductCodes;
	    insert SubscriptionSite;
	
	    //list<Account> Acct2Update=[Select Member__c  from Account where id=:SubscriptionSite.Site_Account__r.id and Member__c=false    limit 1];
	    /*
	    ** 16/01/2012: commented out as this is worked out in the subscription site trigger.
	    list<Account> Acct2Update=[Select Member__c  from Account where id=:SubscriptionSite.Site_Account__c and Member__c=false    limit 1];
	    if (Acct2Update.size()==1)
	       {
	           Acct2Update[0].Member__c=true;
	           update Acct2Update;
	       }
		*/
	    //Create Site Products 
	    SiteProducts = new list<Site_Product__c>();
	    list<Subscription_Line__c> SL2Update = new list<Subscription_Line__c>();
	    for(Products2Add SLine :Products2AddInfo)
	    {
	    	for (Integer i = 0; i < SLine.record.Quantity__c; i++)
	        {
	            Site_Product__c NewSiteProduct= new Site_Product__c();
	            NewSiteProduct.Subscription__c=SubscriptionLines[0].Subscription__c;
	            NewSiteProduct.Subscription_Site__c=SubscriptionSite.id;
	            NewSiteProduct.Subscription_Line__c=SLine.Recordref.id;
	            SiteProducts.add(NewSiteProduct);           
	        }      
	        SLine.Recordref.Quantity_Available__c=SLine.Recordref.Quantity_Available__c-SLine.Record.Quantity__c;
	        SL2Update.add(SLine.Recordref);
	    }             
	    insert SiteProducts;
	    update SL2Update;         
	
	    // Redirect to newly created Subsscription Site
	    return new PageReference('/' + SubscriptionSite.Id);         
    }

    public SelectOption[] getSiteTypePicklistOptions()
    {
        List<SelectOption> options = new List<SelectOption>();
        for (Schema.Picklistentry pe : Schema.SObjectType.Subscription_Site__c.fields.Type__c.getPicklistValues())
        {
            if (pe.isActive()) options.add(new SelectOption(pe.getValue(), pe.getLabel()));
        }
        return options;
    }
        
    public void prev()
    {
        if (pageNum > 1) pageNum--;
    }
  
    public PageReference cancel()
    {
        if (SubscriptionId != null)
            return new PageReference('/' + SubscriptionId);     
        return new PageReference('/home/home.jsp');
    }
            
    public class Products2Add
    {
        public Subscription_Line__c record { get;  set; }
        public Subscription_Line__c recordRef { get;  set; }
        public String ProductName {get; set; }
        public String ProductCode {get; set; }          
    }   
    
    public class AccountContact
    {
        public Contact record { get; private set; }
        public Boolean selected { get; set; }       
        public AccountContact(Contact target)
        {
            this.record = target;
            this.selected = false;
        }
    }   
       
    @IsTest
    private static void testSSCreation()
    {
        //Create a Product
        Product2 prod = new Product2();
        prod.Name = 'Test SSCreation Product';
        insert prod;

        //Create an Account
        Account NewAccount=new Account(name='Test SSCreation Account');
        insert NewAccount;      
        
        // Add a Contact to it
        Contact NewContact= new Contact(LastName='Test SSCreation Contact', Email='testy13213@fffp.com', FirstName = 'Test', Salutation = 'Mr');
        NewContact.AccountId=NewAccount.id;
        insert NewContact;
        
        
        //a Create a Subscription
        Subscription__c NewSubscription= new Subscription__c();
        NewSubscription.Account_Name__c=NewAccount.id;
        NewSubscription.Contact__c = NewContact.id;
        NewSubscription.Status__c = 'Current - Not Paid';
        insert NewSubscription;
        
        //Create a Subscription Line
        Subscription_Line__c NewSubscriptionLine= new Subscription_Line__c();
        NewSubscriptionLine.Subscription__c=NewSubscription.id;
        NewSubscriptionLine.Quantity__c=20.0;
        NewSubscriptionLine.Quantity_Available__c=20.0;
        NewSubscriptionLine.Product__c=prod.id;
        insert NewSubscriptionLine;
        
        Test.startTest();
        PageReference PageRef=Page.SScreation;
        test.setCurrentPage(PageRef);
        ApexPages.currentPage().getParameters().put('SCid',NewSubscription.id);        
        SSCeationController controller= new SSCeationController();
        controller.SubscriptionSite.Site_Account__c=NewAccount.id;
        controller.Products2AddInfo[0].record.Quantity__c=1.0;      
        controller.next();        
        controller.AccountContacts[0].selected=true;
        controller.savesite();
        Test.stopTest();
        
        //Go to Next Page
        //controller.next();
        //controller.AccountContacts[0].selected=true;        
    }
  
}