src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Exclude_from_Auto_Invoicing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If you do not want an invoice or credit note automatically created for this Account check this box</description>
        <inlineHelpText>If you do not want an invoice or credit note automatically created for this Account check this box</inlineHelpText>
        <label>Exclude from Auto Invoicing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Exclude_from_Auto_Invoicing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Exclude this Opportunity from being processed using Auto Invoicing</description>
        <label>Exclude from Auto Invoicing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Finance_to_Credit_Opp__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used to identify if opp needs to be credited or not. This is used to inform the &quot;Invoice Status&quot; field.</inlineHelpText>
        <label>Finance to Credit Opp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The company on which this opportunity will be invoiced.</inlineHelpText>
        <label>Invoice Company</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not an active company.</errorMessage>
            <filterItems>
                <field>c2g__codaCompany__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>c2g__codaCompany__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <formula>IF( Finance_Written_Off__c = True, &apos;Written Off&apos;,
   IF( Finance_to_Credit_Opp__c = True, &apos;To Be Credited&apos;,
      IF( 
         OR( 
            AND(Finance_to_Invoice_Opp__c = True,  ISBLANK(Date_to_be_Invoiced__c)) , 
            AND(Finance_to_Invoice_Opp__c = True,  Date_to_be_Invoiced__c &lt;=  TODAY())
         ),&apos;To Be Invoiced&apos;,
         
         IF( AND(CreatedBy.Alias = &apos;Website&apos;, !ISBLANK(Latest_Invoice__r.Website_Order_Id__c)), &apos;N/A&apos;,
            IF( Using_one_to_one_invoicing__c = &apos;Yes&apos;,
               

               IF( AND(Latest_Invoice__r.Is_Credited_In_Full__c = True,!ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)) ,&apos;Credited&apos;,
                  IF( AND( Latest_Invoice__r.c2g__OutstandingValue__c = 0, !ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)) , &apos;Paid&apos;,
                     IF( AND(Latest_Invoice__r.c2g__OutstandingValue__c &gt; 0, Latest_Invoice__r.c2g__OutstandingValue__c &lt; Latest_Invoice__r.c2g__InvoiceTotal__c, !ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)), &apos;Part Paid&apos;,
                        IF(  AND(Latest_Invoice__r.c2g__OutstandingValue__c =  Latest_Invoice__r.c2g__InvoiceTotal__c, !ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)), &apos;Invoiced&apos;,
                           &apos;No Action&apos;
                        )
                     )
                  )
               )



            ,&apos;N/A&apos;
            )
         ) 
      )
   )
)</formula>
        <inlineHelpText>Determines the current status of the opportunity based on the one to one invoicing model.</inlineHelpText>
        <label>Invoice Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latest_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Whenever a new invoice is created on the opportunity, this is updated to the latest invoice.</inlineHelpText>
        <label>Latest Invoice</label>
        <referenceTo>c2g__codaInvoice__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Using_one_to_one_invoicing__c</fullName>
        <formula>IF( 
   AND(
      CreatedDate &gt;= $Setup.Feature_Settings__c.One_to_One_Invoicing_Start_Date__c, 
      Use_part_invoicing__c = False
   ),
   &apos;Yes&apos;,
   &apos;No&apos;
)</formula>
        <label>Using one to one invoicing</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_Order_Id__c</fullName>
        <description>The unique identifier for the order in the website this may not be unique within Salesforce as an order on the website may match multiple orders in Salesforce.</description>
        <inlineHelpText>The unique identifier for the order in the website this may not be unique within Salesforce as an order on the website may match multiple orders in Salesforce.</inlineHelpText>
        <label>Website Order Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AutoCreditBatch.cls
/*

VS : This batch generate credit notes for the opps that meets the criteria
     Generates 10 credit notes at a time.
     for testing purpose, pass the oppId to teh constructor
     invCompany is set from the AutoInvoiceBatch or the AutoGenerateFinancialTransactions
     
     once there are no more credit notes, calls  AutoInvCreditMatchBatch to match invoices and credit notes
     
*/

global class AutoCreditBatch implements Database.Batchable<sObject>{

    id opportunityId;  
    string invoiceCompany;
    
    global AutoCreditBatch(id oppId, string invCompany){
        opportunityId = oppId;
        invoiceCompany = invCompany;
    }

    
    global Database.QueryLocator  start(Database.BatchableContext BC){
        
        datetime oppsLastModified = datetime.now();
        
        if (AutoInvoiceSettings.autoInvoiceDelay > 0)
            oppsLastModified = oppsLastModified.addHours(AutoInvoiceSettings.autoInvoiceDelay * -1);
        
        system.debug('finding opps that were modified before ' + oppsLastModified);
        
        if (opportunityId == null)
            return Database.getQueryLocator([select id,
                                                    Latest_Invoice__c
                                               from opportunity 
                                              where Finance_to_Credit_Opp__c = true 
                                                and Invoice_Status__c = 'To Be Credited'
                                                and Using_one_to_one_invoicing__c = 'Yes' 
                                                and Invoice_Company__r.Name = :invoiceCompany
                                                and Latest_Invoice__r.Is_Credited_In_Full__c = false
                                                and Exclude_from_Auto_Invoicing__c = false 
                                                and Website_Order_Id__c = null
                                                and lastmodifieddate < :oppsLastModified
                                              limit 10]);
        //and Account.billingCountry in ('United Kingdom','England' ,'Wales' , 'Northern Ireland' , 'Scotland' , 'UK')
        else
            return Database.getQueryLocator([select id,
                                                    Latest_Invoice__c
                                               from opportunity 
                                              where id = : opportunityId
                                              limit 1]);
    }
     
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        system.debug('invoiceCompany ' + invoiceCompany);
        
        list<string> info = new list<string>();
        info.add(AutoInvoiceSettings.emailNotificationTo);
        AutoInvoiceHelper.sendMail('Started CreditNote Generation', 'Opportunities to Credit: ' + scope, info);
        
        list<id> invoicesToCredit = new list<id>();
        
        for (opportunity opp : (list<opportunity>)scope){
            invoicesToCredit.add(opp.Latest_Invoice__c);
        }
        system.debug('scope: ' + scope);
        List<id> creditNotes = AutoInvoiceHelper.createCreditNotes(invoicesToCredit, AutoInvoiceSettings.autoPostCreditNotes, invoiceCompany);
        
        
        if (creditNotes!= null &&  creditNotes.size() > 0){
            
            AutoInvoiceHelper.sendMail('Finished CreditNote Generation', 'Following Credit Notes Processed: ' + string.valueof(creditNotes) + ' for '+invoiceCompany, info);
        } else {
            AutoInvoiceHelper.sendMail('Finished CreditNote Generation', 'No Credit Notes Processed for ' +invoiceCompany, info);
        }
        
    }
    
    global void finish(Database.BatchableContext BC){
        
        system.debug('executing invoice credit match batch for BSC..');         
        AutoInvCreditMatchBatch acmb = new AutoInvCreditMatchBatch(invoiceCompany);
        database.executeBatch(acmb);
    
    }
}