src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Data_Cleanse_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Accounts / Contacts with no associated records and last contact was created over two years ago</description>
        <inlineHelpText>Accounts / Contacts with no associated records and last contact was created over two years ago</inlineHelpText>
        <label>Data Cleanse 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Data_Cleanse_3__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Accounts / Contacts with activity and nothing else, where last activity date was created in old CRM</description>
        <inlineHelpText>Accounts / Contacts with activity and nothing else, where last activity date was created in old CRM</inlineHelpText>
        <label>Data Cleanse 3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Data_Cleanse_6__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Accounts without contacts or any other associates and are not suppliers</description>
        <inlineHelpText>Accounts without contacts or any other associates and are not suppliers</inlineHelpText>
        <label>Data Cleanse 6</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Custom_Email_Template__c.object
<CustomObject>
    <description>Holds Email templates</description>
    <fields>
        <fullName>EmailBody__c</fullName>
        <label>Email Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EmailFrom__c</fullName>
        <label>Email From</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EmailSubject__c</fullName>
        <label>Email Subject</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EmailToTest__c</fullName>
        <label>Email To(Test)</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Custom Email Template</label>
    <nameField>
        <label>Email Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Email Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If populated, this field indicates an original public events opportunity which has been partially closed</description>
        <inlineHelpText>If populated, this field indicates an original public events opportunity which has been partially closed</inlineHelpText>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subsequent Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact to whom renewal reminders are sent (auto populated on creation of subscription renewal opportunities)</inlineHelpText>
        <label>Renewal Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UtilitiesTest.cls
@IsTest(SeeAllData=true)
public class UtilitiesTest{

    static testmethod void testGetCreatableFieldsSOQL(){
        
        account acc = new account(name = 'test utility');
        insert acc;
        contact NewContact= new Contact(
            LastName='Test util' , 
            Email='testutil@bsc.com', 
            FirstName = 'Testutil', 
            Salutation = 'Mr',
            AccountId = acc.id
        );
        insert NewContact;
        opportunity opp = new Opportunity(
            Name = 'testutility',
            AccountId = acc.Id,
            StageName = 'Qualifying',
            CloseDate = Date.today());
        insert opp;
        OpportunityContactRole ocr = new OpportunityContactRole();
        ocr.ContactId  = NewContact.id;
        ocr.OpportunityId = opp.id;
        insert ocr;
        
        test.starttest();
        
        string soql = Utilities.getCreatableFieldsSOQL('Account') + ' limit 1 ';
        system.assert(soql.contains('SELECT'));
        list<Account> acc1 = database.query(soql);
        system.assert(acc1.size() == 1 , 'found account');
    
        
        list<string> relatedFields = new list<string>();
        relatedFields.add('Account.Name');
        relatedFields.add('Account.Id');
        
        list<string> subQueries = new list<string>();
        subQueries.add('select id, name from Opportunities__r');
        
        string soql1 = Utilities.getSOQLQuery('Contact', relatedFields, subQueries) + ' limit 10 ';
        system.assert(soql1.contains('SELECT'));
        system.debug(soql1);
        list<contact> contacts = [select id, account.id, account.name, (select id, name from Opportunities__r) from contact where (Account.Data_Cleanse_1__c != true and Account.Data_Cleanse_3__c != true and Account.Data_Cleanse_6__c != true) limit 2];
        system.assert(contacts.size() > 0 , 'found contacts');
        
        list<task> tasks = new list<task>();
        for (contact con : contacts){
            system.assert(con.Account.Id != null);
            system.assert(con.Opportunities__r.size() >= 0);
            
            task t = Utilities.createTask(true, system.today(), con.Account.Id, 'Test', 'Test Description', userinfo.getUserId() );
            tasks.add(t);
            insert t;
        }

        Custom_Email_Template__c template = new Custom_Email_Template__c();
        template.EmailBody__c = 'Emailbody <Test>';
        template.EmailSubject__c = 'EmailSubject <Test>';
        template.EmailFrom__c = 'VishantShah@yahoo.com';
        template.Name = 'Test';
        template.EmailToTest__c = 'vishant.shah@britsafe.org';
        insert template;
        
        list<string> toEmail = new list<string>();
        toEmail.add('vishant.shah@britsafe.org');
        
        map<string,string> keyValue = new map<string,string>();
        keyvalue.put('<Test>', 'replaced via key value');
        
        Utilities.SendEmail('Test', toEmail, keyValue);
        
        Utilities.SendEmail(' body', 'subject',  toEmail);
        
        
        string[] toEmail1 = new string[1];
        toEmail1[0] = 'vishant.shah@britsafe.org'; 
        
        Utilities.sendTemplatedEmail(toEmail1, 'Request_To_Add_or_Remove_Bookings', acc.id, UserInfo.getUserId());
        
            
        test.stopTest();
    }
}