src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>c2g__CODADimension1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dimension 1</label>
        <referenceTo>c2g__codaDimension1__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c2g__CODADimension2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dimension 2</label>
        <referenceTo>c2g__codaDimension2__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The subscription that needs to be altered.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities (Subscription)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Subscription</fullName>
        <active>true</active>
        <businessProcess>BSC Sales Process</businessProcess>
        <description>Opportunity for Membership and other Subscription Product Sales</description>
        <label>Subscription</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Fee_Product__c</fullName>
        <formula>PricebookEntry.Product2.Cancellation_Fee_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cancellation Fee Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to mark cancellation reconciliation prices as exceptions to avoid triggering approval</description>
        <inlineHelpText>Checkbox to mark cancellation reconciliation prices as exceptions to avoid triggering approval</inlineHelpText>
        <label>Pricing Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transfer_Fee_Product__c</fullName>
        <formula>PricebookEntry.Product2.Transfer_Fee_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Transfer Fee Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>c2g__CODAGeneralLedgerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Override Product GLA</label>
        <referenceTo>c2g__codaGeneralLedgerAccount__c</referenceTo>
        <relationshipLabel>Opportunity Line Items</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Fee_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to Cancellation Fee product used when this product is cancelled.  This product is added to the cancellation Fee opportunity created during the cancellation process</description>
        <inlineHelpText>Links to Cancellation Fee product used when this product is cancelled.</inlineHelpText>
        <label>Cancellation Fee Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>CancellationFeeProduct</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Permitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Affects discount workflow</description>
        <inlineHelpText>Tick this box if discounts are permitted</inlineHelpText>
        <label>Discount Permitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maximum_Discount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>Applies if discount permitted = true</description>
        <inlineHelpText>Enter the maximum discount that may be offered before the opportunity requires approval. (If discount is permitted)</inlineHelpText>
        <label>Maximum Discount</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Fee_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to Transfer Fee product used when this product is transferred. This product is added to the cancellation Fee opportunity created during the transfer process</description>
        <inlineHelpText>Links to Transfer Fee product used when this product is transferred.</inlineHelpText>
        <label>Transfer Fee Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Transfer Fee Product)</relationshipLabel>
        <relationshipName>TransferFeeProduct</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <description>Record type for General Products,Tangible Goods, and Special Events and Ceremonies</description>
        <label>General</label>
    </recordTypes>
    <recordTypes>
        <fullName>Subscription</fullName>
        <active>true</active>
        <description>Record type for Memberships and other Subscription Products</description>
        <label>Subscription</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Determines the type of event from a picklist</description>
        <inlineHelpText>Determine the type of event from the picklist</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NVQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Defines the event booking type whether primary or additional etc</description>
        <inlineHelpText>Defines the event booking type whether primary or additional etc</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional - On the Day</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to manage subscriptions (Memberships, Complywise Subscriptions and other ongoing product deliveries)</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Line__c</fullName>
        <description>The total number of subscription lines on the subscription</description>
        <inlineHelpText>The total number of subscription lines on the subscription.</inlineHelpText>
        <label>Subscription Lines</label>
        <summaryForeignKey>Subscription_Line__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Sub Ref: Current Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Line__c.object
<CustomObject>
    <description>Object to manage products / elements of a subscription</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Subscription Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription_Site__c.object
<CustomObject>
    <description>Object to manage delivery of subscriptions to multiple sites</description>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Site Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Site Subsidiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription Site</label>
    <nameField>
        <displayFormat>SS-{0000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/tncTest.cls
@isTest(SeeAllData=True)
private class tncTest {
    
    public static Account account;
    public static Opportunity opportunity;
    public static OpportunityLineItem OppLineItem;
    public static Special_Event__c specialEvent;
    public static Special_Event__c specialEvent1;
    public static Special_Event_Booking__c specialEventbooking;
    public static Product2 product2;
    public static Subscription__c subscription;
    public static Subscription_Line__c subscriptionLineItem;
    public static Subscription_Site__c subSite;
    public static Contact NewContact;
    
    private static string RandomString{
        get{
            return string.valueof(math.random()).substring(1,10);
        }
    }
    
    static testMethod void TestInCoProvisional() {
        Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
        
        Product2  tranProd = new Product2 (name = 'Tran Fee InCompanyC',Maximum_Discount__c=100, Discount_Permitted__c=true );
        insert tranProd;
        
        Product2  cancProd = new Product2 (name = 'Cancellation Fee InCompanyC',Maximum_Discount__c=100, Discount_Permitted__c=true);
        insert cancProd;
        
        Product2  testProd = new Product2 (name = 'InCompanyC Test', Cancellation_Fee_Product__c=cancProd.id, Transfer_Fee_Product__c= tranProd.id);
        insert testProd;
        
        
        Pricebook2 pbe2Test = new Pricebook2(name =  'InCompanyC Test');
        insert pbe2Test;
        
        Pricebook2 pbe2Tran = new Pricebook2(name =  'Tran Fee InCompanyC');
        insert pbe2Tran;
        
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = testProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice;
        PricebookEntry pbeTest = new PricebookEntry(Product2Id = testProd.Id, Pricebook2Id = pbe2Test.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeTest;
        
        PricebookEntry standardPrice1 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = cancProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice1;
        PricebookEntry pbeCanc = new PricebookEntry(Product2Id = cancProd.Id, Pricebook2Id = pbe2Test.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeCanc;
        
        PricebookEntry standardPrice2 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id=tranProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice2;
        PricebookEntry pbeTran = new PricebookEntry(Product2Id = tranProd.Id, Pricebook2Id = pbe2Tran.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeTran; 
        
        RecordType rType = [select id from RecordType where name = 'In-Company Event' and sObjectType = 'Opportunity'];
        
        id Dimension1Id = [select id from c2g__codaDimension1__c where name = '110 - Finance' limit 1].id;
        id Dimension2Id = [select id from c2g__codaDimension2__c where name = '0000 - General' limit 1].id;
        id glaid = [select id from c2g__codaGeneralLedgerAccount__c where name = '3000 - Income - Sales Activities' Limit 1].Id;
        
        /* CREATE ACCOUNT*/
        account = new Account(
            name = 'tnc '+ RandomString); 
        insert account;
        
        /* CREATE ACCOUNT*/
        NewContact= new Contact(
            LastName='tnc ' +RandomString , 
            Email='testy13213@fffp.com'+RandomString, 
            FirstName = 'tnc'+RandomString, 
            Salutation = 'Mr',
            AccountId = account.id
        );
        insert NewContact;
        
        /* CREATE OPPORTUNITY*/
        opportunity = new Opportunity(
            Name = 'tncopp '+RandomString,
            AccountId = account.Id,
            StageName = 'Qualifying',
            CloseDate = Date.today(), 
            Pricebook2Id = pbe2Test.Id,
            RecordTypeId = rType.Id);
        insert opportunity;
        
        /* CREATE OPP LINE ITEMS*/
        OppLineItem = new OpportunityLineItem(
            OpportunityId = opportunity.Id,
            PricebookEntryId = pbeTest.Id,
            Pricing_Exception__c = true,
            Quantity = 3,
            UnitPrice = 320);
        insert OppLineItem;
        
        specialEvent1 = new Special_Event__c(
            Opportunity__c = opportunity.Id,
            Name = 'tnc1 '+ RandomString,
            Product__c = testProd.Id,
            Type__c = 'In-Company Training',
            Status__c = 'Allocating',
            Stage__c = 'Provisional',
            StartDate__c = Date.today(),
            EndDate__c = Date.today().addDays(5));
        insert specialEvent1;
        
        /* CREATE BSC EVENT BOOKING*/
        Special_Event_Booking__c specialEventbooking2 = new Special_Event_Booking__c(
            Opportunity__c = opportunity.Id,
            Booking_Fee__c =  10000,
            Special_Event__c = specialEvent1.Id,
            Type__c = 'Public',
            OPL_ID__c = OppLineItem.Id,
            status__c = 'Provisional'
        );
        insert specialEventbooking2;
        
        PageReference ref = new PageReference('/apex/tncInCompanyCancellation?id='+ opportunity.id +'&Object=Opportunity');
        Test.setCurrentPage(ref); 
        tncInCompanyCancellationController con = new tncInCompanyCancellationController();
        
        system.assert (con.eventsListing.size() > 0);
        system.debug(con.hasNext);
        system.debug(con.hasPrevious);
        if (con.hasNext)
            con.next();
        if (con.hasPrevious)
            con.previous();
        
        
        con.showCancellationFeeSection(); 
        
        datetime dated = system.Date.today();
        for (tncEventsWrapper wrapper : con.eventsListing){
            wrapper.isSelected = true;
            wrapper.reasonData.cancellationRequestedOn = (dated +1).format('dd/MM/yyyy');
            wrapper.reasonData.reason = 'Client postponed decision';
            wrapper.reasonData.reasonNote = '';
            
        }
        
        con.AutoSelectAllRecords();
        
        for (tncEventsWrapper wrapper : con.eventsListing){
            if (wrapper.isSelected){
                wrapper.reasonData.cancellationRequestedOn = (dated +1).format('dd/MM/yyyy');
                wrapper.reasonData.reason = 'Select Reason';
                wrapper.reasonData.reasonNote = '';
            }
        }
        con.showCancellationFeeSection(); 
        
        for (tncEventsWrapper wrapper : con.eventsListing){
            if (wrapper.isSelected){
                wrapper.reasonData.cancellationRequestedOn = (dated + 1).format('dd/MM/yyyy');
                wrapper.reasonData.reason = 'Adverse weather or safety risk';
                wrapper.reasonData.reasonNote = '';
            }
        }
        con.showCancellationFeeSection(); 
        
        for (tncEventsWrapper wrapper : con.eventsListing){
            if (wrapper.isSelected){
                wrapper.reasonData.cancellationRequestedOn = dated.format('dd/MM/yyyy');
                wrapper.reasonData.reason = 'Client no longer interested';
                wrapper.reasonData.reasonNote = 'Test';
            }
        }
        system.debug('con.eventsListing'+ con.eventsListing);
        con.showCancellationFeeSection(); 
        con.showEventsToSelect();
        con.processCancellation();
        con.cancel();
    }
    
    static testMethod void TestInCoConfirmed() {
        Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
        
        Product2  tranProd = new Product2 (name = 'Tran Fee InCompanyC' );
        insert tranProd;
        
        Product2  cancProd = new Product2 (name = 'Cancellation Fee InCompanyC');
        insert cancProd;
        
        Product2  testProd = new Product2 (name = 'InCompanyC Test', Cancellation_Fee_Product__c=cancProd.id, Transfer_Fee_Product__c= tranProd.id);
        insert testProd;
        
        
        Pricebook2 pbe2Test = new Pricebook2(name =  'InCompanyC Test');
        insert pbe2Test;
        
        Pricebook2 pbe2Tran = new Pricebook2(name =  'Tran Fee InCompanyC');
        insert pbe2Tran;
        
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = testProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice;
        PricebookEntry pbeTest = new PricebookEntry(Product2Id = testProd.Id, Pricebook2Id = pbe2Test.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeTest;
        
        PricebookEntry standardPrice1 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = cancProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice1;
        PricebookEntry pbeCanc = new PricebookEntry(Product2Id = cancProd.Id, Pricebook2Id = pbe2Test.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeCanc;
        
        PricebookEntry standardPrice2 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id=tranProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice2;
        PricebookEntry pbeTran = new PricebookEntry(Product2Id = tranProd.Id, Pricebook2Id = pbe2Tran.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeTran; 
        
        RecordType rType = [select id from RecordType where name = 'In-Company Event' and sObjectType = 'Opportunity'];
        
        id Dimension1Id = [select id from c2g__codaDimension1__c where name = '110 - Finance' limit 1].id;
        id Dimension2Id = [select id from c2g__codaDimension2__c where name = '0000 - General' limit 1].id;
        id glaid = [select id from c2g__codaGeneralLedgerAccount__c where name = '3000 - Income - Sales Activities' Limit 1].Id;
        
        /* CREATE ACCOUNT*/
        account = new Account(
            name = 'tnc '+ RandomString); 
        insert account;
        
        /* CREATE ACCOUNT*/
        NewContact= new Contact(
            LastName='tnc ' +RandomString , 
            Email='testy13213@fffp.com'+RandomString, 
            FirstName = 'tnc'+RandomString, 
            Salutation = 'Mr',
            AccountId = account.id
        );
        insert NewContact;
        
        /* CREATE OPPORTUNITY*/
        opportunity = new Opportunity(
            Name = 'tncopp '+RandomString,
            AccountId = account.Id,
            StageName = 'Qualifying',
            CloseDate = Date.today(), 
            Pricebook2Id = pbe2Test.Id,
            RecordTypeId = rType.Id);
        insert opportunity;
        
        /* CREATE OPP LINE ITEMS*/
        OppLineItem = new OpportunityLineItem(
            OpportunityId = opportunity.Id,
            PricebookEntryId = pbeTest.Id,
            Pricing_Exception__c = true,
            Quantity = 3,
            UnitPrice = 320);
        insert OppLineItem;
        
        /* CREATE BSC EVENT*/
        Special_Event__c specialEvent2 = new Special_Event__c(
            Opportunity__c = opportunity.Id,
            Name = 'tnc1 '+ RandomString,
            Product__c = testProd.Id,
            Type__c = 'In-Company Training',
            Status__c = 'Confirmed',
            Stage__c = 'Confirmed',
            StartDate__c = Date.today(),
            EndDate__c = Date.today().addDays(5));
        insert specialEvent2;
        
        /* CREATE BSC EVENT BOOKING*/
        Special_Event_Booking__c specialEventbooking2 = new Special_Event_Booking__c(
            Opportunity__c = opportunity.Id,
            Booking_Fee__c =  10000,
            Special_Event__c = specialEvent2.Id,
            Type__c = 'Public',
            OPL_ID__c = OppLineItem.Id,
            status__c = 'Confirmed'
        );
        insert specialEventbooking2;
        
        PageReference ref = new PageReference('/apex/tncInCompanyCancellation?id='+ opportunity.id +'&Object=Opportunity');
        Test.setCurrentPage(ref); 
        tncInCompanyCancellationController con = new tncInCompanyCancellationController();
        
        system.assert (con.eventsListing.size() > 0);
        system.debug(con.hasNext);
        system.debug(con.hasPrevious);
        if (con.hasNext)
            con.next();
        if (con.hasPrevious)
            con.previous();
        
        
        con.showCancellationFeeSection(); 
        
        con.AutoSelectAllRecords();
        
        datetime dated = system.Date.today();
        for (tncEventsWrapper wrapper : con.eventsListing){
            wrapper.reasonData.cancellationRequestedOn = (dated).format('dd/MM/yyyy');
            wrapper.reasonData.reason = 'Select Reason';
        }
        con.showCancellationFeeSection(); 
        
        for (tncEventsWrapper wrapper : con.eventsListing){
            wrapper.reasonData.cancellationRequestedOn = (dated + 1).format('dd/MM/yyyy');
            wrapper.reasonData.reason = 'Adverse weather or safety risk';
            wrapper.reasonData.reasonNote = '';
        }
        con.showCancellationFeeSection(); 
        
        for (tncEventsWrapper wrapper : con.eventsListing){
            wrapper.reasonData.cancellationRequestedOn = dated.format('dd/MM/yyyy');
            wrapper.reasonData.reason = 'Client no longer interested';
            wrapper.reasonData.reasonNote = 'Test';
        }
        system.debug('con.eventsListing'+ con.eventsListing);
        con.showCancellationFeeSection(); 
        con.showEventsToSelect();
        con.processCancellation();
        con.cancel();
    }
    
    
    static testMethod void TestInCoConfirmedTransfer() {
        Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
        
        Product2  tranProd = new Product2 (name = 'Tran Fee InCompanyC' );
        insert tranProd;
        
        Product2  cancProd = new Product2 (name = 'Cancellation Fee InCompanyC');
        insert cancProd;
        
        Product2  testProd = new Product2 (name = 'InCompanyC Test', Cancellation_Fee_Product__c=cancProd.id, Transfer_Fee_Product__c= tranProd.id);
        insert testProd;
        
        
        Pricebook2 pbe2Test = new Pricebook2(name =  'InCompanyC Test');
        insert pbe2Test;
        
        Pricebook2 pbe2Tran = new Pricebook2(name =  'Tran Fee InCompanyC');
        insert pbe2Tran;
        
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = testProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice;
        PricebookEntry pbeTest = new PricebookEntry(Product2Id = testProd.Id, Pricebook2Id = pbe2Test.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeTest;
        
        PricebookEntry standardPrice1 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = cancProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice1;
        PricebookEntry pbeCanc = new PricebookEntry(Product2Id = cancProd.Id, Pricebook2Id = pbe2Test.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeCanc;
        
        PricebookEntry standardPrice2 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id=tranProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice2;
        PricebookEntry pbeTran = new PricebookEntry(Product2Id = tranProd.Id, Pricebook2Id = pbe2Tran.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeTran; 
        
        RecordType rType = [select id from RecordType where name = 'In-Company Event' and sObjectType = 'Opportunity'];
        
        id Dimension1Id = [select id from c2g__codaDimension1__c where name = '110 - Finance' limit 1].id;
        id Dimension2Id = [select id from c2g__codaDimension2__c where name = '0000 - General' limit 1].id;
        id glaid = [select id from c2g__codaGeneralLedgerAccount__c where name = '3000 - Income - Sales Activities' Limit 1].Id;
        
        /* CREATE ACCOUNT*/
        account = new Account(
            name = 'tnc '+ RandomString); 
        insert account;
        
        /* CREATE ACCOUNT*/
        NewContact= new Contact(
            LastName='tnc ' +RandomString , 
            Email='testy13213@fffp.com'+RandomString, 
            FirstName = 'tnc'+RandomString, 
            Salutation = 'Mr',
            AccountId = account.id
        );
        insert NewContact;
        
        /* CREATE OPPORTUNITY*/
        opportunity = new Opportunity(
            Name = 'tncopp '+RandomString,
            AccountId = account.Id,
            StageName = 'Qualifying',
            CloseDate = Date.today(), 
            Pricebook2Id = pbe2Test.Id,
            RecordTypeId = rType.Id);
        insert opportunity;
        
        /* CREATE OPP LINE ITEMS*/
        OppLineItem = new OpportunityLineItem(
            OpportunityId = opportunity.Id,
            PricebookEntryId = pbeTest.Id,
            Pricing_Exception__c = true,
            Quantity = 3,
            UnitPrice = 320);
        insert OppLineItem;
        
        /* CREATE BSC EVENT*/
        Special_Event__c specialEvent2 = new Special_Event__c(
            Opportunity__c = opportunity.Id,
            Name = 'tnc1 '+ RandomString,
            Product__c = testProd.Id,
            Type__c = 'In-Company Training',
            Status__c = 'Confirmed',
            Stage__c = 'Confirmed',
            StartDate__c = Date.today(),
            EndDate__c = Date.today().addDays(5));
        insert specialEvent2;
        
        /* CREATE BSC EVENT BOOKING*/
        Special_Event_Booking__c specialEventbooking2 = new Special_Event_Booking__c(
            Opportunity__c = opportunity.Id,
            Booking_Fee__c =  10000,
            Special_Event__c = specialEvent2.Id,
            Type__c = 'Public',
            OPL_ID__c = OppLineItem.Id,
            status__c = 'Confirmed'
        );
        insert specialEventbooking2;
        
        PageReference ref = new PageReference('/apex/tncInCompanyTransfer?oppId='+ opportunity.id +'&Object=Opportunity');
        Test.setCurrentPage(ref); 
        tncInCompanyTransferController con = new tncInCompanyTransferController();
        
        system.assert (con.eventsListing.size() > 0);
        system.debug(con.hasNext);
        system.debug(con.hasPrevious);
        if (con.hasNext)
            con.next();
        if (con.hasPrevious)
            con.previous();
        
        con.showTransferFeeSection(); 
        con.showEventsToSelect(); 
        con.AutoSelectAllRecords();
        
        datetime dated = system.Date.today();
        for (tncEventsWrapper wrapper : con.pager.transferEvents){
            wrapper.reasonData.transferRequestedOn = (dated).format('dd/MM/yyyy');
            wrapper.reasonData.reason = 'Select Reason';
        }
        con.showTransferFeeSection(); 
        for (tncEventsWrapper wrapper : con.pager.transferEvents){
            wrapper.reasonData.transferRequestedOn = (dated + 1).format('dd/MM/yyyy');
            wrapper.reasonData.reason = 'Adverse weather or safety risk';
            wrapper.reasonData.reasonNote = '';
        }
        con.showTransferFeeSection(); 
        
        for (tncEventsWrapper wrapper : con.pager.transferEvents){
            wrapper.reasonData.transferRequestedOn = dated.format('dd/MM/yyyy');
            wrapper.reasonData.reason = 'Client no longer interested';
            wrapper.reasonData.reasonNote = 'Test';
            wrapper.isSelected = true;
        }
        con.showTransferFeeSection(); 
        system.assert (con.selectedEventsListing.size() > 0);
        for (tncEventsWrapper wrapper : con.pager.transferEvents){
            wrapper.transferAction = 'To be Transferred';
        }
        
        con.process();
    }
    
    static testMethod void TestPubEventBookingCancellation() {
        Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
        
        Product2  tranProd = new Product2 (name = 'Tran Fee pubCanc', Maximum_Discount__c=100, Discount_Permitted__c=true );
        insert tranProd;
        
        Product2  cancProd = new Product2 (name = 'Cancellation Fee pubCanc', Maximum_Discount__c=100, Discount_Permitted__c=true);
        insert cancProd;
        
        Product2  testProd = new Product2 (name = 'pubCanc Test', Cancellation_Fee_Product__c=cancProd.id, Transfer_Fee_Product__c= tranProd.id);
        insert testProd;
        
        
        Pricebook2 pbe2Test = new Pricebook2(name =  'pubCanc Test');
        insert pbe2Test;
        
        Pricebook2 pbe2Tran = new Pricebook2(name =  'Tran Fee pubCanc');
        insert pbe2Tran;
        
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = testProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice;
        PricebookEntry pbeTest = new PricebookEntry(Product2Id = testProd.Id, Pricebook2Id = pbe2Test.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeTest;
        
        PricebookEntry standardPrice1 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = cancProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice1;
        PricebookEntry pbeCanc = new PricebookEntry(Product2Id = cancProd.Id, Pricebook2Id = pbe2Test.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeCanc;
        
        PricebookEntry standardPrice2 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id=tranProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice2;
        PricebookEntry pbeTran = new PricebookEntry(Product2Id = tranProd.Id, Pricebook2Id = pbe2Tran.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeTran; 
        
        RecordType rType = [select id from RecordType where name = 'Public Event' and sObjectType = 'Opportunity'];
        
        id Dimension1Id = [select id from c2g__codaDimension1__c where name = '110 - Finance' limit 1].id;
        id Dimension2Id = [select id from c2g__codaDimension2__c where name = '0000 - General' limit 1].id;
        id glaid = [select id from c2g__codaGeneralLedgerAccount__c where name = '3000 - Income - Sales Activities' Limit 1].Id;
        
        /* CREATE ACCOUNT*/
        account = new Account(
            name = 'tnc '+ RandomString); 
        insert account;
        
        /* CREATE ACCOUNT*/
        NewContact= new Contact(
            LastName='tnc ' +RandomString , 
            Email='testy13213@fffp.com'+RandomString, 
            FirstName = 'tnc'+RandomString, 
            Salutation = 'Mr',
            AccountId = account.id
        );
        insert NewContact;
        
        /* CREATE OPPORTUNITY*/
        opportunity = new Opportunity(
            Name = 'tncopp '+RandomString,
            AccountId = account.Id,
            StageName = 'Qualifying',
            CloseDate = Date.today(), 
            Pricebook2Id = pbe2Test.Id,
            RecordTypeId = rType.Id);
        insert opportunity;
        
        /* CREATE OPP LINE ITEMS*/
        OppLineItem = new OpportunityLineItem(
            OpportunityId = opportunity.Id,
            PricebookEntryId = pbeTest.Id,
            Pricing_Exception__c = true,
            Quantity = 3,
            UnitPrice = 320);
        insert OppLineItem;
        
        /* CREATE BSC EVENT*/
        Special_Event__c specialEvent2 = new Special_Event__c(
            Name = 'tnc1 '+ RandomString,
            Product__c = testProd.Id,
            Type__c = 'In-Company Training',
            Status__c = 'Resourced',
            Stage__c = 'Provisional',
            StartDate__c = Date.today(),
            EndDate__c = Date.today().addDays(5));
        insert specialEvent2;
        
        Transfer_Cancellation_Reasons__c tr = [select id from Transfer_Cancellation_Reasons__c limit 1][0];
        
        /* CREATE BSC EVENT BOOKING*/
        Special_Event_Booking__c specialEventbooking2 = new Special_Event_Booking__c(
            Opportunity__c = opportunity.Id,
            Booking_Fee__c =  10000,
            Special_Event__c = specialEvent2.Id,
            Type__c = 'Public',
            OPL_ID__c = OppLineItem.Id,
            status__c = 'Provisional',
            Transfer_Cancellation_Reason__c = tr.id,
            Transfer_Cancellation_Notes__c = 'Test',
            Transfer_Cancellation_Fee__c = 100,
            Customer_Cancellation_Transfer_Date__c = system.today()
        );
        insert specialEventbooking2;
        
        Special_Event_Booking__c specialEventbooking3 = new Special_Event_Booking__c(
            Opportunity__c = opportunity.Id,
            Booking_Fee__c =  1000,
            Special_Event__c = specialEvent2.Id,
            Type__c = 'Public',
            OPL_ID__c = OppLineItem.Id,
            status__c = 'Confirmed'
        );
        insert specialEventbooking3;
        
        PageReference ref = new PageReference('/apex/tncPublicEventCancellation?oppId='+ opportunity.id);
        Test.setCurrentPage(ref); 
        
        tncPublicEventCancellationController con = new tncPublicEventCancellationController();
        con.visibleSection(true,false);
        
        system.assert (con.listBookings.size() > 0);
        system.debug(con.hasNext);
        system.debug(con.hasPrevious);
        
        con.handler.setPageSize = 1;
        if (con.hasNext)
            con.next();
        if (con.hasPrevious)
            con.previous();
        con.handler.setPageSize = 10;
        
        con.checkReason(); 
        con.autoSelectAllRecords();
        
        datetime dated = system.Date.today();
        for (tncPublicEventCancellationWrapper wrapper : con.handler.allBookings){
            wrapper.reasonData.cancellationRequestedOn = (dated).format('dd/MM/yyyy');
            wrapper.reasonData.reason = 'Select Reason';
        }
        con.checkReason(); 
        for (tncPublicEventCancellationWrapper wrapper : con.handler.allBookings){
            wrapper.reasonData.cancellationRequestedOn = (dated + 1).format('dd/MM/yyyy');
            wrapper.reasonData.reason = 'Adverse weather or safety risk';
            wrapper.reasonData.reasonNote = '';
        }
        con.checkReason(); 
        
        for (tncPublicEventCancellationWrapper wrapper : con.handler.allBookings){
            wrapper.reasonData.cancellationRequestedOn = dated.format('dd/MM/yyyy');
            wrapper.reasonData.reason = 'Client no longer interested';
            wrapper.reasonData.reasonNote = 'Test';
            wrapper.isSelected = true;
        }
        con.checkReason(); 
        con.processCancellation();
    }
    
}