src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Principle_Address_ZIP_Postal_Code__c</fullName>
        <label>Principle Address: ZIP / Postal Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Can this Account be used as a venue?</description>
        <inlineHelpText>Can this Account be used as a venue?</inlineHelpText>
        <label>Venue?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>BSC_Event_Trainer__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>BSC Event Trainer</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Event_Account_Name__c</fullName>
        <description>Auto-populated on creation of BSC Event Trainer records</description>
        <inlineHelpText>Name of Account (for In-Company Events)</inlineHelpText>
        <label>Event Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Postcode__c</fullName>
        <description>Auto populated on creation of BSC Event Trainer records to allow tracking of locations</description>
        <label>Event Postcode</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Audit_Outcome__c.object
<CustomObject>
    <description>This houses the findings of an audit and is driven by the compliance areas object</description>
    <fields>
        <fullName>BSC_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BSC Event</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Audit outcomes can only be used as a result of an audit.</errorMessage>
            <filterItems>
                <field>Special_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Audit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>Audit Outcomes</relationshipLabel>
        <relationshipName>Audit_Outcomes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Draft Report</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Chased Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Formatter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to be printed externally</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No report required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extension Agreed with Auditor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Audit Outcome</label>
    <nameField>
        <displayFormat>AO-{0000000}</displayFormat>
        <label>Audit Outcome Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Outcomes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Calculates the number of days the event takes place using the start and end dates (this doesn&apos;t take into account gaps between unit days or weekends)</description>
        <formula>EndDate__c -StartDate__c +1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Number of days from Start to Finish</inlineHelpText>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Shows the stage of the event, which is a dependant pick list of the status field</description>
        <inlineHelpText>Shows the stage of the event, which is a dependant pick list of the status field</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Venue in which the event is being held</description>
        <inlineHelpText>Select the event venue. For an In-company event held on company premises, select the account</inlineHelpText>
        <label>Venue</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Venue</value>
            </filterItems>
            <infoMessage>Search is limited to venues. Select &quot;Show all results&quot; to expand search to all organisations (for In-Company Events)</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events (Held in this Venue)</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Trainer__c.object
<CustomObject>
    <description>Object for tracking which trainers are assigned to an event</description>
    <fields>
        <fullName>BSC_Event_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the event unit (day/time) that the trainer is scheduled to train on</description>
        <inlineHelpText>This is a lookup to the event unit (day/time) that the trainer is scheduled to train on</inlineHelpText>
        <label>BSC Event Unit</label>
        <referenceTo>Special_Event_Unit__c</referenceTo>
        <relationshipLabel>BSC Event Trainers</relationshipLabel>
        <relationshipName>BSC_Event_Trainers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BSC_Event__c</fullName>
        <description>This is the lookup to the event that the trainer is scheduled to train on</description>
        <inlineHelpText>This is the lookup to the event that the trainer is scheduled to train on</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Trainers</relationshipLabel>
        <relationshipName>BSC_Event_Trainers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the trainer record</description>
        <inlineHelpText>Lookup field to the trainer record</inlineHelpText>
        <label>Trainer</label>
        <referenceTo>Trainer__c</referenceTo>
        <relationshipLabel>BSC Event Trainers</relationshipLabel>
        <relationshipName>BSC_Event_Trainers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Trainer</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>BSC Event Trainer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Trainers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit__c.object
<CustomObject>
    <description>Object to manage Units of an event, e.g. sessions or components</description>
    <fields>
        <fullName>BSC_Event_Trainer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to trainer related to the event, shows who will be training/auditing on that day</description>
        <inlineHelpText>Select the trainer (only trainers attached to this event can be selected)</inlineHelpText>
        <label>BSC Event Trainer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Event_Trainer__c.BSC_Event__c</field>
                <operation>equals</operation>
                <valueField>$Source.Special_Event__c</valueField>
            </filterItems>
            <infoMessage>You can only select Unit trainers that have been attached to the Event.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Event_Trainer__c</referenceTo>
        <relationshipLabel>BSC Event Units</relationshipLabel>
        <relationshipName>BSC_Event_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>shows the duration of the event unit depending on the times of the unit and is calculated by a workflow</description>
        <inlineHelpText>Duration in Days (0.5 or 1), calculated by workflow</inlineHelpText>
        <label>Duration</label>
        <precision>2</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>Related event</description>
        <inlineHelpText>Related event</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Units</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_End_Time__c</fullName>
        <description>Stores the End Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event.</description>
        <inlineHelpText>Stores the End Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event.</inlineHelpText>
        <label>Unit End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Unit_Start_Time__c</fullName>
        <description>Stores the Start Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event</description>
        <inlineHelpText>Stores the Start Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event</inlineHelpText>
        <label>Unit Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the Unit venue (if different from the Event venue)</description>
        <inlineHelpText>Select the Unit venue (if different from the Event venue)</inlineHelpText>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Units (Held in this Venue)</relationshipLabel>
        <relationshipName>BSC_Event_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Unit</label>
    <nameField>
        <label>Event Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Event Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trainer__c.object
<CustomObject>
    <description>Object for managing which trainers (users) are capable of teaching which courses (products)</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup to the user who is related to the trainer record.</description>
        <inlineHelpText>This is the lookup to the user who is related to the trainer record.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trainers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Trainer</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Trainer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Trainer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trainer</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EventTrainerHelper.cls
/*
    Created by Ben Mansfield 27 July 2010
    Modified by Ben Mansfield 4 August 2010
    
    Description:
        Note: Cannot set events to private whilst setting the WhatId
                Cannot create an event over 14 days (SF Event limit)
        
    Changes:
    
        12 December 2011
        * Added functionality to remove sharing rules & trainer activities on deletion of the trainer.
        
        4 August 2010
        * Modified so event is linked to event trainer, not event
        
        28 September 2010
        * AB
        * Modified to work with BSC Event Units instead of BSC Events.
        
        
*/
public class EventTrainerHelper
{
    private static final String INVALID_EVENT_LENGTH = 'An Event can be no longer than 14 days.';
    

    public static void createSharingRule(List<Special_Event_Trainer__c> eventTrainerList)
    {
    
        Set<Id> trainerId = new Set<Id>();
        Set<Id> bscEventId = new Set<Id>();
        Set<Id> userId = new Set<Id>();
        Map<Id,Id> trainerMap = new Map<Id,Id>();
        Set<String> eventSharingKey = new Set<String>();
        List<Special_Event__Share> insertSharingRule = new List<Special_Event__Share>();
        
        for(Special_Event_Trainer__c eventTrainer:eventTrainerList)
        {
            //List of trainer ids
            trainerId.add(eventTrainer.Trainer__c);
            //List of event ids
            bscEventId.add(eventTrainer.BSC_Event__c);
        }
        
        for(Trainer__c trainer:[Select Id,User__c from Trainer__c where Id IN:trainerId])
        {
            //Map of trainer records
            trainerMap.put(trainer.Id,trainer.User__c);
            //List of user ids
            userId.add(trainer.User__c);
        
        }
        //Check if there is an existing sharing record against the user
        for(Special_Event__Share eventShare:[Select s.UserOrGroupId, 
                                                    s.ParentId 
                                                    From Special_Event__Share s 
                                                    where s.UserOrGroupId IN:userId
                                                    and s.ParentId IN:bscEventId])
        {
            eventSharingKey.add(eventShare.ParentId+';'+eventShare.UserOrGroupId);
        }
        
        for(Special_Event_Trainer__c eventTrainer:eventTrainerList)
        {
            if(trainerMap.containsKey(eventTrainer.Trainer__c))
            {
            
                Id userTrainerId = trainerMap.get(eventTrainer.Trainer__c);
                if(!eventSharingKey.isEmpty())
                {

                    if(!eventSharingKey.contains(eventTrainer.BSC_Event__c+';'+userTrainerId))
                    {
                        Special_Event__Share sharingRecord = new Special_Event__Share(ParentId =eventTrainer.BSC_Event__c,
                                                                                     UserOrGroupId=userTrainerId,
                                                                                     AccessLevel = 'Read');
                                   
                        insertSharingRule.add(sharingRecord); 
                        
                    }
            
                }else{
                
                    Special_Event__Share sharingRecord = new Special_Event__Share(ParentId =eventTrainer.BSC_Event__c,
                                                                                  UserOrGroupId=userTrainerId,
                                                                                  AccessLevel = 'Read');
                                   
                    insertSharingRule.add(sharingRecord); 
                }    
                
            }
            
        }
        if(!insertSharingRule.isEmpty())
            insert insertSharingRule;
    
    }
    
    /*
     * DELETE TRAINERS
     * 
     * 1. Deletes the related activity records for the trainer events.
     * 2. Removes the sharing rule if the trainer is no longer on the event.
     */
    public static void deleteTrainers(List<Special_Event_Trainer__c> eventTrainers){
        
        // Delete all the activities off when the event trainer is deleted.
        Event[] eventsToDelete = [SELECT Id FROM Event WHERE WhatId IN :eventTrainers];
        delete eventsToDelete;

        // Delete the manual sharing rule for the trainer off the event IF the trainer does
        // not have any other training records associated with the event.

        Special_Event_Trainer__c[] toRemoveSharingRule;

        for(Special_Event_Trainer__c eTrainer : eventTrainers){
        	
        }
        
    }
    
    
    public static void generateEvents(List<Special_Event_Trainer__c> newEventTrainerRecords,
        Map<Id, Special_Event_Trainer__c> oldEventTrainerRecords)
    {
        Map<Id, Event> events = new Map<Id, Event>();
        
        // If this is executing in an insert trigger
        if (!Trigger.isInsert)
        { 
            // If events already exist for the event trainer records, get them
            for (Event e : [
                SELECT
                    Id,
                    BSC_Event_Trainer__c
                FROM
                    Event
                WHERE
                    BSC_Event_Trainer__c IN :oldEventTrainerRecords.keySet()])
            {
                events.put(e.BSC_Event_Trainer__c, e);
            }
        }
        
        // If this is executing in a delete trigger, delete the associated Events
        if (Trigger.isDelete)
            delete events.values();
        else
        {
            // Update / Insert records.
            
            // Get trainer booking record type.
            List<RecordType> trainerBookingRecordType = [
                SELECT
                    Id
                FROM
                    RecordType
                WHERE
                    SObjectType = 'Event'
                AND
                    Name = 'Trainer Booking' Limit 1];
            
            
            Set<Id> eventTrainerIds = new Set<Id>();
            Set<Id> trainerIds = new Set<Id>();
            Set<Id> unitIds = new Set<Id>();
            
            // Get a list of Event Trainer ids being Updated / Inserted
            for (Special_Event_Trainer__c et : newEventTrainerRecords)
            {
                eventTrainerIds.add(et.Id);
                trainerIds.add(et.Trainer__c);
                unitIds.add(et.BSC_Event_Unit__c);
            }
            Map<Id,Special_Event_Trainer__c> currentEventTrainer = new Map<Id,Special_Event_Trainer__c>([Select Id,
                                                                                                                BSC_Event__r.Venue__r.Principle_Address_Zip_Postal_Code__c,
                                                                                                                BSC_Event__r.Opportunity__r.Account.Name
                                                                                                                from Special_Event_Trainer__c
                                                                                                                where Id IN:eventTrainerIds ]);
            // Get trainers
            Map<Id, Trainer__c> trainers = new Map<Id, Trainer__c>([
                SELECT
                    Id,
                    User__c
                FROM
                    Trainer__c
                WHERE
                    Id in :trainerIds]);
                    
            // Get BSC Event Units for this BSC Event Trainer.
            List<Special_Event_Unit__c> trainerUnits = new List<Special_Event_Unit__c>([
                SELECT
                    Id,
                    Duration__c,
                    Unit_Start_Time__c,
                    Unit_End_Time__c,
                    Special_Event__c,
                    Special_Event__r.Name,
                    Special_Event__r.Stage__c,
                    BSC_Event_Trainer__c,
                    Name
                FROM
                    Special_Event_Unit__c
                WHERE
                    Id IN :unitIds
                ORDER BY
                    Special_Event__c]);
            

            // Trainers can have multiple BSC Event Units, so get all Event Units for these Trainers.
//          List<Special_Event_Unit__c> trainerUnits = new List<Special_Event_Unit__c>([
//              SELECT
//                  Id,
//                  Duration__c,
//                  Unit_Start_Time__c,
//                  Unit_End_Time__c,
//                  Special_Event__c,
//                  Special_Event__r.Stage__c,
//                  BSC_Event_Trainer__c
//              FROM
//                  Special_Event_Unit__c
//              WHERE
//                  BSC_Event_Trainer__c IN :eventTrainerIds
//              ORDER BY
//                  Special_Event__c]);
    
            // Create a trainer list, so we can calculate the total time for the event
            // from the Unit Start Time and Duration - if the trainer has no units, the list will not contain him.          
            
            
            // Can't do this, trainer units do not contain a reference to the Special_Event_Trainer__c until after this method has returned.
            List<TrainerUnitsEx> trainerUnitsEx = new List<TrainerUnitsEx>();
            for (Special_Event_Trainer__c et : newEventTrainerRecords)
            {
                trainerUnitsEx.add(new TrainerUnitsEx(et, trainerUnits));
            }
            
            System.debug('*****************************\n\n TRAINERUNITS SIZE: ' + trainerUnitsEx.size() + '\n\n***********************************');
            
            for (TrainerUnitsEx trainerUnitEx : TrainerUnitsEx)
            {
                system.debug('events.containsKey(trainerUnitEx.trainer.Id) : ' + events.containsKey(trainerUnitEx.trainer.Id));
                if (events.containsKey(trainerUnitEx.trainer.Id))
                {
                    trainerUnitEx.UpdateEventForEventUnit(
                        trainerBookingRecordType.get(0).Id, trainers, events.get(trainerUnitEx.trainer.Id));
                }
                else
                {
                    Event event = trainerUnitEx.CreateEventForEventUnit(trainerBookingRecordType.get(0).Id, trainers);
                    if (event != null)
                    {
                        if(currentEventTrainer.containsKey(event.WhatId))
                        {   
                            event.Event_Postcode__c = currentEventTrainer.get(event.WhatId).BSC_Event__r.Venue__r.Principle_Address_Zip_Postal_Code__c;
                            event.Event_Account_Name__c = currentEventTrainer.get(event.WhatId).BSC_Event__r.Opportunity__r.Account.Name;
                        }   
                        
                        events.put(trainerUnitEx.trainer.Id, event);
                    }
                }
            }
            system.debug('EventList'+events.values());
            upsert events.values();
            System.debug('****************************************\n\nEVENTS TO UPDATE: ' + events.size() + '\n\n******************************');
        }
    }
    
    public class TrainerUnitsEx
    {
        private Special_Event_Trainer__c trainer;
        private Special_Event_Unit__c unit;
        
        
        public TrainerUnitsEx(Special_Event_Trainer__c trainer, List<Special_Event_Unit__c> units)
        {
            this.trainer = trainer;
            for (Special_Event_Unit__c unit : units)
            {
                if (trainer.BSC_Event_Unit__c == unit.Id)
                {
                    this.unit = unit;
                    return;
                }
//              if (unit.BSC_Event_Trainer__c == trainer.Id)
//              {
//                  this.unit = unit;
//                  return;
//              }           
            }           
        }
        
        public Event CreateEventForEventUnit(Id recordTypeId, Map<Id, Trainer__c> trainers)
        {
            if (this.unit != null)
            {
                Event event = new Event();
                return UpdateEventForEventUnit(recordTypeId, trainers, event);
            }
            return null;
        }
        
        public Event UpdateEventForEventUnit(Id recordTypeId, Map<Id, Trainer__c> trainers, Event event)
        {
            if (this.unit != null)
            {
                event.BSC_Event_Trainer__c = this.trainer.Id;
                event.RecordTypeId = recordTypeId;
                /*event.Subject = this.unit.Special_Event__r.Name + ' - ' +
                    this.trainer.BSC_Event__r.Stage__c + ' - ' +
                    this.trainer.Status__c + ' - ' +
                    this.trainer.BSC_Event__r.Venue__r.Principle_Address_Country__c;*/
                event.Subject = this.unit.Special_Event__r.Name + ' - ' +unit.Name;    
                event.IsAllDayEvent = true;
                event.StartDateTime = this.unit.Unit_Start_Time__c;
                event.EndDateTime = this.unit.Unit_End_Time__c;
                event.ShowAs = 'Busy';
                event.Event_Trainer_Status__c = this.trainer.Status__c;
                event.Event_Stage__c = this.unit.Special_Event__r.Stage__c;
                event.OwnerId = trainers.get(this.trainer.trainer__c).User__c;
                event.WhatId = this.trainer.Id;
                event.IsPrivate = false;
                
            }
            return event;
        }
    }
    
    public static void propogateTrainerToAO(list<Special_Event_Trainer__c> trainers){
        map<Id, id> events = new map<Id,id>();
        
        for (Special_Event_Trainer__c et : [select id, BSC_Event__c, Trainer__r.User__c from Special_Event_Trainer__c where id in :trainers])
            events.put(et.BSC_Event__c, et.Trainer__r.User__c);
        
        list<Audit_Outcome__c> audits = [select id, BSC_Event__c from Audit_Outcome__c where BSC_Event__c in :events.keySet()];
        
        for(Audit_Outcome__c ao : audits){
            ao.Auditor__c = events.get(ao.BSC_Event__c);
        }
        
        update audits;
    }
}