src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>c2g__CODADimension1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dimension 1</label>
        <referenceTo>c2g__codaDimension1__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c2g__CODADimension2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dimension 2</label>
        <referenceTo>c2g__codaDimension2__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Dimension_1__c</fullName>
        <description>To allow finance to see the dimension 1 code without clicking through to the product (Temporary until the Dimensions pull through to the Sales Invoices automatically)</description>
        <formula>PricebookEntry.Product2.Dimension_1__r.Name</formula>
        <inlineHelpText>To allow finance to see the dimension 1 code without clicking through to the product</inlineHelpText>
        <label>Dimension 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dimension_2__c</fullName>
        <description>To allow finance to see the dimension 2 code without clicking through to the product (Temporary until the Dimensions pull through to the Sales Invoices automatically)</description>
        <formula>PricebookEntry.Product2.Dimension_2__r.Name</formula>
        <inlineHelpText>To allow finance to see the dimension 2 code without clicking through to the product</inlineHelpText>
        <label>Dimension 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to mark cancellation reconciliation prices as exceptions to avoid triggering approval</description>
        <inlineHelpText>Checkbox to mark cancellation reconciliation prices as exceptions to avoid triggering approval</inlineHelpText>
        <label>Pricing Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in workflow</description>
        <inlineHelpText>Indicates if this product is a subscription product</inlineHelpText>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>c2g__CODAGeneralLedgerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Override Product GLA</label>
        <referenceTo>c2g__codaGeneralLedgerAccount__c</referenceTo>
        <relationshipLabel>Opportunity Line Items</relationshipLabel>
        <relationshipName>OpportunityLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Allows_Provisional_Bookings__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Ticking this box allows provisional bookings to be made through the Coursefinder page. (I.e. tick this on public events.)</inlineHelpText>
        <label>Allows Provisional Bookings</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Post_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>During subscription renewals if the opportunity includes a product with this ticked then the invoice will automatically be posted.</inlineHelpText>
        <label>Auto Post Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Core_Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This is used to determine which products should be displayed in the drop down lists on the online booking forms. If checked they won&apos;t be selected. You MUST update all subscription lines using this product to refresh data if this field is changed.</inlineHelpText>
        <label>Core Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dimension_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dimension 1</label>
        <referenceTo>c2g__codaDimension1__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dimension_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dimension 2</label>
        <referenceTo>c2g__codaDimension2__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Used for subscription products only determine the length of the subscription.</description>
        <inlineHelpText>Used for subscription products only determine the length of the subscription.</inlineHelpText>
        <label>Duration</label>
        <picklist>
            <picklistValues>
                <fullName>1 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100 Years</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Initial_Reminder_Days__c</fullName>
        <defaultValue>90</defaultValue>
        <description>Number of days before expiry that an initial reminder should be generated</description>
        <inlineHelpText>How many days before expiry should an initial reminder be generated?</inlineHelpText>
        <label>Initial Reminder Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates if the product is a Membership (affects Trader vs Member distinction on Account)</inlineHelpText>
        <label>Membership</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to feed automatic generation of Subscriptions and Subscription Lines</description>
        <inlineHelpText>Should sales of this product generate Subscriptions and Subscription Lines?</inlineHelpText>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>c2g__CODASalesRevenueAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The general ledger account to which sales revenues for this product be posted.</description>
        <label>Sales Revenue Account</label>
        <referenceTo>c2g__codaGeneralLedgerAccount__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <description>Record type for General Products,Tangible Goods, and Special Events and Ceremonies</description>
        <label>General</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Calculates the number of days the event takes place using the start and end dates (this doesn&apos;t take into account gaps between unit days or weekends)</description>
        <formula>EndDate__c -StartDate__c +1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Number of days from Start to Finish</inlineHelpText>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Determines the type of event from a picklist</description>
        <inlineHelpText>Determine the type of event from the picklist</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NVQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Defines the event booking type whether primary or additional etc</description>
        <inlineHelpText>Defines the event booking type whether primary or additional etc</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional - On the Day</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EventBeforeDeleteTest.cls
@istest(SeeAllData=True)
public class EventBeforeDeleteTest
{
    
    private static string RandomString{
        get{
            return string.valueof(math.random()).substring(1,10);
        }
    }

    private static testmethod void testTrigger()
    {
        Account account;
        Opportunity opportunity;
        OpportunityLineItem OppLineItem;
        Special_Event__c specialEvent;
        Special_Event_Booking__c specialEventbooking;
        Product2 product2;

        Contact NewContact;
        Date startDate = System.Today()-366;
        
        
         //CREATE ACCOUNT
        account = new Account(
            name = 'testAcount '+RandomString);
        insert account;
        system.debug('Account id : ' + account.id);
        
        NewContact= new Contact(
            LastName='Test' +RandomString , 
            Email='testy13213@fffp.com'+RandomString, 
            FirstName = 'Test'+RandomString, 
            Salutation = 'Mr',
            AccountId = account.id
        );
        insert NewContact;
        
        // CREATE OPPORTUNITY
        opportunity = new Opportunity(
            Name = 'testOpportunity '+RandomString,
            AccountId = account.Id,
            StageName = 'Qualifying',
            CloseDate = Date.today());
        insert opportunity;
        system.debug('Opportunity id : ' + opportunity.id);
        
        id Dimension1Id = [select id from c2g__codaDimension1__c where name = '110 - Finance' limit 1].id;
        id Dimension2Id = [select id from c2g__codaDimension2__c where name = '0000 - General' limit 1].id;
        id glaid = [select id from c2g__codaGeneralLedgerAccount__c where name = '3000 - Income - Sales Activities' Limit 1].Id;
        
        // CREATE PRODUCT2
        product2 = new Product2(
            Name = 'Test Event Product' + RandomString,
            Allows_Provisional_Bookings__c = true,
            c2g__CODASalesRevenueAccount__c = glaid,
            Dimension_1__c = Dimension1Id,
            Dimension_2__c = Dimension2Id,
            Auto_Post_Invoice__c=true);
        insert product2;
       
        // GET STANDARD PRICEBOOK
        Pricebook2 stdPricebook = [
            SELECT
            Id
            FROM
            Pricebook2
            WHERE
            IsStandard = true and name = 'Standard Price Book' Limit 1];
        
        
        // Core Product
        Product2 prod = new Product2(
            Name = 'Product Test' + RandomString, 
            Initial_Reminder_Days__c = 1,
            Core_Subscription_Product__c = True,
            Subscription_Product__c = True,
            Membership__c = True,
            Duration__c = '1 Year',
            c2g__CODASalesRevenueAccount__c = glaid,
            Dimension_1__c = Dimension1Id,
            Dimension_2__c = Dimension2Id
        );
        insert prod;
        
        
        // CREATE PRICEBOOK
        PricebookEntry pbe = new PricebookEntry(
            Product2Id = product2.Id,
            UnitPrice = 300,
            Pricebook2Id = stdPricebook.Id,
            IsActive = true);
        insert pbe;
        
        // CREATE OPP LINE ITEMS
        OppLineItem = new OpportunityLineItem(
            OpportunityId = opportunity.Id,
            PricebookEntryId = pbe.Id,
            Pricing_Exception__c = true,
            Quantity =1,
            UnitPrice = 300);
        insert OppLineItem;
        system.debug('Opp Line Item id : ' + OppLineItem.id);
        
        // CREATE BSC EVENT
        specialEvent = new Special_Event__c(
            Opportunity__c = opportunity.Id,
            Name = 'Test Event x'+ RandomString,
            Product__c = product2.Id,
            Type__c = 'In-Company Training',
            Status__c = 'Cancelled - Error',
            Stage__c = 'Anything but Provisional',
            StartDate__c = Date.today(),
            EndDate__c = Date.today().addDays(5));
        
        insert specialEvent;
        system.debug('Special Event id : ' + specialEvent.id);
        
                specialEventbooking = new Special_Event_Booking__c(
            Opportunity__c = opportunity.Id,
            Booking_Fee__c =  0 ,
            Special_Event__c = specialEvent.Id,
            Override_Booking_Fee__c = false,
            opl_id__c = string.valueof(OppLineItem.id),
            Type__c = 'Public');
        insert specialEventbooking;
        system.debug('Special Event Booking id : ' + specialEventbooking.id);
        
        
        delete specialEvent ;
        
    }
}