src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the Account is Active or Inactive i.e. does the Organisation exist.</description>
        <inlineHelpText>Indicates whether the Account is Active or Inactive i.e. does the Organisation exist.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The subscription that needs to be altered.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities (Subscription)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Subscription</fullName>
        <active>true</active>
        <businessProcess>BSC Sales Process</businessProcess>
        <description>Opportunity for Membership and other Subscription Product Sales</description>
        <label>Subscription</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in workflow</description>
        <inlineHelpText>Indicates if this product is a subscription product</inlineHelpText>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Used for subscription products only determine the length of the subscription.</description>
        <inlineHelpText>Used for subscription products only determine the length of the subscription.</inlineHelpText>
        <label>Duration</label>
        <picklist>
            <picklistValues>
                <fullName>1 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100 Years</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to feed automatic generation of Subscriptions and Subscription Lines</description>
        <inlineHelpText>Should sales of this product generate Subscriptions and Subscription Lines?</inlineHelpText>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Subscription</fullName>
        <active>true</active>
        <description>Record type for Memberships and other Subscription Products</description>
        <label>Subscription</label>
    </recordTypes>
</CustomObject>

src/objects/Site_Product__c.object
<CustomObject>
    <fields>
        <fullName>Previous_Site_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Site Product</label>
        <referenceTo>Site_Product__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product associated to this site product</description>
        <formula>Subscription_Line__r.Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Product associated to this site product</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Product_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If the Product should NOT go to the Subscription Site Contact, but instead to a different Contact, select that Contact here</inlineHelpText>
        <label>Site Product Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Site Products (there may be others  via Subscription Sites)</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Status__c</fullName>
        <description>Displays the Subscription Site Status, which will be the same as the Subscription Status, unless the Site is no longer active</description>
        <formula>IF( Subscription_Site__r.Cancelled__c =FALSE,
 TEXT( Subscription_Site__r.Subscription__r.Status__c),
&quot;Inactive&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the Subscription Site Status, which will be the same as the Subscription Status, unless the Site is no longer active</inlineHelpText>
        <label>Site Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Line__c</fullName>
        <description>Master Detail</description>
        <inlineHelpText>Subscription line associated with the site product</inlineHelpText>
        <label>Subscription Line</label>
        <referenceTo>Subscription_Line__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subscription site associated to this site product</description>
        <inlineHelpText>Lookup to Subscription Site</inlineHelpText>
        <label>Subscription Site</label>
        <referenceTo>Subscription_Site__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <description>Master detail</description>
        <inlineHelpText>Subscription associated with this site product</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site Product</label>
    <nameField>
        <displayFormat>SP-{0000000}</displayFormat>
        <label>Site Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to manage subscriptions (Memberships, Complywise Subscriptions and other ongoing product deliveries)</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The primary contact for this subscription</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <picklist>
            <picklistValues>
                <fullName>1 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Product__c</fullName>
        <description>Total number of Site products on the subscription</description>
        <inlineHelpText>Total number of Site products on the subscription</inlineHelpText>
        <label>Site Products</label>
        <summaryForeignKey>Site_Product__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending - Not Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Not Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Renewing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Cancelling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapsing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapse Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Manual Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Line__c</fullName>
        <description>The total number of subscription lines on the subscription</description>
        <inlineHelpText>The total number of subscription lines on the subscription.</inlineHelpText>
        <label>Subscription Lines</label>
        <summaryForeignKey>Subscription_Line__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Sub Ref: Current Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Line__c.object
<CustomObject>
    <description>Object to manage products / elements of a subscription</description>
    <fields>
        <fullName>OPL_ID__c</fullName>
        <label>OPL ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Subscription Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription_Site__c.object
<CustomObject>
    <description>Object to manage delivery of subscriptions to multiple sites</description>
    <fields>
        <fullName>Site_Status__c</fullName>
        <description>Populates site status from Subscription Status, unless the site is no longer active</description>
        <formula>IF( OR(Cancelled__c =TRUE, Active__c=FALSE),
 &quot;Inactive&quot;,
TEXT(Subscription__r.Status__c )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the same as the Subscription Status, unless the site is no longer active</inlineHelpText>
        <label>Site Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Site_Product_Codes__c</fullName>
        <label>Subscription Site Product Codes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Site Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Site Subsidiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription Site</label>
    <nameField>
        <displayFormat>SS-{0000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SiteProductTriggerMethods.cls
public with sharing class SiteProductTriggerMethods {

	/*
	 * SET SUB SITE PRODUCT CODES (Subscription Line)
	 *
	 * If the product has changed on the subscription line then force an update of the product codes on the subscription site.
	 */
	public static void setSubSiteProductCodes(List<Subscription_Line__c> oldSubLines, List<Subscription_Line__c> newSubLines){

		Set<Id> subLinesToUpd = new Set<Id>();
                
        // Loop over records and see if the products have changed and if so then trigger an update of the sub site product codes
        for (Integer i=0; oldSubLines.size() > i; i++){
            if ((oldSubLines[i].Product__c <> newSubLines[i].Product__c)){
                subLinesToUpd.add(newSubLines[i].Id);
            }
        }
        if (subLinesToUpd.size() > 0){
        	
	        List<Site_Product__c> siteProdsToUpd = new List<Site_Product__c>([SELECT
	        																Id,
	        																Subscription_Site__c
	        															FROM
	        																Site_Product__c
	        															WHERE
	        																Subscription_Line__c IN :subLinesToUpd]);
	        setSubSiteProductCodes(siteProdsToUpd);
        }
        
	}
	
	/*
	 * SET SUB SITE PRODUCT CODES (Site_Product__c)
	 *
	 * Gets unique set of subscription sites and then passes to method to work out product codes
	 */
	public static void setSubSiteProductCodes(List<Site_Product__c> siteProducts){
		
		Set<Id> subSites = new Set<Id>();
		for (Site_Product__c siteProduct : siteProducts){
			subSites.add(siteProduct.Subscription_Site__c);
		}
		setSubSiteProductCodes(subSites);
	}
	
	/*
	 * SET SUB SITE PRODUCT CODES (Subscription_Site__c)
	 *
	 * Works out the product codes for the sub site.
	 */
	public static void setSubSiteProductCodes(Set<Id> subSiteIds){
		
    	if (subSiteIds.size() > 0){
	    	List<Subscription_Site__c> allSubSites = new List<Subscription_Site__c>([SELECT
	    											Id,
	    											Subscription_Site_Product_Codes__c,
	    											Site_Status__c,
	    											(SELECT
	    												Id,
	    												Subscription_Line__r.Product__r.ProductCode
	    												FROM
	    													Site_Products__r)
	    											FROM
	    												Subscription_Site__c
	    											WHERE
	    												Id IN :subSiteIds]);
	    	String strProductCodes = '';
	    	for (Subscription_Site__c subSite : allSubSites){
				strProductCodes = '';
				for (Site_Product__c subSiteProd : subSite.Site_Products__r){
					if (strProductCodes == ''){
						strProductCodes = subSiteProd.Subscription_Line__r.Product__r.ProductCode;
					}else{
						// Add new product code but only if it fits in the string:
						if (strProductCodes.length()+subSiteProd.Subscription_Line__r.Product__r.ProductCode.length() < 255){
							strProductCodes=strProductCodes+';'+subSiteProd.Subscription_Line__r.Product__r.ProductCode;
						}
					}
				}
				subSite.Subscription_Site_Product_Codes__c = strProductCodes.left(255);
	    	}
	    	update allSubSites;
    	}		
	}
	
	@isTest
	static void testSetSubSiteProductCodes(){
		
        //Create an Account
        Account NewAccount=new Account(name='Test SSCreation Account');
        insert NewAccount;       
        
        // Add a Contact to it
        Contact NewContact= new Contact(LastName='Test SSCreation Contact', Email='testy13213@fffp.com', FirstName = 'Test', Salutation = 'Mr');
        NewContact.AccountId=NewAccount.id;
        insert NewContact;
            
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.StageName = 'Qualifying';
        opp.CloseDate = System.today();
        opp.AccountId=NewAccount.id;
        insert opp;
        
        OpportunityContactRole oppContRole = new OpportunityContactRole();
        oppContRole.ContactId = NewContact.id;
        oppContRole.OpportunityId = opp.id;
        oppContRole.IsPrimary = true;
        insert oppContRole;
        
        Product2 prod = new Product2();
        prod.Name = 'Test  Product';
        prod.ProductCode = 'TESTCODE1';
        prod.Duration__c='1 Year';
      	prod.Subscription_Product__c = true;
        insert prod;
        
        Pricebook2 stdPricebook = [Select Id From Pricebook2 Where IsStandard = true Limit 1];
        
        PricebookEntry pbe = new PricebookEntry();
        pbe.Product2Id = prod.Id;
        pbe.UnitPrice = 300;
        pbe.Pricebook2Id = stdPricebook.Id;
        pbe.IsActive = true;
        insert pbe;
        
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = opp.Id;
        oli.PricebookEntryId = pbe.Id;
        oli.Quantity = 1;
        oli.UnitPrice = 120;
        
        insert oli;
        
        Subscription__c sub = new Subscription__c();
        sub.Account_Name__c = NewAccount.Id;
        sub.Contact__c = NewContact.Id;
        sub.End_Date__c = Date.today()+365;
        sub.Opportunity__c = opp.Id;
        sub.Start_Date__c = Date.today()-1;
        sub.Status__c = 'Current';
        sub.Type__c = 'New';
        insert sub;
        
        Subscription_Line__c subLine = new Subscription_Line__c();
        subLine.OPL_ID__c = oli.Id;
        subLine.Product__c = prod.Id;
        subLine.Quantity__c = 1;
        subLine.Subscription__c = sub.Id;
        insert subLine;
        
        Subscription_Site__c subSite = new Subscription_Site__c();
        subSite.Active__c = True;
        subSite.Main_Site__c = True;
        subSite.Site_Account__c = NewAccount.Id;
        subSite.Site_Contact__c = NewContact.id;
        subSite.Site_Start_Date__c = Date.today()-1;
        subSite.Subscription__c = sub.Id;
        subSite.Type__c = 'Single Site';
        subSite.Subscription_Site_Product_Codes__c = null;
        insert subSite;
        
        Site_Product__c siteProd = new Site_Product__c();
        siteProd.Site_Product_Contact__c = NewContact.Id;
        siteProd.Subscription__c = sub.Id;
        siteProd.Subscription_Line__c = subLine.Id;
        siteProd.Subscription_Site__c = subSite.Id;
        insert siteProd;
        update siteProd;
        //System.assertEquals(subSite.Subscription_Site_Product_Codes__c, 'TESTCODE1');
        
	}
	
}