src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the Account is Active or Inactive i.e. does the Organisation exist.</description>
        <inlineHelpText>Indicates whether the Account is Active or Inactive i.e. does the Organisation exist.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>E_Delivery_Subscriber__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The account has an active eDelivery subscription.</inlineHelpText>
        <label>E-Delivery Subscriber</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tick if the Account is a current member.</description>
        <inlineHelpText>Tick if the Account is a current member.</inlineHelpText>
        <label>Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether Subscriber or not</description>
        <inlineHelpText>Whether Subscriber or not</inlineHelpText>
        <label>Subscriber</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to manage subscriptions (Memberships, Complywise Subscriptions and other ongoing product deliveries)</description>
    <fields>
        <fullName>Includes_E_Delivery_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates if this Subscription contains an E-Delivery Product</inlineHelpText>
        <label>Includes E-Delivery Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_Membership_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked automatically by Workflow on creation of Subscription Line</inlineHelpText>
        <label>Includes Membership Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_Publication_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Includes Publication Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_RCP_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked automatically by Workflow on save of Subscription Line</inlineHelpText>
        <label>Includes RCP Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending - Not Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Not Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Renewing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Cancelling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapsing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapse Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Manual Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Sub Ref: Current Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Site__c.object
<CustomObject>
    <description>Object to manage delivery of subscriptions to multiple sites</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if a site is currently active</description>
        <inlineHelpText>Indicates if a site is currently active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows the site has been cancelled
Field added by FF and I don&apos;t know what it does.</description>
        <inlineHelpText>DO NOT USE (uncheck &quot;Active&quot; if the site is cancelled)</inlineHelpText>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Site_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Multi_Site_Subscription_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Status__c</fullName>
        <description>Populates site status from Subscription Status, unless the site is no longer active</description>
        <formula>IF( OR(Cancelled__c =TRUE, Active__c=FALSE),
 &quot;Inactive&quot;,
TEXT(Subscription__r.Status__c )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the same as the Subscription Status, unless the site is no longer active</inlineHelpText>
        <label>Site Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Site</label>
    <nameField>
        <displayFormat>SS-{0000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountMemberCheck.cls
public with sharing class AccountMemberCheck {
	
	/*
	 * SET ACCOUNT MEMBER FLAG BY SUB SITE
	 *
	 * Gets a set of unique accounts from the list of sub sites passed and then calls the account
	 * flags update.
	 */
	public static void setAccountMemberFlagBySubSite(Set<Subscription_Site__c> subSiteList){
		
		List<Account> accs = new List<Account>();
		for (Subscription_Site__c subSite : subSiteList){
			
		}
	}
	
	/**
	* Method: isAccountMember
	* New trigger, we need to update the checkbox "Member" 
    * on the account based on whether the account has a subscription site, 
    * which has a site product, where "Membership Product" = TRUE
    * but only when the subscription to which the subscription site is linked has
    * a status that starts with current
    *
    * acc.Subscription_Site__c.Membership_Product__c = true
    * acc.Subscription_Site__c.Subscription__c.Status like 'Current%'
    * 
	**/
	public static void setAccountMemberFlagByAcc(Set<Id> accList){
		
		List<Account> accUpdList = new List<Account>();
		List<Account> accObjList = new List<Account>([SELECT 
				Id, 
				Member__c, 
				Subscriber__c,
				E_Delivery_Subscriber__c,
				(SELECT Subscription__r.Includes_RCP_Product__c, 
						Subscription__r.Includes_Membership_Product__c, 
						Subscription__r.Includes_E_Delivery_Product__c,
						Subscription__r.Includes_Publication_Product__c
				 	FROM 
				 		Multi_Site_Subscription_Sites__r
				 	WHERE
				 		//Site_Status__c like 'Current%' AND
				 		Subscription__r.Status__c like 'Current%' AND
				 		Active__c = True AND
				 		Cancelled__c = False
				 		) 
			FROM 
				Account 
			WHERE Id IN :accList]);
		
		System.debug('Account List: '+accObjList);
		
		for (Account acc : accObjList){

			boolean statusHasChanged = false;
			boolean isAccountMember = false;
			boolean isSubscriptionMember = false;
			boolean isEDeliveryMember = false;
			
			if (acc !=null){
				for(Subscription_Site__c subSite : acc.Multi_Site_Subscription_Sites__r){					
					System.debug(subSite);
					if (subSite.Subscription__r.Includes_Membership_Product__c == true){
						System.debug(acc.Id+' has membership from subscription: '+subSite.Id);
						isAccountMember = true;
					}
					if (subSite.Subscription__r.Includes_Publication_Product__c == true){
						System.debug(acc.Id+' has subscription from subscription: '+subSite.Id);
						isSubscriptionMember = true;
					}					
					if (subSite.Subscription__r.Includes_E_Delivery_Product__c == true){
						System.debug(acc.Id+' has eDelivery Subscription from subscription: '+subSite.Id);
						isEDeliveryMember = true;
					}	
				}
				
				if ((acc.Subscriber__c <> isSubscriptionMember) || (acc.Member__c <> isAccountMember) || (acc.E_Delivery_Subscriber__c <> isEDeliveryMember)){
					// Change has been made to this accounts status
					statusHasChanged = True;
				}
				
			}
			
			System.debug('FJP** ACC Fields: Mem:' + acc.Member__c + ' Sub:'+acc.Subscriber__c);
			System.debug('FJP** isAccountMember: ' + isAccountMember);
			System.debug('FJP** isSubscriber: ' + isSubscriptionMember);
			System.debug('FJP** Status has Changed: ' + statusHasChanged);
			
			// Add account to update list if the status has changed in anyway
			if (statusHasChanged){
				if (acc.Member__c <> isAccountMember){
					acc.Member__c = isAccountMember;
				}
				if (acc.Subscriber__c <> isSubscriptionMember){
					acc.Subscriber__c = isSubscriptionMember;
				}
				if (acc.E_Delivery_Subscriber__c <> isEDeliveryMember){
					acc.E_Delivery_Subscriber__c = isEDeliveryMember;
				}
				accUpdList.add(acc);
			}
		}
		System.debug('FJP Updating: '+accUpdList);
		update accUpdList;
	}

	/*
	 * SET ACCOUNT MEMBER FLAG
	 * 
	 * Sets the account member flag but unlike above works based on the subscription not just the account.
	 */
	public static void setAccountMemberFlag(List<Subscription__c> subsList){
		
		// List of all accounts that need to be updated 
		Set<Id> accsToUpdate = new Set<Id>();
		
		for(Subscription_Site__c subSite : [SELECT Site_Account__c
											FROM Subscription_Site__c
											WHERE Subscription__c IN :subsList AND Site_Account__c != null]){
			if (!accsToUpdate.contains(subSite.Site_Account__c)){
				accsToUpdate.add(subSite.Site_Account__c);
			}
		}
		
		System.debug('Disabling AccountReAssignment');
		ApexCodePatrol.disable('AccountReAssignment');
		
		setAccountMemberFlagByAcc(accsToUpdate);

		ApexCodePatrol.enable('AccountReAssignment');

	}
	
}