src/objects/Area__c.object
<CustomObject>
    <description>Object to associate Accounts with Territories</description>
    <fields>
        <fullName>Area_Postcode__c</fullName>
        <description>Postcode of the area - used for matching UK postcodes to the correct Area</description>
        <inlineHelpText>Enter Postcode of the area</inlineHelpText>
        <label>Area Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Area Country</description>
        <inlineHelpText>Enter Country</inlineHelpText>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Åland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United Kingdom</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Postcode_District__c</fullName>
        <description>Postcode District</description>
        <inlineHelpText>Enter Postcode District</inlineHelpText>
        <label>Postcode District</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to territory</description>
        <inlineHelpText>Search for related territory</inlineHelpText>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Areas</relationshipLabel>
        <relationshipName>Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of account manager who will be responsible for this Area</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>AE</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>RAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Delegate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Area</label>
    <nameField>
        <displayFormat>AREA-{0000000}</displayFormat>
        <label>Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Allocated_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Allocated Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Principle_Address_Country__c</fullName>
        <label>Principle Address: Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Åland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United Kingdom</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Principle_Address_ZIP_Postal_Code__c</fullName>
        <description>Address Field - Maps to Account on Conversion</description>
        <label>Principle Address: ZIP / Postal Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Territory__c.object
<CustomObject>
    <description>Object for gathering accounts via Areas into a Territory and assigning them to the correct account manager</description>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Salesperson associated to territory</description>
        <inlineHelpText>Search for Salesperson associated to this territory</inlineHelpText>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Denotes areas type relating to sales groups (key account, regional accounts)</description>
        <inlineHelpText>Select Sales group Kam, Ram etc.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LeadManagement.cls
public class LeadManagement {

    public static string uk = 'United Kingdom';
    
    public static void assignOwners(list<Lead> newleads ){
        
        set<string> postcodes = new set<string>();
        set<string> countries = new set<string>();
        
        for (Lead l : newLeads){
            postcodes.add(parsePostcode(l.Principle_Address_ZIP_Postal_Code__c));
            
            if (l.Principle_Address_Country__c != uk)
            	countries.add(l.Principle_Address_Country__c);
        }
        
        system.debug(postcodes +':' + countries);    
        
        Map<String, Map<String, Area__c>> areas = getAreas(postcodes, countries);
        
        if (areas.size() > 0){
            for (Lead l : newLeads){
                
                string postcode = parsePostcode(l.Principle_Address_ZIP_Postal_Code__c);
                
                Map<String, Area__c> foundAreaMap;
                                
                if (l.Principle_Address_Country__c == uk){
                    string str= l.Principle_Address_Country__c + '-' + postcode;
                    foundAreaMap = areas.get(str.toLowerCase());
                    system.debug(str.toLowerCase());
                } else {
                    string str = l.Principle_Address_Country__c;
                    foundAreaMap = areas.get(str.toLowerCase());
                    system.debug(str.toLowerCase());
                }
                
                system.debug(foundAreaMap); 
                
                Area__c foundArea = null;
                
                if (l.NumberOfEmployees >= 1999) {
                    if(foundAreaMap.get('KAM') != null)
                        foundArea = foundAreaMap.get('KAM');
                    else {
                        if(foundAreaMap.get('RAM') != null)
                            foundArea = foundAreaMap.get('RAM');
                    }
                } else if (l.NumberOfEmployees < 1999 || l.NumberOfEmployees == null ) {
                    if(foundAreaMap.get('RAM') != null)
                        foundArea = foundAreaMap.get('RAM');
                }
                
                if (foundArea != null){
                    l.Allocated_Area__c = foundArea.Id;
                    l.OwnerId = foundArea.Territory__r.Territory_Manager__c;
                }
            }
        }
            
    }
 
    public static Map<String, Map<String, Area__c>> getAreas(Set<String> postcodes, Set<String> countries){
        
        Map<String, Map<String, Area__c>> areas = new Map<String, Map<String, Area__c>>();
        
        for (Area__c a : [SELECT Id, Name, Area_Postcode__c, Country__c, Postcode_District__c, Territory__c, Territory__r.Territory_Manager__c, Type__c  FROM Area__c WHERE (Area_Postcode__c in :postcodes AND Country__c = :uk ) or Country__c in :countries ]){
            
            String key = a.Country__c + (a.Country__c == uk ? '-' + a.Area_Postcode__c : '');
           
            key =  key.toLowerCase();
            
            if (!areas.containsKey(key))
                areas.put(key, new Map<String, Area__c>());
            
            areas.get(key).put(a.Type__c, a);
            
        }
        system.debug('Areas found: ' + areas);
        return areas;
    }
    
    public static String parsePostcode(String postcode){
        
        if (postcode != null && postcode != '') {
            
            String[] splitted = postcode.split('[0-9]');
            
            if (splitted.size() > 0 && splitted[0] != null && splitted[0] != '') 
                return splitted[0];
        }
        
        return null;
    }
    
}