src/objects/AutoInvoiceSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>AutoPost_CreditNotes__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Will the Credit notes be automatically posted?</description>
        <label>AutoPost CreditNotes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AutoPost_Invoices__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Will the Invoices be automatically posted?</description>
        <label>AutoPost Invoices</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Invoice_Delay__c</fullName>
        <description>This will set the when a opp will be picked for invoicing, 0 is all eligible opps, 1 is all opps edited before hour and so on....</description>
        <label>Auto Invoice Delay</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Complywise_Last_Execution__c</fullName>
        <description>When was the last time comply wise auto invoice process triggered?</description>
        <inlineHelpText>When was the last time comply wise auto invoice process triggered?</inlineHelpText>
        <label>Complywise Last Execution</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Email_Notification_To__c</fullName>
        <description>Where will the start, stop or error messages be delivered</description>
        <label>Email Notification To</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enable_Auto_Invoicing__c</fullName>
        <defaultValue>true</defaultValue>
        <description>will the auto invoicing run at all, removes the need to stop the schedule</description>
        <label>Enable Auto Invoicing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Evaluate_Delivery_Workflow__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Will the workflow be fired to email or print invoices/credit notes</description>
        <label>Evaluate Delivery Workflow</label>
        <type>Checkbox</type>
    </fields>
    <label>AutoInvoiceSettings</label>
</CustomObject>

src/classes/AutoInvoiceSettings.cls
public class AutoInvoiceSettings {
   
    static AutoInvoiceSettings__c settings;
    
    private static void initiateSettings(){
        if ( settings == null )
            settings = AutoInvoiceSettings__c.getOrgDefaults();    
    }
    
    public static Integer autoInvoiceDelay { get{ initiateSettings(); return (Integer)settings.Auto_Invoice_Delay__c; } }
    
    public static boolean autoPostCreditNotes { get{ initiateSettings(); return settings.AutoPost_CreditNotes__c; } }
    
    public static boolean autoPostInvoices { get{ initiateSettings(); return settings.AutoPost_Invoices__c; } }
    
    public static boolean autoInvoicingEnabled { get{ initiateSettings(); return settings.Enable_Auto_Invoicing__c; } }
    
    public static boolean evaluateDeliveryWorkflow { get{ initiateSettings(); return settings.Evaluate_Delivery_Workflow__c; } } 
    
    public static string emailNotificationTo { get{ initiateSettings(); return settings.Email_Notification_To__c; } }
    
    public static datetime cwLastExecution { get{ initiateSettings(); return (datetime)settings.Complywise_Last_Execution__c; } }
    
}