src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <displayFormat>O-{0000000}</displayFormat>
        <label>Opportunity Number</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Certificate_Course_Name__c</fullName>
        <description>Formula to select the name specified in the field &quot;Alternative Certificate Course Name&quot; where not blank or this selects the product name but removes any text on the product name that appear after an open bracket</description>
        <formula>IF 
( 
!ISBLANK( Alternative_Certificate_Course_Name__c ), Alternative_Certificate_Course_Name__c,
IF(FIND(&quot;(&quot;,Product__r.Name )=0, Product__r.Name, LEFT(Product__r.Name , FIND(&quot;(&quot;,Product__r.Name ) -1) 
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula to select the name specified in the field &quot;Alternative Certificate Course Name&quot; where not blank or this selects the product name but removes any text on the product name that appear after an open bracket</inlineHelpText>
        <label>Course Name to appear on Certificate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Cancellation_Transfer_Date__c</fullName>
        <description>The date and time on which the customer asked for the transfer or cancellation.</description>
        <inlineHelpText>The date and time on which the customer asked for the transfer or cancellation.</inlineHelpText>
        <label>Customer Cancellation/Transfer Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date when Special Event ends.</description>
        <inlineHelpText>Date when Special Event ends.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when Special Event starts.</description>
        <inlineHelpText>Date when Special Event starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trainer_Name__c</fullName>
        <description>Name of the trainer to be used in Email Notifications.</description>
        <label>Trainer Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Notes__c</fullName>
        <inlineHelpText>Notes entered in the transfer and cancellation reason VF Component.</inlineHelpText>
        <label>Transfer / Cancellation Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Venue_Name__c</fullName>
        <description>Pulls in the related Venue&apos;s name if there is one</description>
        <formula>IF(ISBLANK( Venue__r.Name),&quot;&quot;,Venue__r.Name)</formula>
        <inlineHelpText>Pulls in the related Venue&apos;s name if there is one</inlineHelpText>
        <label>Venue Name</label>
        <type>Text</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Contact_Last_Name__c</fullName>
        <description>Pulls in the related contact&apos;s last name, this is used on the Delegate Badges only so doesn&apos;t appear on the page layouts</description>
        <formula>Contact__r.LastName</formula>
        <inlineHelpText>Pulls in the related contact&apos;s last name, this is used on the Delegate Badges only so doesn&apos;t appear on the page layouts</inlineHelpText>
        <label>Contact Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Salutation__c</fullName>
        <description>Pulls in the related Contact Salutation</description>
        <formula>TEXT(Contact__r.Salutation)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related Contact Salutation</inlineHelpText>
        <label>Contact Salutation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the person attending the event as a delegate pulled from the contact</description>
        <inlineHelpText>The name of the person attending the event as a delegate</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Cancellation_Transfer_Date__c</fullName>
        <description>The date and time on which the customer asked for the transfer or cancellation.</description>
        <inlineHelpText>The date and time on which the customer asked for the transfer or cancellation.</inlineHelpText>
        <label>Customer Cancellation/Transfer Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Certificate_Course_Name__c</fullName>
        <description>Shows the Event.Certificate Course Name and is used to pull information into drawloop document</description>
        <formula>Special_Event__r.Certificate_Course_Name__c</formula>
        <inlineHelpText>Shows the Event.Certificate Course Name and is used to pull information into drawloop document</inlineHelpText>
        <label>Event Certificate Course Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Notes__c</fullName>
        <description>Notes entered in the transfer and cancellation reason VF Component.</description>
        <label>Transfer / Cancellation Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Transfer_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for transferring public bookings to a new event. Auto populated when transferring a public booking.</description>
        <inlineHelpText>Used for transferring public bookings to a new event. Auto populated when transferring a public booking.</inlineHelpText>
        <label>Transfer to: Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (Transfer To)</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Event_Trainer__c.object
<CustomObject>
    <description>Object for tracking which trainers are assigned to an event</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Determines the status of the scheduled trainer</description>
        <inlineHelpText>Determines the status of the scheduled trainer</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trainer_Name__c</fullName>
        <description>Pulls in the related users first name and last name</description>
        <formula>Trainer__r.User__r.FirstName  &amp; &quot; &quot;&amp;  Trainer__r.User__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related users first name and last name</inlineHelpText>
        <label>Trainer Name</label>
        <type>Text</type>
    </fields>
    <label>BSC Event Trainer</label>
    <nameField>
        <displayFormat>ET-{0000000}</displayFormat>
        <label>BSC Event Trainer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Trainers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/tncPublicEventCancellation.cls
global class tncPublicEventCancellation{
    
    webservice static string cancelPublicEvent(id eventId){
        
        Special_Event__c event = [select id, status__c, 
                                  (select id,Special_Event__c, Opportunity__r.Opportunity_Number__c, Status__c, Event_Certificate_Course_Name__c, Opportunity__r.OwnerId, Opportunity__r.Name, 
                                   Opportunity__r.Owner.IsActive, Opportunity__r.Owner.Email,  Opportunity__r.Account.OwnerId, Opportunity__r.Account.Owner.Email, Contact_Salutation__c, 
                                   Contact_Last_Name__c, Contact__r.FirstName, Transfer_To__c  from R00N50000001mIaiEAE__r where not (Status__c like '%Cancelled%' and Status__c like '%Transferred%')),
                                  Venue_Name__c, Certificate_Course_Name__c, StartDate__c, EndDate__c, Name,
                                  Transfer_Cancellation_Notes__c, Customer_Cancellation_Transfer_Date__c,
                                  (select id, Trainer_Name__c, Trainer__r.User__r.Email from BSC_Event_Trainers__r), Transfer_Cancellation_Reason__r.Name, Transfer_Cancellation_Reason__c
                                  from Special_Event__c where Id = :eventId];
        
        tncEventsWrapper trainersToDelete = new tncEventsWrapper(false, event);
        event.Status__c = 'To Be Cancelled';
        event.Stage__c = 'Cancelled';
        
        id reason = [select id from Transfer_Cancellation_Reasons__c where name = 'BSC Cancelled Event' limit 1].id;
        
        string notes= tncHelper.deleteTrainerEvents(trainersToDelete);
        event.Transfer_Cancellation_Notes__c = notes == '' ? '' : 'Trainers Deleted: \n' + notes;
        event.Transfer_Cancellation_Process_Date__c = system.Datetime.now();
        event.Transfer_Cancellation_Reason__c = reason;
        event.Customer_Cancellation_Transfer_Date__c = system.today();
        
        list<Special_Event_booking__C> bookings = new list<Special_Event_booking__C>();
        list<Task> tasks = new list<task>();
        
        for (Special_Event_booking__C booking : event.R00N50000001mIaiEAE){
            system.debug('cancelling booking');
            string status = booking.Status__C;
            
            if (booking.Status__C == 'Provisional'){
                booking.Status__C = 'Cancelled - BSC';
                booking.OPL_ID__c = '';
                booking.Booking_Fee__c = 0;
                booking.Override_Booking_Fee__c = true;
            } else if (booking.Status__C == 'Confirmed'){
                booking.Status__C = 'To be Transferred';
            }
            
            
            booking.Transfer_Cancellation_Notes__c = notes == '' ? '' : 'Trainers Deleted: \n' + notes;
            booking.Transfer_Cancellation_Process_Date__c = system.Datetime.now();
            booking.Transfer_Cancellation_Reason__c = reason;
            booking.Customer_Cancellation_Transfer_Date__c = system.today();
            
            if (status == 'Provisional' || status == 'Confirmed' || status == 'To be Transferred'){
                
                Id taskFor; 
                if (booking.Opportunity__r.Owner.IsActive == true){
                    taskFor = booking.Opportunity__r.OwnerId;
                } else {
                    taskFor = booking.Opportunity__r.Account.OwnerId;
                }
                
                system.debug('taskFor' +taskFor);
                
                map<string,string> keyValueMap = new map<string,string>{ '<Event Name>' => booking.Event_Certificate_Course_Name__c,
                    '<Event_Booking.Status>'=> booking.Status__c ,
                    '<Event_Booking.Contact.Saluation>' => booking.Contact_Salutation__c,
                    '<Event_Booking.Contact.surname>' => booking.Contact_Last_Name__c,
                    '<Event_Booking.Contact.firstname>' => booking.Contact__r.FirstName,
                    '<Booking.Event.Opportunity.Name>' => booking.Opportunity__r.Opportunity_Number__c};
                        
                        list<string> data = Utilities.getCustomTemplate('Sales Rep: Public Event Cancellation task template', keyValueMap);
                string subject = data[0];
                string description = data[1];
                task t =  Utilities.createTask(true, system.today(), booking.Special_Event__c, subject, description, taskFor);
                insert t;
                tasks.add(t);
                system.debug('tasks'  + tasks);
            }
            
            bookings.add(booking);
        }
        
        update event;        
        update bookings;
        system.debug('tasks size'  + tasks.size());
        
        for (Special_Event_booking__C booking : event.R00N50000001mIaiEAE){
            
            if (booking.Status__C == 'Provisional' || booking.Status__C == 'Confirmed' || booking.Status__C == 'To be Transferred'){
                
                string emailTo;
                id taskId;
                if (booking.Opportunity__r.Owner.IsActive == true){
                    emailTo = booking.Opportunity__r.Owner.Email;
                } else {
                    emailTo = booking.Opportunity__r.Account.Owner.Email;                
                }
                
                for (task t: tasks){
                    if (t.whatId == booking.Special_Event__c){
                        taskId = t.Id;
                        break;
                    }                
                }
                
                map<string,string> keyValueMap = new map<string,string>{ '<Event Name>' => booking.Event_Certificate_Course_Name__c,
                    '<task link>' => URL.getSalesforceBaseUrl().toExternalForm() + '/' + taskId};
                        system.debug ('keyValueMapEmail ' + keyValueMap);    
                Utilities.SendEmail('Public Event Cancellation email template',new list<string>{ emailTo }, keyValueMap);
                system.debug ('email sent');
            }
        }
        
        return string.valueof(eventId);
    } 
}