src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Integrate_With_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If enabled the contact will be pushed to marketo for Marketing Automation</description>
        <inlineHelpText>If enabled the contact will be pushed to marketo for Marketing Automation</inlineHelpText>
        <label>Integrate With Marketo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X18_Digit_Contact_ID__c</fullName>
        <formula>casesafeid(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>18 Digit Contact ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Start date of the event the user wishes to book</description>
        <inlineHelpText>Start date of the event the user wishes to book</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Integrate_With_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If enabled the Lead will be pushed to marketo for Marketing Automation</description>
        <inlineHelpText>If enabled the Lead will be pushed to marketo for Marketing Automation</inlineHelpText>
        <label>Integrate With Marketo</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Copied from Lead - Start date of the event the user wishes to book</description>
        <inlineHelpText>Copied from Lead - Start date of the event the user wishes to book</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Subscription</fullName>
        <active>true</active>
        <businessProcess>BSC Sales Process</businessProcess>
        <description>Opportunity for Membership and other Subscription Product Sales</description>
        <label>Subscription</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the person attending the event as a delegate pulled from the contact</description>
        <inlineHelpText>The name of the person attending the event as a delegate</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Pulls in the related event&apos;s start date</description>
        <formula>Special_Event__r.StartDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related event&apos;s start date</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription_Site__c.object
<CustomObject>
    <description>Object to manage delivery of subscriptions to multiple sites</description>
    <fields>
        <fullName>Site_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Multi_Site_Subscription_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Status__c</fullName>
        <description>Populates site status from Subscription Status, unless the site is no longer active</description>
        <formula>IF( OR(Cancelled__c =TRUE, Active__c=FALSE),
 &quot;Inactive&quot;,
TEXT(Subscription__r.Status__c )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the same as the Subscription Status, unless the site is no longer active</inlineHelpText>
        <label>Site Status</label>
        <type>Text</type>
    </fields>
    <label>Subscription Site</label>
    <nameField>
        <displayFormat>SS-{0000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MarketoIntegrationScheduledClass.cls
global class MarketoIntegrationScheduledClass Implements Schedulable
{
    public static String CRON_EXP = '0 0 0 3 9 ? 2022';

    global void execute(SchedulableContext sc)
    {
        system.debug('In Execute');
        Set<Contact> allContact_site = new Set<Contact>();
        Set<Contact> allContact_oppc = new Set<Contact>();
        Set<Contact> allContact_eve = new Set<Contact>();
        Set<Lead> allLead = new Set<Lead>();
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :sc.getTriggerId()];

        //System.assertEquals(CRON_EXP, ct.CronExpression);
        //System.assertEquals(0, ct.TimesTriggered);
        //System.assertEquals('2022-09-03 00:00:00', String.valueOf(ct.NextFireTime));

        for(Subscription_Site__c ssc : [SELECT Site_Contact__r.X18_Digit_Contact_ID__c, Site_Contact__r.Integrate_With_Marketo__c 
                                                    FROM Subscription_Site__c 
                                                    WHERE Site_Status__c LIKE 'Current%' 
                                                    AND Site_Contact__r.Integrate_With_Marketo__c = false 
                                                    AND Site_Contact__r.X18_Digit_Contact_ID__c != null])
        {
            Contact c = new Contact(Id = ssc.Site_Contact__r.X18_Digit_Contact_ID__c, Integrate_With_Marketo__c = true);
            allContact_site.add(c);
        }
        system.debug('allContact_site.size() - ' + allContact_site.size());

        try
        {
            List<Contact> l_allContact = new List<Contact> (allContact_site);
            update new List<Contact> (l_allContact);
        }
        catch(Exception e)
        {
            system.debug('allContact Exception - ' + e);
        }

        for(OpportunityContactRole ocr : [SELECT Contact.X18_Digit_Contact_ID__c, Contact.Integrate_With_Marketo__c 
                                                    FROM OpportunityContactRole 
                                                    WHERE IsPrimary = true 
                                                    AND (Opportunity.CloseDate >= 2012-03-01) 
                                                    AND Contact.Integrate_With_Marketo__c = false 
                                                    AND Opportunity.IsWon = true])
        {
            Contact c = new Contact(Id = ocr.Contact.X18_Digit_Contact_ID__c, Integrate_With_Marketo__c = true);
            allContact_oppc.add(c);
        }
        system.debug('allContact_oppc.size() - ' + allContact_oppc.size());

        try
        {
            List<Contact> l_allContact = new List<Contact> (allContact_oppc);
            update new List<Contact> (l_allContact);
        }
        catch(Exception e)
        {
            system.debug('allContact Exception - ' + e);
        }

        for(Special_Event_Booking__c seb : [SELECT Contact__r.X18_Digit_Contact_ID__c, Contact__r.Integrate_With_Marketo__c 
                                                                FROM Special_Event_Booking__c 
                                                                WHERE Event_Start_Date__c > 2012-03-01 
                                                                AND Status__c in ('Provisional','Confirmed','Attended','No Show','Attended - Fail','Attended - Pass','Attended - Merit','Attended - Distinction') 
                                                                AND Contact__r.Integrate_With_Marketo__c = false 
                                                                AND Contact__r.X18_Digit_Contact_ID__c != null])
        {
            Contact c = new Contact(Id = seb.Contact__r.X18_Digit_Contact_ID__c, Integrate_With_Marketo__c = true);
            allContact_eve.add(c);
        }
        system.debug('allContact_eve.size() - ' + allContact_eve.size());

        try
        {
            List<Contact> l_allContact = new List<Contact> (allContact_eve);
            update new List<Contact> (l_allContact);
        }
        catch(Exception e)
        {
            system.debug('allContact Exception - ' + e);
        }

        for(Lead l : [SELECT Id, Integrate_With_Marketo__c FROM Lead WHERE LeadSource = 'Live Chat' AND Integrate_With_Marketo__c = false AND IsConverted = false])
        {
            l.Integrate_With_Marketo__c = true;
            allLead.add(l);
        }

        system.debug('allLead.size() - ' + allLead.size());

        try
        {
            update new List<Lead> (allLead);
        }
        catch(Exception e)
        {
            system.debug('allLead Exception - ' + e);
        }

        try
        {
            List<String> EmailId = new List<String> ();
            EmailId.add('salesforcealerts@britsafe.org');
            //EmailId.add('rahul.borgaonkar@britsafe.org');

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(EmailId);
            mail.setSubject('Daily Update Count of Integrate With Marketo flag On Contacts - ' + Date.today().format());

            String mailBody = 'Hi\n\nCount of Integrate With Marketo flag Updated for Related Contacts\n\n';
            mailBody = mailBody + 'Subscription Sites Contact Count - ' + allContact_site.size() + '\n\n';
            mailBody = mailBody + 'Opportunity Contact Role Contact Count - ' + allContact_oppc.size() + '\n\n';
            mailBody = mailBody + 'Event Booking Contact Count - ' + allContact_eve.size() + '\n\n';
            mailBody = mailBody + 'And\n\n';
            mailBody = mailBody + 'Lead Count - ' + allLead.size() + '\n\n';
            mailBody = mailBody + 'Thank You\n';
            mail.setPlainTextBody(mailBody);

            List<Messaging.SendEmailResult> results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            system.debug('Mail Result - ' + results);
        }
        catch(Exception e)
        {
            system.debug('Email Exception - ' + e);
        }

    }
}