src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Copied from Lead - Start date of the event the user wishes to book</description>
        <inlineHelpText>Copied from Lead - Start date of the event the user wishes to book</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <displayFormat>O-{0000000}</displayFormat>
        <label>Opportunity Number</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Customer_Cancellation_Transfer_Date__c</fullName>
        <description>The date and time on which the customer asked for the transfer or cancellation.</description>
        <inlineHelpText>The date and time on which the customer asked for the transfer or cancellation.</inlineHelpText>
        <label>Customer Cancellation/Transfer Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_ID__c</fullName>
        <description>Pulls in the related product id</description>
        <formula>Product__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related product id</inlineHelpText>
        <label>Product ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Shows the stage of the event, which is a dependant pick list of the status field</description>
        <inlineHelpText>Shows the stage of the event, which is a dependant pick list of the status field</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Notes__c</fullName>
        <inlineHelpText>Notes entered in the transfer and cancellation reason VF Component.</inlineHelpText>
        <label>Transfer / Cancellation Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Reason__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reason why the cancellation or transfer is taking place</description>
        <inlineHelpText>The reason why the cancellation or transfer is taking place</inlineHelpText>
        <label>Transfer &amp; Cancellation Reason</label>
        <referenceTo>Transfer_Cancellation_Reasons__c</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the person attending the event as a delegate pulled from the contact</description>
        <inlineHelpText>The name of the person attending the event as a delegate</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Cancellation_Transfer_Date__c</fullName>
        <description>The date and time on which the customer asked for the transfer or cancellation.</description>
        <inlineHelpText>The date and time on which the customer asked for the transfer or cancellation.</inlineHelpText>
        <label>Customer Cancellation/Transfer Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Pulls in the related event&apos;s start date</description>
        <formula>Special_Event__r.StartDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related event&apos;s start date</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_end_Date__c</fullName>
        <description>Pulls in the related event&apos;s end date</description>
        <formula>Special_Event__r.EndDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related event&apos;s end date</inlineHelpText>
        <label>Event end Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OPL_ID__c</fullName>
        <description>18 digit opportunity product line id that the event booking relates to</description>
        <externalId>true</externalId>
        <inlineHelpText>18 digit opportunity product line id that the event booking relates to</inlineHelpText>
        <label>OPL ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_ID__c</fullName>
        <description>Used for Conga Transfer Form</description>
        <formula>Special_Event__r.Product__r.Id</formula>
        <inlineHelpText>Pulls in the related event product&apos;s id</inlineHelpText>
        <label>Product ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TnC_Event_Units__c</fullName>
        <label>TnC Event Units</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Fee__c</fullName>
        <description>Transfer / Cancellation Fees</description>
        <inlineHelpText>Transfer / Cancellation Fees</inlineHelpText>
        <label>Transfer / Cancellation Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Notes__c</fullName>
        <description>Notes entered in the transfer and cancellation reason VF Component.</description>
        <label>Transfer / Cancellation Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Reason__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer / Cancellation Reason</label>
        <referenceTo>Transfer_Cancellation_Reasons__c</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transfer_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for transferring public bookings to a new event. Auto populated when transferring a public booking.</description>
        <inlineHelpText>Used for transferring public bookings to a new event. Auto populated when transferring a public booking.</inlineHelpText>
        <label>Transfer to: Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (Transfer To)</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/tncPublicEventCancellationHandler.cls
public class tncPublicEventCancellationHandler  implements Iterator<List<tncPublicEventCancellationWrapper>>{
    
    public list<tncPublicEventCancellationWrapper> allBookings		 {get; set;}
    public list<tncPublicEventCancellationWrapper> requestedBookings {get; set;}
    public integer setPageSize                                       {get; set;}
    
    integer recordNumber                                             {get; set;}
    
    public tncPublicEventCancellationHandler(Id oppId){
        allBookings = new list<tncPublicEventCancellationWrapper>(); 
        requestedBookings = new list<tncPublicEventCancellationWrapper>();
        
        List<Special_Event_Booking__c> bookings = [SELECT Name, Contact__r.Name, Product__c, Special_Event__r.Name,
                                                   Event_Start_Date__c, Event_End_Date__c, Status__C, OPL_ID__c, Special_Event__r.Stage__c, Product_ID__c,
                                                   Opportunity__c, Opportunity__r.Opportunity_Number__c, Transfer_To__c , Transfer_To__r.Name, 
                                                   Customer_Cancellation_Transfer_Date__c , TnC_Event_Units__c , Transfer_Cancellation_Reason__c,
                                                   Transfer_Cancellation_Reason__r.Name, Transfer_Cancellation_Notes__c, Transfer_Cancellation_Fee__c
                                                   FROM Special_Event_Booking__c 
                                                   where opportunity__r.recordtype.name = 'Public Event' and 
                                                   status__c in ('To Be Transferred', 'Confirmed', 'Provisional', 'To Be Cancelled') and Opportunity__c  = :oppId
                                                  ];
        List<Id> oliIds = new List<Id>();
        
        for (Special_Event_Booking__c booking: bookings){
            allbookings.add(new tncPublicEventCancellationWrapper(booking));
            oliIds.add(Id.ValueOf(booking.OPL_ID__c));
        }
        
        list<OpportunityLineItem> oppLines = [select unitprice, 
                                                     id, 
                                                     pricebookentry.product2.name, 
                                                     Quantity, 
                                                     OpportunityId,
                                                     PricebookEntry.Product2.Cancellation_Fee_Product__c, 
                                                     PricebookEntry.pricebook2id,
                                                     PricebookEntry.Product2Id, 
                                                     Transfer_Cancellation__c,
                                                     PricebookEntry.Product2.Transfer_Charge_Fee_Final__c, 
                                                     PricebookEntry.Product2.Transfer_Charge_Fee_3__c, 
                                                     PricebookEntry.Product2.Transfer_Charge_Fee_2__c, 
                                                     PricebookEntry.Product2.Transfer_Charge_Fee_1__c, 
                                                     PricebookEntry.Product2.Transfer_Charge_Day_3__c, 
                                                     PricebookEntry.Product2.Transfer_Charge_Day_2__c, 
                                                     PricebookEntry.Product2.Transfer_Charge_Day_1__c, 
                                                     PricebookEntry.Product2.Cancellation_Charge_Fee_Final__c, 
                                                     PricebookEntry.Product2.Cancellation_Charge_Fee_3__c, 
                                                     PricebookEntry.Product2.Cancellation_Charge_Fee_2__c, 
                                                     PricebookEntry.Product2.Cancellation_Charge_Fee_1__c, 
                                                     PricebookEntry.Product2.Cancellation_Charge_Day_3__c, 
                                                     PricebookEntry.Product2.Cancellation_Charge_Day_2__c, 
                                                     PricebookEntry.Product2.Cancellation_Charge_Day_1__c  
                                                from opportunitylineitem 
                                               where id in :oliIds];
        system.debug('oppLines' + oppLines);
        for (tncPublicEventCancellationWrapper wrapper : allbookings){
            for (OpportunityLineItem opl : oppLines){
                if (string.valueof(opl.id) == wrapper.booking.OPL_ID__c){
                    wrapper.oli = opl;
                    break;
                }
            }
        }
        
        
        setPageSize = 10;
        recordNumber = 0;
    }
    
    /*
    * checks if the next page is available.
    */
    public boolean hasNext(){ 
        if(recordNumber >= allBookings.size()) {
            return false; 
        } else {
            return true; 
        }
    } 
    
    /*
    * checks if previous page is available.
    */   
    public boolean hasPrevious(){ 
        if(recordNumber <= setPageSize) {
            return false; 
        } else {
            return true;
        }
    }
    
    /*
    * Loads next set of records
    */
    public List<tncPublicEventCancellationWrapper> next(){
        
        requestedBookings = new List<tncPublicEventCancellationWrapper>(); 
        integer startNumber = 0;
        
        if(hasNext()) {
            if(allBookings.size() <= (recordNumber + setPageSize)){
                startNumber = recordNumber;
                recordNumber = allBookings.size();
            } else {
                recordNumber = (recordNumber + setPageSize);
                startNumber = (recordNumber - setPageSize);
            }
            
            for(integer start = startNumber; start < recordNumber; start++) {
                requestedBookings.add(allBookings[start]);
            }
        } 
        
        return requestedBookings;
    }
    
    /*
    * Loads previous set of records
    */
    public List<tncPublicEventCancellationWrapper> previous(){
        
        integer size = allBookings.size(); 
        requestedBookings = new list<tncPublicEventCancellationWrapper>(); 
        
        if(recordNumber == size){
            if(math.mod(size, setPageSize) > 0)
            {    
                recordNumber = size - math.mod(size, setPageSize);
            }
            else
            {
                recordNumber = (size - setPageSize);
            } 
        } else {
            recordNumber = (recordNumber - setPageSize);
        }
        
        for(integer start = (recordNumber - setPageSize); start < recordNumber; ++start) {
            requestedBookings.add(allBookings[start]);
        } 
        
        return requestedBookings;
    }
}