src/objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Debug_Text__c</fullName>
        <label>Debug Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <inlineHelpText>The function for the error</inlineHelpText>
        <label>Function</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Message</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Create_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked opportunity is added into the queue to create an invoice for (currently only used for complywise invoices)</inlineHelpText>
        <label>Create Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The company on which this opportunity will be invoiced.</inlineHelpText>
        <label>Invoice Company</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or is not an active company.</errorMessage>
            <filterItems>
                <field>c2g__codaCompany__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>c2g__codaCompany__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Latest_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Whenever a new invoice is created on the opportunity, this is updated to the latest invoice.</inlineHelpText>
        <label>Latest Invoice</label>
        <referenceTo>c2g__codaInvoice__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BatchCreateInvoices.cls
global class BatchCreateInvoices implements Database.Batchable<sObject> {

	global final String Query;
	
	global BatchCreateInvoices(Integer size){
		query = 'SELECT Id FROM Opportunity WHERE create_invoice__c = True AND Latest_Invoice__c = null AND Invoice_Company__r.Name = \'Complywise Ltd\'';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC){
		return Database.getQueryLocator(query);
	}
	
	global void execute(Database.BatchableContext BC, List<Opportunity> scope){
		
		System.debug('FJP Executing create invoice batch based on: '+scope);
		
		for (Opportunity opp : scope){
			System.debug('FJP Creating invoice for opp: '+opp.Id);
			FinanceHelper.createInvoiceFromOpp(opp.Id, true);
		}
		
	}
	
	global void finish(Database.BatchableContext BC){
		
		AsyncApexJob a = [
			SELECT
				Id,
				Status,
				NumberOfErrors,
				JobItemsProcessed,
				TotalJobItems,
				MethodName,
				JobType,
				CreatedBy.Email
			FROM
				AsyncApexJob
			WHERE
				Id = : BC.getJobId()];
		
		Error_Log__c err = new Error_Log__c();
		
		err.Function__c = 'BatchCreateInvoices';
		if (a.NumberOfErrors > 0){
			err.Severity__c = 'Medium';
		}else{
			err.Severity__c = 'Message';
		}
		err.Debug_Text__c = 'The batch Apex job processed ' + a.TotalJobItems + ' batches with '+
			a.NumberOfErrors + ' failures.';
		
		insert err;
				
	}
	
	
	public static testMethod void testBatchCreateInvoices(){
		Test.startTest();
		BatchCreateInvoices batch = new BatchCreateInvoices(1);		
		Database.executeBatch(batch,1);
		Test.stopTest();
	}
	
}