src/objects/Invoice_History__c.object
<CustomObject>
    <fields>
        <fullName>Email_to__c</fullName>
        <description>Associated document will be emailed to this address</description>
        <inlineHelpText>Associated document will be emailed to this address</inlineHelpText>
        <label>Email to</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Evaluate_delivery_Workflow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Evaluate delivery Workflow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Failure_Message__c</fullName>
        <label>Failure Message</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Credit_Amount__c</fullName>
        <label>Invoice/Credit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount__c</fullName>
        <label>Opportunity Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Stage__c</fullName>
        <description>Opportunity Stage at Invoice / Credit Note creation</description>
        <label>Opportunity Stage</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoice History</relationshipLabel>
        <relationshipName>InvoiceHistory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Credit_Note__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Credit Notes</description>
        <label>Sales Credit Note</label>
        <referenceTo>c2g__codaCreditNote__c</referenceTo>
        <relationshipLabel>Invoice History</relationshipLabel>
        <relationshipName>Invoice_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Invoice</label>
        <referenceTo>c2g__codaInvoice__c</referenceTo>
        <relationshipLabel>Invoice History</relationshipLabel>
        <relationshipName>InvoiceHistory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credited &amp; Cash Un-Matched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>if this is a Invoice or a Credit</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice History</label>
    <nameField>
        <displayFormat>IH-{0000}</displayFormat>
        <label>Invoice History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AutoInvoiceHistory.cls
public class AutoInvoiceHistory {

	public static void createHistory(decimal invAmount, id opportunity, decimal oppAmount, string oppStage,
	                                 id creditNote, id invoice, string status, string type, string errorMessage, string emailTo){ 
		
		Invoice_History__c ih = new Invoice_History__c();
		ih.Invoice_Credit_Amount__c = invAmount;
		ih.Opportunity__c = opportunity;
		ih.Opportunity_Amount__c = oppAmount;
		ih.Opportunity_Stage__c = oppStage;
		ih.Sales_Credit_Note__c = creditNote;
		ih.Sales_Invoice__c = invoice;
		ih.Status__c = status;
		ih.Type__c = type;
		ih.Failure_Message__c = errorMessage;
		ih.Evaluate_delivery_Workflow__c = AutoInvoiceSettings.evaluateDeliveryWorkflow;
		ih.Email_to__c = emailTo;
		insert ih;
	}

    
}