src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Date_to_be_Invoiced__c</fullName>
        <inlineHelpText>The data on which this opportunity should be invoiced.</inlineHelpText>
        <label>Date to be Invoiced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Copied from Lead - Start date of the event the user wishes to book</description>
        <inlineHelpText>Copied from Lead - Start date of the event the user wishes to book</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <description>Requested by Sales, see case: 00002457</description>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If populated, this field indicates an original public events opportunity which has been partially closed</description>
        <inlineHelpText>If populated, this field indicates an original public events opportunity which has been partially closed</inlineHelpText>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subsequent Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rollover_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, this box indicates an opportunity has been created from partial closure of a public events opportunity</description>
        <inlineHelpText>If ticked, this box indicates an opportunity has been created from partial closure of a public events opportunity</inlineHelpText>
        <label>Rollover Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>T_C_Price__c</fullName>
        <description>Field automatically populated by Transfer / Cancellation trigger - used to track differences to require approval</description>
        <label>T/C Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Transfer_Charge_Day_1__c</fullName>
        <defaultValue>99</defaultValue>
        <description>Minimum number of days at which Fee 1 will be charged (the lowest rate)</description>
        <inlineHelpText>Minimum number of days at which Fee 1 will be charged (the lowest rate)</inlineHelpText>
        <label>Transfer Charge Day 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_2__c</fullName>
        <defaultValue>28</defaultValue>
        <description>Minimum number of days at which Fee 2 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 2 will be charged</inlineHelpText>
        <label>Transfer Charge Day 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_3__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Minimum number of days at which Fee 3 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 3 will be charged</inlineHelpText>
        <label>Transfer Charge Day 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_1__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee (lowest rate)</description>
        <inlineHelpText>Lowest percentage for calculating transfer fee - will apply if transfer takes place before Days 1</inlineHelpText>
        <label>Transfer Charge Fee 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_2__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 1 and before Days 2</inlineHelpText>
        <label>Transfer Charge Fee 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_3__c</fullName>
        <defaultValue>0.25</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 2 and before Days 3</inlineHelpText>
        <label>Transfer Charge Fee 3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_Final__c</fullName>
        <defaultValue>1.0</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 3</inlineHelpText>
        <label>Transfer Charge Fee Final</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Determines the type of event from a picklist</description>
        <inlineHelpText>Determine the type of event from the picklist</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NVQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Booking_Fee__c</fullName>
        <description>This is pulled from the opportunity product unit price for public an total price on the in-company primary for in-company</description>
        <inlineHelpText>The amount that should be charged for this booking. This is automatically updated, change this by updating the opportunity line.</inlineHelpText>
        <label>Booking Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related to the original account booking the event booking.</description>
        <inlineHelpText>Related to the original account booking the event booking</inlineHelpText>
        <label>Booking Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>R00N50000001mIaxEAE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the person attending the event as a delegate pulled from the contact</description>
        <inlineHelpText>The name of the person attending the event as a delegate</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Requested_Transfer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to determine whether to charge a customer for a public booking transfer. Auto populated when transferring a public booking.</description>
        <inlineHelpText>Tick this box if the client should incur transfer fees!</inlineHelpText>
        <label>Customer Requested Transfer Apply Fees</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Pulls in the related event&apos;s start date</description>
        <formula>Special_Event__r.StartDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related event&apos;s start date</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OPL_ID__c</fullName>
        <description>18 digit opportunity product line id that the event booking relates to</description>
        <externalId>true</externalId>
        <inlineHelpText>18 digit opportunity product line id that the event booking relates to</inlineHelpText>
        <label>OPL ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transfer_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for transferring public bookings to a new event. Auto populated when transferring a public booking.</description>
        <inlineHelpText>Used for transferring public bookings to a new event. Auto populated when transferring a public booking.</inlineHelpText>
        <label>Transfer to: Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (Transfer To)</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Defines the event booking type whether primary or additional etc</description>
        <inlineHelpText>Defines the event booking type whether primary or additional etc</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional - On the Day</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PublicBookingTransferController.cls
/*
    Test Coverage - 86%     06-10-10
    Created by Ben Mansfield 4 August 2010
    Modified by Ben Mansfield 6 August 2010
    
    Description:
    
    Changes:
    
        6 August 2010:
        * Changed way products are added to transfer fee opp - now takes pricebook into account
    
*/
public with sharing class PublicBookingTransferController
{   
    private static final String ERROR_NO_TRANSFER_SCHEDULED = 'Unable to transfer booking. Please make sure you have initiated a transfer ' +
        'by clicking on the \'Public Transfer\' button and following the wizard.';
    private static final String ERROR_NO_ORIG_OPPORTUNITY = 'Cannot find original Opportunity for this booking.';
    private static final String ERROR_NO_ORIG_PRODUCT = 'Cannot find original Product for this booking.';
    private static final String ERROR_NO_TRANSFER_FEE_FOUND = 'Cannot find \'Transfer Fees (Public)\' product. ' +
        'Please make sure this product is in the system and has been assigned to the correct pricebooks.';
        
        
        
    public Special_Event_Booking__c record              { get; set; }
    public Boolean transferSuccess                      { get; set; }
    
    public PublicBookingTransferController()
    {
        record = getEventBooking(ApexPages.CurrentPage().getParameters().get('id'));
        transferSuccess = false;
    }
    
    private Special_Event_Booking__c getEventBooking(Id id)
    {
        List<Special_Event_Booking__c> bookingQuery = [
            SELECT
                Id,
                Name,
                Special_Event__r.Product__c,
                Special_Event__r.RecordTypeId,
                Contact__c,
                Company__c,
                Type__c,
                Transfer_To__c,
                Customer_Requested_Transfer__c,
                Booking_Fee__c,
                Opportunity__c,
                OPL_ID__c,
                Event_Start_Date__c
            FROM
                Special_Event_Booking__c
            WHERE
                Id = :id];
                
        if (bookingQuery.size() == 1)
            return bookingQuery.get(0);
        
        return null;
    }
    
    public PageReference doTransfer()
    {
        System.savePoint sp = Database.setSavepoint();
        
        if (record.Transfer_To__c == null)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, ERROR_NO_TRANSFER_SCHEDULED));
            return null;
        }
        
        // Get the old opportunity
        List<Opportunity> opps = [
            SELECT
                Id,
                Name,
                OwnerId,
                AccountId,
                Pricebook2Id
            FROM
                Opportunity
            WHERE
                Id = :record.Opportunity__c];
        if (opps.size() != 1)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, ERROR_NO_ORIG_OPPORTUNITY));
            return null;
        }
        Opportunity oldOpp = opps.get(0);
        
        List<RecordType> recordTypes = [
            SELECT
                Id
            FROM
                RecordType
            WHERE
                SObjectType = 'Opportunity'
            AND
                Name = 'Public Event'];
        
        // Create a new opportunity
        Opportunity newOpp = new Opportunity(
            AccountId = oldOpp.AccountId,
            OwnerId = oldOpp.OwnerId,
            Name = oldOpp.Name + ' (' + record.name + ') - Transfer Fee',
            // brm - 6 August 2010 - add pricebook id to new opp
            Pricebook2Id = oldOpp.Pricebook2Id,
            RecordTypeId = (recordTypes.size() == 1 ? recordTypes.get(0).Id : null),
            Type = 'Public Course',
            CloseDate = System.today(),
            StageName = 'Quote/Proposal',
            Rollover_Opportunity__c = true,
            Date_to_be_Invoiced__c = Date.today(),
            Expected_Delivery_Date__c = Date.today(),
            Original_Opportunity__c = oldOpp.Id
            );

        insert newOpp;

        // START: Add old contact roles to new opportunity
        List<OpportunityContactRole> oppConts = new List<OpportunityContactRole>([SELECT ContactId, 
        																				isPrimary,
        																				Role
        																				FROM
        																					OpportunityContactRole
        																				WHERE
            																				isDeleted = False
	        																				AND OpportunityId = :oldOpp.Id]);
        List<OpportunityContactRole> newOppConts = new List<OpportunityContactRole>();
        
        for(OpportunityContactRole oppCont : oppConts){
        	OpportunityContactRole newOCR = new OpportunityContactRole(
        		ContactId = oppCont.ContactId,
        		OpportunityId = newOpp.Id,
	        	isPrimary = oppCont.isPrimary,
	        	Role = oppCont.Role);
        	newOppConts.add(newOCR);
        }
        if (newOppConts.size() > 0){
            insert newoppConts;
        }
        // END: Add old contact roles to new opportunity

        // Get public transfer fee product - brm - 6 August 2010 - now takes into account the pricebook
        Map<String, PricebookEntry> entries = BookingHelper.getPricebookEntries(newOpp.Pricebook2Id, new String[] { 'Transfer Fees (Public)' } );
        
        // Create a new line item for the new opp
        OpportunityLineItem oli = null;
        if (entries.containsKey('Transfer Fees (Public)'))
        {
            oli = new OpportunityLineItem(
                PricebookEntryId = entries.get('Transfer Fees (Public)').Id,
                OpportunityId = newOpp.Id,
                Quantity = 1,
                UnitPrice = 0,
                T_C_Price__c = 0);
        }
        else
        {
            // brm - 6 August 2010 - if we can't find product, rollback database and add error
            Database.rollback(sp);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, ERROR_NO_TRANSFER_FEE_FOUND));
            return null;
        }
        
        Double transferCost = 0;
        if (record.Customer_Requested_Transfer__c)
        {
            // Get currently booked product
            List<Product2> products = [
                SELECT
                    Id,
                    Transfer_Charge_Day_1__c,
                    Transfer_Charge_Day_2__c,
                    Transfer_Charge_Day_3__c,
                    Transfer_Charge_Fee_1__c,
                    Transfer_Charge_Fee_2__c,
                    Transfer_Charge_Fee_3__c,
                    Transfer_Charge_Fee_Final__c
                FROM
                    Product2
                WHERE
                    Id = :record.Special_Event__r.Product__c];
            if (products.size() != 1)
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, ERROR_NO_ORIG_PRODUCT));
                return null;
            }
            
            // Calculate transfer fees
            transferCost = BookingHelper.calculateTransferCost(record, products.get(0));
            
            // Set a transfer fee on opportunity product
            if (oli != null)
            {
                oli.UnitPrice = transferCost;
                oli.T_C_Price__c = transferCost;
            }
        }
        if (oli != null)
            insert oli;
        
        // Create a new BSC Event booking
        Special_Event_Booking__c newBooking = new Special_Event_Booking__c(
            Opportunity__c = oldOpp.Id,
            Special_Event__c = record.Transfer_To__c,
            Status__c = 'Confirmed',
            Contact__c = record.Contact__c,
            Company__c = record.Company__c,
            Transferred_From__c = record.Id,
            Type__c = record.Type__c,
            OPL_ID__c = record.OPL_ID__c,
            Booking_Fee__c = record.Booking_Fee__c);
        insert newBooking;
        
        // Modify existing event booking
        record.Status__c = 'Transferred';
        record.Opportunity__c = newOpp.Id;
        record.Transferred_To__c = newBooking.Id;
        record.Booking_Fee__c = transferCost;
        record.Transfer_Cancellation_Date__c = System.today();
        // brm - 4 August 2010 - Reset transfer to field
        //booking.Transfer_To__c = null;
        update record;
        transferSuccess = true;
        return new PageReference('/' + newOpp.Id);
    }
    
    @IsTest
    private static void test()
    {
    	string random = string.valueof(math.random()).substring(1,10);
    	
        Opportunity opp = new Opportunity(
            Name = 'Test Opp' + random,
            StageName = 'Closed Won',
            CloseDate = System.today());
        insert opp;
        
        Product2 prod = new Product2(
            Name = 'Test Event Product' + random,
            Allows_Provisional_Bookings__c = true,
            Transfer_Charge_Day_1__c = 10,
            Transfer_Charge_Day_2__c = 5,
            Transfer_Charge_Day_3__c = 2,
            Transfer_Charge_Fee_1__c = 120,
            Transfer_Charge_Fee_2__c = 60,
            Transfer_Charge_Fee_3__c = 40,
            Maximum_Attendees__c = 100,
            Transfer_Charge_Fee_Final__c = 10);
        insert prod;
        
        Special_Event__c event = new Special_Event__c(
            Product__c = prod.Id,
            Name = 'hello test'  + random,
            City__c = 'London',
            StartDate__c = System.today().addDays(3),
            Maximum_Places__c = 1000);
            
        insert event;
        
        Special_Event__c transferToEvent = new Special_Event__c(
            Product__c = prod.Id,
            Name = 'hello test2' + random,
            City__c = 'Birmingham',
            StartDate__c = System.today().addDays(3),
            Maximum_Places__c = 1000
            );
            
        insert transferToEvent;
        
        Special_Event_Booking__c eventBooking = new Special_Event_Booking__c(
            Opportunity__c = opp.Id,
            Special_Event__c = event.Id,
            Transfer_To__c = transferToEvent.Id,
            Customer_Requested_Transfer__c = true);
        insert eventBooking;
        
        PageReference pagRef = new PageReference('/apex/test');
        pagRef.getParameters().put('id', eventBooking.Id);
        Test.setCurrentPage(pagRef);
        //ApexPages.Standardcontroller stdContr = new ApexPages.Standardcontroller(eventBooking);
        PublicBookingTransferController controller = new PublicBookingTransferController();
        
        controller.doTransfer();
    }
}