src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Date_to_be_Invoiced__c</fullName>
        <inlineHelpText>The data on which this opportunity should be invoiced.</inlineHelpText>
        <label>Date to be Invoiced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Copied from Lead - Start date of the event the user wishes to book</description>
        <inlineHelpText>Copied from Lead - Start date of the event the user wishes to book</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <description>Requested by Sales, see case: 00002457</description>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IC_Price_Variation_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This box is ticked by the approval process of submitting a variation in In-Company products for approval</inlineHelpText>
        <label>IC Price Variation Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If populated, this field indicates an original public events opportunity which has been partially closed</description>
        <inlineHelpText>If populated, this field indicates an original public events opportunity which has been partially closed</inlineHelpText>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subsequent Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rollover_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, this box indicates an opportunity has been created from partial closure of a public events opportunity</description>
        <inlineHelpText>If ticked, this box indicates an opportunity has been created from partial closure of a public events opportunity</inlineHelpText>
        <label>Rollover Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Pricing_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to mark cancellation reconciliation prices as exceptions to avoid triggering approval</description>
        <inlineHelpText>Checkbox to mark cancellation reconciliation prices as exceptions to avoid triggering approval</inlineHelpText>
        <label>Pricing Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Manager_Price__c</fullName>
        <description>Price set by the Sales Manager for In-Company events - used in workflow</description>
        <inlineHelpText>Sales Manager enters the TOTAL PRICE (i.e. if Quantity is 3, this is the price for all 3)</inlineHelpText>
        <label>In-Company: Sales Manager Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>T_C_Price__c</fullName>
        <description>Field automatically populated by Transfer / Cancellation trigger - used to track differences to require approval</description>
        <label>T/C Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Charge_Day_1__c</fullName>
        <defaultValue>99</defaultValue>
        <description>Minimum number of days at which Fee 1 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 1 will be charged</inlineHelpText>
        <label>Cancellation Charge Day 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Day_2__c</fullName>
        <defaultValue>60</defaultValue>
        <description>Minimum number of days at which Fee 2 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 2 will be charged</inlineHelpText>
        <label>Cancellation Charge Day 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Day_3__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Minimum number of days at which Fee 3 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 3 will be charged</inlineHelpText>
        <label>Cancellation Charge Day 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_1__c</fullName>
        <defaultValue>0.3</defaultValue>
        <description>Percentage for calculating Cancellation fee (lowest rate)</description>
        <inlineHelpText>Lowest percentage for calculating cancellation fee - will apply if cancellation takes place before Days 1</inlineHelpText>
        <label>Cancellation Charge Fee 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_2__c</fullName>
        <defaultValue>0.3</defaultValue>
        <description>Percentage for calculating cancellation fee</description>
        <inlineHelpText>Percentage for calculating cancellation fee - will apply if cancellation takes place after Days 1 and before Days 2</inlineHelpText>
        <label>Cancellation Charge Fee 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_3__c</fullName>
        <defaultValue>0.3</defaultValue>
        <description>Percentage for calculating cancellation fee</description>
        <inlineHelpText>Percentage for calculating cancellation fee - will apply if cancellation takes place after Days 2 and before Days 3</inlineHelpText>
        <label>Cancellation Charge Fee 3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_Final__c</fullName>
        <defaultValue>1.0</defaultValue>
        <description>Percentage for calculating cancellation fee</description>
        <inlineHelpText>Percentage for calculating cancellation fee - will apply if cancellation takes place after Days 3</inlineHelpText>
        <label>Cancellation Charge Fee Final</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Booking_Fee__c</fullName>
        <description>This is pulled from the opportunity product unit price for public an total price on the in-company primary for in-company</description>
        <inlineHelpText>The amount that should be charged for this booking. This is automatically updated, change this by updating the opportunity line.</inlineHelpText>
        <label>Booking Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Pulls in the related event&apos;s start date</description>
        <formula>Special_Event__r.StartDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related event&apos;s start date</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Date__c</fullName>
        <description>The date on which the booking is transferred or cancelled</description>
        <inlineHelpText>The date on which the booking is transferred or cancelled</inlineHelpText>
        <label>Transfer / Cancellation Date</label>
        <type>Date</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InCompanyCancellationController.cls
/*
    Code Coverage - 99% 07-10-10
    Created by Ben Mansfield 16 July 2010
    Modified by Ben Mansfield 4 August 2010 
    
    Description:
    
    Changes:
    
        4 August 2010
        * Changed Opportunity and Opportunity Product creation by adding Pricebook from original Opportunity
    
*/
public with sharing class InCompanyCancellationController {

    private Special_Event__c record;
    
    

    public InCompanyCancellationController(ApexPages.StandardController controller)
    {
        record = getEvent(controller.getId());
    }
    
    private Special_Event__c getEvent(Id id)
    {
        List<Special_Event__c> eventQuery = [
            SELECT
                Name,
                Id,
                Product__c,
                Opportunity__c, 
                Opportunity__r.Name,
                Opportunity__r.AccountId,
                Opportunity__r.OwnerId,
                Opportunity__r.Pricebook2Id
            FROM
                Special_Event__c
            WHERE
                Id = :id];
                                            
        if (eventQuery.size() == 1)
            return eventQuery.get(0);
        
        return null;
    }
    
    public PageReference doAction()
    {
        
        
        List<Product2> products = [
            SELECT
                Id,
                Cancellation_Charge_Day_1__c,
                Cancellation_Charge_Day_2__c, 
                Cancellation_Charge_Day_3__c,
                Cancellation_Charge_Fee_1__c, 
                Cancellation_Charge_Fee_2__c,
                Cancellation_Charge_Fee_3__c, 
                Cancellation_Charge_Fee_Final__c,
                Description 
            FROM
                Product2
            WHERE
                Id = :record.Product__c];
        
        if (products.size() == 1)
        {
            Double totalCost = 0;
            List<Special_Event_Booking__c> eventBookings = new List<Special_Event_Booking__c>();
            for (Special_Event_Booking__c booking : [
                SELECT
                    Id,
                    Booking_Fee__c,
                    Event_Start_Date__c
                FROM
                    Special_Event_Booking__c
                WHERE
                    Special_Event__c = :record.Id])
            {
                Double cancellationCost = BookingHelper.calculateCancellationCost(booking, products.get(0));
                booking.Booking_Fee__c = cancellationCost;
                booking.Status__c = 'Cancelled';
                booking.Transfer_Cancellation_Date__c = System.today();
                totalCost += cancellationCost;
                
                eventBookings.add(booking);
            }
            
            update eventBookings;
            
            List<RecordType> recordTypes = [
                SELECT
                    Id
                FROM
                    RecordType
                WHERE
                    SObjectType = 'Opportunity'
                AND
                    Name = 'In-Company Event'
                LIMIT
                    1];
            
            Opportunity opp = new Opportunity(
                AccountId = record.Opportunity__r.AccountId,
                OwnerId = record.Opportunity__r.OwnerId,
                Name = record.Opportunity__r.Name + ' (' + record.Name + ') - Cancellation Fee',
                RecordTypeId = recordTypes.isEmpty() ? null : recordTypes.get(0).Id,                
                // brm - 4 August 2010 - set pricebook in new opp
                Pricebook2Id = record.Opportunity__r.Pricebook2Id,
                Type = 'In-Company Course',
                CloseDate = System.Today(),
                StageName = 'Quote/Proposal',
                IC_Price_Variation_Approved__c = true,
                Rollover_Opportunity__c = true,
                Date_to_be_Invoiced__c = System.today(),
                Expected_Delivery_Date__c = System.today(),
                Original_Opportunity__c = record.Opportunity__c);
                
            insert opp;
            
            // START: Add old contact roles to new opportunity
            List<OpportunityContactRole> oppConts = new List<OpportunityContactRole>([SELECT ContactId, 
            																				isPrimary,
            																				OpportunityId,
            																				Role
            																				FROM
            																					OpportunityContactRole
            																				WHERE
	            																				isDeleted = False
    	        																				AND OpportunityId = :record.Opportunity__c]);
            List<OpportunityContactRole> newOppConts = new List<OpportunityContactRole>();
            
	        for(OpportunityContactRole oppCont : oppConts){
	        	OpportunityContactRole newOCR = new OpportunityContactRole(
	        		ContactId = oppCont.ContactId,
	        		OpportunityId = opp.Id,
		        	isPrimary = oppCont.isPrimary,
		        	Role = oppCont.Role);
	        	newOppConts.add(newOCR);
	        }
	        if (newOppConts.size() > 0){
	            insert newoppConts;
	        }
            // END: Add old contact roles to new opportunity

            // brm - 4 August 2010 - now using pricebook when finding pricebook entries
            Map<String, PricebookEntry> entries = BookingHelper.getPricebookEntries(record.Opportunity__r.Pricebook2Id,
                new String[] {'Cancellation Fees (In-Company)', 'Reconciliation (In-Company)'});
            
            List<OpportunityLineItem> olisToInsert = new List<OpportunityLineItem>();
            
            if (entries.containsKey('Cancellation Fees (In-Company)'))
            {
                OpportunityLineItem oli = new OpportunityLineItem(
                    PricebookEntryId = entries.get('Cancellation Fees (In-Company)').Id,
                    OpportunityId = opp.Id,
                    Quantity = 1,
                    Sales_Manager_Price__c = totalCost,
                    UnitPrice = totalCost,
                    Pricing_Exception__c = true,
                    T_C_Price__c = totalCost); 
                
                olisToInsert.add(oli);
            }
            
            List<OpportunityLineItem> originalOlis = [
                SELECT
                    c2g__CODAUnitOfWork__c,
                    UnitPrice,
                    TotalPrice,
                    T_C_Price__c,
                    T_C_Price_Variation__c,
                    SystemModstamp, 
                    Subscription_Start_Date__c,
                    Subscription_Product__c, 
                    SortOrder,
                    ServiceDate,
                    Sales_Manager_Price__c, 
                    SM_Price_Needed__c,
                    Quantity,
                    Pricing_Exception__c, 
                    PricebookEntryId,
                    OpportunityId,
                    ListPrice, 
                    LastModifiedDate,
                    LastModifiedById,
                    IsDeleted,
                    Id, 
                    IC_Price_Difference__c,
                    HasSchedule,
                    HasRevenueSchedule, 
                    HasQuantitySchedule,
                    Duration_Years__c,
                    Discounted__c, 
                    Description,
                    CurrencyIsoCode,
                    CreatedDate,
                    CreatedById, 
                    ConnectionSentId,
                    ConnectionReceivedId 
                FROM
                    OpportunityLineItem
                WHERE
                    PricebookEntry.Product2Id = :products.get(0).Id
                AND
                    OpportunityId = :record.Opportunity__c];
            
            if (originalOlis.size() == 1)
            {
                // Step 6
                OpportunityLineItem clonedOli = originalOlis.get(0).clone(false, true);
                clonedOli.UnitPrice = -clonedOli.UnitPrice;
                clonedOli.TotalPrice = null;
                clonedOli.Pricing_Exception__c = true;
                clonedOli.Sales_Manager_Price__c = originalOlis.get(0).TotalPrice;
                olisToInsert.add(clonedOli);
                
                // Step 7 - 9
                if (entries.containsKey('Reconciliation (In-Company)'))
                {
                    OpportunityLineItem reconOrigOli = new OpportunityLineItem(
                        PricebookEntryId = entries.get('Reconciliation (In-Company)').Id,
                        OpportunityId = record.Opportunity__c,
                        Sales_Manager_Price__c = originalOlis.get(0).TotalPrice,
                        Quantity = 1,
                        UnitPrice = originalOlis.get(0).TotalPrice,
                        Pricing_Exception__c = true
                        );
                    olisToInsert.add(reconOrigOli);
                    
                    OpportunityLineItem reconNewOli = new OpportunityLineItem(
                        PricebookEntryId = entries.get('Reconciliation (In-Company)').Id,
                        OpportunityId = opp.Id,
                        Quantity = 1,
                        Sales_Manager_Price__c = originalOlis.get(0).TotalPrice,
                        UnitPrice = -originalOlis.get(0).TotalPrice,
                        Pricing_Exception__c = true);
                    olisToInsert.add(reconNewOli);
                }
            }
            
            insert olisToInsert;
            if (entries.containsKey('Cancellation Fees (In-Company)'))
            {
                for(Special_Event_Booking__c booking:eventBookings)
                {
                    booking.OPL_ID__c = olisToInsert.get(0).Id;
                }
                
                update eventBookings;
            }
            
            
            // brm - 20 July 2010 - change event status to 'to be cancelled'
            record.Status__c = 'To be cancelled';
            
            update record;
            products.get(0).Description =  record.Name;
            update products;
            if(record.RecordTypeId == '012200000001W3h')
                return new PageReference('/'+opp.Id);
        }
        
        return new PageReference('/' + record.Id);
    }
    
    @IsTest
    private static void test()
    {
        Product2 prod = new Product2(Name = 'Product Test');
        prod.Cancellation_Charge_Day_1__c = 32;
        prod.Cancellation_Charge_Day_2__c = 16;
        prod.Cancellation_Charge_Day_3__c = 4;
        
        prod.Cancellation_Charge_Fee_1__c = 10;
        prod.Cancellation_Charge_Fee_2__c = 20;
        prod.Cancellation_Charge_Fee_3__c = 50;
        prod.Cancellation_Charge_Fee_Final__c = 100;
        insert prod;
        
        Pricebook2 stdPricebook = [Select Id From Pricebook2 Where IsStandard = true Limit 1];
        
        PricebookEntry pbe = new PricebookEntry();
        pbe.Pricebook2Id = stdPricebook.Id;
        pbe.Product2Id = prod.Id;
        pbe.UnitPrice = 360;
        pbe.IsActive = true;
        insert pbe;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'In-Company Event Test';
        opp.StageName = 'Qualifying';
        opp.CloseDate = System.today();
        insert opp;
        
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = opp.Id;
        oli.PricebookEntryId = pbe.Id;
        oli.UnitPrice = 360;
        oli.Quantity = 1;
        insert oli;
        
        Special_Event__c event = new Special_Event__c();
        event.StartDate__c = System.today() + 5;
        event.Product__c = prod.Id;
        event.Opportunity__c = opp.Id;
        insert event;
        
        Special_Event_Booking__c booking = new Special_Event_Booking__c();
        booking.Booking_Fee__c = 200;
        booking.Special_Event__c = event.Id;
        insert booking;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(event);
        InCompanyCancellationController controller = new InCompanyCancellationController(stdController);
        controller.doAction();
    }
}