src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>IC_Price_Variation_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This box is ticked by the approval process of submitting a variation in In-Company products for approval</inlineHelpText>
        <label>IC Price Variation Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Delegates__c</fullName>
        <description>Copied from Lead - the number of delegates the customers wishes to book on the course</description>
        <inlineHelpText>Copied from Lead - the number of delegates the customers wishes to book on the course</inlineHelpText>
        <label>Number of Delegates</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Approval_Given__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Price Approval Given</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Audit</fullName>
        <active>true</active>
        <businessProcess>BSC Sales Process</businessProcess>
        <description>Opportunity to manage sale of an Audit</description>
        <label>Audit</label>
    </recordTypes>
    <recordTypes>
        <fullName>In_Company_Event</fullName>
        <active>true</active>
        <businessProcess>BSC Sales Process</businessProcess>
        <description>Opportunity to manage sale of an in-company training course</description>
        <label>In-Company Event</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>E_Delivery_Number_of_Licences__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of licenses (multiplied by Quantity to produce total count)</description>
        <inlineHelpText>Do not confuse with Quantity!</inlineHelpText>
        <label>E-Delivery: Number of Licences</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_Company_Number_of_Days__c</fullName>
        <inlineHelpText>Number of Days</inlineHelpText>
        <label>In Co: No. of Days</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Delegates__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of Delegates for In-Company Courses</description>
        <inlineHelpText>In-Company Training Courses Only</inlineHelpText>
        <label>IC Training: No. of Delegates</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Fee_Product__c</fullName>
        <formula>PricebookEntry.Product2.Transfer_Fee_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Transfer Fee Product</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Allows_Provisional_Bookings__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Ticking this box allows provisional bookings to be made through the Coursefinder page. (I.e. tick this on public events.)</inlineHelpText>
        <label>Allows Provisional Bookings</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Record_Type__c</fullName>
        <label>Event Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Maximum_Discount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>Applies if discount permitted = true</description>
        <inlineHelpText>Enter the maximum discount that may be offered before the opportunity requires approval. (If discount is permitted)</inlineHelpText>
        <label>Maximum Discount</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_1__c</fullName>
        <defaultValue>99</defaultValue>
        <description>Minimum number of days at which Fee 1 will be charged (the lowest rate)</description>
        <inlineHelpText>Minimum number of days at which Fee 1 will be charged (the lowest rate)</inlineHelpText>
        <label>Transfer Charge Day 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_2__c</fullName>
        <defaultValue>28</defaultValue>
        <description>Minimum number of days at which Fee 2 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 2 will be charged</inlineHelpText>
        <label>Transfer Charge Day 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_3__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Minimum number of days at which Fee 3 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 3 will be charged</inlineHelpText>
        <label>Transfer Charge Day 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_1__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee (lowest rate)</description>
        <inlineHelpText>Lowest percentage for calculating transfer fee - will apply if transfer takes place before Days 1</inlineHelpText>
        <label>Transfer Charge Fee 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_2__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 1 and before Days 2</inlineHelpText>
        <label>Transfer Charge Fee 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_3__c</fullName>
        <defaultValue>0.25</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 2 and before Days 3</inlineHelpText>
        <label>Transfer Charge Fee 3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_Final__c</fullName>
        <defaultValue>1.0</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 3</inlineHelpText>
        <label>Transfer Charge Fee Final</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Fee_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to Transfer Fee product used when this product is transferred. This product is added to the cancellation Fee opportunity created during the transfer process</description>
        <inlineHelpText>Links to Transfer Fee product used when this product is transferred.</inlineHelpText>
        <label>Transfer Fee Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Transfer Fee Product)</relationshipLabel>
        <relationshipName>TransferFeeProduct</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>City__c</fullName>
        <description>Select the city that the event will be taking place</description>
        <inlineHelpText>Select the city that the event will be taking place</inlineHelpText>
        <label>City</label>
        <picklist>
            <picklistValues>
                <fullName>Aberdeen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birmingham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bristol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crawley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dundee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edinburgh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exeter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huntingdon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sheffield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stirling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Latest_Start_Date__c</fullName>
        <description>Field populated when provisional events are created from the opportunity</description>
        <inlineHelpText>Field populated when provisional events are created from the opportunity and is selected when using the request event wizard on the opportunity</inlineHelpText>
        <label>Latest Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when Special Event starts.</description>
        <inlineHelpText>Date when Special Event starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <recordTypes>
        <fullName>Audit</fullName>
        <active>true</active>
        <description>Audit or Advisory Session</description>
        <label>Audit</label>
    </recordTypes>
    <recordTypes>
        <fullName>In_Company_Event</fullName>
        <active>true</active>
        <description>In-Company Training Course or similar</description>
        <label>In-Company Event</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Event_Type__c</fullName>
        <formula>Special_Event__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/tncConfirmTransferTest.cls
@IsTest(SeeAllData=true)
public class tncConfirmTransferTest{
    
    static testmethod void testConfirmTransfer(){
        string random = string.valueof(math.random()).substring(1,10);

        Account acc = new Account(name = 'BSC Test');
        insert acc;
        system.debug('Account acc - ' + acc);
        
        Contact cont = new Contact (FirstName = 'BSC', LastName = 'Test', Accountid = acc.id);
        insert cont;
        system.debug('Contact cont - ' + cont);

/*        
        Opportunity opp = new Opportunity(
            Name = 'Test Opp ' + random,
            StageName = 'Qualifying',
            IC_Price_Variation_Approved__c = true,
            CloseDate = System.today());
        insert opp;
*/

        RecordType rt = [SELECT Id, DeveloperName, SobjectType FROM RecordType where DeveloperName = 'In_Company_Event' and sObjectType = 'Opportunity' limit 1];

        Opportunity opp = new Opportunity(
            Name = 'BSC Test',
            RecordTypeId = rt.id,
            AccountId = acc.id,
            Type = 'Audit',
            StageName = 'Quote/Proposal',
            IC_Price_Variation_Approved__c = true,
            Price_Approval_Given__c = true,
            CloseDate = System.today());
        insert opp;
        system.debug('Opportunity opp - ' + opp);
        
/*
         Product2 prod1 = new Product2(
            Name = 'Test Event1 Product' +random
            );
        insert prod1;
*/
         Product2 prod1 = [select name, Maximum_Discount__c from product2 where name = 'Transfer Fees (Audit)'];
        system.debug('Product2 prod1 - ' + prod1);
/*
        Product2 prod = new Product2(
            Name = 'Test Event Product' +random,
            Allows_Provisional_Bookings__c = true,
            Transfer_Charge_Day_1__c = 10,
            Transfer_Charge_Day_2__c = 5,
            Transfer_Charge_Day_3__c = 2,
            family = 'Audit',
            Event_Record_Type__c = 'Audit',
            Event_Type__c = 'Audit',
            Transfer_Charge_Fee_1__c = 120,
            Transfer_Charge_Fee_2__c = 60,
            Transfer_Charge_Fee_3__c = 40,
            Transfer_Charge_Fee_Final__c = 10,
            Transfer_Fee_Product__c = prod1.id);
        insert prod;
*/
         Product2 prod = [select name, Maximum_Discount__c, Allows_Provisional_Bookings__c, Transfer_Charge_Day_1__c, Transfer_Charge_Day_2__c, Transfer_Charge_Day_3__c,
                            family, Event_Record_Type__c, Event_Type__c, 
                            Transfer_Charge_Fee_1__c, Transfer_Charge_Fee_2__c, Transfer_Charge_Fee_3__c, Transfer_Charge_Fee_Final__c,
                            Transfer_Fee_Product__c
                            from product2 where name = 'Five Star Occupational Health and Safety Audit'];
        system.debug('Product2 prod - ' + prod);

        Pricebook2 stdPricebook = [SELECT Id FROM Pricebook2 WHERE IsStandard = true and Name = 'Standard Price Book' Limit 1];
        system.debug('Pricebook2 stdPricebook - ' + stdPricebook);
/*
        PricebookEntry pbe1 = new PricebookEntry(
            Product2Id = prod1.Id,
            UnitPrice = 300,
            Pricebook2Id = stdPricebook.Id,
            IsActive = true);
        insert pbe1;
*/

        PricebookEntry pbe1 = [SELECT IsActive, UnitPrice, Id, Pricebook2Id, ProductCode, Product2Id, Name, UseStandardPrice 
                                FROM PricebookEntry where Product2Id = :prod1.id and Pricebook2Id = :stdPricebook.id];
        system.debug('PricebookEntry pbe1 - ' + pbe1);
/*
        PricebookEntry pbe = new PricebookEntry(
            Product2Id = prod.Id,
            UnitPrice = 300,
            Pricebook2Id = stdPricebook.Id,
            IsActive = true);
        insert pbe;
*/
        PricebookEntry pbe = [SELECT IsActive, UnitPrice, Id, Pricebook2Id, ProductCode, Product2Id, Name, UseStandardPrice 
                                FROM PricebookEntry where Product2Id = :prod.id and Pricebook2Id = :stdPricebook.id];
        system.debug('PricebookEntry pbe - ' + pbe);

        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            PricebookEntryId = pbe.Id,
            Quantity = 1,
            UnitPrice = pbe.unitprice,
            Number_of_Delegates__c=1,
            E_Delivery_Number_of_Licences__c = 1,
            In_Company_Number_of_Days__c=1);
        insert oli;
        system.debug('OpportunityLineItem oli - ' + oli);
/*        
        Account acc = new Account(name = 'TestAccount'+random);
        insert acc;
        
        Contact cont = new Contact ();
        cont.FirstName = 'TestFN'+random;
        cont.LastName = 'TestLN'+random;
        cont.Accountid = acc.id;
        insert cont;
*/
        OpportunityContactRole ocr = new OpportunityContactRole(
            OpportunityId = opp.Id,
            ContactId = cont.Id,
            isPrimary = true);
        insert ocr;
        system.debug('OpportunityContactRole ocr - ' + ocr);
/*        
        Special_Event__c event = new Special_Event__c();
        event.Product__c = prod.Id;
        event.City__c = 'London';
        event.StartDate__c = System.today();
        event.Latest_Start_Date__c = system.today().addDays(3);
        event.Status__c ='Confirmed';
        insert event;
*/

        Special_Event__c event = new Special_Event__c();
        event.Product__c = prod.Id;
        event.Opportunity__c = opp.id;
        event.Status__c ='To Be Transferred';
        event.Stage__c ='Cancelled';
        event.StartDate__c = System.today();
        event.Latest_Start_Date__c = system.today();
        event.Audit_Number_of_Days__c = 1;
        event.Minimum_Places__c = 1;
        event.Maximum_Places__c = 1;
        event.Liability_at_Cancellation_Transfer__c = 0;
        insert event;
        system.debug('Special_Event__c event - ' + event);

        Special_Event_Booking__c eventBooking = new Special_Event_Booking__c();
        eventBooking.Opportunity__c = opp.Id;
        eventBooking.Contact__c = cont.id;
        eventBooking.Special_Event__c = event.Id;
        eventBooking.OPL_ID__c = oli.id;
        insert eventBooking;
        system.debug('Special_Event_Booking__c eventBooking - ' + eventBooking);

        Special_Event__c event1 = new Special_Event__c();
        event1.Product__c = prod.Id;
        event1.Opportunity__c = opp.id;
        event1.Status__c ='Resourced';
        event1.Stage__c ='Provisional';
        event1.StartDate__c = System.today();
        event1.Latest_Start_Date__c = system.today().addDays(1);
        insert event1;
        system.debug('Special_Event__c event1 - ' + event1);
       
        event.Transferred_To__c = event1.id;
        update event;
       
        Special_Event_Booking__c eventBooking1 = new Special_Event_Booking__c();
        eventBooking1.Opportunity__c = opp.Id;
        eventBooking1.Special_Event__c = event1.Id;
        eventBooking1.OPL_ID__c = oli.id;
        insert eventBooking1;
        system.debug('Special_Event_Booking__c eventBooking1 - ' + eventBooking1);

        Test.startTest();
        PageReference pagRef = new PageReference('/apex/tncConfirmTransfer?oppId=' + string.valueOf(opp.Id));
        Test.setCurrentPage(pagRef);
        tncConfirmTransfer con = new tncConfirmTransfer();
        for (tncConfirmTransfer.ConfirmEvents conf : con.events){
            conf.selected = true;
        }
        con.confirmTransfer();
    }
}