src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Copied from Lead - Start date of the event the user wishes to book</description>
        <inlineHelpText>Copied from Lead - Start date of the event the user wishes to book</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IC_Price_Variation_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This box is ticked by the approval process of submitting a variation in In-Company products for approval</inlineHelpText>
        <label>IC Price Variation Approved</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Pricing_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to mark cancellation reconciliation prices as exceptions to avoid triggering approval</description>
        <inlineHelpText>Checkbox to mark cancellation reconciliation prices as exceptions to avoid triggering approval</inlineHelpText>
        <label>Pricing Exception</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Allows_Provisional_Bookings__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Ticking this box allows provisional bookings to be made through the Coursefinder page. (I.e. tick this on public events.)</inlineHelpText>
        <label>Allows Provisional Bookings</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_1__c</fullName>
        <defaultValue>99</defaultValue>
        <description>Minimum number of days at which Fee 1 will be charged (the lowest rate)</description>
        <inlineHelpText>Minimum number of days at which Fee 1 will be charged (the lowest rate)</inlineHelpText>
        <label>Transfer Charge Day 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_2__c</fullName>
        <defaultValue>28</defaultValue>
        <description>Minimum number of days at which Fee 2 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 2 will be charged</inlineHelpText>
        <label>Transfer Charge Day 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_3__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Minimum number of days at which Fee 3 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 3 will be charged</inlineHelpText>
        <label>Transfer Charge Day 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_1__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee (lowest rate)</description>
        <inlineHelpText>Lowest percentage for calculating transfer fee - will apply if transfer takes place before Days 1</inlineHelpText>
        <label>Transfer Charge Fee 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_2__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 1 and before Days 2</inlineHelpText>
        <label>Transfer Charge Fee 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_3__c</fullName>
        <defaultValue>0.25</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 2 and before Days 3</inlineHelpText>
        <label>Transfer Charge Fee 3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_Final__c</fullName>
        <defaultValue>1.0</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 3</inlineHelpText>
        <label>Transfer Charge Fee Final</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>City__c</fullName>
        <description>Select the city that the event will be taking place</description>
        <inlineHelpText>Select the city that the event will be taking place</inlineHelpText>
        <label>City</label>
        <picklist>
            <picklistValues>
                <fullName>Aberdeen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birmingham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bristol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crawley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dundee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edinburgh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exeter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huntingdon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sheffield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stirling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when Special Event starts.</description>
        <inlineHelpText>Date when Special Event starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Booking_Fee__c</fullName>
        <description>This is pulled from the opportunity product unit price for public an total price on the in-company primary for in-company</description>
        <inlineHelpText>The amount that should be charged for this booking. This is automatically updated, change this by updating the opportunity line.</inlineHelpText>
        <label>Booking Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Pulls in the related event&apos;s start date</description>
        <formula>Special_Event__r.StartDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related event&apos;s start date</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/tncTransferBookingTest.cls
@IsTest(SeeAllData=true)
public class tncTransferBookingTest{
    
    static testMethod void testtncTransferBooking()
    {
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.StageName = 'Closed Won';
        opp.CloseDate = System.today();
        insert opp;
        
        Product2 prod = new Product2();
        prod.Name = 'Test Event Product';
        prod.Allows_Provisional_Bookings__c = true;
        prod.Transfer_Charge_Day_1__c = 10;
        prod.Transfer_Charge_Day_2__c = 5;
        prod.Transfer_Charge_Day_3__c = 2;
        
        prod.Transfer_Charge_Fee_1__c = 120;
        prod.Transfer_Charge_Fee_2__c = 60;
        prod.Transfer_Charge_Fee_3__c = 40;
        prod.Transfer_Charge_Fee_Final__c = 10;
        insert prod;
        
        Special_Event__c event = new Special_Event__c();
        event.Product__c = prod.Id;
        event.City__c = 'London';
        event.StartDate__c = System.today().addDays(3);
        insert event;
        
        Special_Event_Booking__c eventBooking = new Special_Event_Booking__c();
        eventBooking.Opportunity__c = opp.Id;
        eventBooking.Special_Event__c = event.Id;
        insert eventBooking;
        
        PageReference pagRef = new PageReference('/apex/tncTransferBookingWizard?id='+eventBooking.Id+'&fieldname='+eventBooking.Id+'&events='+event.Name);
        Test.setCurrentPage(pagRef);
        tncTransferBookingWizard con = new tncTransferBookingWizard();
        system.assert(con.record != null);
    }
    
    @IsTest
    private static void testTransfer()
    {
        string random = string.valueof(math.random()).substring(1,10);
        system.debug('************* VS *******' + random);
        Account acc = new Account (
            Name = 'Test Acc'+random,
            Phone = '00000'
            );
        insert acc;
        
        Opportunity opp = new Opportunity(
            AccountId = acc.Id,
            Name = 'Test Opp'+random,
            StageName = 'Qualifying',
            IC_Price_Variation_Approved__c = true,
            CloseDate = System.today());
        system.debug('************* VS *******' + opp.Name);
        insert opp;
        
        Product2 prod = new Product2(
            Name = 'Test Event Product'+random,
            Allows_Provisional_Bookings__c = true,
            Transfer_Charge_Day_1__c = 10,
            Transfer_Charge_Day_2__c = 5,
            Transfer_Charge_Day_3__c = 2,
            Transfer_Charge_Fee_1__c = 120,
            Transfer_Charge_Fee_2__c = 60,
            Transfer_Charge_Fee_3__c = 40,
            Transfer_Charge_Fee_Final__c = 10);
        insert prod;
        
        Pricebook2 stdPricebook = [
            SELECT
                Id
            FROM
                Pricebook2
            WHERE
                IsStandard = true Limit 1];
        
        PricebookEntry pbe = new PricebookEntry(
            Product2Id = prod.Id,
            UnitPrice = 300,
            Pricebook2Id = stdPricebook.Id,
            IsActive = true);
        insert pbe;
        
        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            PricebookEntryId = pbe.Id,
            Pricing_Exception__c = true,
            Quantity = 3,
            UnitPrice = 320);
        insert oli;
        
        Special_Event__c event = new Special_Event__c(
            Product__c = prod.Id,
            City__c = 'London',
            StartDate__c = System.today().addDays(3),
        	Name = 'Test123');
        insert event;
        
        Special_Event_Booking__c eventBooking = new Special_Event_Booking__c(
            Opportunity__c = opp.Id,
            Special_Event__c = event.Id);
        insert eventBooking;
        
        // Event to transfer
        Special_Event__c transferevent = new Special_Event__c(
            Product__c = prod.Id,
            City__c = 'London',
            Status__c= 'Confirmed',
            StartDate__c = System.today().addDays(30));
        insert transferevent;
        
        tncTransferBookingController con = new tncTransferBookingController();
        con.bookingType = 'Transfer';
        con.eventstoExclude  = event.Name;
        system.debug('con.eventstoExclude: '+con.eventstoExclude);
        con.fieldName = eventBooking.id;
        List<Special_Event_Booking__c> bookingQuery = [
            SELECT
                Id,
                Name,
                Special_Event__r.Product__c,
                Booking_Fee__c,
                Opportunity__c,
                Event_Start_Date__c
            FROM
                Special_Event_Booking__c
            WHERE
                Id = :eventBooking.id];
        
        if (bookingQuery.size() == 1)
            eventBooking = bookingQuery.get(0);
        
        con.booking = [
            SELECT
                Id,
                Name,
                Special_Event__r.Product__c,
                Contact__c,
                Company__c,
                Booking_Fee__c,
                Opportunity__c,
                Event_Start_Date__c 
            FROM
                Special_Event_Booking__c
            WHERE
                Id = :eventBooking.Id];
        
        con.locationCriteria.add('London');
        
        con.next();
        //System.assertEquals(new List<ApexPages.Message>(), ApexPages.getMessages());
        
        // Select the event we created above
        for (tncTransferBookingController.BSCEvent ev : con.eventSelections)
        {
            if (ev.record.Id == transferevent.Id) ev.selected = true;
        }
        
        con.next();
        //System.assertEquals(new List<ApexPages.Message>(), ApexPages.getMessages());
        
        con.save();
        //System.assertEquals(new List<ApexPages.Message>(), ApexPages.getMessages());
        con.cancel();
    }
    
}