src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <displayFormat>O-{0000000}</displayFormat>
        <label>Opportunity Number</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Transfer_Cancellation_Reasons__c.object
<CustomObject>
    <description>Reason for Transfer/Cancellation of bookings</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <description>Event to be set to Status for the selected reason if the Event is cancelled</description>
        <inlineHelpText>Event to be set to Status for the selected reason</inlineHelpText>
        <label>Cancel Event Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fees_To_Be_Applied__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If fees are to be applied = Client at fault (client no longer wants to do the course)
If fees are not to be applied means that BSC is at fault (i.e. BSC had to cancel the course)</inlineHelpText>
        <label>Fees To Be Applied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Need_Attachments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Needs attachment for this reason</description>
        <inlineHelpText>Needs attachment for this reason</inlineHelpText>
        <label>Need Attachments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notes Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Transfer &amp; Cancellation Reason</label>
    <nameField>
        <label>Transfer &amp; Cancellation Reason</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfer &amp; Cancellation Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/tncPublicEventCancellationController.cls
public class tncPublicEventCancellationController{
     
    private Id oppId	                                            {get; set;}
    public tncPublicEventCancellationHandler handler               {get; set;}
    
    public list<tncPublicEventCancellationWrapper> selectedBookings {get; set;}
    public list<tncPublicEventCancellationWrapper> listBookings     {get; set;}


    public boolean displaySelectionSection                          {get; set;}
    public boolean displayFeeEntrySection                           {get; set;}
    public boolean showError                                        {get; set;}
    public string cancellationError                                 {get; set;}
    public List<SelectOption> selectOptionReasons                   {get; set;}
    public List<Transfer_Cancellation_Reasons__c> tcReasons         {get; set;}

    
    public tncPublicEventCancellationController(){
        
        oppId = id.ValueOf(System.currentPageReference().getParameters().get('oppId'));
        
        string allClear = tncHelper.allowedToCancelInCompanyEvent('Opportunity', oppId);
        system.debug(allclear);
        if (allClear == 'All Clear' || allClear == 'Part Invoicing'){

            handler = new tncPublicEventCancellationHandler(oppId);
            selectedBookings = new list<tncPublicEventCancellationWrapper>();
            visibleSection(true, false);
            
            selectOptionReasons = new List<SelectOption>();
            tcReasons = [select id, Name, Notes_Required__c, Fees_To_Be_Applied__c, Need_Attachments__c, Event_Status__c  from Transfer_Cancellation_Reasons__c where Active__c = true];
            
            selectOptionReasons.add(new SelectOption('Select Reason', 'Select Reason'));
            for (Transfer_Cancellation_Reasons__c tcReason : tcReasons){
                selectOptionReasons.add(new SelectOption(tcReason.Name, tcReason.Name));
            }
            
            next();
        } else {
            visibleSection(false, false);
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, allClear));
        }
    }
    
    public void visibleSection(boolean one, boolean two){
    	displaySelectionSection = one;
        displayFeeEntrySection = two;
    }
    
    public void back(){
        visibleSection(true, false);
    }
    
    public void next() {
        listBookings = handler.next();
    }
    
    public Boolean hasNext {
        get {
            return handler.hasNext();
        }
        set;
    }
    
    public void previous() {
        listBookings = handler.previous();
    }
    
    public Boolean hasPrevious {
        get {
            return handler.hasPrevious();
        }
        set;
    }
    
    public void autoSelectAllRecords(){
        for (tncPublicEventCancellationWrapper bookingWrapper : handler.allBookings){
            bookingWrapper.isSelected = true;
        }
        //checkReason();
    }
    
    public PageReference checkReason(){
        cancellationError = '';
        showError = false;
        selectedBookings.clear();
        integer numberOfAttachments;
		try{
			numberOfAttachments = (integer)[select count(Id) totalattachments from Attachment where ParentId = :oppId][0].get('totalattachments');
		} catch (Exception e) {
			numberOfAttachments = 0;
        }
        for (tncPublicEventCancellationWrapper bookingSelected : handler.allBookings){
            if (bookingSelected.isSelected) {
                boolean rowHasError = false;
                
                system.debug('bookingSelected.reasonData ' + bookingSelected.reasonData);
                
                if (bookingSelected.reasonData.cancellationRequestedOn == ''){
                    cancellationError += 'Error: ' + bookingSelected.booking.Name + ': Cancellation Request Date is required <BR/>';
                    rowHasError = true;
                    system.debug('1');
                } else if (bookingSelected.reasonData.cancellationRequestedOn != '' &&
                    date.parse(bookingSelected.reasonData.cancellationRequestedOn) > system.today()){
                    cancellationError += 'Error: ' + bookingSelected.booking.Name + ': Cancellation Request Date cannot be in the future <BR/>';
                    rowHasError = true;
                    system.debug('2');
                }
                if (bookingSelected.reasonData.reason == 'Select Reason'){
                    cancellationError += 'Error: ' + bookingSelected.booking.Name + ': Cancellation Reason Invalid. <BR/>';
                    rowHasError = true;
                    system.debug('3');
                } else {
                    for (Transfer_Cancellation_Reasons__c checkReason : tcReasons){
                        
                        if (bookingSelected.reasonData.reason == checkreason.Name){
                            bookingSelected.reasonData.reasonId = checkreason.Id;
                            bookingSelected.reasonData.eventStatus = checkreason.Event_Status__c;
                            bookingSelected.feesToBeApplied = checkreason.Fees_To_Be_Applied__c;
                        }
                        
                        if (bookingSelected.reasonData.reason == checkreason.Name && 
                            bookingSelected.reasonData.reasonNote == '' &&
                            (checkreason.Notes_Required__c == true || checkreason.Need_Attachments__c == true)){
                                if (checkreason.Notes_Required__c == true) {
                                    cancellationError += 'Error: ' + bookingSelected.booking.Name + ': Cancellation Notes are required <BR/>';
                                    rowHasError = true;
                                    system.debug('4');
                                }
                                if (checkreason.Need_Attachments__c == true && numberOfAttachments == 0){
                                    cancellationError += 'Error: ' + bookingSelected.booking.Name + ': Need Attachments for Opp <a href="/' + 
                                                         bookingSelected.booking.Opportunity__c + '" target="_blank">' + bookingSelected.booking.Opportunity__r.Opportunity_Number__c +
                                                         '</a> to Proceed <BR/>';
                                    rowHasError = true;
                                    system.debug('5');
                                }
                            }
                    }
                    system.debug('bookingSelected.reasonData ' + bookingSelected.reasonData);
                }
                if (rowHasError == false){
                    tncPublicEventCancellationWrapper bookingwrap = bookingSelected;
                    bookingwrap.processCancellationFee();
                    selectedBookings.add(bookingSelected); 
                } else {
                    showError = true;
                }
            }
        }
        
        system.debug(cancellationError);
        if (selectedBookings.size() == 0 && cancellationError == ''){
            showError = true;
            cancellationError += 'Error: Select atleast one event OR correct errors.<BR/>';
            visibleSection(true, false);
        }  else if (selectedBookings.size() > 0 && cancellationError == ''){
            visibleSection(false, true);
        } else {
            visibleSection(true, false);
        }
        return null;
    }
    
    public PageReference cancel(){
        return new pagereference('/' + oppId);
    }    
    
    public PageReference processCancellation(){
        system.debug('Calling tncHelper.processPublicEventCancellation');
        tncHelper.processPublicEventCancellation(selectedBookings, oppId);
        system.debug('Finished tncHelper.processPublicEventCancellation');
        
        return new pagereference('/' + oppId);
    }

}