src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The subscription that needs to be altered.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities (Subscription)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Subscription</fullName>
        <active>true</active>
        <businessProcess>BSC Sales Process</businessProcess>
        <description>Opportunity for Membership and other Subscription Product Sales</description>
        <label>Subscription</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Duration_Years__c</fullName>
        <description>Used in workflow</description>
        <inlineHelpText>Duration of the subscription product in years (auto populates on save)</inlineHelpText>
        <label>Duration (Years)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in workflow</description>
        <inlineHelpText>Indicates if this product is a subscription product</inlineHelpText>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Duration_Years__c</fullName>
        <description>add the corresponding number of years depending on the duration field</description>
        <formula>IF (TEXT(Duration__c) = &quot;1 Year&quot;,1,
(IF (TEXT(Duration__c) = &quot;2 Years&quot;,2,
(IF (TEXT(Duration__c) = &quot;3 Years&quot;,3,
(IF (TEXT(Duration__c) = &quot;100 Years&quot;,100,
0)))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>add the corresponding number of years depending on the duration field</inlineHelpText>
        <label>Duration (Years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>E_Delivery_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Product is an E-Delivery Subscription Product (reflects on the Subscription and Renewal Opportunity)</description>
        <inlineHelpText>Indicates if the Product is an E-Delivery Subscription Product</inlineHelpText>
        <label>E-Delivery (Subscription)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Guides_Publication_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this products is a Guides Publication product this should be ticked. If you tick this field after the product has been used on a Subscription Line you MUST update all subscription lines using this product to refresh the data.</inlineHelpText>
        <label>Guides Publication Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HSWA_Publication_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this products is a HSWA Publication product this should be ticked. If you tick this field after the product has been used on a Subscription Line you MUST update all subscription lines using this product to refresh the data.</inlineHelpText>
        <label>HSWA Publication Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Info_Membership_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this products is a information membership product this should be ticked. If you tick this field after the product has been used on a Subscription Line you MUST update all subscription lines using this product to refresh the data.</inlineHelpText>
        <label>Info Membership Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates if the product is a Membership (affects Trader vs Member distinction on Account)</inlineHelpText>
        <label>Membership</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publication_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates this product is a publication subscription product</inlineHelpText>
        <label>Publication Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RCP_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Drives workflow that selects Subscription checkbox to govern renewal reminder emails</description>
        <inlineHelpText>Tick if this subscription product is an RCP Product</inlineHelpText>
        <label>RCP Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SUSA_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to populate subscription type on subscription and subscription line</description>
        <inlineHelpText>Tick this box if this product is a JOMC Engage SUSA product</inlineHelpText>
        <label>SUSA Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Safety_Management_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this products is a Safety Management product this should be ticked. If you tick this field after the product has been used on a Subscription Line you MUST update all subscription lines using this product to refresh the data.</inlineHelpText>
        <label>Safety Management Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to feed automatic generation of Subscriptions and Subscription Lines</description>
        <inlineHelpText>Should sales of this product generate Subscriptions and Subscription Lines?</inlineHelpText>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tools_Membership_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this products is a tools membership product this should be ticked.</inlineHelpText>
        <label>Tools Membership Product</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Subscription</fullName>
        <active>true</active>
        <description>Record type for Memberships and other Subscription Products</description>
        <label>Subscription</label>
    </recordTypes>
</CustomObject>

src/objects/Site_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product associated to this site product</description>
        <formula>Subscription_Line__r.Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Product associated to this site product</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Line__c</fullName>
        <description>Master Detail</description>
        <inlineHelpText>Subscription line associated with the site product</inlineHelpText>
        <label>Subscription Line</label>
        <referenceTo>Subscription_Line__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <description>Master detail</description>
        <inlineHelpText>Subscription associated with this site product</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site Product</label>
    <nameField>
        <displayFormat>SP-{0000000}</displayFormat>
        <label>Site Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to manage subscriptions (Memberships, Complywise Subscriptions and other ongoing product deliveries)</description>
    <fields>
        <fullName>Includes_E_Delivery_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates if this Subscription contains an E-Delivery Product</inlineHelpText>
        <label>Includes E-Delivery Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_Guides_Publication_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Includes Guides Publication Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_HSWA_Publication_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Includes HSWA Publication Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_Info_Membership_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If ticked this subscription includes an Info membership product.</inlineHelpText>
        <label>Includes Info Membership Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_Membership_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked automatically by Workflow on creation of Subscription Line</inlineHelpText>
        <label>Includes Membership Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_Publication_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Includes Publication Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_RCP_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked automatically by Workflow on save of Subscription Line</inlineHelpText>
        <label>Includes RCP Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_SUSA_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If ticked this subscription includes a SUSA subscription product.</inlineHelpText>
        <label>Includes SUSA Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_Safety_Management_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Includes Safety Management Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_Tools_Membership_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this is ticked the subscription includes a tools membership product.</inlineHelpText>
        <label>Includes Tools Membership Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Longest_Duration_Years__c</fullName>
        <label>Longest Duration Years</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Codes__c</fullName>
        <label>Product Codes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Line__c</fullName>
        <description>The total number of subscription lines on the subscription</description>
        <inlineHelpText>The total number of subscription lines on the subscription.</inlineHelpText>
        <label>Subscription Lines</label>
        <summaryForeignKey>Subscription_Line__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Sub Ref: Current Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Line__c.object
<CustomObject>
    <description>Object to manage products / elements of a subscription</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Subscription Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription_Site__c.object
<CustomObject>
    <description>Object to manage delivery of subscriptions to multiple sites</description>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Site</label>
    <nameField>
        <displayFormat>SS-{0000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubscriptionLineTriggerMethods.cls
public without sharing class SubscriptionLineTriggerMethods
{
	/* 
	 * UPDATE SUBSCRIPTION PRODUCT STATUS
	 * 
	 * Updates the subscription includes e-learning product, subscription product, publication and RCP Product
	 * fields on the subscription.
	 * 
	*/
	public static void updateSubscriptionProdStatus(List<Subscription_Line__c> subLineList){
		
		// Identify the subscriptions that need to be updated
		Map<ID,ID> subsToBeUpdated = new Map<ID,ID>();
		for(Subscription_Line__c subLine : subLineList){
			if(!subsToBeUpdated.containsKey(subLine.Subscription__c)){
				subsToBeUpdated.put(subLine.Subscription__c,subLine.Subscription__c);
			}
		}
		
		List<Subscription__c> subsToUpdate = new List<Subscription__c>();
		
		for(Subscription__c sub : [SELECT Includes_RCP_Product__c, 
											Includes_Membership_Product__c, 
											Includes_E_Delivery_Product__c,
											Includes_Publication_Product__c,
											(SELECT s.Product__r.Subscription_Product__c, 
															s.Product__r.RCP_Product__c,
															s.Product__r.Membership__c, 
															s.Product__r.E_Delivery_Subscription__c, 
															s.Product__r.Publication_Subscription__c,
															s.Product__r.Tools_Membership_Product__c,
															s.Product__r.Info_Membership_Product__c,
															s.Product__r.Guides_Publication_Product__c,
															s.Product__r.HSWA_Publication_Product__c,
															s.Product__r.Safety_Management_Product__c,
															s.Product__r.ProductCode,
															s.Product__r.Duration_Years__c,
															s.Product__r.SUSA_Product__c,
															Quantity__c
													 FROM Subscription_Lines__r s )
		 							FROM Subscription__c WHERE Id IN :subsToBeUpdated.values()]){

			System.debug('Current Sub: '+sub);
			sub.Includes_RCP_Product__c = false;
			sub.Includes_Membership_Product__c = false;
			sub.Includes_E_Delivery_Product__c = false;
			sub.Includes_Publication_Product__c = false;
			sub.Includes_Tools_Membership_Product__c = false;
			sub.Includes_Info_Membership_Product__c = false;
			sub.Includes_Guides_Publication_Product__c = false;
			sub.Includes_HSWA_Publication_Product__c = false;
			sub.Includes_Safety_Management_Product__c = false;
			sub.Includes_SUSA_Product__c = false;
			
			String StrProductCodes = '';
			Double longestDuration = 0;

			//List<SObject> subLines=sub.getSObjects('Subscription_Lines__c');
			for (Subscription_Line__c allSubLine : sub.Subscription_Lines__r)
			{
				if (allSubLine.Product__r.Tools_Membership_Product__c == true){
					System.debug(sub.Id+' has at least one Tools Membership Product');
					sub.Includes_Tools_Membership_Product__c = true;
				}
				if (allSubLine.Product__r.Info_Membership_Product__c == true){
					System.debug(sub.Id+' has at least one Info Membership Product');
					sub.Includes_Info_Membership_Product__c = true;
				}
				if (allSubLine.Product__r.RCP_Product__c == true){
					System.debug(sub.Id+' has at least one RCP Product');
					sub.Includes_RCP_Product__c = true;
				}
				if (allSubLine.Product__r.Membership__c == true){
					System.debug(sub.Id+' has at least one Membership Product');
					sub.Includes_Membership_Product__c = true;
				}
				if (allSubLine.Product__r.E_Delivery_Subscription__c == true){
					System.debug(sub.Id+' has at least one E Delivery Subscription');
					sub.Includes_E_Delivery_Product__c = true;
				}
				if (allSubLine.Product__r.Publication_Subscription__c == true){
					System.debug(sub.Id+' has at least one Publication Subscription');
					sub.Includes_Publication_Product__c = true;
				}

				if (allSubLine.Product__r.Guides_Publication_Product__c == true){
					System.debug(sub.Id+' has at least one Guides Publication Subscription');
					sub.Includes_Guides_Publication_Product__c = true;
				}
				if (allSubLine.Product__r.HSWA_Publication_Product__c == true){
					System.debug(sub.Id+' has at least one HSWA Publication Subscription');
					sub.Includes_HSWA_Publication_Product__c = true;
				}
				if (allSubLine.Product__r.Safety_Management_Product__c == true){
					System.debug(sub.Id+' has at least one Safety Management Publication Subscription');
					sub.Includes_Safety_Management_Product__c = true;
				}
				if (allSubLine.Product__r.SUSA_Product__c == true){
					System.debug(sub.Id+' has at least one SUSA Subscription');
					sub.Includes_SUSA_Product__c = true;
				}
				system.debug('Steve Code has set sub SUSA value'+sub.Includes_SUSA_Product__c);

                // Build product codes line
                if(allSubLine.Quantity__c > 0)
                {
                    if (StrProductCodes == ''){
                        StrProductCodes=allSubLine.Product__r.ProductCode;
                    }else{
                        StrProductCodes=StrProductCodes + ';' + allSubLine.Product__r.ProductCode;
                    }
                }
                // Work out longest product duration (used for renewals to work out the length of the renewal)
                if (allSubLine.Product__r.Duration_Years__c > longestDuration){
                	longestDuration = allSubLine.Product__r.Duration_Years__c;
                }
                
                
			}
			
			sub.Longest_Duration_Years__c = longestDuration;
			
			// Set the product codes value.
			sub.Product_Codes__c = StrProductCodes;
			subsToUpdate.add(sub);
		}
		update subsToUpdate;
	}
	
    public static void updateInvoiceStatus(Map<Id,Subscription_Line__c> subsLineMap)
    {
    
    	List<Id> subsToMarkPaid = new List<Id>();
    	
        for(c2g__codaInvoiceLineItem__c invoiceLineItem:[Select c2g__Invoice__c,
        														c2g__Invoice__r.Copy_Invoice_Status__c,
                                                                c2g__Invoice__r.c2g__InvoiceStatus__c,
                                                                SL__c,
                                                                SL__r.Subscription__c
                                                                from c2g__codaInvoiceLineItem__c
                                                                where SL__c IN:subsLineMap.keySet()
                                                                ])
       {
                                                                                                               
            if(subsLineMap.containsKey(invoiceLineItem.SL__c))
            {
                Subscription_Line__c subsLine = subsLineMap.get(invoiceLineItem.SL__c);
                if(invoiceLineItem.c2g__Invoice__r.c2g__InvoiceStatus__c == 'Discarded')
                {    
                    subsLine.Invoice_Status__c = 'Not-Invoiced'; 
                }
                else{
                
                    subsLine.Invoice_Status__c = invoiceLineItem.c2g__Invoice__r.Copy_Invoice_Status__c;
                    if(subsLine.Invoice_Status__c == 'Paid')
                    {
                    	System.debug('Sub Line has invoice paid'+invoiceLineItem.SL__c);
                         subsLine.Invoice_Paid_Date__c = Date.today();
                         subsToMarkPaid.add(invoiceLineItem.SL__r.Subscription__c);
                    }
                }
            }    
        }
        
    }
    
    
    public testmethod static void testUpdateSubscriptionProductType()
    {
    	
		//Set variables
		Pricebook2 stdPricebook = [Select Id From Pricebook2 Where IsStandard = true Limit 1];
		//Create Data
    	
		//Create Pricebook
		Pricebook2 pb = new Pricebook2();
		pb.Name = 'TestPb';
		pb.IsActive = True;
		insert pb;
		System.debug('Steve pbId'+' '+pb.Id);
    	
		//Create product Positive test
		Product2 proPos = new Product2();
		proPos.Name = 'TestProd';
		proPos.RecordType = [Select Id from RecordType where sObjectType = 'Product2' and Name = 'Subscription' LIMIT 1][0];
		proPos.IsActive = True;
		proPos.Subscription_Product__c = True;
		proPos.SUSA_Product__c = True;
		insert proPos;
		System.debug('Steve is produt positive SUSA'+' '+proPos.SUSA_Product__c);
		
		//Create product Negative test
		Product2 proNeg = new Product2();
		proNeg.Name = 'TestProd';
		proNeg.RecordType = [Select Id from RecordType where sObjectType = 'Product2' and Name = 'Subscription' LIMIT 1][0];
		proNeg.IsActive = True;
		proNeg.Subscription_Product__c = False;
		proNeg.SUSA_Product__c = False;
		insert proNeg;
		System.debug('Steve is product Neg SUSA'+' '+proNeg.SUSA_Product__c);
    	
		//Create Pricebook entry
		PricebookEntry pbe = new PricebookEntry();
		pbe.IsActive = True;
		pbe.Pricebook2Id = stdPricebook.Id;
		pbe.Product2Id = proPos.Id;
		pbe.UnitPrice = 100;
		insert pbe;
		System.debug('Steve priceBookId'+' '+pbe.Id);

		//Create Account
		Account acc = new Account();
		acc.Name = 'TestCo';
		acc.CurrencyIsoCode = 'GBP';
		acc.Active__c = True;
		insert acc;
		System.debug('Steve acc Name'+' '+acc.Name);
		
		//Create conatct
		Contact contact = new Contact();
		contact.AccountId = acc.Id;
		contact.LastName = 'Contact';
		contact.FirstName = 'Test';
		insert contact;
        System.debug('Steve ContactId'+' '+contact.Id);
        
		//Create Opportunity
		Opportunity opp = New Opportunity();
		opp.Name = 'Test Opp';
		RecordType rType = [Select Id From RecordType where sObjectType = 'Opportunity' and name = 'Subscription' and isactive=true LIMIT 1][0];
		opp.RecordTypeId = rType.Id;
		opp.AccountId = acc.id;
		opp.Subscription_Start_Date__c = Date.today();
		opp.CloseDate = Date.today();
		opp.StageName = 'Qualifying';
		insert Opp;
        System.debug('Steve Opp Stage on creation'+' '+Opp.StageName);
        
        //Create Contact Role
		OpportunityContactRole oppContRole = new OpportunityContactRole();
		oppContRole.OpportunityId = opp.Id;
		oppContRole.ContactId = contact.Id;
		oppContRole.IsPrimary = True;
		oppContRole.Role = 'Sales Contact';
		insert oppContRole;
		System.debug('Steve contact role Id'+' '+oppContRole.Id);
        
        //Create Opp Line item
		OpportunityLineItem oppLine = new OpportunityLineItem();
		oppLine.OpportunityId = opp.Id;
		oppLine.PricebookEntryId = pbe.Id;
		oppLine.Quantity = 1;
		oppLine.TotalPrice = 100;
		insert oppLine;
		System.debug('Steve Opp Line Id'+' '+oppLine.Id);
        
        //Update Opp stagename after product has been added to deal with validation rule
		//Opp.StageName = 'Booking Received';
		//update Opp;
		//system.debug('Steve Opp Stage after update'+Opp.StageName);
        
        
        //Create subcription
		Subscription__c sub = new Subscription__c();     
		sub.Account_Name__c = Acc.Id;
		sub.Contact__c = contact.Id;
		sub.Opportunity__c = opp.Id;
		sub.Start_Date__c = Date.today();
		sub.Status__c = 'Current';
		sub.Type__c = 'New';
		insert sub;
        System.debug('Steve Sub Includes SUSA? on creation'+' '+sub.Includes_SUSA_Product__c);
        system.debug('Steve SubID ' +sub.Id);
        
        //Create Subscription Line
		Subscription_Line__c subLn= new Subscription_Line__C();
		subLn.Subscription__c = sub.Id;
		subLn.Product__c = proPos.Id;
		System.debug('Steve1111'+' '+subLn.Id);
		insert subLn;
		System.debug('Steve'+' '+subLn.Id);
		System.debug('Steve Sub Includes SUSA? on creation of Sub Line'+[Select Includes_SUSA_Product__c from subscription__c where Id = :Sub.Id]);
        
        //Create Subscription Site
		Subscription_Site__C subSite = new Subscription_Site__C();
		subSite.Subscription__c = sub.Id;
		subSite.Site_Start_Date__c = sub.Start_Date__c;
		subSite.Active__c = True;
		subSite.Type__c = 'Single Site';
		subSite.Site_Account__c = acc.Id;
		subSite.Site_Contact__c = contact.Id;
		insert subSite;
		System.debug('Steve subSiteId'+' '+subSite.Id);
        
        //Create Subscription site product
		Site_Product__c siteProd = new Site_Product__c();
		siteProd.Subscription__c = sub.Id;
        siteProd.Subscription_Line__c = subLn.Id;
        siteProd.Subscription_Site__c = subSite.Id;
        siteProd.Site_Product_Contact__c = contact.Id;
        insert siteProd;
		System.debug('Steve SiteProdId'+' '+siteProd.Id); 
		
		//Create subcription
		Subscription__c subNeg = new Subscription__c();     
		subNeg.Account_Name__c = Acc.Id;
		subNeg.Contact__c = contact.Id;
		subNeg.Opportunity__c = opp.Id;
		subNeg.Start_Date__c = Date.today();
		subNeg.Status__c = 'Current';
		subNeg.Type__c = 'New';
		insert subNeg;
        System.debug('Steve Sub Includes SUSA? on creation'+' '+subNeg.Includes_SUSA_Product__c);
        system.debug('Steve SubID ' +subNeg.Id);
        
        //Create Subscription Line
		Subscription_Line__c subLnNeg= new Subscription_Line__C();
		subLnNeg.Subscription__c = subNeg.Id;
		subLnNeg.Product__c = proNeg.Id;
		System.debug('Steve1111'+' '+subLnNeg.Id);
		insert subLnNeg;
		System.debug('Steve'+' '+subLnNeg.Id);
		System.debug('Steve Sub Includes SUSA? on creation of Sub Line'+[Select Includes_SUSA_Product__c from subscription__c where Id = :SubNeg.Id]);
        
        //Create Subscription Site
		Subscription_Site__C subSiteNeg = new Subscription_Site__C();
		subSiteNeg.Subscription__c = subNeg.Id;
		subSiteNeg.Site_Start_Date__c = sub.Start_Date__c;
		subSiteNeg.Active__c = True;
		subSiteNeg.Type__c = 'Single Site';
		subSiteNeg.Site_Account__c = acc.Id;
		subSiteNeg.Site_Contact__c = contact.Id;
		insert subSiteNeg;
		System.debug('Steve subSiteId'+' '+subSiteNeg.Id);
        
        //Create Subscription site product
		Site_Product__c siteProdNeg = new Site_Product__c();
		siteProdNeg.Subscription__c = subNeg.Id;
        siteProdNeg.Subscription_Line__c = subLnNeg.Id;
        siteProdNeg.Subscription_Site__c = subSiteNeg.Id;
        siteProdNeg.Site_Product_Contact__c = contact.Id;
        insert siteProdNeg;
		System.debug('Steve SiteProdId'+' '+siteProd.Id); 
		
		Test.StartTest();
		//Positive test - product flag - true
		//Subscription__c Output;
		//Output = [Select Includes_SUSA_Product__c from subscription__c where Id = :Sub.Id LIMIT 1][0].Includes_SUSA_Product__c;
		Boolean returnflagPos = [Select Includes_SUSA_Product__c from subscription__c where Id = :Sub.Id LIMIT 1][0].Includes_SUSA_Product__c;
		System.assert(returnflagPos == True,'Inc SUSA flag update has failed FAIL');
		
		//Negative test - product flag - false 
		Boolean returnFlagNeg = [Select Includes_SUSA_Product__c from subscription__c where Id = :SubNeg.Id LIMIT 1][0].Includes_SUSA_Product__c;
		System.assert(returnFlagNeg == False,'Inc SUSA flag update has failed FAIL');
		
		Test.StopTest();
        
    	/*
    		CREATE TEST DATA
    		================
    		Create an account
    		Create a contact
    		Create a opp
    		Create prods (one with Product2.SUSA_Product__c == true, one Product2.SUSA_Product__c == false)
    		Create Opp lines
    		Create sub
    		create sub lines
    		c sub prod
    		c sub sites
    		join sub opps
    		
    		1. Prod.Product__r.SUSA_Product__c == true & Sub = INCLUDES_SUSA_Product__c == true EXPECTED: sub.INCLUDES_SUSA_Product__c == true
    		2. Prod.Product__r.SUSA_Product__c == false & Sub = INCLUDES_SUSA_Product__c == true EXPECTED: sub.INCLUDES_SUSA_Product__c == false
    		3. Prod.Product__r.SUSA_Product__c == true (multiple false with one true) & Sub = INCLUDES_SUSA_Product__c == true EXPECTED: sub.INCLUDES_SUSA_Product__c == true
    		4. Prod.Product__r.SUSA_Product__c == false (multiple true with one false) & Sub = INCLUDES_SUSA_Product__c == true EXPECTED: sub.INCLUDES_SUSA_Product__c == false
    		5. Bulk tests (clone subs and opps etc for XXX records and put in list);
    		
    		
    		
    		START TEST
    		==========
    		Test.StartTest();
    		
    		
    		CHECK RESULTS:
    		==============
    		System.assert(sub.INCLUDES_SUSA_Product__c == true, 'The sub isnt updating the XXX field for whatever test');
    		
    		Test.StopTest();
    		
    	
    	*/
    	
    	
	  /*
	  Subscription_Line__c subsLine = [Select Id from Subscription_Line__c limit 1];
	  c2g__codaInvoiceLineItem__c invoiceLineItem = [Select Id,SL__c,c2g__Invoice__c from c2g__codaInvoiceLineItem__c where c2g__Invoice__c='a1ZD0000000TTYV' limit 1];
	  c2g__codaInvoice__c invoice = [Select c.Id, c.Copy_Invoice_Status__c From c2g__codaInvoice__c c where Id=:invoiceLineItem.c2g__Invoice__c limit 1];
	  invoice.Copy_Invoice_Status__c = 'Paid';
	  update invoice;
	  Map<Id,Subscription_Line__c> subsLineMap= new Map<Id,Subscription_Line__c>();
	  subsLineMap.put(subsLine.Id,subsLine);
	  invoiceLineItem.SL__c = subsLine.Id;
	  update invoiceLineItem;
	  SubscriptionLineTriggerMethods.updateInvoiceStatus(subsLineMap);
	  */
    }
}