src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Service_notes__c</fullName>
        <label>Customer Service notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Decision_Making_Process__c</fullName>
        <label>Decision Making Process</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If populated, this field indicates an original public events opportunity which has been partially closed</description>
        <inlineHelpText>If populated, this field indicates an original public events opportunity which has been partially closed</inlineHelpText>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subsequent Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Notes__c</fullName>
        <inlineHelpText>Sales notes to Sales manager for details of pricing</inlineHelpText>
        <label>Pricing Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, this box indicates that the opportunity has been created automatically as a subscription is up for renewal</description>
        <inlineHelpText>If ticked, this box indicates that the opportunity has been created automatically as a subscription is up for renewal</inlineHelpText>
        <label>Renewal Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rollover_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, this box indicates an opportunity has been created from partial closure of a public events opportunity</description>
        <inlineHelpText>If ticked, this box indicates an opportunity has been created from partial closure of a public events opportunity</inlineHelpText>
        <label>Rollover Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>Object to manage tenders and bespoke projects</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Viability Review</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Proposal Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQQ Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Proposal Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQQ Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation of Initial Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Proposal Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bid Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Proposal Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bid Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiaion of Final Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Further Requirements Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Further Requirements Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualifying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Positioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiating Terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot/Taster Session Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn by BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn by Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transferred_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populates automatically with the originating Event when an In-Company Event / Audit is transferred</description>
        <inlineHelpText>Populates automatically with the originating Event when an In-Company Event / Audit is transferred</inlineHelpText>
        <label>Transferred From</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>Originating Events</relationshipLabel>
        <relationshipName>BSC_Events1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transferred_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>At the moment Sales to Manually populate with the new event ref if an In-Company event is being transferred</description>
        <inlineHelpText>Populate when Transferring In-Company Events and Audits</inlineHelpText>
        <label>Transferred To</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Date__c</fullName>
        <description>The date on which the booking is transferred or cancelled</description>
        <inlineHelpText>The date on which the booking is transferred or cancelled</inlineHelpText>
        <label>Transfer / Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transferred_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be populated with the previous field if a booking is transferred</description>
        <inlineHelpText>This field will be populated with the previous field if a booking is transferred</inlineHelpText>
        <label>Transferred From</label>
        <referenceTo>Special_Event_Booking__c</referenceTo>
        <relationshipLabel>Previous Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transferred_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field indicates the subsequent booking if a booking is transferred</description>
        <inlineHelpText>This field indicates the subsequent booking if a booking is transferred</inlineHelpText>
        <label>Transferred to: Booking</label>
        <referenceTo>Special_Event_Booking__c</referenceTo>
        <relationshipLabel>Subsequent Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OpportunitySplitController.cls
/*
  Created by Deepak Gupta 19 July 2010
  
  Description:
  Todo:
    * Test Methods 
*/
public with sharing class OpportunitySplitController{
private Opportunity record;
  public OpportunitySplitController(ApexPages.StandardController controller)
  {
    record = getOpportunity(controller.getId());
  }
  private Opportunity getOpportunity(Id id)
  {
    List<Opportunity> OpportunityQuery = [Select  Pricing_Notes__c, Decision_Making_Process__c, Customer_Service_notes__c,IsClosed,RecordTypeId,AccountId,CampaignId,Project__c,Renewal_Opportunity__c, OwnerId, Name, Description, Amount,CloseDate From Opportunity where Id = :id];
    if (OpportunityQuery.size() == 1) return OpportunityQuery.get(0);
    return null;   
  } 
 public PageReference doAction()
  {
    //if (record != null)
    //{
        Savepoint SP = Database.setSavepoint(); 
        Id OppId=record.Id;
        //original opportunity is cloned 
        Opportunity NewOpp =  record.clone(false);  
        NewOpp.Name=record.Name+'-R'; 
        NewOpp.Rollover_Opportunity__c=true;
        NewOpp.StageName='Qualifying'; 
        NewOpp.Original_Opportunity__c=record.Id; 
        insert NewOpp;   
        TRY 
        {
            
            List<OpportunityContactRole> copyContactRole = new List<OpportunityContactRole>(); 
            for(OpportunityContactRole contactRole:[Select o.Role, o.OpportunityId, o.IsPrimary, o.ContactId From OpportunityContactRole o where o.OpportunityId=:OppId ])
            {
               OpportunityContactRole newContactRole = new OpportunityContactRole(OpportunityId = NewOpp.Id,
                                                                                  ContactId = contactRole.ContactId,
                                                                                  IsPrimary = contactRole.IsPrimary,
                                                                                  Role = contactRole.Role);
               copyContactRole.add(newContactRole);
            }
            if(!copyContactRole.isEmpty())
                insert copyContactRole;
                
            // Clone BSC Event bookings except where status is equal to Provisional
            List<Special_Event_Booking__c> OppNewEventBookings =new List<Special_Event_Booking__c>();
            List<Special_Event_Booking__c> OppOrigEventBookings =[Select Special_Event__r.Product__c, Transferred_To__c, Transferred_From__c, Transfer_Cancellation_Date__c, Status__c, Special_Event__c, PK_CB_ELEM_ID__c,  Name, Fee_Date__c, FK_CB_COURSE_ID__c, FK_CB_BOOK_ID__c, Event_end_Date__c, Event_Start_Date__c, Contact__c, ConnectionSentId, ConnectionReceivedId, Company__c, Booking_Fee__c From Special_Event_Booking__c  where Status__c='Provisional' and  Opportunity__c= :(string) (OppId)];
            //List<Special_Event_Booking__c> OppOrigConfirmedEventBookings =[Select Special_Event__r.Product__c, Transferred_To__c, Transferred_From__c, Transfer_Cancellation_Date__c, Status__c, Special_Event__c, PK_CB_ELEM_ID__c,  Name, Fee_Date__c, FK_CB_COURSE_ID__c, FK_CB_BOOK_ID__c, Event_end_Date__c, Event_Start_Date__c, Contact__c, ConnectionSentId, ConnectionReceivedId, Company__c, Booking_Fee__c From Special_Event_Booking__c  where Status__c='Confirmed' and  Opportunity__c= :(string) (OppId)];
            //Map<Id, Id> m = new Map<Id, Id>(); // Define a new map
            Map<String, decimal> n = new Map<String, decimal>(); // Define a new map
                string PcodePrice;
                Decimal CurrentValue;   
                Decimal CurrentValue1;          
                if (OppOrigEventBookings.size()>0)
                {  
                  for (Special_Event_Booking__c OppEventBooking:OppOrigEventBookings )          
                    {
                        Special_Event_Booking__c NewEventBooking=OppEventBooking.clone(false);
                        NewEventBooking.Opportunity__c=NewOpp.Id;
                        OppNewEventBookings.add(NewEventBooking);
                    } 
                    
                    if (OppNewEventBookings.size()>0)
                    {
                        insert OppNewEventBookings; 
                    }                                       
                    //BSC Event Bookings where the status is equal to “Provisional” are deleted from the old opportunity
                    if (OppOrigEventBookings.size()>0)
                    {
                        Delete  OppOrigEventBookings;
                    }        
                }

            for (Special_Event_Booking__c ConfirmedBooking :[Select Special_Event__r.Product__c, Transferred_To__c, Transferred_From__c, Transfer_Cancellation_Date__c, Status__c, Special_Event__c, PK_CB_ELEM_ID__c,  Name, Fee_Date__c, FK_CB_COURSE_ID__c, FK_CB_BOOK_ID__c, Event_end_Date__c, Event_Start_Date__c, Contact__c, ConnectionSentId, ConnectionReceivedId, Company__c, Booking_Fee__c From Special_Event_Booking__c  where Status__c='Confirmed' and  Opportunity__c= :(string) (OppId)])
            {
                PcodePrice=(string) ConfirmedBooking.Special_Event__r.Product__c + ConfirmedBooking.Booking_Fee__c.toPlainString();
                if (!n.containsKey(PcodePrice))
                {
                    n.put(PcodePrice, 1.00);
                }               
                else
                {
                    CurrentValue=n.get(PcodePrice);
                    CurrentValue1=n.Remove(PcodePrice);
                    n.put(PcodePrice,(CurrentValue + 1.00) );
                }           
            }   
            //List<OpportunityLineItem> OppLineItemsOrig =[Select PricebookEntry.product2Id,UnitPrice, T_C_Price__c, ListPrice,Quantity,PricebookEntryId  From OpportunityLineItem  where OpportunityId= :OppId];
            
            List<OpportunityLineItem> OppNewLineItems     =new List<OpportunityLineItem>();
            List<OpportunityLineItem> OppLineItems2Delete =new List<OpportunityLineItem>();
            List<OpportunityLineItem> OppLineItems2Update =new List<OpportunityLineItem>();
            for (OpportunityLineItem OppLineItemOrig :[Select PricebookEntry.product2Id,UnitPrice, T_C_Price__c, ListPrice,Quantity,PricebookEntryId  From OpportunityLineItem  where OpportunityId= :OppId])
            {
                PcodePrice=(string) OppLineItemOrig.PricebookEntry.product2Id + OppLineItemOrig.UnitPrice.toPlainString();
                if (!n.containsKey(PcodePrice))
                {
                    //Add to New Opp, a new Opp Lineitem with number as Original
                     OpportunityLineItem NewLineItem=OppLineItemOrig.clone(false);
                     NewLineItem.OpportunityId=  NewOpp.id;
                     OppNewLineItems.add(NewLineItem);                  
                    // Delete Opp LineItem from Original Opp
                    OppLineItems2Delete.add(OppLineItemOrig);
                }               
                else
                {
                    //Add to New Opp, a new Opp Lineitem with number as (Original-in Map) if that is > 0
                    if ((OppLineItemOrig.Quantity -n.get(PcodePrice))>0.0)
                    {
                     OpportunityLineItem NewLineItem=OppLineItemOrig.clone(false);
                     NewLineItem.OpportunityId=  NewOpp.id;
                     NewLineItem.Quantity=OppLineItemOrig.Quantity -n.get(PcodePrice);
                     OppNewLineItems.add(NewLineItem);                                      
                    }
                    //Update Original OppLineItem with Number as in Map                 
                    OppLineItemOrig.Quantity=n.get(PcodePrice);
                    OppLineItems2Update.add(OppLineItemOrig);                                       
                }                           
            }   
                if  (OppNewLineItems.size()>0)
                {
                    insert OppNewLineItems;
                }

                if  (OppLineItems2Delete.size()>0)
                {
                    Delete OppLineItems2Delete;
                }

                if  (OppLineItems2Update.size()>0)
                {
                    Update OppLineItems2Update ;    
                }
                                                  
                        

        }
        CATCH (Exception e)
            {
                // roll back everything
                Database.rollback(SP);
                Apexpages.addMessages(e);
                return null;
            }       
        return new Pagereference('/'+ NewOpp.Id);
  }  
}