src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Date_to_be_Invoiced__c</fullName>
        <inlineHelpText>The data on which this opportunity should be invoiced.</inlineHelpText>
        <label>Date to be Invoiced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Copied from Lead - Start date of the event the user wishes to book</description>
        <inlineHelpText>Copied from Lead - Start date of the event the user wishes to book</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <description>Requested by Sales, see case: 00002457</description>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If populated, this field indicates an original public events opportunity which has been partially closed</description>
        <inlineHelpText>If populated, this field indicates an original public events opportunity which has been partially closed</inlineHelpText>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subsequent Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rollover_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, this box indicates an opportunity has been created from partial closure of a public events opportunity</description>
        <inlineHelpText>If ticked, this box indicates an opportunity has been created from partial closure of a public events opportunity</inlineHelpText>
        <label>Rollover Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>c2g__CODAUnitOfWork__c</fullName>
        <label>Unit of Work</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <label>Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>T_C_Price_Variation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>T/C Price Variation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>T_C_Price__c</fullName>
        <description>Field automatically populated by Transfer / Cancellation trigger - used to track differences to require approval</description>
        <label>T/C Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>c2g__CODAUnitOfWork__c</fullName>
        <label>Unit of Work</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Charge_Day_1__c</fullName>
        <defaultValue>99</defaultValue>
        <description>Minimum number of days at which Fee 1 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 1 will be charged</inlineHelpText>
        <label>Cancellation Charge Day 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Day_2__c</fullName>
        <defaultValue>60</defaultValue>
        <description>Minimum number of days at which Fee 2 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 2 will be charged</inlineHelpText>
        <label>Cancellation Charge Day 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Day_3__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Minimum number of days at which Fee 3 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 3 will be charged</inlineHelpText>
        <label>Cancellation Charge Day 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_1__c</fullName>
        <defaultValue>0.3</defaultValue>
        <description>Percentage for calculating Cancellation fee (lowest rate)</description>
        <inlineHelpText>Lowest percentage for calculating cancellation fee - will apply if cancellation takes place before Days 1</inlineHelpText>
        <label>Cancellation Charge Fee 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_2__c</fullName>
        <defaultValue>0.3</defaultValue>
        <description>Percentage for calculating cancellation fee</description>
        <inlineHelpText>Percentage for calculating cancellation fee - will apply if cancellation takes place after Days 1 and before Days 2</inlineHelpText>
        <label>Cancellation Charge Fee 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_3__c</fullName>
        <defaultValue>0.3</defaultValue>
        <description>Percentage for calculating cancellation fee</description>
        <inlineHelpText>Percentage for calculating cancellation fee - will apply if cancellation takes place after Days 2 and before Days 3</inlineHelpText>
        <label>Cancellation Charge Fee 3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_Final__c</fullName>
        <defaultValue>1.0</defaultValue>
        <description>Percentage for calculating cancellation fee</description>
        <inlineHelpText>Percentage for calculating cancellation fee - will apply if cancellation takes place after Days 3</inlineHelpText>
        <label>Cancellation Charge Fee Final</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>c2g__CODAUnitOfWork__c</fullName>
        <label>Unit of Work</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Booking_Fee__c</fullName>
        <description>This is pulled from the opportunity product unit price for public an total price on the in-company primary for in-company</description>
        <inlineHelpText>The amount that should be charged for this booking. This is automatically updated, change this by updating the opportunity line.</inlineHelpText>
        <label>Booking Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Pulls in the related event&apos;s start date</description>
        <formula>Special_Event__r.StartDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related event&apos;s start date</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Date__c</fullName>
        <description>The date on which the booking is transferred or cancelled</description>
        <inlineHelpText>The date on which the booking is transferred or cancelled</inlineHelpText>
        <label>Transfer / Cancellation Date</label>
        <type>Date</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PublicBookingCancellationController.cls
/*
	Code Coverage - 94%	-	07-10-2010
	Created by Ben Mansfield 16 July 2010
	Modified by Ben Mansfield 4 August 2010
	
	Description:
	
	Changes:
		
		4 August 2010:
		* Event booking modified to link to new opportunity (previously linked to old opportunity)
		* Cloned Line Item with negative amount now has a description set to 'Cancellation'
		
		7 October 2010:
		*AB
		
	
*/
public with sharing class PublicBookingCancellationController
{
	private static final String ERROR_NO_ORIG_PRODUCT = 'Cannot find original Product for this booking.';
	
	private Special_Event_Booking__c record;
	private Id priceBookId;
	
	public PublicBookingCancellationController(ApexPages.StandardController controller)
	{
		record = getBooking(controller.getId());
		priceBookId = [
			SELECT
				priceBook2Id
			FROM
				Opportunity
			WHERE
				Id=:record.Opportunity__c].priceBook2Id;
	}
	
	private Special_Event_Booking__c getBooking(Id id)
	{
		List<Special_Event_Booking__c> bookingQuery = [
			SELECT
				Id,
				Status__c,
				Name,
				Special_Event__r.Product__c,
				Special_Event__r.Product__r.Name,
				Event_Start_Date__c,
				Booking_Fee__c,
				// Opportunity fields
				Opportunity__c,
				Opportunity__r.AccountId,
				Opportunity__r.OwnerId,
				Opportunity__r.Name
			from
				Special_Event_Booking__c
			WHERE
				Id = :id];
		
		if (bookingQuery.size() == 1)
			return bookingQuery.get(0);
		
		return null;
	}
	
	public PageReference doAction()
	{
		if (record != null)
		{
			List<RecordType> recordTypes = [
				SELECT
					Id
				FROM
					RecordType
				WHERE
					SObjectType = 'Opportunity'
				AND
					Name = 'Public Event'];
			
			Opportunity newOpp = new Opportunity(
				AccountId = record.Opportunity__r.AccountId,
				OwnerId = record.Opportunity__r.OwnerId,
				// rjd - 3 August 2010 - using pricebook from opportunity
				Pricebook2Id = PricebookId,
				Name = record.Opportunity__r.Name + ' (' + record.Name + ') - Cancellation Fee',
				RecordTypeId = (recordTypes.isEmpty() ? null : recordTypes.get(0).Id),
				Type = 'Public Course',
				CloseDate = System.today(),
				Expected_Delivery_Date__c = System.today(),
				Date_to_be_Invoiced__c = System.today(),
				StageName = 'Quote/Negotiation',
				Rollover_Opportunity__c = true,
				Original_Opportunity__c = record.Opportunity__c);
			insert newOpp;
			
	        // START: Add old contact roles to new opportunity
	        List<OpportunityContactRole> oppConts = new List<OpportunityContactRole>([SELECT ContactId, 
	        																				isPrimary,
	        																				Role
	        																				FROM
	        																					OpportunityContactRole
	        																				WHERE
	            																				isDeleted = False
		        																				AND OpportunityId = :record.Opportunity__c]);
	        List<OpportunityContactRole> newOppConts = new List<OpportunityContactRole>();
	        
	        for(OpportunityContactRole oppCont : oppConts){
	        	OpportunityContactRole newOCR = new OpportunityContactRole(
	        		ContactId = oppCont.ContactId,
	        		OpportunityId = newOpp.Id,
		        	isPrimary = oppCont.isPrimary,
		        	Role = oppCont.Role);
	        	newOppConts.add(newOCR);
	        }
	        if (newOppConts.size() > 0){
	            insert newoppConts;
	        }
	        // END: Add old contact roles to new opportunity

			Map<String, PricebookEntry> entries = BookingHelper.getPricebookEntries(newOpp.Pricebook2Id,
				new String[] { 'Cancellation Fees (Public)', 'Reconciliation (Public)', record.Special_Event__r.Product__r.Name });
			
			List<OpportunityLineItem> olisToInsert = new List<OpportunityLineItem>();
			
			OpportunityLineItem oli = null;
			// Calculate cancellation fee
			if (entries.containsKey('Cancellation Fees (Public)'))
			{
				oli = new OpportunityLineItem(
					PricebookEntryId = entries.get('Cancellation Fees (Public)').Id,
					OpportunityId = newOpp.Id,
					Quantity = 1,
					UnitPrice = 0,
					T_C_Price__c = 0);
				
				if (record.Status__c != 'Cancelled' && record.Status__c != 'To be cancelled')
				{
					// Get currently booked product
					List<Product2> products = [
						SELECT
							Id,
							Cancellation_Charge_Day_1__c,
							Cancellation_Charge_Day_2__c, 
							Cancellation_Charge_Day_3__c,
							Cancellation_Charge_Fee_1__c,
							Cancellation_Charge_Fee_2__c,
							Cancellation_Charge_Fee_3__c, 
							Cancellation_Charge_Fee_Final__c
						FROM
							Product2 
						WHERE
							Id = :record.Special_Event__r.Product__c];
					if (products.size() != 1)
					{
						ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, ERROR_NO_ORIG_PRODUCT));
						return null;
					}
					
					oli.UnitPrice = oli.T_C_Price__c = record.Booking_Fee__c = BookingHelper.calculateCancellationCost(record, products[0]);
				}
				olisToInsert.add(oli);
				
				// Status set to cancelled
				record.Status__c = 'Cancelled';
				record.Transfer_Cancellation_Date__c = System.today();
				update record;
				
				// Clone original opportunity line item and calculate quantity of 1
				List<OpportunityLineItem> originalLineItems = [
					SELECT
						c2g__CODAUnitOfWork__c,
						UnitPrice,
						TotalPrice,
						T_C_Price__c,
						T_C_Price_Variation__c, 
						SystemModstamp,
						Subscription_Start_Date__c, 
						Subscription_Product__c,
						SortOrder,
						ServiceDate,
						Sales_Manager_Price__c,
						SM_Price_Needed__c,
						Quantity, 
						Pricing_Exception__c,
						PricebookEntryId,
						OpportunityId, 
						ListPrice,
						LastModifiedDate,
						LastModifiedById,
						IsDeleted, 
						Id,
						IC_Price_Difference__c,
						HasSchedule,
						HasRevenueSchedule, 
						HasQuantitySchedule,
						Duration_Years__c,
						Discounted__c, 
						Description,
						CurrencyIsoCode,
						CreatedDate,
						CreatedById, 
						ConnectionSentId,
						ConnectionReceivedId 
					FROM
						OpportunityLineItem
					WHERE 
						OpportunityId = :record.Opportunity__c
					AND
						PricebookEntry.Product2Id = :record.Special_Event__r.Product__c];
												
				if (originalLineItems.size() > 0)
				{
					OpportunityLineItem clonedOli = originalLineItems.get(0).clone(false, true);
					// Set clone to quantity of 1 since we only remove 1 booking
					clonedOli.Quantity = 1;
					clonedOli.TotalPrice = null;
					clonedOli.UnitPrice = -clonedOli.UnitPrice;
					// brm - 4 August 2010 - Added tag as cancellation in description
					clonedOli.Description = 'Cancellation';
					clonedOli.Pricing_Exception__c = true;
					
					olisToInsert.add(clonedOli);
					
					if (entries.containsKey('Reconciliation (Public)'))
					{
						OpportunityLineItem reconOrigOli = new OpportunityLineItem(
							PricebookEntryId = entries.get('Reconciliation (Public)').Id,
							OpportunityId = originalLineItems.get(0).OpportunityId,
							Quantity = 1,
							UnitPrice = originalLineItems.get(0).UnitPrice);						
						olisToInsert.add(reconOrigOli);
						
						OpportunityLineItem reconNewOli = new OpportunityLineItem(
							PricebookEntryId = entries.get('Reconciliation (Public)').Id,
							OpportunityId = newOpp.Id,
							Quantity = 1,
							UnitPrice = -originalLineItems.get(0).UnitPrice,
							Pricing_Exception__c = true);
						
						olisToInsert.add(reconNewOli);
					}
				}
			}
			insert olisToInsert;
			
			// brm - 4 August 2010 - Change event booking to link to new opportunity
			record.Opportunity__c = newOpp.Id;
			update record;
		}
		
		return new PageReference('/' + record.Id);
	}
	
	private static string RandomString{
		get{
			return string.valueof(math.random()).substring(1,10);
		}
	}
	
	@IsTest
	private static void test()
	{
		Product2 prod = new Product2(
			Name = 'Product Test' + RandomString,
			Cancellation_Charge_Day_1__c = 32,
			Cancellation_Charge_Day_2__c = 16,
			Cancellation_Charge_Day_3__c = 4,
			Cancellation_Charge_Fee_1__c = 10,
			Cancellation_Charge_Fee_2__c = 20,
			Cancellation_Charge_Fee_3__c = 50,
			Cancellation_Charge_Fee_Final__c = 100);
		insert prod;
		
		Pricebook2 stdPricebook = [
			SELECT
				Id
			FROM
				Pricebook2
			WHERE
				IsStandard = true
			LIMIT
				1];
		
		PricebookEntry pbe = new PricebookEntry(
			Pricebook2Id = stdPricebook.Id,
			Product2Id = prod.Id,
			UnitPrice = 360,
			IsActive = true);
		insert pbe;
		
		Opportunity opp = new Opportunity(
			Name = 'Public Event Test'+ RandomString,
			StageName = 'Qualifying',
			CloseDate = System.today());
		insert opp;
		
		OpportunityLineItem oli = new OpportunityLineItem(
			OpportunityId = opp.Id,
			PricebookEntryId = pbe.Id,
			UnitPrice = 360,
			Quantity = 1);
		insert oli;
		
		Special_Event__c event = new Special_Event__c(
			StartDate__c = System.today() + 5,
			Product__c = prod.Id,
			Opportunity__c = opp.Id);
		insert event;
		
		Special_Event_Booking__c booking = new Special_Event_Booking__c(
			Booking_Fee__c = 200,
			Special_Event__c = event.Id,
			Opportunity__c = opp.Id);
		insert booking;
		
		ApexPages.StandardController stdController = new ApexPages.StandardController(booking);
		PublicBookingCancellationController controller = new PublicBookingCancellationController(stdController);
		controller.doAction();
	}
}