src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <formula>IF( Finance_Written_Off__c = True, &apos;Written Off&apos;,
   IF( Finance_to_Credit_Opp__c = True, &apos;To Be Credited&apos;,
      IF( 
         OR( 
            AND(Finance_to_Invoice_Opp__c = True,  ISBLANK(Date_to_be_Invoiced__c)) , 
            AND(Finance_to_Invoice_Opp__c = True,  Date_to_be_Invoiced__c &lt;=  TODAY())
         ),&apos;To Be Invoiced&apos;,
         
         IF( AND(CreatedBy.Alias = &apos;Website&apos;, !ISBLANK(Latest_Invoice__r.Website_Order_Id__c)), &apos;N/A&apos;,
            IF( Using_one_to_one_invoicing__c = &apos;Yes&apos;,
               

               IF( AND(Latest_Invoice__r.Is_Credited_In_Full__c = True,!ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)) ,&apos;Credited&apos;,
                  IF( AND( Latest_Invoice__r.c2g__OutstandingValue__c = 0, !ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)) , &apos;Paid&apos;,
                     IF( AND(Latest_Invoice__r.c2g__OutstandingValue__c &gt; 0, Latest_Invoice__r.c2g__OutstandingValue__c &lt; Latest_Invoice__r.c2g__InvoiceTotal__c, !ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)), &apos;Part Paid&apos;,
                        IF(  AND(Latest_Invoice__r.c2g__OutstandingValue__c =  Latest_Invoice__r.c2g__InvoiceTotal__c, !ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)), &apos;Invoiced&apos;,
                           &apos;No Action&apos;
                        )
                     )
                  )
               )



            ,&apos;N/A&apos;
            )
         ) 
      )
   )
)</formula>
        <inlineHelpText>Determines the current status of the opportunity based on the one to one invoicing model.</inlineHelpText>
        <label>Invoice Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The subscription that needs to be altered.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities (Subscription)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Subscription</fullName>
        <active>true</active>
        <businessProcess>BSC Sales Process</businessProcess>
        <description>Opportunity for Membership and other Subscription Product Sales</description>
        <label>Subscription</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date when Special Event ends.</description>
        <inlineHelpText>Date when Special Event ends.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when Special Event starts.</description>
        <inlineHelpText>Date when Special Event starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Determines the type of event from a picklist</description>
        <inlineHelpText>Determine the type of event from the picklist</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NVQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <description>When related to an invoice, adds in the related invoice status</description>
        <inlineHelpText>When related to an invoice, adds in the related invoice status</inlineHelpText>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not-Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OPL_ID__c</fullName>
        <description>18 digit opportunity product line id that the event booking relates to</description>
        <externalId>true</externalId>
        <inlineHelpText>18 digit opportunity product line id that the event booking relates to</inlineHelpText>
        <label>OPL ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Defines the event booking type whether primary or additional etc</description>
        <inlineHelpText>Defines the event booking type whether primary or additional etc</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional - On the Day</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to manage subscriptions (Memberships, Complywise Subscriptions and other ongoing product deliveries)</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not-Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sub_Ref__c</fullName>
        <description>Reference for Subscription - this is constant year on year
Populated via workflow</description>
        <inlineHelpText>Reference for Subscription - this is constant year on year</inlineHelpText>
        <label>Sub Ref</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Line__c</fullName>
        <description>The total number of subscription lines on the subscription</description>
        <inlineHelpText>The total number of subscription lines on the subscription.</inlineHelpText>
        <label>Subscription Lines</label>
        <summaryForeignKey>Subscription_Line__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Sub Ref: Current Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Line__c.object
<CustomObject>
    <description>Object to manage products / elements of a subscription</description>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not-Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OPL_ID__c</fullName>
        <label>OPL ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Subscription Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvoiceLineItemsTriggerMethods.cls
public with sharing class InvoiceLineItemsTriggerMethods {
/*
	Changes: 
		24/03/2010
		* Case 00001735 - Discarded Invoices do not update the Opportunity Line
				While an invoice is still "In progress", the opportunity line will not be updated
				This resolves the issue when the invoice is discarded.

*/

    public class Test_Exception extends Exception{}
        
    public static  boolean isBookingEvent(String bookingId)
    {
        Schema.DescribeSObjectResult result = Special_Event_Booking__c.SObjectType.getDescribe();
        return(bookingId.trim().startsWith(result.getKeyPrefix()));
    }
    
    public static boolean isOpportunityLineItem(String oppLineItemId)
    {
        Schema.DescribeSObjectResult result = OpportunityLineItem.SObjectType.getDescribe();
        return(oppLineItemId.trim().startsWith(result.getKeyPrefix()));
    }
    
    public static  boolean isSubscriptionLine(String subsLineId)
    {
        Schema.DescribeSObjectResult result = Subscription_Line__c.SObjectType.getDescribe();
        return(subsLineId.trim().startsWith(result.getKeyPrefix()));
    }
    
    
    public static void updateOppLineItemSubsLineBookingEvent(List<c2g__codaInvoiceLineItem__c> invoiceLineItemList)
    {
        
        Set<Id> bookingId = new Set<Id>();
        Set<Id> subsLineId = new Set<Id>();
        Set<Id> oppLineItemId = new Set<Id>();
	// Case 00001735
        Set<id> invIds = new Set<id>();
          
        for (c2g__codaInvoiceLineItem__c invline : invoiceLineItemList)
        	invIds.add(invline.c2g__Invoice__c);
        
        //Map<id, c2g__codaInvoice__c> invMap = new Map<id, c2g__codaInvoice__c>([Select c2g__InvoiceStatus__c From c2g__codaInvoice__c where id = :invIds]);
        	
        //Invoice line items
         for(c2g__codaInvoiceLineItem__c invoiceLineItem:invoiceLineItemList)
          {
          	// invMap.get(invoiceLineItem.c2g__Invoice__c).c2g__InvoiceStatus__c)
          	//c2g__Invoice__c inv =[Select c2g__InvoiceStatus__c From c2g__codaInvoice__c Where id = :invoiceLineItem.c2g__Invoice__c ];
          	//if (c2g__Invoice__c.c2g__InvoiceStatus__c <> 'In Progress')
          	if (invoiceLineItem.Invoice_Status__c <> 'In Progress')
          	{
              if(invoiceLineItem.OPL_ID__c !=null)
                  oppLineItemId.add(invoiceLineItem.OPL_ID__c);
             
              if(invoiceLineItem.BEB__c !=null)
                  bookingId.add(invoiceLineItem.BEB__c);
                  
              if(invoiceLineItem.SL__c !=null)
                  subsLineId.add(invoiceLineItem.SL__c);
          	}    
          }
	  // End of Case 00001735
          
          if(!oppLineItemId.isEmpty())
          {    
            
            List<OpportunityLineItem> updateOppLineItem = new List<OpportunityLineItem>([Select Id from OpportunityLineItem where Id IN:oppLineItemId]);
            update updateOppLineItem; 
            
          }
          
          if(!bookingId.isEmpty())
          {    
            
            List<Special_Event_Booking__c> updateBooking = new List<Special_Event_Booking__c>([Select Id from Special_Event_Booking__c where Id IN:bookingId]);
            update updateBooking; 
            
          }
          
          if(!subsLineId.isEmpty())
          {    
            
            List<Subscription_Line__c> updateSubsLine = new List<Subscription_Line__c>([Select Id from Subscription_Line__c where Id IN:subsLineId]);
            update updateSubsLine; 
            
          }   
    }

    
    
    
    public static void populateFields(List<c2g__codaInvoiceLineItem__c> invoiceLineItemList)
    {
        Boolean checked = false;
        
        System.debug('FJP pre: '+invoiceLineItemList);
        
        for(c2g__codaInvoiceLineItem__c invoiceLineItem:invoiceLineItemList)
        {
             if(invoiceLineItem.c2g__LineDescription__c !=null && invoiceLineItem.c2g__LineDescription__c != '')
             {   
                //throw new Test_Exception(String.valueOf(invoiceLineItem.c2g__LineDescription__c.split(';')[3]));
                //checked = false;
                
                //Populate (text) lookup field to opportunity line item
                if(InvoiceLineItemsTriggerMethods.isOpportunityLineItem(invoiceLineItem.c2g__LineDescription__c.split(';')[0]))
                {
                    invoiceLineItem.OPL_ID__c = invoiceLineItem.c2g__LineDescription__c.split(';')[0];
                }
                
                //Populate lookup fied to booking event
                if(invoiceLineItem.c2g__LineDescription__c.split(';').size()== 2 || invoiceLineItem.c2g__LineDescription__c.split(';').size()>2 )
                {
                    
                    if(InvoiceLineItemsTriggerMethods.isBookingEvent(invoiceLineItem.c2g__LineDescription__c.split(';')[1]))
                    {   
                        invoiceLineItem.BEB__c = invoiceLineItem.c2g__LineDescription__c.split(';')[1];
                        //invoiceLineItem.c2g__LineDescription__c = '';
                        //checked =true;
                    }
                } 
                //Populate lookup fied to susbscription line 
                if(invoiceLineItem.c2g__LineDescription__c.split(';').size() == 2 || invoiceLineItem.c2g__LineDescription__c.split(';').size()>2)
                {
                    if(InvoiceLineItemsTriggerMethods.isSubscriptionLine(invoiceLineItem.c2g__LineDescription__c.split(';')[1]))
                    {   
                        invoiceLineItem.SL__c = invoiceLineItem.c2g__LineDescription__c.split(';')[1];
                        //invoiceLineItem.c2g__LineDescription__c = '';
                        checked =true;
                    }
                }
                
                if(invoiceLineItem.c2g__LineDescription__c.split(';').size()== 4)
                {
                    invoiceLineItem.c2g__LineDescription__c = invoiceLineItem.c2g__LineDescription__c.split(';')[2]+';'+invoiceLineItem.c2g__LineDescription__c.split(';')[3];
                }
                else{
                    invoiceLineItem.c2g__LineDescription__c = '';
                }
                
               
             }        
        }
        invoiceLineItemList = InvoiceLineItemsTriggerMethods.createLineDescs(invoiceLineItemList);
        
    }
    
    /*
     * CREATE LINE DESCRIPTIONS
     *
     * Creates line descriptions based on the type of product that is on the invoice line.
     *
     * SUBSCRIPTION LINE:
	 *	Format:
	 *	<Product Name>
	 *	Subscription End Date: <End date of subscription in DD-MM-YYYY format>
	 *	Product Code: <The product code of the product>
	 *	
	 *	Example:
	 *	1 Year Subscription Module - Tools - 1 to 5 Sites
	 *	Subscription End Date: 01-11-2012
	 *	Product Code 1SMT-1-5
	 *
     */
    public static List<c2g__codaInvoiceLineItem__c> createLineDescs(List<c2g__codaInvoiceLineItem__c> invoiceLineItemList){
    	
    	// Create a list of event bookings and subscription lines and based on the list create
    	// the correct invoice line description for each so that they can be used by the invoice lines
    	Map<Id,String> subLineList = new Map<Id,String>();
    	Map<Id,String> evtBookingList = new Map<Id,String>();
    	
    	for (c2g__codaInvoiceLineItem__c invLineItem : invoiceLineItemList){
    		    		
    		if (invLineItem.SL__c !=null){
    			subLineList.put(invLineItem.SL__c, '');
    		}
       		if (invLineItem.BEB__c !=null){
    			evtBookingList.put(invLineItem.BEB__c, '');
    		}
    	}
    	
    	// Generate Subscripiton Line description
    	if (subLineList.size() > 0){
	    	for(Subscription_Line__c subLine : [SELECT
	    								Id,
	    								Subscription__r.Start_date__c,
	    								Subscription__r.End_date__c,
	    								Subscription__r.Type__c,
	    								Subscription__r.Sub_Ref__c
	    							FROM
	    								Subscription_Line__c
	    							WHERE
	    								Id IN:subLineList.keySet()]){

	    		if (subLine.Subscription__r.Type__c == 'Renewal'){
	    			
	    			Datetime dtStart = subLine.Subscription__r.Start_date__c;
	    			string startDateFrmt = dtStart.format('dd MMM yyyy');
	    			
		    		Datetime dtEnd = subLine.Subscription__r.End_date__c;
	    			string endDateFrmt = dtEnd.format('dd MMM yyyy');
	    			
	    			subLineList.put(subLine.Id, '('+startDateFrmt+' - '+endDateFrmt+')\nSubscription Number: '+subLine.Subscription__r.Sub_Ref__c);
	    		}else{
	    			subLineList.put(subLine.Id, 'Subscription Number: '+subLine.Subscription__r.Sub_Ref__c);
	    		}
	    	}
    	}
    	
    	if (evtBookingList.size() > 0){
    		System.debug('FJP1 lines'+evtBookingList);
			for(Special_Event_Booking__c evtBookLine : [SELECT
	    								Id,
	    								Special_Event__r.Name,
	    								Special_Event__r.StartDate__c,
	    								Special_Event__r.EndDate__c
	    							FROM
	    								Special_Event_Booking__c
	    							WHERE
	    								Id IN:evtBookingList.keySet()]){

	    			Datetime dtStart = evtBookLine.Special_Event__r.StartDate__c;
	    			string startDateFrmt = dtStart.format('dd MMM yyyy');
	    			
	    			string endDateFrmt = '';
	    			if (evtBookLine.Special_Event__r.EndDate__c != null){
			    		Datetime dtEnd = evtBookLine.Special_Event__r.EndDate__c;
		    			endDateFrmt = dtEnd.format('dd MMM yyyy');
	    			}else{
	    				endDateFrmt = 'n/a';
	    			}
	    			evtBookingList.put(evtBookLine.Id, '('+startDateFrmt+' - '+endDateFrmt+')\nEvent Reference: '+evtBookLine.Special_Event__r.Name);

	    	}
    	}
    	
    	for (c2g__codaInvoiceLineItem__c invLine : invoiceLineItemList){

			if (invLine.SL__c != null){
				invLine.c2g__LineDescription__c = subLineList.get(invLine.SL__c);
			}
			if (invLine.BEB__c != null){
	    		invLine.c2g__LineDescription__c = evtBookingList.get(invLine.BEB__c);
			}
    	}
    	return invoiceLineItemList;
    }
    
    public testmethod static void testInvoiceLineItemTriggerMethods()
    {
        // OpportunityLineItem oppLineItem  =[Select Id from OpportunityLineItem limit 1];
    	// Case 1359 and  1254 -- Added due to Winter 11 FF release where the default company of the user is required to determine the appropriate data
    	c2g__codaUserCompany__c userCompany = [Select id, c.c2g__User__r.Username, c.c2g__Company__c From  c2g__codaUserCompany__c c Where c.c2g__User__r.Username = :UserInfo.getUserName() and c.c2g__Company__r.name='British Safety Council'];
         
		Test.startTest();
        Special_Event_Booking__c bookingEvt = TestHelper.CreateSpecialEventBooking();
        OpportunityLineItem opl = TestHelper.OppLineItem;
        Subscription_Line__c subsline = TestHelper.subscriptionLineItem;
        
        List<c2g__codaInvoiceLineItem__c> invoiceLineItemList= [Select c.Id,c.OPL_ID__c,c.c2g__Invoice__c,c.SL__c,c.BEB__c,c.c2g__LineDescription__c from c2g__codaInvoiceLineItem__c c Where c.c2g__Invoice__r.c2g__OwnerCompany__c = :userCompany.c2g__Company__c  and OPL_ID__c = :opl.Id];
        
        invoiceLineItemList.get(0).c2g__LineDescription__c = '12345'+';'+subsline.Id;
        InvoiceLineItemsTriggerMethods.populateFields(invoiceLineItemList);
        
        invoiceLineItemList.get(0).c2g__LineDescription__c = '12345'+';'+bookingEvt.Id;
        InvoiceLineItemsTriggerMethods.populateFields(invoiceLineItemList);
        Test.stopTest();
         
    }


}