src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <formula>IF( Finance_Written_Off__c = True, &apos;Written Off&apos;,
   IF( Finance_to_Credit_Opp__c = True, &apos;To Be Credited&apos;,
      IF( 
         OR( 
            AND(Finance_to_Invoice_Opp__c = True,  ISBLANK(Date_to_be_Invoiced__c)) , 
            AND(Finance_to_Invoice_Opp__c = True,  Date_to_be_Invoiced__c &lt;=  TODAY())
         ),&apos;To Be Invoiced&apos;,
         
         IF( AND(CreatedBy.Alias = &apos;Website&apos;, !ISBLANK(Latest_Invoice__r.Website_Order_Id__c)), &apos;N/A&apos;,
            IF( Using_one_to_one_invoicing__c = &apos;Yes&apos;,
               

               IF( AND(Latest_Invoice__r.Is_Credited_In_Full__c = True,!ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)) ,&apos;Credited&apos;,
                  IF( AND( Latest_Invoice__r.c2g__OutstandingValue__c = 0, !ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)) , &apos;Paid&apos;,
                     IF( AND(Latest_Invoice__r.c2g__OutstandingValue__c &gt; 0, Latest_Invoice__r.c2g__OutstandingValue__c &lt; Latest_Invoice__r.c2g__InvoiceTotal__c, !ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)), &apos;Part Paid&apos;,
                        IF(  AND(Latest_Invoice__r.c2g__OutstandingValue__c =  Latest_Invoice__r.c2g__InvoiceTotal__c, !ISBLANK(Latest_Invoice__c),ISPICKVAL(Latest_Invoice__r.c2g__InvoiceStatus__c , &apos;Complete&apos;)), &apos;Invoiced&apos;,
                           &apos;No Action&apos;
                        )
                     )
                  )
               )



            ,&apos;N/A&apos;
            )
         ) 
      )
   )
)</formula>
        <inlineHelpText>Determines the current status of the opportunity based on the one to one invoicing model.</inlineHelpText>
        <label>Invoice Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Delegates__c</fullName>
        <description>Copied from Lead - the number of delegates the customers wishes to book on the course</description>
        <inlineHelpText>Copied from Lead - the number of delegates the customers wishes to book on the course</inlineHelpText>
        <label>Number of Delegates</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <displayFormat>O-{0000000}</displayFormat>
        <label>Opportunity Number</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Number_of_Delegates__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of Delegates for In-Company Courses</description>
        <inlineHelpText>In-Company Training Courses Only</inlineHelpText>
        <label>IC Training: No. of Delegates</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>No_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When a product has no timed event this should be true, in order to pull the products through on the booking form.</description>
        <label>No Event</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Booking_Fee__c</fullName>
        <description>This is pulled from the opportunity product unit price for public an total price on the in-company primary for in-company</description>
        <inlineHelpText>The amount that should be charged for this booking. This is automatically updated, change this by updating the opportunity line.</inlineHelpText>
        <label>Booking Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the person attending the event as a delegate pulled from the contact</description>
        <inlineHelpText>The name of the person attending the event as a delegate</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <description>When related to an invoice, adds in the related invoice status</description>
        <inlineHelpText>When related to an invoice, adds in the related invoice status</inlineHelpText>
        <label>Invoice Status</label>
        <picklist>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not-Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OPL_ID__c</fullName>
        <description>18 digit opportunity product line id that the event booking relates to</description>
        <externalId>true</externalId>
        <inlineHelpText>18 digit opportunity product line id that the event booking relates to</inlineHelpText>
        <label>OPL ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Booking__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Signifies whether this booking is Primary or not..</description>
        <inlineHelpText>Signifies whether this booking is Primary or not..</inlineHelpText>
        <label>Primary Booking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transfer_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for transferring public bookings to a new event. Auto populated when transferring a public booking.</description>
        <inlineHelpText>Used for transferring public bookings to a new event. Auto populated when transferring a public booking.</inlineHelpText>
        <label>Transfer to: Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (Transfer To)</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit__c.object
<CustomObject>
    <description>Object to manage Units of an event, e.g. sessions or components</description>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>Related event</description>
        <inlineHelpText>Related event</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Units</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BSC Event Unit</label>
    <nameField>
        <label>Event Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Event Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event Unit (Session or component)</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to the contact to show the name of the delegate booked on that session.</description>
        <inlineHelpText>lookup to the contact to show the name of the delegate booked on that session.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>BSC Event Unit Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Unit_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Booking__c</fullName>
        <description>Lookup to the related event booking</description>
        <inlineHelpText>Lookup to the related event booking</inlineHelpText>
        <label>Event Booking</label>
        <referenceTo>Special_Event_Booking__c</referenceTo>
        <relationshipLabel>BSC Event Unit Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Unit_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BSC Event Unit Booking</label>
    <nameField>
        <displayFormat>EUB-{0000000}</displayFormat>
        <label>Event Unit Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Unit Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/addBookingExtension.cls
public class addBookingExtension {

    public Opportunity opp               {get; set;}
    public list<prodEvts> prodEvt        {get; set;}
    public boolean showsection			 {get; set;}
    
    public string eventName {get; set;}
    
    public addBookingExtension(ApexPages.StandardController con){
        opp = (Opportunity)con.getRecord();
        id oppId = opp.Id;
        
        map <id,special_event__c> oppEvents = new map<id, special_event__c>();
        map <id,OpportunityLineItem> oppProduct = new map<id, OpportunityLineItem>();
        map <id,Special_Event_Booking__c> oppBookings = new map<id, Special_Event_Booking__c>();
        set <id> productIds = new set<id>();
        
        prodEvt = new list<prodEvts>();

		opp = [select id, Name, Opportunity_Number__c,AccountId,CurrencyIsoCode,StageName,Invoice_Status__c,
               (SELECT Id,Name,TotalPrice,UnitPrice,PricebookEntry.Product2.Name,PricebookEntry.Product2Id,Number_of_Delegates__c,Quantity FROM OpportunityLineItems o WHERE PricebookEntry.Product2.No_Event__c = False),
               (SELECT Id,Name,Special_Event__c, opl_id__c, Contact__c,Booking_Fee__c,Primary_Booking__c,Status__c from BSC_Event_Bookings__r order by Primary_Booking__c desc, Name),
               (SELECT Id,Name,StartDate__c,EndDate__c,Status__c,Add_Remove_Bookings__c, No_of_Delegates_Booked__c, Maximum_Places__c  from BSC_Events__r)
               from Opportunity where id = :oppId];

        boolean proceed = true;
        

        if(opp.StageName == 'Invoiced' || opp.StageName == 'Part Invoiced' || opp.StageName == 'Paid' || opp.StageName == 'Part Paid' ||
           opp.Invoice_Status__c == 'Invoiced' || opp.Invoice_Status__c == 'Paid' || opp.Invoice_Status__c == 'Part Paid'  || opp.Invoice_Status__c == 'To Be Credited'){
               proceed = false;
               ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'This opportunity has an invoice associated with it which first needs to be credited by Finance.  Please tick the Finance To Credit Opp flag on this opportunity.  You will need to wait for the opportunity to be credited before continuing'));
           }
        
        if (opp.StageName == 'Booking Received' || opp.StageName == 'Customer Approved'){
            showsection = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Cannot Add/Remove bookings when the Opp stage is at  Booking Received or  Customer Approved'));
            
        } else if (proceed) {
        	showsection = true;
            AggregateResult[] bookings = [SELECT Special_Event__c, opl_id__c from Special_Event_Booking__c where Opportunity__c = :oppId Group by Special_Event__c, opl_id__c];
            
            system.debug('bookings for opp: ' + bookings);
            
            for (AggregateResult ar :  bookings){
                id evnt = (Id)ar.get('Special_Event__c');
                id opl = (id)ar.get('opl_id__c');
                
                system.debug('event' + evnt);
                
                Special_Event__c foundEvent;
                OpportunityLineItem foundOPL;
                list<oppBookings> foundBookings = new list<oppBookings>();
                
                for (Special_Event__c bscEvent : opp.BSC_Events__r){
                    if (evnt == bscEvent.Id){
                        foundEvent = bscEvent;
                    }
                }
                
                for (OpportunityLineItem oppLine : opp.OpportunityLineItems){
                    if (opl == oppLine.Id){
                        foundOPL = oppLine;
                    }
                }
                
                system.debug('foundEvent ' + foundEvent);
                system.debug('foundOPL ' + foundOPL);
                
                if (foundEvent != null && foundOPL != null){
                    for (Special_Event_Booking__c bkg : opp.BSC_Event_Bookings__r){
                        if (bkg.Special_Event__c == evnt && bkg.opl_id__c == opl){
                            foundBookings.add( new oppBookings(bkg) );
                        }
                    }
                    
                    prodEvt.add(new prodEvts(foundEvent, foundOPL, foundBookings));
                }
                
            }
            
            system.debug('Product Event Map: '+ prodEvt);
            system.debug('Product Event Map size: '+ prodEvt.size());
        }
        
    }

    public class addBookingException extends Exception{}
    
    public PageReference confirmBookings(){
        
        try{
            
            list<Special_Event__c> updateEvents = new list<Special_Event__c>();
            list<Special_Event_Booking__c> addBookings = new list<Special_Event_Booking__c>();
            list<Special_Event_Booking__c> deleteBookings = new list<Special_Event_Booking__c>();
            
            list<task> tasks = new list<task>();
            
            map<id,opportunitylineitem> oppmap = new map<id,opportunitylineitem> ();
            for (prodEvts p : prodEvt){
                if (oppmap.containsKey(p.opl.id) == false){
                    oppmap.put(p.opl.id, p.opl);
                }
            }
            
            
            User manager = [select Manager.Email,ManagerId,email from User where id = :UserInfo.getUserId()];
            
            for (prodEvts p : prodEvt){
                
                system.debug('Adding ' + p.newBookings + ' bookings to Event ' + p.event.Name);
                
                opportunitylineitem oplUpd = oppmap.get(p.opl.id);
                
                if (!p.requestApproval){
                    for(integer i = 0; i < p.newBookings; i++){
                        Special_Event_Booking__c bookingAdditional = new Special_Event_Booking__c(
                            Opportunity__c = opp.Id,
                            Status__c='Provisional',
                            Type__c = 'In-Company Additional',
                            Special_Event__c = p.event.Id,
                            Company__c = opp.AccountId,
                            Booking_Fee__c = 0.0,
                            OPL_ID__c  = p.opl.Id);
                        
                        p.opl.Number_of_Delegates__c = oplUpd.Number_of_Delegates__c + 1;
                        addBookings.add(bookingAdditional);
                    }
                    
                    for(oppBookings b : p.bookings){
                        if (b.selected){
                            system.debug('Deleting booking ' + b.booking.Name + ' from event ' + p.event.Name);
                            p.opl.Number_of_Delegates__c = oplUpd.Number_of_Delegates__c  - 1;
                            deleteBookings.add(b.Booking);
                        }
                    }
                    oppmap.remove(p.opl.id);
                    oppmap.put(p.opl.id, oplUpd);
                    
                    if(p.newBookings > 0 || p.bookingsRemoved > 0 ){
                        string subject = 'Bookings Added/Removed for Event:' + p.event.Name;
                        
                        string body = 'Event: ' + p.event.Name  +  
                            '\r\n' + 
                            'Start Date: ' + p.Event.StartDate__c + 
                            '\r\n' + 
                            'End Date: ' + p.Event.EndDate__c + 
                            '\r\n' + 
                            'Number of Bookings added: ' + p.newBookings + 
                            '\r\n' + 
                            'Number of Bookings removed: '+ p.bookingsRemoved;
                        
                        string[] toEmail = new string[3];
                        toEmail[0] = 'operations.inbox@britsafe.org';
                        toEmail[1] = manager.Manager.Email;
                        toEmail[2] = manager.Email;
                        
                        Utilities.SendEmail(body, subject, toEmail);
                        p.event.Add_Remove_Bookings__c = false;
                        updateEvents.add(p.event);
                    }
                } else {
                    
                    string body = 'Please authorise to Add/Remove bookings on this Event: '+ URL.getSalesforceBaseUrl().toExternalForm() + '/' + p.event.id + ' '+ p.event.Name + '\r\nSubmitted by: ' + UserInfo.getName();
                    string subject = 'Request to Add/Remove Bookings for Event ' + p.event.Name;
                    task t  = Utilities.createTask(false, date.today(), p.event.id, subject, body, manager.ManagerId );
                    tasks.add(t);
                    string[] toEmail = new string[2];
                    toEmail[0] = 'operations.inbox@britsafe.org'; 
                    toEmail[1] = manager.Manager.Email;
                    

                    Utilities.sendTemplatedEmail(toEmail, 'Request_To_Add_or_Remove_Bookings', p.event.id, UserInfo.getUserId());
                    
                }
            }
            system.debug('OPL Updates' + oppmap.values());
            insert tasks;
            update oppmap.values();
            delete deleteBookings;
            insert addBookings;
            update updateEvents;
           
            system.debug('Adding Special_Event_Unit_Booking__c ');
            list<Special_Event_Unit_Booking__c> unitBookings = new list<Special_Event_Unit_Booking__c>();
            for (Special_Event_Booking__c b : addBookings){
                for (Special_Event_Unit__c u:[Select Id From Special_Event_Unit__c Where Special_Event__c=:b.Special_Event__c])
                {
                    System.debug('Looping special Event unit to create special event Unit Booking: '+u.id);
                    Special_Event_Unit_Booking__c unitBooking = new Special_Event_Unit_Booking__c(currencyIsoCode=opp.CurrencyIsoCode,
                                                                                                  attended__c = false,
                                                                                                  event_unit__c = u.Id,
                                                                                                  event_booking__c=b.id);
                    unitBookings.add(unitBooking);
                }
            }
            
            insert unitBookings;
            
            opp.Price_Approval_Given__c = false;
            opp.IC_Price_Variation_Approved__c = false;
            opp.T_C_Variation_Approved__c = false;
            
            update opp;
            
            return new pagereference('/' + opp.id);
            
        } catch (Exception e) {
             throw new addBookingException(e.getMessage());
        }
    }
    
    public PageReference selectBookingsForEvent(){
        system.debug(' in selectBookingsForEvent' + eventName);
        for (prodEvts p : prodEvt){
            if (p.event.Name == eventName){
                for(oppBookings b : p.bookings){
                    if (b.booking.Primary_Booking__c == false)
                        b.selected= true;
                }
            }
        }
        return null;
    }
    
    public class prodEvts{
        
        public OpportunityLineItem opl {get; set;}
        public Product2 product; 
        public Special_Event__c event {get; set;}
        public list<oppBookings> bookings {get; set;}
        public boolean requestApproval {get; set;}
        public integer newBookings {get; set;}
        
        public integer avaliableBookings{
            get{
                return (Integer)(event.Maximum_Places__c - event.No_of_Delegates_Booked__c);
            }
        }
        
        public integer bookingsRemoved{
            get{
                integer i= 0;
                for (oppBookings b : bookings){
                    if (b.selected){
                        i = i + 1;
                    }
                }
                return i;
            }
        }
        
        
        public boolean validEvent { 
            get {
                date current = date.today();
                
                if (current.daysBetween(event.StartDate__c) < 22 && event.Add_Remove_Bookings__c == false)
                    return false;
                else
                    return true;
            }
        }
        
        public prodEvts(Special_Event__c e,OpportunityLineItem o, list<oppBookings> b){
            this.event = e;
            opl = o; 
            bookings = b;
            requestApproval = false;
        }
    }
    
    public class oppBookings{
        public boolean selected {get; set;}
        public Special_Event_Booking__c booking {get; set;}
        
        public oppBookings(Special_Event_Booking__c b){
            booking = b;
            selected = false;
        }
    }
    
    
}