src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Pricing_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to mark cancellation reconciliation prices as exceptions to avoid triggering approval</description>
        <inlineHelpText>Checkbox to mark cancellation reconciliation prices as exceptions to avoid triggering approval</inlineHelpText>
        <label>Pricing Exception</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date when Special Event ends.</description>
        <inlineHelpText>Date when Special Event ends.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Shows the stage of the event, which is a dependant pick list of the status field</description>
        <inlineHelpText>Shows the stage of the event, which is a dependant pick list of the status field</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when Special Event starts.</description>
        <inlineHelpText>Date when Special Event starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Determines the type of event from a picklist</description>
        <inlineHelpText>Determine the type of event from the picklist</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NVQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Booking_Fee__c</fullName>
        <description>This is pulled from the opportunity product unit price for public an total price on the in-company primary for in-company</description>
        <inlineHelpText>The amount that should be charged for this booking. This is automatically updated, change this by updating the opportunity line.</inlineHelpText>
        <label>Booking Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OPL_ID__c</fullName>
        <description>18 digit opportunity product line id that the event booking relates to</description>
        <externalId>true</externalId>
        <inlineHelpText>18 digit opportunity product line id that the event booking relates to</inlineHelpText>
        <label>OPL ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Defines the event booking type whether primary or additional etc</description>
        <inlineHelpText>Defines the event booking type whether primary or additional etc</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Additional - On the Day</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit__c.object
<CustomObject>
    <description>Object to manage Units of an event, e.g. sessions or components</description>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>Related event</description>
        <inlineHelpText>Related event</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Units</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_End_Time__c</fullName>
        <description>Stores the End Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event.</description>
        <inlineHelpText>Stores the End Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event.</inlineHelpText>
        <label>Unit End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Unit_Start_Time__c</fullName>
        <description>Stores the Start Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event</description>
        <inlineHelpText>Stores the Start Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event</inlineHelpText>
        <label>Unit Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>BSC Event Unit</label>
    <nameField>
        <label>Event Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Event Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/addBookingExtensionTest.cls
@isTest(SeeAllData = true)
public class addBookingExtensionTest {
    
    public static Account acc;
    public static Opportunity opp;
    public static OpportunityLineItem OppLineItem;
    public static Special_Event__c specialEvent;
    public static Special_Event_Booking__c specialEventbooking;
    public static Contact NewContact;
    
    private static string RandomString{
        get{
            return string.valueof(math.random()).substring(1,10);
        }
    }
    
    static testMethod void TestInCoProvisional() {
        Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
        
        Product2  testProd = new Product2 (name = 'InCompany Test');
        insert testProd;
        
        Pricebook2 pbe2Test = new Pricebook2(name =  'InCompany Test');
        insert pbe2Test;
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = testProd.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice;
        
        PricebookEntry pbeTest = new PricebookEntry(Product2Id = testProd.Id, Pricebook2Id = pbe2Test.Id, unitPrice = 100, UseStandardPrice = false, IsActive = true);
        insert pbeTest;
        
        RecordType rType = [select id from RecordType where name = 'In-Company Event' and sObjectType = 'Opportunity'];
        
        /* CREATE ACCOUNT*/
        acc = new Account(
            name = 'tnc '+ RandomString); 
        insert acc;
        
        /* CREATE ACCOUNT*/
        NewContact= new Contact(
            LastName='tnc ' +RandomString , 
            Email='testy13213@fffp.com'+RandomString, 
            FirstName = 'tnc'+RandomString, 
            Salutation = 'Mr',
            AccountId = acc.id
        );
        insert NewContact;
        
        /* CREATE OPPORTUNITY*/
        opp = new Opportunity(
            Name = 'tncopp '+RandomString,
            AccountId = acc.Id,
            StageName = 'Qualifying',
            CloseDate = Date.today(), 
            Pricebook2Id = pbe2Test.Id,
            RecordTypeId = rType.Id);
        insert opp;
        
        /* CREATE OPP LINE ITEMS*/
        OppLineItem = new OpportunityLineItem(
            OpportunityId = opp.Id,
            PricebookEntryId = pbeTest.Id,
            Pricing_Exception__c = true,
            Quantity = 3,
            UnitPrice = 320);
        insert OppLineItem;
        
        specialEvent = new Special_Event__c(
            Opportunity__c = opp.Id,
            Name = 'tnc1 '+ RandomString,
            Product__c = testProd.Id,
            Type__c = 'In-Company Training',
            Status__c = 'Allocating',
            Stage__c = 'Provisional',
            StartDate__c = Date.today(),
            EndDate__c = Date.today().addDays(0));
        insert specialEvent;
        
        Special_Event_Unit__c evUn = new Special_Event_Unit__c(
            Name = 'TestDAy',
            Special_Event__c = specialEvent.id,
            Unit_Start_Time__c = datetime.newInstance(2014, 9, 9, 9, 0, 0),
            Unit_End_Time__c = datetime.newInstance(2014, 9, 9, 9, 0, 0)
        );
        insert evUn;
        
        /* CREATE BSC EVENT BOOKING*/
        specialEventbooking = new Special_Event_Booking__c(
            Opportunity__c = opp.Id,
            Booking_Fee__c =  10000,
            Special_Event__c = specialEvent.Id,
            Type__c = 'Public',
            OPL_ID__c = OppLineItem.Id,
            status__c = 'Provisional'
        );
        insert specialEventbooking;
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        addBookingExtension bkgExt = new addBookingExtension(sc);
        
        PageReference ref = new PageReference('/apex/addBooking?id='+ opportunity.id);
        Test.setCurrentPage(ref); 
        
        for (addBookingExtension.prodEvts p : bkgExt.prodEvt){
            p.newBookings = 6;
            
           for (addBookingExtension.oppBookings o : p.bookings){
                o.selected = true;
            }
        }

        bkgext.eventName = specialEvent.Name;
        bkgext.selectBookingsForEvent();
        
        bkgExt.confirmBookings();
    }
    
}