src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Copied from Lead - Start date of the event the user wishes to book</description>
        <inlineHelpText>Copied from Lead - Start date of the event the user wishes to book</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity_Value__c</fullName>
        <description>Populated with the total value of the opportunity when the rollover process is initiated</description>
        <inlineHelpText>Value of opportunity before split</inlineHelpText>
        <label>Original Opportunity Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If populated, this field indicates an original public events opportunity which has been partially closed</description>
        <inlineHelpText>If populated, this field indicates an original public events opportunity which has been partially closed</inlineHelpText>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subsequent Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, this box indicates that the opportunity has been created automatically as a subscription is up for renewal</description>
        <inlineHelpText>If ticked, this box indicates that the opportunity has been created automatically as a subscription is up for renewal</inlineHelpText>
        <label>Renewal Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rollover_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, this box indicates an opportunity has been created from partial closure of a public events opportunity</description>
        <inlineHelpText>If ticked, this box indicates an opportunity has been created from partial closure of a public events opportunity</inlineHelpText>
        <label>Rollover Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>T_C_Price__c</fullName>
        <description>Field automatically populated by Transfer / Cancellation trigger - used to track differences to require approval</description>
        <label>T/C Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transferred_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populates automatically with the originating Event when an In-Company Event / Audit is transferred</description>
        <inlineHelpText>Populates automatically with the originating Event when an In-Company Event / Audit is transferred</inlineHelpText>
        <label>Transferred From</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>Originating Events</relationshipLabel>
        <relationshipName>BSC_Events1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transferred_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>At the moment Sales to Manually populate with the new event ref if an In-Company event is being transferred</description>
        <inlineHelpText>Populate when Transferring In-Company Events and Audits</inlineHelpText>
        <label>Transferred To</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the person attending the event as a delegate pulled from the contact</description>
        <inlineHelpText>The name of the person attending the event as a delegate</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Pulls in the related event&apos;s start date</description>
        <formula>Special_Event__r.StartDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related event&apos;s start date</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_end_Date__c</fullName>
        <description>Pulls in the related event&apos;s end date</description>
        <formula>Special_Event__r.EndDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related event&apos;s end date</inlineHelpText>
        <label>Event end Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FK_CB_BOOK_ID__c</fullName>
        <description>This is a Foreign Key which maps to the Opportunities table in Salesforce from each BSC Event Booking via Oppotunitiy.PK_CB_BOOK_ID__c

It is used during migration to associate BSC Event Bookings to Opportunities (Bookings)</description>
        <inlineHelpText>This is a System Administrator field</inlineHelpText>
        <label>FK_CB_BOOK_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FK_CB_COURSE_ID__c</fullName>
        <description>This is a Foreign Key which maps to the BSC Events table in Salesforce from each BSC Event Booking via BSC_Event__c.PK_CB_COURSE_ID__c

It is used during migration to associate BSC Event Bookings (Elements) to BSC Events (Courses)</description>
        <inlineHelpText>This is a System Administrator field</inlineHelpText>
        <label>FK_CB_ COURSE_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fee_Date__c</fullName>
        <description>Updates to the Transfer cancellation date or if this is blank pulls in the event start date</description>
        <formula>IF( ISBLANK(Transfer_Cancellation_Date__c ), Special_Event__r.StartDate__c ,Transfer_Cancellation_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the date on which revenues can be realised (i.e. event date for normal bookings and transfer / cancellation date for transfers / cancellations)</inlineHelpText>
        <label>Fee Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PK_CB_ELEM_ID__c</fullName>
        <description>This is the Primary Key of the Element (BSC Event Booking) from the source Elements  data and maps to Elements.ELEM_ID from the Elements  table in the CB database.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is a system admin field</inlineHelpText>
        <label>PK_CB_ELEM_ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Date__c</fullName>
        <description>The date on which the booking is transferred or cancelled</description>
        <inlineHelpText>The date on which the booking is transferred or cancelled</inlineHelpText>
        <label>Transfer / Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transferred_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be populated with the previous field if a booking is transferred</description>
        <inlineHelpText>This field will be populated with the previous field if a booking is transferred</inlineHelpText>
        <label>Transferred From</label>
        <referenceTo>Special_Event_Booking__c</referenceTo>
        <relationshipLabel>Previous Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transferred_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field indicates the subsequent booking if a booking is transferred</description>
        <inlineHelpText>This field indicates the subsequent booking if a booking is transferred</inlineHelpText>
        <label>Transferred to: Booking</label>
        <referenceTo>Special_Event_Booking__c</referenceTo>
        <relationshipLabel>Subsequent Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <recordTypes>
        <fullName>BSC_Event_Booking</fullName>
        <active>true</active>
        <label>BSC Event Booking</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OpportunityRollOver.cls
public class OpportunityRollOver 
{
	//public OpportunityRollOver ()
	//{
	//}
	public void CreateOpportunityRollOver(ID OppId)
	{
		//Opportunity MyOpp=[Select Id from Opportunity where name='InCompOppTest' limit  1];
		//ID Myid =MyOpp.Id ;  
		Savepoint SP=Database.setSavepoint();
		// Clone the Original Opprtunity
		//Opportunity NewOpp=[Select StageName, Renewal_Opportunity__c, OwnerId, Name, Description, Amount From Opportunity where ID='006R0000005iRBNIA2'];		
		Opportunity OrigOpp=[
			SELECT
				StageName,
				Renewal_Opportunity__c,
				OwnerId,
				Name,
				Description,
				Amount
			FROM
				Opportunity
			WHERE
				ID=:OppId];
		Opportunity NewOpp = OrigOpp.clone(false);
		NewOpp.Name = OrigOpp.Name + '-R';
		NewOpp.Rollover_Opportunity__c = true;
		NewOpp.Original_Opportunity__c = OppId;
		OrigOpp.Original_Opportunity_Value__c = OrigOpp.Amount;
		try
		{
			 // Get list of all underlying Opportunity Line Items and Clone Product Line Items		
			List<OpportunityLineItem> OppNewLineItems =new List<OpportunityLineItem>();			
			//Delete from original opp where status is equal to Provisional
			List<Special_Event_Booking__c> OrigOppProvisionalEventBooking = [
				SELECT
					Id
				FROM
					Special_Event_Booking__c
				WHERE
					Id= :OppId
				AND
					Status__c = 'Provisional'];
			//Database.Deleteresult[] oResults=Databas.delete(OrigOppProvisionalEventBooking);									
		 	
		 	for (OpportunityLineItem OppLineItem: [
		 		SELECT
		 			UnitPrice,
		 			T_C_Price__c,
		 			ListPrice,
		 			Quantity,
		 			PricebookEntryId
		 		FROM
		 			OpportunityLineItem
		 		WHERE
		 			OpportunityId= :OppId])
	        {
			    OpportunityLineItem NewLineItem = OppLineItem.clone(false);
			    NewLineItem.OpportunityId = NewOpp.Id;
			    OppNewLineItems.add(NewLineItem);
	        }
	 		insert OppNewLineItems;	 			
	 		// **Clone BSC Event bookings except where status is equal to Provisional
	 		List<Special_Event_Booking__c> OppNewEventBookings = new List<Special_Event_Booking__c>();
		 	for (Special_Event_Booking__c OppEventBooking: [
		 		SELECT
		 			Transferred_To__c,
		 			Transferred_From__c,
		 			Transfer_Cancellation_Date__c,
		 			Status__c,
		 			Special_Event__c,
		 			PK_CB_ELEM_ID__c,
		 			Name,
		 			Fee_Date__c,
		 			FK_CB_COURSE_ID__c,
		 			FK_CB_BOOK_ID__c,
		 			Event_end_Date__c,
		 			Event_Start_Date__c,
		 			Contact__c,
		 			ConnectionSentId,
		 			ConnectionReceivedId,
		 			Company__c, Booking_Fee__c
		 		FROM
		 			Special_Event_Booking__c
		 		WHERE
		 			Status__c='Provisional'
		 		AND
		 			Opportunity_ID__c= : OppId])
	        {
			    Special_Event_Booking__c NewEventBooking=OppEventBooking.clone(false);
			    NewEventBooking.Opportunity__c=NewOpp.Id;
			    OppNewEventBookings.add(NewEventBooking);
	        }
	 		insert OppNewEventBookings;	 		
			//TODO On both opportunities,  Product lines are deleted where there is not a corresponding booking:
			// i.e. where the product is not referred in BSC_Event_Booking.BSC_Event.Product  in the bookings attached to the Opportunity.			
	 		update NewOpp;
	 		update OrigOpp;
		}
		catch (Exception e)
		{
			// roll back everything
			Database.rollback(SP);
			//Apexpages.addMessages(e);
			//return null;
		}					
	}
}