src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>IC_Price_Variation_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This box is ticked by the approval process of submitting a variation in In-Company products for approval</inlineHelpText>
        <label>IC Price Variation Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Delegates__c</fullName>
        <description>Copied from Lead - the number of delegates the customers wishes to book on the course</description>
        <inlineHelpText>Copied from Lead - the number of delegates the customers wishes to book on the course</inlineHelpText>
        <label>Number of Delegates</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Audit</fullName>
        <active>true</active>
        <businessProcess>BSC Sales Process</businessProcess>
        <description>Opportunity to manage sale of an Audit</description>
        <label>Audit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>In_Company_Number_of_Days__c</fullName>
        <inlineHelpText>Number of Days</inlineHelpText>
        <label>In Co: No. of Days</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Delegates__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of Delegates for In-Company Courses</description>
        <inlineHelpText>In-Company Training Courses Only</inlineHelpText>
        <label>IC Training: No. of Delegates</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pricing_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to mark cancellation reconciliation prices as exceptions to avoid triggering approval</description>
        <inlineHelpText>Checkbox to mark cancellation reconciliation prices as exceptions to avoid triggering approval</inlineHelpText>
        <label>Pricing Exception</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Allows_Provisional_Bookings__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Ticking this box allows provisional bookings to be made through the Coursefinder page. (I.e. tick this on public events.)</inlineHelpText>
        <label>Allows Provisional Bookings</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Record_Type__c</fullName>
        <label>Event Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Public Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_1__c</fullName>
        <defaultValue>99</defaultValue>
        <description>Minimum number of days at which Fee 1 will be charged (the lowest rate)</description>
        <inlineHelpText>Minimum number of days at which Fee 1 will be charged (the lowest rate)</inlineHelpText>
        <label>Transfer Charge Day 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_2__c</fullName>
        <defaultValue>28</defaultValue>
        <description>Minimum number of days at which Fee 2 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 2 will be charged</inlineHelpText>
        <label>Transfer Charge Day 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_3__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Minimum number of days at which Fee 3 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 3 will be charged</inlineHelpText>
        <label>Transfer Charge Day 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_1__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee (lowest rate)</description>
        <inlineHelpText>Lowest percentage for calculating transfer fee - will apply if transfer takes place before Days 1</inlineHelpText>
        <label>Transfer Charge Fee 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_2__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 1 and before Days 2</inlineHelpText>
        <label>Transfer Charge Fee 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_3__c</fullName>
        <defaultValue>0.25</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 2 and before Days 3</inlineHelpText>
        <label>Transfer Charge Fee 3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_Final__c</fullName>
        <defaultValue>1.0</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 3</inlineHelpText>
        <label>Transfer Charge Fee Final</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>City__c</fullName>
        <description>Select the city that the event will be taking place</description>
        <inlineHelpText>Select the city that the event will be taking place</inlineHelpText>
        <label>City</label>
        <picklist>
            <picklistValues>
                <fullName>Aberdeen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birmingham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bristol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crawley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dundee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edinburgh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exeter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huntingdon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sheffield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stirling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Latest_Start_Date__c</fullName>
        <description>Field populated when provisional events are created from the opportunity</description>
        <inlineHelpText>Field populated when provisional events are created from the opportunity and is selected when using the request event wizard on the opportunity</inlineHelpText>
        <label>Latest Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when Special Event starts.</description>
        <inlineHelpText>Date when Special Event starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <recordTypes>
        <fullName>Audit</fullName>
        <active>true</active>
        <description>Audit or Advisory Session</description>
        <label>Audit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Event_Type__c</fullName>
        <formula>Special_Event__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OPL_ID__c</fullName>
        <description>18 digit opportunity product line id that the event booking relates to</description>
        <externalId>true</externalId>
        <inlineHelpText>18 digit opportunity product line id that the event booking relates to</inlineHelpText>
        <label>OPL ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/tncRequestEventTest.cls
@IsTest(SeeAllData=true)
public class tncRequestEventTest{
    private static TestMethod void CreateProvisionalEventsControllerTest()
    {
        string random = string.valueof(math.random()).substring(1,10);
        
        Opportunity opp = new Opportunity(
            Name = 'Test Opp ' + random,
            StageName = 'Qualifying',
            IC_Price_Variation_Approved__c = true,
            CloseDate = System.today());
        insert opp;
        
        Product2 prod = new Product2(
            Name = 'Test Event Product' +random,
            Allows_Provisional_Bookings__c = true,
            Transfer_Charge_Day_1__c = 10,
            Transfer_Charge_Day_2__c = 5,
            Transfer_Charge_Day_3__c = 2,
            family = 'Audit',
            Event_Record_Type__c = 'Audit',
            Event_Type__c = 'Audit',
            Transfer_Charge_Fee_1__c = 120,
            Transfer_Charge_Fee_2__c = 60,
            Transfer_Charge_Fee_3__c = 40,
            Transfer_Charge_Fee_Final__c = 10);
        insert prod;
        
        Pricebook2 stdPricebook = [
            SELECT
            Id
            FROM
            Pricebook2
            WHERE
            IsStandard = true and Name = 'Standard Price Book' Limit 1];
        
        PricebookEntry pbe = new PricebookEntry(
            Product2Id = prod.Id,
            UnitPrice = 300,
            Pricebook2Id = stdPricebook.Id,
            IsActive = true);
        insert pbe;
        
        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            PricebookEntryId = pbe.Id,
            Quantity = 1,
            Pricing_Exception__c = true, 
            UnitPrice = 320,
            Number_of_Delegates__c=3,
            In_Company_Number_of_Days__c=2);
        insert oli;
        
        Account acc = new Account(name = 'TestAccount'+random);
        insert acc;
        
        Contact cont = new Contact ();
        cont.FirstName = 'TestFN'+random;
        cont.LastName = 'TestLN'+random;
        cont.Accountid = acc.id;
        insert cont;
        
        OpportunityContactRole ocr = new OpportunityContactRole(
            OpportunityId = opp.Id,
            ContactId = cont.Id,
            isPrimary = true);
        insert ocr;
        
        Special_Event__c event = new Special_Event__c();
        event.Product__c = prod.Id;
        event.City__c = 'London';
        event.StartDate__c = System.today();
       
        event.Latest_Start_Date__c = system.today().addDays(3);
        insert event;
        
        Special_Event_Booking__c eventBooking = new Special_Event_Booking__c();
        eventBooking.Opportunity__c = opp.Id;
        eventBooking.Special_Event__c = event.Id;
        eventBooking.OPL_ID__c = oli.id;
        insert eventBooking;
        
        Test.startTest();
        PageReference pagRef = new PageReference('/apex/tncRequestEvent?Id=' + string.valueOf(opp.Id)+'&opl='+string.valueOf(oli.id)+':'+string.valueOf(event.id)+',' );
        Test.setCurrentPage(pagRef);
        
        tncRequestEvent con = new tncRequestEvent(new ApexPages.Standardcontroller(opp));
        con.theProductId = prod.Id;
        con.oplId = oli.id;
        con.addRow();
        
         for(tncRequestEvent.myProduct p : con.theProducts){
            Special_Event__c ev = p.theEvents[0];
            ev.StartDate__c = System.today();
            ev.Latest_Start_Date__c = system.today();
         }
        con.save();
        Test.stopTest();
    }
}