src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <businessProcess>BSC Sales Process</businessProcess>
        <description>Opportunity to manage sales for Tenders and other Bespoke projects</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>Object to manage tenders and bespoke projects</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunities_open_total__c</fullName>
        <description>Total value of all open opportunities related to this project</description>
        <inlineHelpText>This value includes all expenses and additional costs</inlineHelpText>
        <label>Opportunities open total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunities_won_total__c</fullName>
        <description>Total value of all won opportunities related to this project</description>
        <inlineHelpText>This value includes all expenses and additional costs</inlineHelpText>
        <label>Opportunities won total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestOpportunityRollup.cls
/**
 * Test Class: TestOpportunityRollup
 *
 * Tests for the OpportunityRollup class
 *
 **/
@isTest
private class TestOpportunityRollup {
	
	/**
 	 * Test the opportunity rollup class create
	 * new account and a number of opportunities
	 * Call the rollup class and verify that all
	 * opportunities have been included in totals
	 **/	
	static testMethod void testOpportunityRollup()
	{
		Account account = new Account(
			name = 'testAcount');
		insert account;
		
		Project__c project = new Project__c();
		project.Account__c = account.Id;
		insert project;
		
		Opportunity opportunity = new Opportunity(
			Name = 'testOpportunity',
			AccountId = account.Id,
			StageName = 'Qualifying',
			CloseDate = Date.today());
			
			opportunity.Project__c = project.Id;
			opportunity.Amount = 10;
		insert opportunity;
		
		Opportunity opportunity2 = new Opportunity(
			Name = 'testOpportunity',
			AccountId = account.Id,
			StageName = 'Won',
			CloseDate = Date.today());
			
			opportunity2.Project__c = project.Id;
		
		opportunity2.Amount = 20;
		insert opportunity2;
		
		Opportunity opportunity3 = new Opportunity(
			Name = 'testOpportunity',
			AccountId = account.Id,
			StageName = 'Negotiation',
			CloseDate = Date.today());
			
			opportunity3.Project__c = project.Id;
		
		opportunity3.Amount = 100;
		insert opportunity3;
		
		System.debug('** inserted opp: ' + opportunity3.Id);
		
		OpportunityRollup.rollUpOpportunityValue(opportunity2);
		
		Project__c updatedProject = [select Opportunities_open_total__c, Opportunities_won_total__c
			from Project__c where Id =: project.Id];
		
		System.assertEquals(Decimal.valueOf(110), updatedProject.Opportunities_open_total__c);
		System.assertEquals(Decimal.valueOf(20), updatedProject.Opportunities_won_total__c);
	}

}