src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Charge_Day_1__c</fullName>
        <defaultValue>99</defaultValue>
        <description>Minimum number of days at which Fee 1 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 1 will be charged</inlineHelpText>
        <label>Cancellation Charge Day 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Day_2__c</fullName>
        <defaultValue>60</defaultValue>
        <description>Minimum number of days at which Fee 2 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 2 will be charged</inlineHelpText>
        <label>Cancellation Charge Day 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Day_3__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Minimum number of days at which Fee 3 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 3 will be charged</inlineHelpText>
        <label>Cancellation Charge Day 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_1__c</fullName>
        <defaultValue>0.3</defaultValue>
        <description>Percentage for calculating Cancellation fee (lowest rate)</description>
        <inlineHelpText>Lowest percentage for calculating cancellation fee - will apply if cancellation takes place before Days 1</inlineHelpText>
        <label>Cancellation Charge Fee 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_2__c</fullName>
        <defaultValue>0.3</defaultValue>
        <description>Percentage for calculating cancellation fee</description>
        <inlineHelpText>Percentage for calculating cancellation fee - will apply if cancellation takes place after Days 1 and before Days 2</inlineHelpText>
        <label>Cancellation Charge Fee 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_3__c</fullName>
        <defaultValue>0.3</defaultValue>
        <description>Percentage for calculating cancellation fee</description>
        <inlineHelpText>Percentage for calculating cancellation fee - will apply if cancellation takes place after Days 2 and before Days 3</inlineHelpText>
        <label>Cancellation Charge Fee 3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_1__c</fullName>
        <defaultValue>99</defaultValue>
        <description>Minimum number of days at which Fee 1 will be charged (the lowest rate)</description>
        <inlineHelpText>Minimum number of days at which Fee 1 will be charged (the lowest rate)</inlineHelpText>
        <label>Transfer Charge Day 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_2__c</fullName>
        <defaultValue>28</defaultValue>
        <description>Minimum number of days at which Fee 2 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 2 will be charged</inlineHelpText>
        <label>Transfer Charge Day 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_3__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Minimum number of days at which Fee 3 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 3 will be charged</inlineHelpText>
        <label>Transfer Charge Day 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_1__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee (lowest rate)</description>
        <inlineHelpText>Lowest percentage for calculating transfer fee - will apply if transfer takes place before Days 1</inlineHelpText>
        <label>Transfer Charge Fee 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_2__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 1 and before Days 2</inlineHelpText>
        <label>Transfer Charge Fee 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_3__c</fullName>
        <defaultValue>0.25</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 2 and before Days 3</inlineHelpText>
        <label>Transfer Charge Fee 3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_Final__c</fullName>
        <defaultValue>1.0</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 3</inlineHelpText>
        <label>Transfer Charge Fee Final</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Customer_Cancellation_Transfer_Date__c</fullName>
        <description>The date and time on which the customer asked for the transfer or cancellation.</description>
        <inlineHelpText>The date and time on which the customer asked for the transfer or cancellation.</inlineHelpText>
        <label>Customer Cancellation/Transfer Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Notes__c</fullName>
        <inlineHelpText>Notes entered in the transfer and cancellation reason VF Component.</inlineHelpText>
        <label>Transfer / Cancellation Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Reason__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reason why the cancellation or transfer is taking place</description>
        <inlineHelpText>The reason why the cancellation or transfer is taking place</inlineHelpText>
        <label>Transfer &amp; Cancellation Reason</label>
        <referenceTo>Transfer_Cancellation_Reasons__c</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Customer_Cancellation_Transfer_Date__c</fullName>
        <description>The date and time on which the customer asked for the transfer or cancellation.</description>
        <inlineHelpText>The date and time on which the customer asked for the transfer or cancellation.</inlineHelpText>
        <label>Customer Cancellation/Transfer Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Pulls in the related event&apos;s start date</description>
        <formula>Special_Event__r.StartDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the related event&apos;s start date</inlineHelpText>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TnC_Event_Units__c</fullName>
        <label>TnC Event Units</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Fee__c</fullName>
        <description>Transfer / Cancellation Fees</description>
        <inlineHelpText>Transfer / Cancellation Fees</inlineHelpText>
        <label>Transfer / Cancellation Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Notes__c</fullName>
        <description>Notes entered in the transfer and cancellation reason VF Component.</description>
        <label>Transfer / Cancellation Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Reason__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer / Cancellation Reason</label>
        <referenceTo>Transfer_Cancellation_Reasons__c</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transfer_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for transferring public bookings to a new event. Auto populated when transferring a public booking.</description>
        <inlineHelpText>Used for transferring public bookings to a new event. Auto populated when transferring a public booking.</inlineHelpText>
        <label>Transfer to: Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (Transfer To)</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/tncPublicEventCancellationWrapper.cls
public class tncPublicEventCancellationWrapper{
	
    private double percentage = 0.30; // VS-TODO get the percentages from the product object rather than hardcode. page 58
    
    public boolean isSelected 	                {get; set;}
    public Special_Event_Booking__c booking		{get; set;}
    public double cancellationFee				{get; set;}
    public double cancellationFeeOriginal       {get; set;}
    public tncReasonData reasonData             {get; set;}
    public OpportunityLineItem oli              {get; set;}
    public string transferToId					{get; set;} 
    public string transferToName				{get; set;}
    public string StatusChanged				    {get; set;}
    public string oldBookingStatus				{get; set;}
    public id oldBookingTransferTo   			{get; set;}
    public string eventUnits 	    			{get; set;}
    public boolean feesToBeApplied              {get; set;}
    public double unitPrice                     {get{
        												if (oli == null ) {
                                                            return 0;
                                                        } else {
                                                            system.debug('opportunityLineItem.UnitPrice' + oli.UnitPrice);
                                                            return double.valueof(oli.UnitPrice);
                                                        }
    												}
                                                }
    
    public tncPublicEventCancellationWrapper(Special_Event_Booking__c booking){
        this.isSelected = false;
        this.booking = booking;
        this.cancellationFee = 0;
        this.oldBookingStatus = booking.Status__c;
        this.reasonData = new tncReasonData();
        if (booking.Transfer_To__c != null){
            transferToName = booking.Transfer_To__r.Name;
            transferToId = booking.Transfer_To__c;
            oldBookingTransferTo = booking.Transfer_To__c; 
        }
        
        if(booking.Customer_Cancellation_Transfer_Date__c != null){
            datetime dt = booking.Customer_Cancellation_Transfer_Date__c;
            this.reasonData.cancellationRequestedOn = dt.format('dd/MM/yyyy');
            this.reasonData.reasonId = booking.Transfer_Cancellation_Reason__c;
            this.reasonData.reason = booking.Transfer_Cancellation_Reason__r.Name;
            this.reasonData.reasonNote = booking.Transfer_Cancellation_Notes__c;
            this.cancellationFeeOriginal = booking.Transfer_Cancellation_Fee__c;
        }
        
        this.eventUnits = booking.TnC_Event_Units__c;
        this.transferToId = booking.Transfer_to__c;
    }
    
    
        /*
     * Calculates cancellation fees for the selected event
    */
    public double processTransferFee(){
        
        if (feesToBeApplied){
            if (booking.Status__c != 'Provisional'){
                
                double daysBetween = date.parse(reasonData.cancellationRequestedOn).daysBetween(booking.Event_Start_Date__c);
            	
            	
            	
                if (daysBetween >= oli.PricebookEntry.Product2.Transfer_Charge_Day_1__c )
                    percentage = oli.PricebookEntry.Product2.Transfer_Charge_Fee_1__c;
                    
            	else if (daysBetween < oli.PricebookEntry.Product2.Transfer_Charge_Day_1__c &&
                         daysBetween >= oli.PricebookEntry.Product2.Transfer_Charge_Day_2__c)
                     percentage = oli.PricebookEntry.Product2.Transfer_Charge_Fee_2__c;

            	else if (daysBetween < oli.PricebookEntry.Product2.Transfer_Charge_Day_2__c &&
                         daysBetween >= oli.PricebookEntry.Product2.Transfer_Charge_Day_3__c)
            	    percentage = oli.PricebookEntry.Product2.Transfer_Charge_Fee_3__c;
                
                else
            		percentage = oli.PricebookEntry.Product2.Transfer_Charge_Fee_Final__c;

                system.debug('daysBetween/unitPrice/percentage: ' + daysBetween +'/' + unitPrice+'/'+percentage);

            		
            	cancellationFee = unitPrice * (percentage/100);
       
            } else if (booking.Status__c == 'Provisional'){
                cancellationFee = 0;
            }
            
            cancellationFee =  decimal.valueof( cancellationFee ).setScale(2);
            cancellationFeeOriginal = cancellationFee;
        } else {
            cancellationFeeOriginal = 0;
            cancellationFee = 0;
        }
        return cancellationFee;
    }
    
    
    /*
     * Calculates cancellation fees for the selected event
    */
    public double processCancellationFee(){
        
        if (feesToBeApplied){
            if (booking.Status__c != 'Provisional'){
                
                double daysBetween = date.parse(reasonData.cancellationRequestedOn).daysBetween(booking.Event_Start_Date__c);
            	
                if (daysBetween >= oli.PricebookEntry.Product2.Cancellation_Charge_Day_1__c )
                    percentage = oli.PricebookEntry.Product2.Cancellation_Charge_Fee_1__c;
                    
            	else if (daysBetween < oli.PricebookEntry.Product2.Cancellation_Charge_Day_1__c &&
                         daysBetween >= oli.PricebookEntry.Product2.Cancellation_Charge_Day_2__c)
                     percentage = oli.PricebookEntry.Product2.Cancellation_Charge_Fee_2__c;

            	else if (daysBetween < oli.PricebookEntry.Product2.Cancellation_Charge_Day_2__c &&
                         daysBetween >= oli.PricebookEntry.Product2.Cancellation_Charge_Day_3__c)
            	    percentage = oli.PricebookEntry.Product2.Cancellation_Charge_Fee_3__c;

                else
            		percentage = oli.PricebookEntry.Product2.Cancellation_Charge_Fee_Final__c;

                system.debug('daysBetween/unitPrice/percentage: ' + daysBetween +'/' + unitPrice+'/'+percentage);

                cancellationFee = unitPrice * (percentage/100);
                
            } else if (booking.Status__c == 'Provisional'){
                cancellationFee = 0;
            }
            
            cancellationFee = decimal.valueof( cancellationFee ).setScale(2);
            cancellationFeeOriginal = cancellationFee;
        } else {
            cancellationFeeOriginal = 0;
            cancellationFee = 0;
        }
        return cancellationFee;
    }
    
}