src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Duration_Years__c</fullName>
        <description>add the corresponding number of years depending on the duration field</description>
        <formula>IF (TEXT(Duration__c) = &quot;1 Year&quot;,1,
(IF (TEXT(Duration__c) = &quot;2 Years&quot;,2,
(IF (TEXT(Duration__c) = &quot;3 Years&quot;,3,
(IF (TEXT(Duration__c) = &quot;100 Years&quot;,100,
0)))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>add the corresponding number of years depending on the duration field</inlineHelpText>
        <label>Duration (Years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to feed automatic generation of Subscriptions and Subscription Lines</description>
        <inlineHelpText>Should sales of this product generate Subscriptions and Subscription Lines?</inlineHelpText>
        <label>Subscription Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Voucher_product_codes__c</fullName>
        <inlineHelpText>The product codes used to create vouchers</inlineHelpText>
        <label>Voucher product codes</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Subscription</fullName>
        <active>true</active>
        <description>Record type for Memberships and other Subscription Products</description>
        <label>Subscription</label>
    </recordTypes>
</CustomObject>

src/objects/Site_Product__c.object
<CustomObject>
    <fields>
        <fullName>Previous_Site_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Site Product</label>
        <referenceTo>Site_Product__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product associated to this site product</description>
        <formula>Subscription_Line__r.Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Product associated to this site product</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Status__c</fullName>
        <description>Displays the Subscription Site Status, which will be the same as the Subscription Status, unless the Site is no longer active</description>
        <formula>IF( Subscription_Site__r.Cancelled__c =FALSE,
 TEXT( Subscription_Site__r.Subscription__r.Status__c),
&quot;Inactive&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the Subscription Site Status, which will be the same as the Subscription Status, unless the Site is no longer active</inlineHelpText>
        <label>Site Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Line__c</fullName>
        <description>Master Detail</description>
        <inlineHelpText>Subscription line associated with the site product</inlineHelpText>
        <label>Subscription Line</label>
        <referenceTo>Subscription_Line__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subscription site associated to this site product</description>
        <inlineHelpText>Lookup to Subscription Site</inlineHelpText>
        <label>Subscription Site</label>
        <referenceTo>Subscription_Site__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <description>Master detail</description>
        <inlineHelpText>Subscription associated with this site product</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site Product</label>
    <nameField>
        <displayFormat>SP-{0000000}</displayFormat>
        <label>Site Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to manage subscriptions (Memberships, Complywise Subscriptions and other ongoing product deliveries)</description>
    <fields>
        <fullName>Site_Product__c</fullName>
        <description>Total number of Site products on the subscription</description>
        <inlineHelpText>Total number of Site products on the subscription</inlineHelpText>
        <label>Site Products</label>
        <summaryForeignKey>Site_Product__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Subscription_Line__c</fullName>
        <description>The total number of subscription lines on the subscription</description>
        <inlineHelpText>The total number of subscription lines on the subscription.</inlineHelpText>
        <label>Subscription Lines</label>
        <summaryForeignKey>Subscription_Line__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Sub Ref: Current Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Line__c.object
<CustomObject>
    <description>Object to manage products / elements of a subscription</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_Quantity__c</fullName>
        <inlineHelpText>This displays the quantity that will renewed as part of the renewal process. If this is blank the current quantity is used.</inlineHelpText>
        <label>Renewal Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Subscription Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription_Site__c.object
<CustomObject>
    <description>Object to manage delivery of subscriptions to multiple sites</description>
    <fields>
        <fullName>Site_Status__c</fullName>
        <description>Populates site status from Subscription Status, unless the site is no longer active</description>
        <formula>IF( OR(Cancelled__c =TRUE, Active__c=FALSE),
 &quot;Inactive&quot;,
TEXT(Subscription__r.Status__c )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the same as the Subscription Status, unless the site is no longer active</inlineHelpText>
        <label>Site Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Voucher_Max_Qty__c</fullName>
        <defaultValue>100</defaultValue>
        <description>Maximum number of products that can be purchases with this voucher</description>
        <inlineHelpText>Enter the maximum number of products that can be purchases with this voucher</inlineHelpText>
        <label>Voucher Max Qty</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Voucher_Product_Codes__c</fullName>
        <description>Online product code</description>
        <inlineHelpText>Select product code for voucher</inlineHelpText>
        <label>Voucher Product Codes</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Voucher__c</fullName>
        <inlineHelpText>The voucher for the subscription site which is created when the site is current and active.</inlineHelpText>
        <label>Voucher</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Voucher_created_at__c</fullName>
        <inlineHelpText>The date and time at which the voucher was created</inlineHelpText>
        <label>Voucher created at</label>
        <type>DateTime</type>
    </fields>
    <label>Subscription Site</label>
    <nameField>
        <displayFormat>SS-{0000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubscriptionSiteTriggerMethods.cls
public with sharing class SubscriptionSiteTriggerMethods {

    /*
     * CONSTRUCTOR
     */
    public SubscriptionSiteTriggerMethods(){}
    
    /*
     * PUBLIC METHODS
     */

    /*
     * ACTIVATE SUBSCRIPTION SITE ACTIONS
     *
     * Update qty's for renewal on subline IDs
     */
    public static void activateSubSites(List<Subscription_Site__c> subSites){
        updateQtyOnSubLines(subSites, true);
    }

    /*
     * DEACTIVATE SUBSCRIPTION SITE ACTIONS
     *
     * Update qty's for renewal on subline IDs
     */
    public static void deactivateSubSites(List<Subscription_Site__c> subSites){
        updateQtyOnSubLines(subSites, false);
    }
    
    /*
     * UPDATE VOUCHER PRODUCT CODES & QUANTITY
     *
     * Updates the voucher products codes on the subscription site if the product attached to the site
     * has a voucher product code attached to it. 
     */
    public static void updateVoucherProdCodesAndQty(List<Subscription_Site__c> triggerSubSites, Boolean beforeTrigger){
    	
    	List<Subscription_Site__c> subSites = new List<Subscription_Site__c>();
    	for (Subscription_Site__c subSite : triggerSubSites){
    		if (subSite.Site_Status__c == 'Current' || subSite.Site_Status__c == 'Pending - Paid'){
    			subSites.add(subSite);
    		}
    	}
    	if (subSites.size() > 0){
	    	List<Subscription_Site__c> allSubSites = new List<Subscription_Site__c>([SELECT
	    											Id,
	    											Voucher_Product_Codes__c,
	    											Site_Status__c,
	    											(SELECT
	    												Id,
	    												Subscription_Line__r.Product__r.Voucher_product_codes__c,
	    												Subscription_Line__r.Product__r.Duration_Years__c,
	    												Subscription_Line__r.Product__r.Subscription_Product__c
	    												FROM
	    													Site_Products__r
	    												WHERE
	    													Subscription_Line__r.Product__r.Voucher_product_codes__c <> '' AND
	    													Subscription_Line__r.Product__r.Subscription_Product__c = True)
	    											FROM
	    												Subscription_Site__c
	    											WHERE
	    												Id IN :subSites]);
	    	
	    	for (Subscription_Site__c subSite : allSubSites){
	    		
				// Get site status based on trigger.new values not DB query
				String siteStatus = 'unknown';
	
				for (Subscription_Site__c singleSite : subSites){
	    			if (singleSite.id == subSite.id){
	    				siteStatus = singleSite.Site_Status__c;
	    			}
	    		}
	    		if (siteStatus == 'Current' || siteStatus == 'Pending - Paid'){
		    		String strVoucherProdCodes = '';
		    		Decimal decVoucherQty = 0;
	
		    		for (Site_Product__c subSiteProd : subSite.Site_Products__r){
		    			if (strVoucherProdCodes == ''){
		                	strVoucherProdCodes=subSiteProd.Subscription_Line__r.Product__r.Voucher_product_codes__c;
		                }else{
		                	strVoucherProdCodes=strVoucherProdCodes + ';' + subSiteProd.Subscription_Line__r.Product__r.Voucher_product_codes__c;
		    			}
		    			if (subSiteProd.Subscription_Line__r.Product__r.Subscription_Product__c == true){
			    			decVoucherQty = decVoucherQty+(subSiteProd.Subscription_Line__r.Product__r.Duration_Years__c*100);
		    			}
		    		}    		
		    		System.debug('prod codes: '+strVoucherProdCodes);
		    		subSite.Voucher_Product_Codes__c = strVoucherProdCodes;
		    		
		    		if (beforeTrigger){
			    		// find subsite in trigger list and update prodcodes
			    		for (Subscription_Site__c singleSite : subSites){
			    			if (singleSite.id == subSite.id){
			    				System.debug('found record');
			    				singleSite.Voucher_Product_Codes__c = strVoucherProdCodes;
			    				singleSite.Voucher_Max_Qty__c = decVoucherQty;
			    			}
			    		}
		    		}else{
		    			subSite.Voucher_Product_Codes__c = strVoucherProdCodes;
		    			subSite.Voucher_Max_Qty__c = decVoucherQty;
		    		}
	    		}
	    	}
	    	if (!beforeTrigger){
		    	update allSubSites;
	    	}
    	}
    }
    
    /*
     * PRIVATE METHODS
     */
     
    /*
     * UPDATE QTY ON SUB LINES
     *
     * When a site is deactivated or activated the subscription line renewal quantity needs to incremented or decremented.
     */
    private static void updateQtyOnSubLines(List<Subscription_Site__c> subSites, Boolean isChangedToActive){
        
        Map<Id, Decimal> subLineQty = new Map<Id, Decimal>();
        
        // Get Products the reated products for each sub site
        for(Subscription_Site__c subSite : [SELECT
                Id,
                (SELECT
                        Id,
                        Subscription__c,
                        Subscription_Line__c,
                        Subscription_Line__r.Quantity__c,
                        Subscription_Line__r.Renewal_Quantity__c
                    FROM
                        Site_Products__r)
            FROM
                Subscription_Site__c
            WHERE
                Id IN :subSites
            ]){
            
            for (Site_Product__c subSiteProd : subSite.Site_Products__r){
                // Add the initial qty to the map so that it can be manipulated.
                if(subLineQty.get(subSiteProd.Subscription_Line__c) == null){
                    System.debug('Sub not in map :: Add subscription line to map');
                    if (subSiteProd.Subscription_Line__r.Renewal_Quantity__c == null){
                        System.debug('Subscription line has no renewal quantity ('+subSiteProd.Subscription_Line__r.Renewal_Quantity__c+')');
                        subLineQty.put(subSiteProd.Subscription_Line__c, subSiteProd.Subscription_Line__r.Quantity__c);
                    }else{
                        System.debug('Subscription line has a renewal quantity ('+subSiteProd.Subscription_Line__r.Renewal_Quantity__c+')');
                        subLineQty.put(subSiteProd.Subscription_Line__c, subSiteProd.Subscription_Line__r.Renewal_Quantity__c);
                    }
                }
                
                // remove the record to re-add it with the new value.
                Decimal origRenewalQty = subLineQty.remove(subSiteProd.Subscription_Line__c);
    
                if (isChangedToActive){
                    subLineQty.put(subSiteProd.Subscription_Line__c,origRenewalQty+1);
                }else{
                    subLineQty.put(subSiteProd.Subscription_Line__c,origRenewalQty-1);
                }
            }
        }
        
        Set <Id> subLineIds = new Set<Id>();
        subLineIds = subLineQty.keySet();
        
        List<Subscription_Line__c> subLinesToUpd = new List<Subscription_Line__c>([SELECT 
                Id, 
                Renewal_Quantity__c
            FROM
                Subscription_Line__c
            WHERE
                Id IN :subLineIds
        ]);
        
        for(Subscription_Line__c subLine : subLinesToUpd){
            subLine.Renewal_Quantity__c = subLineQty.get(subLine.Id);
        }
        System.debug('Subscription Lines updating: '+subLinesToUpd);
        update subLinesToUpd;
    }
    
    /*
     * CREATE VOUCHER (with Sub Sites)
     *
     * Creates a voucher for the subscription site if the subscription site has a current subscription.
     *
     * @returns List<SubscriptionSite__c>  List of all sub sites that have had a voucher added to them.
     */
    public static List<Subscription_Site__c> createVoucher(List<Subscription_Site__c> subSites){
        
        System.debug('Voucher Creation Method');
        List<Subscription_Site__c> sitesUpdated = new List<Subscription_Site__c>();
        
        for(Subscription_Site__c subSite : SubSites){
            if (subSite.Site_Status__c == 'Current' || subSite.Site_Status__c == 'Pending - Paid'){
                if (subSite.Voucher__c == null){
                    System.debug('Creating Voucher');
                    subSite.Voucher__c = subSite.Name + Math.round(Math.random()*10000);
                    subSite.Voucher_created_at__c = System.now();
                    sitesUpdated.add(subSite);
                }else{
                    System.debug('Voucher Already created');
                    
                }
            }else{
                System.debug('Not creating voucher Subscription Site not \'Current\' yet.');
            }
        }
        return sitesUpdated;
    }
    
    /*
     * CREATE VOUCHER (with Subs)
     *
     * Creates vouchers for the subscription's sub sites if the subscription site status is current.
     *
     * @returns List<SubscriptionSite__c>  List of all sub sites that have had a voucher added to them.
     */
    public static List<Subscription_Site__c> createVoucher(List<Subscription__c> subs){
    
        List<Subscription_Site__c> subSites = new List<Subscription_Site__c>([SELECT
                Id,
                Site_Status__c,
                Voucher__c,
                Voucher_created_at__c,
                Name
            FROM
                Subscription_Site__c
            WHERE
                Subscription__c IN :subs
        ]);
        
        List<Subscription_Site__c> subSiteResults = createVoucher(subSites);
        return subSiteResults;
    }
    
    private static void updateQtyOnSubLines(List<Subscription__c> subs){
        
    }
    
}