src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Charge_Day_1__c</fullName>
        <defaultValue>99</defaultValue>
        <description>Minimum number of days at which Fee 1 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 1 will be charged</inlineHelpText>
        <label>Cancellation Charge Day 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Day_2__c</fullName>
        <defaultValue>60</defaultValue>
        <description>Minimum number of days at which Fee 2 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 2 will be charged</inlineHelpText>
        <label>Cancellation Charge Day 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Day_3__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Minimum number of days at which Fee 3 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 3 will be charged</inlineHelpText>
        <label>Cancellation Charge Day 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_1__c</fullName>
        <defaultValue>0.3</defaultValue>
        <description>Percentage for calculating Cancellation fee (lowest rate)</description>
        <inlineHelpText>Lowest percentage for calculating cancellation fee - will apply if cancellation takes place before Days 1</inlineHelpText>
        <label>Cancellation Charge Fee 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_2__c</fullName>
        <defaultValue>0.3</defaultValue>
        <description>Percentage for calculating cancellation fee</description>
        <inlineHelpText>Percentage for calculating cancellation fee - will apply if cancellation takes place after Days 1 and before Days 2</inlineHelpText>
        <label>Cancellation Charge Fee 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_3__c</fullName>
        <defaultValue>0.3</defaultValue>
        <description>Percentage for calculating cancellation fee</description>
        <inlineHelpText>Percentage for calculating cancellation fee - will apply if cancellation takes place after Days 2 and before Days 3</inlineHelpText>
        <label>Cancellation Charge Fee 3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cancellation_Charge_Fee_Final__c</fullName>
        <defaultValue>1.0</defaultValue>
        <description>Percentage for calculating cancellation fee</description>
        <inlineHelpText>Percentage for calculating cancellation fee - will apply if cancellation takes place after Days 3</inlineHelpText>
        <label>Cancellation Charge Fee Final</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_1__c</fullName>
        <defaultValue>99</defaultValue>
        <description>Minimum number of days at which Fee 1 will be charged (the lowest rate)</description>
        <inlineHelpText>Minimum number of days at which Fee 1 will be charged (the lowest rate)</inlineHelpText>
        <label>Transfer Charge Day 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_2__c</fullName>
        <defaultValue>28</defaultValue>
        <description>Minimum number of days at which Fee 2 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 2 will be charged</inlineHelpText>
        <label>Transfer Charge Day 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_3__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Minimum number of days at which Fee 3 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 3 will be charged</inlineHelpText>
        <label>Transfer Charge Day 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_1__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee (lowest rate)</description>
        <inlineHelpText>Lowest percentage for calculating transfer fee - will apply if transfer takes place before Days 1</inlineHelpText>
        <label>Transfer Charge Fee 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_2__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 1 and before Days 2</inlineHelpText>
        <label>Transfer Charge Fee 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_3__c</fullName>
        <defaultValue>0.25</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 2 and before Days 3</inlineHelpText>
        <label>Transfer Charge Fee 3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_Final__c</fullName>
        <defaultValue>1.0</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 3</inlineHelpText>
        <label>Transfer Charge Fee Final</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>BSC_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Liability__c</fullName>
        <formula>Total_Cost__c  *
(
   IF
   ( 
      NOW() &lt; Liability_1_Date__c, Liability_1_Percentage__c, 
      IF
      (
         AND(  NOW() &gt; Liability_1_Date__c, NOW() &lt;= Liability_2_Date__c
            ), Liability_2_Percentage__c,
         IF
         (
            AND( OR(NOW() &gt; Liability_1_Date__c, NOW() &gt; Liability_2_Date__c) , NOW() &lt;= Liability_3_Date__c
               ),Liability_3_Percentage__c, 0
         )
      )
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Liability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>PO Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Customer_Cancellation_Transfer_Date__c</fullName>
        <description>The date and time on which the customer asked for the transfer or cancellation.</description>
        <inlineHelpText>The date and time on which the customer asked for the transfer or cancellation.</inlineHelpText>
        <label>Customer Cancellation/Transfer Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Shows the stage of the event, which is a dependant pick list of the status field</description>
        <inlineHelpText>Shows the stage of the event, which is a dependant pick list of the status field</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when Special Event starts.</description>
        <inlineHelpText>Date when Special Event starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trainer_Fees__c</fullName>
        <description>total trainer fees by calculating the sum of the trainer fee from the related active event trainer</description>
        <inlineHelpText>total trainer fees by calculating the sum of the trainer fee from the related active event trainer</inlineHelpText>
        <label>Trainer Fees</label>
        <summarizedField>Special_Event_Trainer__c.Trainer_Fee__c</summarizedField>
        <summaryFilterItems>
            <field>Special_Event_Trainer__c.Type__c</field>
            <operation>equals</operation>
            <value>Active Trainer</value>
        </summaryFilterItems>
        <summaryForeignKey>Special_Event_Trainer__c.BSC_Event__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Notes__c</fullName>
        <inlineHelpText>Notes entered in the transfer and cancellation reason VF Component.</inlineHelpText>
        <label>Transfer / Cancellation Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Transfer_Cancellation_Reason__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The reason why the cancellation or transfer is taking place</description>
        <inlineHelpText>The reason why the cancellation or transfer is taking place</inlineHelpText>
        <label>Transfer &amp; Cancellation Reason</label>
        <referenceTo>Transfer_Cancellation_Reasons__c</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Transfer_Cancellation_Reasons__c.object
<CustomObject>
    <description>Reason for Transfer/Cancellation of bookings</description>
    <label>Transfer &amp; Cancellation Reason</label>
    <nameField>
        <label>Transfer &amp; Cancellation Reason</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfer &amp; Cancellation Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/tncEventsWrapper.cls
public class tncEventsWrapper{
    
    private double percentage = 0.30; // VS-TODO get the percentages from the product object rather than hardcode. page 58
    
    public double bscLiability                       {get;set;}
    public double cancellationFee                    {get;set;}
    public double transferFee                        {get;set;}
	public double cancellationFeeOriginal            {get;set;}    
    public double transferFeeOriginal                {get;set;}    
    public tncReasonData reasonData                  {get;set;}
    public boolean isSelected                        {get;set;}
    public Special_Event__c event                    {get;set;}
    public OpportunityLineItem opportunityLineItem   {get;set;}
    public string transferAction					 {get;set;} 
    public List<SelectOption> selectTransferAction	 {get;set;}
    public boolean feesToBeApplied            {get;set;}     
    
    public double unitPrice                          {get{
                                                            if (opportunityLineItem == null ) {
                                                            	return 0;
                                                            } else {
                                                            	return opportunityLineItem.UnitPrice;
                                                            }
                                                         }
                                                     }
    
    private string calledFrom                        {get;set;}
    
    /*
     * Constructor
    */
    public tncEventsWrapper(boolean isSelected, Special_Event__c event){
        this.isSelected = isSelected;
        this.event = event;
        this.reasonData = new tncReasonData();
        
        if (event.Customer_Cancellation_Transfer_Date__c != null){
            Datetime transferDate = event.Customer_Cancellation_Transfer_Date__c;
            this.reasonData.transferRequestedOn = transferDate.format('dd/MM/yyyy');
        
            this.reasonData.reason = event.Transfer_Cancellation_Reason__r.Name;
            this.reasonData.reasonNote = event.Transfer_Cancellation_Notes__c;
        }
        selectTransferAction = new List<SelectOption>();
        if (event.Status__c == 'To Be Transferred'){
            selectTransferAction.add(new SelectOption('Request Event', 'Request Event'));
        } else {
            selectTransferAction.add(new SelectOption('Select Action', 'Select Action'));
            selectTransferAction.add(new SelectOption('Request Event', 'Request Event'));
            selectTransferAction.add(new SelectOption('To be Transferred', 'To be Transferred'));
        }
        
    }
    
    /*
     * Calculates cancellation fees for the selected event
    */
    public double processCancellationFee(){
        transferFee = 0;
        calledFrom = 'Cancellation';
        
        if (feesToBeApplied){
            if (event.Stage__c != 'Provisional'){
            	double daysBetween = date.parse(reasonData.cancellationRequestedOn).daysBetween(event.StartDate__c);
            	
            	system.debug('daysBetween: ' + daysBetween);
            	
                if (daysBetween >= opportunityLineItem.PricebookEntry.Product2.Cancellation_Charge_Day_1__c )
                    percentage = opportunityLineItem.PricebookEntry.Product2.Cancellation_Charge_Fee_1__c;
                    
            	else if (daysBetween < opportunityLineItem.PricebookEntry.Product2.Cancellation_Charge_Day_1__c &&
                         daysBetween >= opportunityLineItem.PricebookEntry.Product2.Cancellation_Charge_Day_2__c)
                     percentage = opportunityLineItem.PricebookEntry.Product2.Cancellation_Charge_Fee_2__c;
                     
            	else if (daysBetween < opportunityLineItem.PricebookEntry.Product2.Cancellation_Charge_Day_2__c &&
                         daysBetween >= opportunityLineItem.PricebookEntry.Product2.Cancellation_Charge_Day_3__c)
            	    percentage = opportunityLineItem.PricebookEntry.Product2.Cancellation_Charge_Fee_3__c;

                else
            		percentage = opportunityLineItem.PricebookEntry.Product2.Cancellation_Charge_Fee_Final__c;
                
            	system.debug('daysBetween/unitPrice/percentage: ' + daysBetween +'/' + unitPrice+'/'+percentage);
            		
            	cancellationFee = unitPrice * (percentage/100);
            	
            } else if (event.Stage__c == 'Provisional'){
                cancellationFee = 0;
            }
            
            cancellationFee =  decimal.valueof( cancellationFee ).setScale(2);
            cancellationFeeOriginal = cancellationFee;
            
        } else {
            cancellationFeeOriginal = 0;
            cancellationFee = 0;
        }
        return cancellationFee;
    }
    
    /*
     * Calculates Transfer fees for the selected event
    */
    public double processTransferFee(){
        cancellationFee = 0;
        calledFrom = 'Transfer';
        
        if (feesToBeApplied){
	        if (event.Stage__c != 'Provisional'){
                
                double daysBetween = date.parse(reasonData.transferRequestedOn).daysBetween(event.StartDate__c);
            	
                if (daysBetween >= opportunityLineItem.PricebookEntry.Product2.Transfer_Charge_Day_1__c )
                    percentage = opportunityLineItem.PricebookEntry.Product2.Transfer_Charge_Fee_1__c;
                    
            	else if (daysBetween < opportunityLineItem.PricebookEntry.Product2.Transfer_Charge_Day_1__c &&
                         daysBetween >= opportunityLineItem.PricebookEntry.Product2.Transfer_Charge_Day_2__c)
                     percentage = opportunityLineItem.PricebookEntry.Product2.Transfer_Charge_Fee_2__c;
            	
            	else if (daysBetween < opportunityLineItem.PricebookEntry.Product2.Transfer_Charge_Day_2__c &&
                         daysBetween >= opportunityLineItem.PricebookEntry.Product2.Transfer_Charge_Day_3__c)
            	    percentage = opportunityLineItem.PricebookEntry.Product2.Transfer_Charge_Fee_3__c;
                
                else
            		percentage = opportunityLineItem.PricebookEntry.Product2.Transfer_Charge_Fee_Final__c;

            	system.debug('daysBetween/unitPrice/percentage: ' + daysBetween +'/' + unitPrice+'/'+percentage);
                
            	transferFee = unitPrice * (percentage/100);
                
	        } else if (event.Stage__c == 'Provisional'){
	            transferFee = 0;
	        }
            
            transferFee = decimal.valueof( transferFee ).setScale(2);
	        transferFeeOriginal = transferFee;
            
        } else {
            transferFee = 0;
            transferFeeOriginal = 0;
        }
        
        return transferFee;
    }
    
    /* 
     * Calculates BSC Liability for the selected event
    */
    public void processBSCLiability(){
        double liability = 0;
        double trainerFees = 0;
        bscLiability = 0;
        for (Purchase_Order__c order : event.purchase_orders__r){
            liability = liability + order.Current_Liability__c;
        }
        integer timeLeft;
        if (calledFrom == 'Cancellation'){
        	timeLeft = date.parse(reasonData.cancellationRequestedOn).daysBetween(event.StartDate__c);
        } else {
        	timeLeft = date.parse(reasonData.transferRequestedOn).daysBetween(event.StartDate__c);
        }
        
        if (timeleft < 14){
            trainerFees = event.Trainer_Fees__c;
        } else if(timeleft > 14){
            trainerFees = event.Trainer_Fees__c * 0.50;
        } 
        system.debug('transfer fee2 : ' + transferFee);
        system.debug('calledFrom '+ calledFrom);
        system.debug('transferfee: ' + (calledFrom != 'Transfer'? 0 : (transferFee * 0.10)));
        bscLiability = liability + trainerFees + 
            		   (calledFrom != 'Cancellation' ? 0 : (cancellationFee * 0.10)) + 
            		   (calledFrom != 'Transfer'? 0 : (transferFee * 0.10))  ;
    }
    

}