src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Allows_Provisional_Bookings__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Ticking this box allows provisional bookings to be made through the Coursefinder page. (I.e. tick this on public events.)</inlineHelpText>
        <label>Allows Provisional Bookings</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_1__c</fullName>
        <defaultValue>99</defaultValue>
        <description>Minimum number of days at which Fee 1 will be charged (the lowest rate)</description>
        <inlineHelpText>Minimum number of days at which Fee 1 will be charged (the lowest rate)</inlineHelpText>
        <label>Transfer Charge Day 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_2__c</fullName>
        <defaultValue>28</defaultValue>
        <description>Minimum number of days at which Fee 2 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 2 will be charged</inlineHelpText>
        <label>Transfer Charge Day 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Day_3__c</fullName>
        <defaultValue>14</defaultValue>
        <description>Minimum number of days at which Fee 3 will be charged</description>
        <inlineHelpText>Minimum number of days at which Fee 3 will be charged</inlineHelpText>
        <label>Transfer Charge Day 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_1__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee (lowest rate)</description>
        <inlineHelpText>Lowest percentage for calculating transfer fee - will apply if transfer takes place before Days 1</inlineHelpText>
        <label>Transfer Charge Fee 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_2__c</fullName>
        <defaultValue>0.1</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 1 and before Days 2</inlineHelpText>
        <label>Transfer Charge Fee 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_3__c</fullName>
        <defaultValue>0.25</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 2 and before Days 3</inlineHelpText>
        <label>Transfer Charge Fee 3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transfer_Charge_Fee_Final__c</fullName>
        <defaultValue>1.0</defaultValue>
        <description>Percentage for calculating transfer fee</description>
        <inlineHelpText>Percentage for calculating transfer fee - will apply if transfer takes place after Days 3</inlineHelpText>
        <label>Transfer Charge Fee Final</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Record type for Training (Public and In-Company), Audit, and Advisory</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>City__c</fullName>
        <description>Select the city that the event will be taking place</description>
        <inlineHelpText>Select the city that the event will be taking place</inlineHelpText>
        <label>City</label>
        <picklist>
            <picklistValues>
                <fullName>Aberdeen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birmingham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bristol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crawley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dundee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edinburgh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exeter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huntingdon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sheffield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stirling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when Special Event starts.</description>
        <inlineHelpText>Date when Special Event starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>OPL_ID__c</fullName>
        <description>18 digit opportunity product line id that the event booking relates to</description>
        <externalId>true</externalId>
        <inlineHelpText>18 digit opportunity product line id that the event booking relates to</inlineHelpText>
        <label>OPL ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transfer_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for transferring public bookings to a new event. Auto populated when transferring a public booking.</description>
        <inlineHelpText>Used for transferring public bookings to a new event. Auto populated when transferring a public booking.</inlineHelpText>
        <label>Transfer to: Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (Transfer To)</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transferred_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field indicates the subsequent booking if a booking is transferred</description>
        <inlineHelpText>This field indicates the subsequent booking if a booking is transferred</inlineHelpText>
        <label>Transferred to: Booking</label>
        <referenceTo>Special_Event_Booking__c</referenceTo>
        <relationshipLabel>Subsequent Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CourseFinderWizardController.cls
/*
	Created by Ben Mansfield 12 July 2010
	Modified by Ben Mansfield 4 August 2010
	
	Description:
	
	Changes:
		
		4 August 2010
		* Opportunity stages added to list of permitted Opportunity states 
			(previously only when opportunity is closed and won)
		
*/
public with sharing class CourseFinderWizardController {
	
	public Opportunity record { get; private set; }
	
	public Boolean enableBookings { get; private set; }
	
	public CourseFinderWizardController(ApexPages.StandardController controller)
	{
		enableBookings = false;
		
		record = getOpportunity(controller.getId());
		if (record != null && isInPermittedStage(record) && hasPublicCourses(record))
		{
			enableBookings = true;
		}
	}
	
	private Opportunity getOpportunity(Id id)
	{
		// brm - 19 July 2010 - added unit price to query so it can be used to work out booking fees
		List<Opportunity> oppQuery = [Select Id, Name, IsWon, IsClosed, StageName, AccountId, 
											(Select Id, PricebookEntry.Product2.Name, 
											PricebookEntry.Product2.Allows_Provisional_Bookings__c, Quantity, 
											UnitPrice From OpportunityLineItems) , (select id, opl_id__c from BSC_Event_Bookings__r)
										From Opportunity Where Id = :id];
										
		if (oppQuery.size() == 1) return oppQuery.get(0);
		
		return null;
	}
	
	private Boolean hasPublicCourses(Opportunity target)
	{
		if (target != null)
		{
			for (OpportunityLineItem oli : target.OpportunityLineItems)
			{
				if (oli.PricebookEntry.Product2.Allows_Provisional_Bookings__c) return true;
			}
		}
		
		return false;
	}
	
	private Boolean isInPermittedStage(Opportunity target)
	{
		// brm - 4 August 2010 - old way of permitting opportunities
		//return target.IsWon && target.IsClosed;
		
		// brm - 4 August 2010 - new way of permitting opportunities - based on opportunity stages
		return target.StageName == 'Quote/Proposal' || target.StageName == 'Negotiation' || 
				target.StageName == 'Booking Received' || target.StageName == 'Won';
	}
	
	public PageReference backToOpp()
	{
		return new PageReference('/' + record.Id);
	}
	
	@IsTest
	private static void test()
	{
		Opportunity opp = new Opportunity();
		opp.Name = 'Test Opp';
		opp.StageName = 'Closed Won';
		opp.CloseDate = System.today();
		insert opp;
		
		Product2 prod = new Product2();
		prod.Name = 'Test Event Product';
		prod.Allows_Provisional_Bookings__c = true;
		prod.Transfer_Charge_Day_1__c = 10;
		prod.Transfer_Charge_Day_2__c = 5;
		prod.Transfer_Charge_Day_3__c = 2;
		
		prod.Transfer_Charge_Fee_1__c = 120;
		prod.Transfer_Charge_Fee_2__c = 60;
		prod.Transfer_Charge_Fee_3__c = 40;
		prod.Transfer_Charge_Fee_Final__c = 10;
		insert prod;
		
		Special_Event__c event = new Special_Event__c();
		event.Product__c = prod.Id;
		event.City__c = 'London';
		event.StartDate__c = System.today().addDays(3);
		insert event;
		
		ApexPages.Standardcontroller stdContr = new ApexPages.Standardcontroller(opp);
		CourseFinderWizardController controller = new CourseFinderWizardController(stdContr);
	}
}