src/objects/Project__c.object
<CustomObject>
    <description>Object to manage tenders and bespoke projects</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Viability Review</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Proposal Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQQ Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Proposal Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQQ Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation of Initial Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Proposal Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bid Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Proposal Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bid Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiaion of Final Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Further Requirements Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Further Requirements Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualifying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Positioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiating Terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot/Taster Session Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn by BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn by Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Framework/Call Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Populates related subscription site account name + postcode</description>
        <formula>Subscription_Site__r.Site_Account__r.Name + &quot;, &quot; +  Subscription_Site__r.Site_Account__r.Principle_Address_ZIP_Postal_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Auto populated by site account plus postcode</inlineHelpText>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product associated to this site product</description>
        <formula>Subscription_Line__r.Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Product associated to this site product</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Product_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If the Product should NOT go to the Subscription Site Contact, but instead to a different Contact, select that Contact here</inlineHelpText>
        <label>Site Product Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Site Products (there may be others  via Subscription Sites)</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Line__c</fullName>
        <description>Master Detail</description>
        <inlineHelpText>Subscription line associated with the site product</inlineHelpText>
        <label>Subscription Line</label>
        <referenceTo>Subscription_Line__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subscription site associated to this site product</description>
        <inlineHelpText>Lookup to Subscription Site</inlineHelpText>
        <label>Subscription Site</label>
        <referenceTo>Subscription_Site__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <description>Master detail</description>
        <inlineHelpText>Subscription associated with this site product</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Site Products</relationshipLabel>
        <relationshipName>Site_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site Product</label>
    <nameField>
        <displayFormat>SP-{0000000}</displayFormat>
        <label>Site Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to manage subscriptions (Memberships, Complywise Subscriptions and other ongoing product deliveries)</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The primary contact for this subscription</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Product__c</fullName>
        <description>Total number of Site products on the subscription</description>
        <inlineHelpText>Total number of Site products on the subscription</inlineHelpText>
        <label>Site Products</label>
        <summaryForeignKey>Site_Product__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending - Not Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Not Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Renewing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Cancelling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapsing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapse Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Manual Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription_Line__c</fullName>
        <description>The total number of subscription lines on the subscription</description>
        <inlineHelpText>The total number of subscription lines on the subscription.</inlineHelpText>
        <label>Subscription Lines</label>
        <summaryForeignKey>Subscription_Line__c.Subscription__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Sub Ref: Current Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription_Line__c.object
<CustomObject>
    <description>Object to manage products / elements of a subscription</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Available__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Available</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscription Lines</relationshipLabel>
        <relationshipName>Subscription_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subscription Line</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Subscription Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription_Site__c.object
<CustomObject>
    <description>Object to manage delivery of subscriptions to multiple sites</description>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipName>Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Site Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Site Subsidiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription Site</label>
    <nameField>
        <displayFormat>SS-{0000000}</displayFormat>
        <label>Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAccountMemberCheck.cls
@isTest
private class TestAccountMemberCheck {

    static testMethod void testAccountMemberUpdate() {
        Account account = new Account(
			name = 'testAcount');
		insert account;
		
		Contact cont = new Contact ();
        cont.FirstName = 'TestFN';
        cont.LastName = 'TestLN';
        cont.Accountid = account.id;
        insert cont;
        
		/*
		Project__c project = new Project__c();
		project.Account__c = account.Id;
		insert project;
		*/
		
	
		Subscription__c subs = new Subscription__c();
		subs.Name = '2013';
		subs.Status__c = 'Current';
		subs.Account_Name__c = account.id;
		subs.CurrencyIsoCode = 'GBP';
		subs.Type__c = 'New';
		subs.Contact__c = cont.id;
		insert subs;
		
		/*Subscription__c subs = [select Id, Status__c from 
			Subscription__c where Status__c like 'Current%' limit 1];*/
		
		Subscription_Site__c site = new Subscription_Site__c();
		site.Subscription__c = subs.Id;		
		insert site;
		
		// CREATE SUBSCRIPTION LINE HERE
		Subscription_Line__c sline = new Subscription_Line__c();
		sline.Subscription__c = subs.id;
		sline.CurrencyIsoCode = 'GBP';
		sline.Product__c = [select id from Product2 where name = '1 Year Subscription Module - Tools (1 to 5 Sites)'].id;
		sline.Quantity__c = 1;
		sline.Quantity_Available__c = 0;
		insert sline;
		
		Site_Product__c prod  = new Site_Product__c();
		prod.Subscription_Site__c = site.id;
		prod.Subscription__c = subs.Id;
		prod.Subscription_Line__c = sline.id;
		prod.Site_Product_Contact__c = cont.id;
		
		/*Site_Product__c prod = [select Id, Membership_Product__c
		from Site_Product__c where Membership_Product__c = 'true' limit 1];
		*/
		
		prod.Subscription_Site__c = site.id;
		subs.Account_Name__c = account.Id;
		site.Site_Account__c = account.Id;
		
		update subs;
		update site;
		
		Set<Id> accsToUpdate = new Set<Id>();
		accsToUpdate.add(account.Id);
		AccountMemberCheck.setAccountMemberFlagByAcc(accsToUpdate);
		
    }
}