src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit__c.object
<CustomObject>
    <description>Object to manage Units of an event, e.g. sessions or components</description>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>Related event</description>
        <inlineHelpText>Related event</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Units</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BSC Event Unit</label>
    <nameField>
        <label>Event Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Event Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event Unit (Session or component)</description>
    <fields>
        <fullName>Event_Booking__c</fullName>
        <description>Lookup to the related event booking</description>
        <inlineHelpText>Lookup to the related event booking</inlineHelpText>
        <label>Event Booking</label>
        <referenceTo>Special_Event_Booking__c</referenceTo>
        <relationshipLabel>BSC Event Unit Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Unit_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related event unit</description>
        <inlineHelpText>Lookup to the related event unit</inlineHelpText>
        <label>Event Unit</label>
        <referenceTo>Special_Event_Unit__c</referenceTo>
        <relationshipLabel>BSC Event Unit Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Unit_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Unit Booking</label>
    <nameField>
        <displayFormat>EUB-{0000000}</displayFormat>
        <label>Event Unit Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Unit Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BSCEventUnitBookingUpdate.cls
public with sharing class BSCEventUnitBookingUpdate
/*
This Class will allow us to update the BSC Event Unit Booking to the correct Unit
*/
{
	public static void updateBscEventUnitBooking(List<Special_Event_Unit_Booking__c> seub)
	{
		//List<Special_Event_Unit_Booking__c> seub = [SELECT Event_Unit__r.special_event__c, Event_Unit__r.name, Event_Booking__r.special_event__c FROM Special_Event_Unit_Booking__c];
		for(Special_Event_Unit_Booking__c s: seub)
		{
			if(s.Event_Unit__r.special_event__c!=s.Event_Booking__r.special_event__c)
			{
				try
				{
					Special_Event_Unit__c seu = [Select id From Special_Event_Unit__c Where Special_Event__c = :s.Event_Booking__r.special_event__c and name=:s.Event_Unit__r.name limit 1];
					s.Event_Unit__c = seu.id;
				}
				catch (QueryException Q1)
				{
					// Do Nothing
				}
				catch (Exception e)
				{
					
				}
				
			}
		}
		if(seub.size()>0)
			update seub;
	}

}