src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Allow_Overbooking__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked the number of confirmed bookings can exceed the maximum delegates</description>
        <inlineHelpText>If ticked the number of confirmed bookings can exceed the maximum delegates</inlineHelpText>
        <label>Allow Overbooking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Alternative_Certificate_Course_Name__c</fullName>
        <description>This is a text field that can be edited by logistics</description>
        <inlineHelpText>This is a text field that can be edited by logistics</inlineHelpText>
        <label>Alternative Certificate Course Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Select the city that the event will be taking place</description>
        <inlineHelpText>Select the city that the event will be taking place</inlineHelpText>
        <label>City</label>
        <picklist>
            <picklistValues>
                <fullName>Aberdeen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birmingham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bristol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crawley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dundee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edinburgh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exeter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huntingdon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sheffield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stirling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Courier_Costs__c</fullName>
        <defaultValue>50.00</defaultValue>
        <description>Courier costs for event</description>
        <inlineHelpText>Courier costs for event</inlineHelpText>
        <label>Courier Costs</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Course_Note_Costs__c</fullName>
        <description>Costs (per delegate) for the course notes</description>
        <inlineHelpText>Costs (per delegate) for the course notes</inlineHelpText>
        <label>Course Note Costs</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Course_Reference__c</fullName>
        <description>Mapped from Course_Ref in the source Course table in CB</description>
        <inlineHelpText>Course_Ref migrated from Course Booker</inlineHelpText>
        <label>Course Reference</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delegate_Pack_Costs__c</fullName>
        <description>Cost (per delegate) for the delegate pack</description>
        <inlineHelpText>Cost (per delegate) for the delegate pack</inlineHelpText>
        <label>Delegate Pack Costs</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event_Notes__c</fullName>
        <description>Any notes that are relevant to the event</description>
        <inlineHelpText>Any notes that are relevant to the event</inlineHelpText>
        <label>Event Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>International__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether an event is international (outside the UK)</description>
        <inlineHelpText>Auto populated by venue region</inlineHelpText>
        <label>International</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maximum_Places__c</fullName>
        <description>This is pulled from the maximum attendees held on the product when the event is first saved.</description>
        <inlineHelpText>Number of places available for Delegates at the Venue - i.e. maximum allowable Delegate acceptances.</inlineHelpText>
        <label>Maximum Places</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Places__c</fullName>
        <description>This is pulled from the minimum attendees held on the product when the event is first saved.</description>
        <inlineHelpText>Shows the minimum number of delegates to allow the course to go ahead.</inlineHelpText>
        <label>Minimum Places</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue_Code__c</fullName>
        <description>This is the Revenue Code for the BSC Event</description>
        <inlineHelpText>This is the Revenue Code for the BSC Event</inlineHelpText>
        <label>Revenue Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Shows the stage of the event, which is a dependant pick list of the status field</description>
        <inlineHelpText>Shows the stage of the event, which is a dependant pick list of the status field</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Contribution_Event__c</fullName>
        <description>The Target Contribution for the event (populated automatically from the product if left blank)</description>
        <inlineHelpText>The Target Contribution for the event (populated automatically from the product if left blank)</inlineHelpText>
        <label>Target Contribution (Event)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Determines the type of event from a picklist</description>
        <inlineHelpText>Determine the type of event from the picklist</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advisory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Company Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NVQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Venue_Delegate_Day_Rate__c</fullName>
        <description>Add the cost of the venue per delegate per day</description>
        <inlineHelpText>Add the cost of the venue per delegate per day</inlineHelpText>
        <label>Venue Delegate Day Rate</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Venue_Flat_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Add the cost of the venue if not taking into account the number of delegates</description>
        <inlineHelpText>Add the cost of the venue if not taking into account the number of delegates</inlineHelpText>
        <label>Venue Flat Rate</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Venue in which the event is being held</description>
        <inlineHelpText>Select the event venue. For an In-company event held on company premises, select the account</inlineHelpText>
        <label>Venue</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Venue</value>
            </filterItems>
            <infoMessage>Search is limited to venues. Select &quot;Show all results&quot; to expand search to all organisations (for In-Company Events)</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events (Held in this Venue)</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit__c.object
<CustomObject>
    <description>Object to manage Units of an event, e.g. sessions or components</description>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>Related event</description>
        <inlineHelpText>Related event</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Units</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Venue_Delegate_Day_Rate__c</fullName>
        <description>Populates automatically from Account (Venue)</description>
        <inlineHelpText>Populates automatically from Account (Venue)</inlineHelpText>
        <label>Venue Delegate Day Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the Unit venue (if different from the Event venue)</description>
        <inlineHelpText>Select the Unit venue (if different from the Event venue)</inlineHelpText>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Units (Held in this Venue)</relationshipLabel>
        <relationshipName>BSC_Event_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Unit</label>
    <nameField>
        <label>Event Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Event Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CloneEvent.cls
public class CloneEvent {
    
    public id eventId {get; set;}
    public integer  numberOfDays  {get; set;}
    public datetime  startDate        {get; set;}
    
    public CloneEvent(ApexPages.StandardController controller) {
        Special_Event__c event1 = (Special_Event__c)controller.getRecord();
        system.debug(event1);
        eventId = event1.id;
    }
    
    public PageReference CloneRecord(){
        
        Special_Event__c event = database.query(Utilities.getCreatableFieldsSOQL('Special_Event__c') + ' where id = :eventId');

        Special_Event__c cloneEvent = new Special_Event__c();
        
        cloneEvent.Product__c = event.Product__c;
        cloneEvent.Type__c = event.Type__c;
        cloneEvent.Status__c = 'Confirmed';
        cloneEvent.Stage__c = 'Confirmed';
        cloneEvent.Alternative_Certificate_Course_Name__c = event.Alternative_Certificate_Course_Name__c;
        cloneEvent.Maximum_Places__c = event.Maximum_Places__c;
        cloneEvent.Minimum_Places__c = event.Minimum_Places__c;
        cloneEvent.Allow_Overbooking__c = event.Allow_Overbooking__c;
        cloneEvent.Venue__c = event.Venue__c;
        cloneEvent.City__c = event.City__c;
        cloneEvent.International__c = event.International__c;
        cloneEvent.Event_Notes__c = event.Event_Notes__c;
        cloneEvent.Courier_Costs__c = event.Courier_Costs__c;
        cloneEvent.Venue_Flat_Rate__c = event.Venue_Flat_Rate__c;
        cloneEvent.Delegate_Pack_Costs__c = event.Delegate_Pack_Costs__c;
        cloneEvent.Course_Note_Costs__c = event.Course_Note_Costs__c;
        cloneEvent.Venue_Delegate_Day_Rate__c = event.Venue_Delegate_Day_Rate__c;
        cloneEvent.Target_Contribution_Event__c = event.Target_Contribution_Event__c;
        cloneEvent.Course_Reference__c = event.Course_Reference__c;
        cloneEvent.Revenue_Code__c = event.Revenue_Code__c;
        cloneEvent.Private__c = event.Private__c;
        cloneEvent.Dimension_4__c = event.Dimension_4__c;

        // This part was added as cloneEvent.name was not populated before -- Rahul
        system.debug('cloneEvent - ' + cloneEvent);

        insert cloneEvent;

        Product2 prod = [SELECT Id, IsActive, ProductCode FROM Product2 where id = :event.Product__c][0];
        Special_Event__c b = [select Event_Auto_Number__c from Special_Event__c where id = :cloneEvent.id][0];
        cloneEvent.name = prod.ProductCode + '/' + b.Event_Auto_Number__c;

        system.debug('cloneEvent.name - ' + cloneEvent.name);
        update cloneEvent;
        system.debug('cloneEvent.name - ' + cloneEvent.name);
        // -- Rahul

        list<Special_Event_Unit__c> eventUnits = new list<Special_Event_Unit__c>();
        
        for (integer i=1; i<=numberOfDays ; i++){
            Special_Event_Unit__c eventUnit = new Special_Event_Unit__c();
            
            if (i == 1){
                eventUnit.Primary_c__c = true;
            }
            eventUnit.Special_Event__c = cloneEvent.Id;
            eventUnit.Name = 'Day ' + string.valueOf(i);
            eventUnit.Unit_Start_Time__c = startDate;
            eventUnit.Unit_End_Time__c = startDate.addHours(8);
            eventUnit.Venue__c = cloneEvent.Venue__c;
            startDate = startDate.addDays(1);
            
            if (startDate.format('E') == 'Sat')
                startDate = startDate.addDays(2);
            else if (startDate.format('E') == 'Sun') 
                startDate = startDate.addDays(1);
            
            system.debug('startDate.format(E): '+startDate.format('E'));
            
            eventUnits.add(eventUnit);
        }
        
        insert eventUnits;

        return new PageReference('/' + cloneEvent.Id);
    }
}