src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit__c.object
<CustomObject>
    <description>Object to manage Units of an event, e.g. sessions or components</description>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>Related event</description>
        <inlineHelpText>Related event</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Units</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BSC Event Unit</label>
    <nameField>
        <label>Event Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Event Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event Unit (Session or component)</description>
    <fields>
        <fullName>Event_Booking__c</fullName>
        <description>Lookup to the related event booking</description>
        <inlineHelpText>Lookup to the related event booking</inlineHelpText>
        <label>Event Booking</label>
        <referenceTo>Special_Event_Booking__c</referenceTo>
        <relationshipLabel>BSC Event Unit Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Unit_Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related event unit</description>
        <inlineHelpText>Lookup to the related event unit</inlineHelpText>
        <label>Event Unit</label>
        <referenceTo>Special_Event_Unit__c</referenceTo>
        <relationshipLabel>BSC Event Unit Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Unit_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Unit Booking</label>
    <nameField>
        <displayFormat>EUB-{0000000}</displayFormat>
        <label>Event Unit Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Unit Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchUpdateEventUnitBooking.cls
global class BatchUpdateEventUnitBooking implements Database.Batchable<sObject>
/*
  Batch Process to run BSC Event Unit Booking update
*/
{

    global final String Query;
    public List<Integer> maxLevel = new List<Integer>();
    public static boolean isTest = false;

    global BatchUpdateEventUnitBooking(Integer size)
    {
        if (isTest)
            Query = 'SELECT Event_Unit__r.special_event__c, Event_Unit__r.name, Event_Booking__r.special_event__c FROM Special_Event_Unit_Booking__c Where Event_Unit__c <> null and  Event_Booking__c <> null LIMIT ' + size;
        else
        {
            Query = 'SELECT Event_Unit__r.special_event__c, Event_Unit__r.name, Event_Booking__r.special_event__c FROM Special_Event_Unit_Booking__c Where Event_Unit__c <> null and  Event_Booking__c <> null LIMIT ' + size;
        }
            
    }

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Special_Event_Unit_Booking__c> scope)
    {
        BSCEventUnitBookingUpdate.updateBscEventUnitBooking(scope);
    }
    
    global void finish(Database.BatchableContext BC)
    {
        AsyncApexJob a = [
            SELECT
                Id,
                Status,
                NumberOfErrors,
                JobItemsProcessed,
                TotalJobItems,
                CreatedBy.Email
            FROM
                AsyncApexJob
            WHERE
                Id = : BC.getJobId()];
                
        String message = 'The batch Apex job processed ' + a.TotalJobItems + ' batches with '+
            a.NumberOfErrors + ' failures.';
        
        // Send an email to the Apex job's submitter notifying of job completion.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        // Email the current user regarding the completion of the process
        user getCurrentUser = [Select u.email from user u where u.id = :UserInfo.getUserId()];
        // system.debug(getCurrentUser.email);
        // String[] toAddresses = new String[] {a.CreatedBy.Email, getCurrentUser.email};
        String[] toAddresses = new String[] {a.CreatedBy.Email, 'it.helpdesk@britsafe.org'};
        mail.setToAddresses(toAddresses);
        mail.setSubject('BSCEventUnitBookingUpdate ' + a.Status);
        mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems + ' batches with '+ a.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });       
    }   

    public static testMethod void testBatchUpdateInvoice()
    {
        Test.startTest();
        BatchUpdateEventUnitBooking.isTest = true;
        BatchUpdateEventUnitBooking batch = new BatchUpdateEventUnitBooking(1);     
        Database.executeBatch(batch,1);
        Test.stopTest();
    }  
    
    


}