src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date when Special Event ends.</description>
        <inlineHelpText>Date when Special Event ends.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when Special Event starts.</description>
        <inlineHelpText>Date when Special Event starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit__c.object
<CustomObject>
    <description>Object to manage Units of an event, e.g. sessions or components</description>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>Related event</description>
        <inlineHelpText>Related event</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Units</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Travel_Day__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tick if the event unit is a travel day and shouldn&apos;t be included as part of the code to update the event start/end date</description>
        <inlineHelpText>Tick if the event unit is a travel day and shouldn&apos;t be included as part of the code to update the event start/end date</inlineHelpText>
        <label>Travel Day</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_End_Time__c</fullName>
        <description>Stores the End Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event.</description>
        <inlineHelpText>Stores the End Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event.</inlineHelpText>
        <label>Unit End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Unit_Start_Time__c</fullName>
        <description>Stores the Start Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event</description>
        <inlineHelpText>Stores the Start Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event</inlineHelpText>
        <label>Unit Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>BSC Event Unit</label>
    <nameField>
        <label>Event Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Event Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SpecialEventUnitTriggerMethods.cls
public with sharing class SpecialEventUnitTriggerMethods {

	/*
	 * SYNC EVENT START AND END DATES (Special_Event_Unit__c)
	 *
	 * Works out the unique events from the event units that have been updated and passes to
	 * method to do start & end date calculations.
	 */
	public static void syncEventStartEndDate(List<Special_Event_Unit__c> oldVals, List<Special_Event_Unit__c> newVals){
		
		Set<Id> events = new Set<Id>();
		
		// Loop over records and see if the start or end dates have changed. If so add it to the list of events to re-sync
		for (Integer i=0; oldVals.size() > i; i++){
			if ((oldVals[i].Travel_Day__c <> newVals[i].Travel_Day__c) || (oldVals[i].Unit_Start_Time__c <> newVals[i].Unit_Start_Time__c) || (oldVals[i].Unit_End_Time__c <> newVals[i].Unit_End_Time__c)){
				events.add(newVals[i].Special_Event__c);
			}
		}
		syncEventStartEndDate(events);
	}
	
	/*
	 * SYNC EVENT START AND END DATES (Special_Event__c)
	 *
	 * Works out the MAX(End_Date) and MIN(Start_Date) on the event units for a particular event
	 * and sets the value on the event.
	 */
	public static void syncEventStartEndDate(Set<Id> eventsToSync){
		
		// Empty list to hold events that need to be updated
		List<Special_Event__c> eventsToUpd = new List<Special_Event__c>();
		
		List<Special_Event__c> eventsList = new List<Special_Event__c>([SELECT Id,
																			StartDate__c,
																			EndDate__c,
																			(SELECT
																				Unit_Start_Time__c,
																				Unit_End_Time__c
																			FROM
																				Sessions__r
																			WHERE
																				Travel_day__c = false)
																		FROM
																			Special_Event__c
																		WHERE
																			Id IN :eventsToSync]);
		
		// Loop over events and work out the min and max for the start and end dates.
		for (Special_Event__c event : eventsList){
			
			Date startDate;
			Date endDate;
			
			for (Special_Event_Unit__c evtUnit : event.Sessions__r){
				if((evtUnit.Unit_Start_Time__c < startDate) || startDate == null){
					startDate = date.newinstance(evtUnit.Unit_Start_Time__c.year(), evtUnit.Unit_Start_Time__c.month(), evtUnit.Unit_Start_Time__c.day());
				}
				if((evtUnit.Unit_End_Time__c > endDate) || endDate == null){
					endDate = date.newinstance(evtUnit.Unit_End_Time__c.year(), evtUnit.Unit_End_Time__c.month(), evtUnit.Unit_End_Time__c.day());
				}
			}
			if ((startDate != null && (startDate <> event.StartDate__c)) || (endDate != null && (endDate <> event.EndDate__c))){
				//System.debug('FJP old start/end: '+event.StartDate__c+'/'+event.EndDate__c);
				//System.debug('FJP new start/end: '+startDate+'/'+endDate);
				event.StartDate__c = startDate;
				event.EndDate__c = endDate;
				eventsToUpd.add(event);
			}
		}
		if (eventsToUpd.size() > 0){
			update eventsToUpd;
		}
	}
}