src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Allow_Overbooking__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked the number of confirmed bookings can exceed the maximum delegates</description>
        <inlineHelpText>If ticked the number of confirmed bookings can exceed the maximum delegates</inlineHelpText>
        <label>Allow Overbooking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_places__c</fullName>
        <formula>Maximum_Places__c -  No_of_Delegates_Booked__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The number of places available (maximum places minus confirmed places)</inlineHelpText>
        <label>Available places</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Select the city that the event will be taking place</description>
        <inlineHelpText>Select the city that the event will be taking place</inlineHelpText>
        <label>City</label>
        <picklist>
            <picklistValues>
                <fullName>Aberdeen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birmingham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bristol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crawley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dundee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Durham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edinburgh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exeter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huntingdon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sheffield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stirling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Calculates the number of days the event takes place using the start and end dates (this doesn&apos;t take into account gaps between unit days or weekends)</description>
        <formula>EndDate__c -StartDate__c +1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Number of days from Start to Finish</inlineHelpText>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date when Special Event ends.</description>
        <inlineHelpText>Date when Special Event ends.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maximum_Places__c</fullName>
        <description>This is pulled from the maximum attendees held on the product when the event is first saved.</description>
        <inlineHelpText>Number of places available for Delegates at the Venue - i.e. maximum allowable Delegate acceptances.</inlineHelpText>
        <label>Maximum Places</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Places__c</fullName>
        <description>This is pulled from the minimum attendees held on the product when the event is first saved.</description>
        <inlineHelpText>Shows the minimum number of delegates to allow the course to go ahead.</inlineHelpText>
        <label>Minimum Places</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Delegates_Booked__c</fullName>
        <description>Roll up summary of the number of Event Booking objects linked to this event</description>
        <inlineHelpText>Count of Delegates who are: Confirmed, Attended, No Show</inlineHelpText>
        <label>Confirmed Bookings</label>
        <summaryFilterItems>
            <field>Special_Event_Booking__c.Status__c</field>
            <operation>equals</operation>
            <value>Confirmed, Attended, No Show</value>
        </summaryFilterItems>
        <summaryForeignKey>Special_Event_Booking__c.Special_Event__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when Special Event starts.</description>
        <inlineHelpText>Date when Special Event starts.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Venue in which the event is being held</description>
        <inlineHelpText>Select the event venue. For an In-company event held on company premises, select the account</inlineHelpText>
        <label>Venue</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Venue</value>
            </filterItems>
            <infoMessage>Search is limited to venues. Select &quot;Show all results&quot; to expand search to all organisations (for In-Company Events)</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Events (Held in this Venue)</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Event_Unit__c.object
<CustomObject>
    <description>Object to manage Units of an event, e.g. sessions or components</description>
    <fields>
        <fullName>Duration__c</fullName>
        <description>shows the duration of the event unit depending on the times of the unit and is calculated by a workflow</description>
        <inlineHelpText>Duration in Days (0.5 or 1), calculated by workflow</inlineHelpText>
        <label>Duration</label>
        <precision>2</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>Related event</description>
        <inlineHelpText>Related event</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Units</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Description__c</fullName>
        <description>Any text needed to describe or is relevant to the unit</description>
        <inlineHelpText>Any text needed to describe or is relevant to the unit</inlineHelpText>
        <label>Unit Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Unit_Start_Time__c</fullName>
        <description>Stores the Start Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event</description>
        <inlineHelpText>Stores the Start Date/Time of a BSC Event Unit or &apos;Session&apos; e.g. a Gala Dinner could be a BSC Event Unit of a BSC Event</inlineHelpText>
        <label>Unit Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the Unit venue (if different from the Event venue)</description>
        <inlineHelpText>Select the Unit venue (if different from the Event venue)</inlineHelpText>
        <label>Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Event Units (Held in this Venue)</relationshipLabel>
        <relationshipName>BSC_Event_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSC Event Unit</label>
    <nameField>
        <label>Event Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Event Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/tncTransferBookingController.cls
public class tncTransferBookingController{
    // Error messages   
    private static final String ERROR_MULTIPLE_EVENTS =         'Only one event can be selected when transferring a booking.';
    private static final String ERROR_SAME_EVENT_TRANSFER =     'You cannot transfer a booking to the same event.';
    private static final String ERROR_NO_EVENT_SELECTED =       'Please select at least one event.';
    private static final String ERROR_INVALID_UNK_DELEGATES =   'The Unknown Delegates field is not a valid number.';
    private static final String ERROR_NO_CONTACT_UNK_DELEGATE = 'Please select at least one contact or specify at least one unknown delegate.';
    private static final String ERROR_NO_EVT_SPACES_AVAILABLE = ' does not have enough space on the event. You cannot book that many delegates.';
    private static final String ERROR_SAME_EVENT_TRANSFER1 = 'One of the bookings you are attempting to transfer is currently booked on the Event selected, please select a different event / booking to transfer.';
    
    private Boolean requiresInit;
    
    public string eventstoExclude {get; set;}
    public string eventUnitString {get; set;}
    
    public string fieldName 	{get; set;}
    public Special_Event__c specialEvent {get;set;}
    public string bookingStatus{get;set;}
    // Used for booking
    public Opportunity opportunity                  { get; set { this.opportunity = value; if (requiresInit) initialise(); } }
    
    // Used for transfer
    public Special_Event_Booking__c booking         { get; set { this.booking = value; if (requiresInit) initialise(); } }
    
    public String bookingType                       { get; set { this.bookingType = value; if (requiresInit) initialise(); } }
    
    // Page 1
    public Special_Event__c eventCriteria           { get; set; }
    public String[] locationCriteria                { get; set; }
    
    public List<Product> productSelections          { get; set; }
    // transfer only
    public Boolean customerTransferRequest          { get; set; }
    
    // Page 2
    // booking
    public List<Product> eventSelectionsByProduct   { get; set; }
    // transfer
    public List<BSCEvent> eventSelections           { get; set; }
    
    // Page 3
    public List<BSCEvent> eventUnitSelections       { get; set; }
    
    // Page 4 - booking only
    public List<OpportunityContact> linkedContacts  { get; private set; }
    public String numberUnknownDelegates            { get; set; }
    
    
    public Integer pageNum                          { get; private set; }
    private final Integer maxPages = 4;
    
    public tncTransferBookingController()
    {
        eventUnitString = 'Test';
            
        requiresInit = true;
        locationCriteria = new String[] {};
        // Select all locations as default
        for (SelectOption so : getEventCityPicklistOptions())
        {
            locationCriteria.add(so.getValue());
        }
    }
    
    public void initialise()
    {
        // If the booking type is null, don't initialise yet
        if (bookingType == null)
            return;
        // If both opportunity and booking are null, don't initialise yet
        if (opportunity == null && booking == null)
            return;
        
        eventCriteria = new Special_Event__c(StartDate__c = System.today());
        if (bookingType == 'Transfer')
        {
            productSelections = null;
            linkedContacts = null;
            customerTransferRequest = true;
        }
        
        pageNum = 1;
        requiresInit = false;
    }
    

    
    private void generateBSCEvents()
    {
        Set<Id> productIds = new Set<Id>();
        if (bookingType == 'Transfer')
            productIds.add(booking.Special_Event__r.Product__c);
        
        List<Special_Event__c> selectedEvents = [
            SELECT
                Id,
                Name,
                Product__c,
                StartDate__c,
                EndDate__c,
                City__c,
                Maximum_Places__c,
                No_of_Delegates_Booked__c,
                Available_Places__c,
                Minimum_Places__c,
                Allow_Overbooking__c
            FROM
                Special_Event__c
            WHERE
                City__c in :locationCriteria
            AND
                Status__c ='Confirmed' 
            AND
                StartDate__c >= :eventCriteria.StartDate__c
            AND
                EndDate__c <= :eventCriteria.EndDate__c
            AND
                Product__c in :productIds];
        
        // Group events by products for bookings
        if (bookingType == 'Transfer')
        {
            eventSelections = new List<BSCEvent>();
            for (Special_Event__c bscEvent : selectedEvents)
            {
                if (eventCriteria.Maximum_Places__c == null ||
                    bscEvent.Maximum_Places__c == null ||
                    (bscEvent.Maximum_Places__c - bscEvent.No_of_Delegates_Booked__c) >= eventCriteria.Maximum_Places__c)
                {
                    eventSelections.add(new BSCEvent(bscEvent));
                }
            }
        }
    }
    
    private Boolean generateBSCEventUnits()
    {
        Set<Id> eventIds = new Set<Id>();
        
        if (bookingType == 'Transfer')
        {
            string eventName = '';
            for (BSCEvent e : eventSelections)
            {
                if (e.selected == true){
                    eventIds.add(e.record.Id);
                    eventName = e.record.Name;
                }
            }
            if (eventIds.size() > 1)
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, ERROR_MULTIPLE_EVENTS));
                return false;
            }
            if (eventIds.contains(booking.Special_Event__c))
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, ERROR_SAME_EVENT_TRANSFER));
                return false;
            }
            if (eventstoExclude.contains(eventName)){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, ERROR_SAME_EVENT_TRANSFER1));
                return false;
            }
        }
        if (eventIds.size() == 0)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, ERROR_NO_EVENT_SELECTED));
            return false;
        }
        
        List<Special_Event_Unit__c> selectedEventUnits = [
            SELECT
                Id,
                Name,
                Unit_Description__c,
                Venue__c,
                Unit_Start_Time__c,
                Duration__c,
                Special_Event__c
            FROM
                Special_Event_Unit__c
            WHERE
                Special_Event__c in :eventIds];
        
        eventUnitSelections = new List<BSCEvent>();
        if (bookingType == 'Transfer')
        {
            for (BSCEvent e : eventSelections)
            {
                if (e.selected == true)
                {
                    BSCEvent selected = new BSCEvent(e.record);
                    specialEvent = e.record;
                    selected.units = new List<BSCEventUnit>();
                    for (Special_Event_Unit__c bscEventUnit : selectedEventUnits)
                    {
                        if (bscEventUnit.Special_Event__c == e.record.Id)
                        {
                            selected.units.add(new BSCEventUnit(bscEventUnit));
                        }
                    }
                    eventUnitSelections.add(selected);
                }
            }
        }
        
        return true;
    }
    
    public SelectOption[] getEventCityPicklistOptions()
    {
        List<SelectOption> options = new List<SelectOption>();
        for (Schema.Picklistentry pe : Schema.SObjectType.Special_Event__c.fields.City__c.getPicklistValues())
        {
            if (pe.isActive())
                options.add(new SelectOption(pe.getValue(), pe.getLabel()));
        }
        return options;
    }
    
    public void next()
    {
        if (pageNum < maxPages) pageNum++;
        
        if (pageNum == 2)
        {
            generateBSCEvents();
        }
        else if (pageNum == 3)
        {
            Boolean success = generateBSCEventUnits();
            if (!success)
                pageNum--;
        }
    }
    
    public void prev()
    {
        if (pageNum > 1)
            pageNum--;
    }
    
    public void save()
    {
        if (bookingType == 'Transfer')
        {
            transferBooking();
        }
        
        //return cancel();
    }
     

    
    public void transferBooking()
    {
        system.debug('entering transferBooking');
        list<string> bookingList = fieldName.split(',');
         string units = '';
        for (BSCEvent event : eventUnitSelections)
        {
            for (BSCEventUnit unit : event.units)
            {
                if (unit.selected)
                {
                    units += unit.record.Id + ',';
                }
            }
        }
        eventUnitString = units;
        system.debug(eventUnitString);
        
        list<Special_Event_Booking__c> bookings = [select name from Special_Event_Booking__c where id in :bookingList];
        
        for (Special_Event_Booking__c bookingtoUpdate : bookings){
            bookingtoUpdate.Transfer_To__c = eventUnitSelections[0].record.Id;
            bookingtoUpdate.Customer_Requested_Transfer__c = customerTransferRequest;
            bookingtoUpdate.Status__c = 'To Be Transferred';
            bookingtoUpdate.TnC_Event_Units__c = units;
        }
        bookingStatus = 'To Be Transferred';
        update bookings;
        
        booking = bookings[0];
        
        system.debug('finished transferBooking');
    }
    
    public PageReference cancel()
    {
        if (opportunity != null)
            return new PageReference('/' + opportunity.Id);
        if (booking != null)
            return new PageReference('/' + booking.Id);
        
        return new PageReference('/home/home.jsp');
    }
    
    public class Product
    {
        public OpportunityLineItem record       { get; private set; }
        public Boolean selected                 { get; set; }
        
        public List<BSCEvent> events            { get; set; }
        
        public Product(OpportunityLineItem target)
        {
            this.record = target;
            this.selected = true;
        }
    }
    
    public class BSCEvent
    {
        public Special_Event__c record          { get; private set; }
        public Boolean selected                 { get; set; }
        
        public List<BSCEventUnit> units         { get; set; }
        
        public BSCEvent(Special_Event__c target)
        {
            this.record = target;
            this.selected = false;
        }
    }
    
    public class BSCEventUnit
    {
        public Special_Event_Unit__c record     { get; private set; }
        public Boolean selected                 { get; set; }
        
        public BSCEventUnit(Special_Event_Unit__c target)
        {
            this.record = target;
            this.selected = true;
        }
    }
    
    public class OpportunityContact
    {
        public OpportunityContactRole record    { get; private set; }
        public Boolean selected                 { get; set; }
        
        public OpportunityContact(OpportunityContactRole target)
        {
            this.record = target;
            this.selected = false;
        }
    }
}