src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is only for the In-Company events but is a lookup to the related opportunity</description>
        <inlineHelpText>This is only for the In-Company events but is a lookup to the related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related product</description>
        <inlineHelpText>Related product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>BSC Events</relationshipLabel>
        <relationshipName>BSC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event.</description>
        <inlineHelpText>Shows the status of the event.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Client Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timed Out (Sales Provisional)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred - Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Booking_Fee__c</fullName>
        <description>This is pulled from the opportunity product unit price for public an total price on the in-company primary for in-company</description>
        <inlineHelpText>The amount that should be charged for this booking. This is automatically updated, change this by updating the opportunity line.</inlineHelpText>
        <label>Booking Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to related opportunity</description>
        <inlineHelpText>Lookup field to related opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Pulls in the related events product name</description>
        <formula>Special_Event__r.Product__r.Name</formula>
        <inlineHelpText>Pulls in the related events product name</inlineHelpText>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the status of the event booking</description>
        <inlineHelpText>Shows the status of the event booking</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled - BSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Merit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended - Distinction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/testSplitOpportunity.cls
@isTest
private class testSplitOpportunity 
{

	private static string RandomString{
		get{
			return string.valueof(math.random()).substring(1,12);
		}
	}
	
    static testMethod void testSplitOpportunityMethod()
	{
		Pagereference pref=Page.SplitOpportunity ;
		Test.setCurrentPage(pref);
		
		// Create a New Account
		Account NewAccount=new Account();
		NewAccount.Name='TestSplitOpportunity' +RandomString;
		insert NewAccount;
		
		//Create a new Opportunity
		Opportunity NewOpp= new Opportunity(); 
		NewOpp.Name='TestSplitOpportunity' +RandomString;
		NewOpp.StageName='Qualifying';
		NewOpp.CloseDate=System.today();
		NewOpp.AccountId=NewAccount.Id;
		insert NewOpp;
		 
		//Create Product Line items 
		OpportunityLineItem NewOpportunityLineItem=new OpportunityLineItem();
		NewOpportunityLineItem.OpportunityId=NewOpp.id;
		NewOpportunityLineItem.Quantity=100;
		PricebookEntry PricebookEntryId=[Select Id,Product2Id From PricebookEntry WHERE IsActive = True limit 1];
		NewOpportunityLineItem.PricebookEntryId=PricebookEntryId.Id;
		Id ProductId=PricebookEntryId.Product2Id; 
		NewOpportunityLineItem.TotalPrice=100;
		insert NewOpportunityLineItem;			

		//Create Event for that Product
		Special_Event__c NewBSCEvent=new Special_Event__c();
		NewBSCEvent.Name='TestSplitOpportunity'+RandomString;
		NewBSCEvent.Opportunity__c=NewOpp.Id;
		NewBSCEvent.Status__c='Provisional';
		NewBSCEvent.Product__c=ProductId;
		Insert NewBSCEvent;
		
		//Create Event booking for that Event
		 Special_Event_Booking__c NewBSCEventBooking=new Special_Event_Booking__c();
		 NewBSCEventBooking.Special_Event__c=NewBSCEvent.Id;
		 NewBSCEventBooking.Status__c='Provisional';
		 NewBSCEventBooking.Opportunity__c=NewOpp.Id;
		 NewBSCEventBooking.Booking_Fee__c=100;
		 Insert NewBSCEventBooking;

		 Special_Event_Booking__c NewBSCEventBooking2=new Special_Event_Booking__c();
		 NewBSCEventBooking2.Special_Event__c=NewBSCEvent.Id;
		 NewBSCEventBooking2.Status__c='Confirmed';
		 NewBSCEventBooking2.Opportunity__c=NewOpp.Id;
		 NewBSCEventBooking2.Booking_Fee__c=100;
		 Insert NewBSCEventBooking2;		 
		  
		// get a Product id
		

		 // Construct the standard controller
		 Apexpages.Standardcontroller con= new Apexpages.Standardcontroller(NewOpp);
		 
		 //Create Custom controller
		 OpportunitySplitController ext=new OpportunitySplitController(con);
		 
		 // Switch to test context
    	 Test.startTest();
    	 
    	 Pagereference ref=ext.doAction();
    	 //PageReference redir = new PageReference('/' + ext. );
    	 
    	 Test.stopTest();
    }
}