src/objects/Special_Event__c.object
<CustomObject>
    <description>Object for managing Events</description>
    <label>BSC Event</label>
    <nameField>
        <label>BSC Event Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BSC Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Special_Event_Booking__c.object
<CustomObject>
    <description>Object to manage bookings to an event</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The name of the person attending the event as a delegate pulled from the contact</description>
        <inlineHelpText>The name of the person attending the event as a delegate</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>BSC Event Bookings</relationshipLabel>
        <relationshipName>BSC_Event_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Booking__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Signifies whether this booking is Primary or not..</description>
        <inlineHelpText>Signifies whether this booking is Primary or not..</inlineHelpText>
        <label>Primary Booking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Special_Event__c</fullName>
        <description>lookup to the event the event booking relates to</description>
        <inlineHelpText>lookup to the event the event booking relates to</inlineHelpText>
        <label>BSC Event</label>
        <referenceTo>Special_Event__c</referenceTo>
        <relationshipLabel>BSC Event Bookings (BSC Event)</relationshipLabel>
        <relationshipName>R00N50000001mIaiEAE</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BSC Event Booking</label>
    <nameField>
        <displayFormat>EB-{0000000}</displayFormat>
        <label>Event Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSC Event Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/clsContactsForTrainerEmail.cls
public class clsContactsForTrainerEmail{ 

    private List<special_event_booking__c> bookings;
    
    public id eventId {get;set;}
        
	public clsContactsForTrainerEmail() {
	}

	public List<special_event_booking__c> getBookings() {
        bookings = [select id, name, Primary_Booking__c, contact__r.name, contact__r.email, contact__r.phone from special_event_booking__c where special_event__c =: eventId];
		return bookings;
	}
    
}