src/objects/Subscription__c.object
<CustomObject>
    <description>Object to manage subscriptions (Memberships, Complywise Subscriptions and other ongoing product deliveries)</description>
    <fields>
        <fullName>Auto_Create_Sales_Invoice__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Default TRUE, if this is unchecked the automated renewals will not create an invoice</description>
        <inlineHelpText>Uncheck this box if you do not want an invoice created for this subscription on the first reminder date</inlineHelpText>
        <label>Auto Create Sales Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Renewal_Objects_on__c</fullName>
        <description>Calculates date renewal objects will be created based on longest reminder days</description>
        <formula>IF 
(
   Includes_SUSA_Product__c = True, 
   (End_Date__c - Longest_Reminder_Days__c) - 35,

   IF ( 
      Includes_E_Delivery_Product__c = True, 
      (End_Date__c - Longest_Reminder_Days__c) - 45, 
      (End_Date__c - Longest_Reminder_Days__c) - 7
      )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The date on which the subscription with automatically create the renewal opportunity &amp; subscription etc..</inlineHelpText>
        <label>Create Renewal Objects on</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Reminder_Date__c</fullName>
        <formula>IF(  Subscription_Value__c &gt; 0,
   IF(  ISPICKVAL(Type__c, &apos;Renewal&apos;),
      IF( ISPICKVAL(Paying_By__c, &apos;Direct Debit&apos;), Start_Date__c - 20, Start_Date__c - Longest_Reminder_Days__c),
      null
   ),
   null
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Date is only displayed if the subscription is a renewal, not paying by direct debit and the subscription value is greater than zero.</inlineHelpText>
        <label>First Reminder Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Includes_E_Delivery_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates if this Subscription contains an E-Delivery Product</inlineHelpText>
        <label>Includes E-Delivery Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_Membership_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked automatically by Workflow on creation of Subscription Line</inlineHelpText>
        <label>Includes Membership Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_Publication_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Includes Publication Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_RCP_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked automatically by Workflow on save of Subscription Line</inlineHelpText>
        <label>Includes RCP Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Includes_SUSA_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If ticked this subscription includes a SUSA subscription product.</inlineHelpText>
        <label>Includes SUSA Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This  is updated by the scheduled task which creates a renewal opportunity for subscriptions due to renew.</description>
        <inlineHelpText>Denotes when a renewal opportunity has been created by scheduled task.</inlineHelpText>
        <label>Renewal Opportunity Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Untick this box if you DO NOT wish to renew this subscription in the future</inlineHelpText>
        <label>Renewal Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Sales_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The latest Sales Proforma/Invoice that has been created for this Subscription.</inlineHelpText>
        <label>Latest Sales Invoice</label>
        <referenceTo>c2g__codaInvoice__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending - Not Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Not Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Renewing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Cancelling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Renewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapsing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended - Lapse Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current - Manual Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subsequent_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subsequent Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscriptions (Subsequent Subscription)</relationshipLabel>
        <relationshipName>Subscriptions_Subsequent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Sub Ref: Current Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ScheduleSubscriptionRenewalBatch.cls
global class ScheduleSubscriptionRenewalBatch implements Schedulable {
    
    // First Stage create subscription 
    private String subRenewalQuery = 'SELECT Id FROM Subscription__c  WHERE Renewal_Opportunity__c = true  AND Renewal_Opportunity_Created__c <> true AND Status__c = \'Current - Renewing\' AND (Includes_Membership_Product__c = true OR Includes_Publication_Product__c = true OR Includes_RCP_Product__c = true OR Includes_E_Delivery_Product__c = true OR Includes_SUSA_Product__c = true) AND Create_Renewal_Objects_on__c <= TODAY AND Subsequent_Subscription__c = null';

    // Secound Stage create subscription invoice 
    private String subRenewalInvoiceQuery = 'SELECT Id, Opportunity__c FROM Subscription__c WHERE (Status__c = \'Pending - Not Paid\' OR Status__c = \'Current - Not Paid\') AND (Includes_Membership_Product__c = true OR Includes_Publication_Product__c = true OR Includes_RCP_Product__c = true OR Includes_E_Delivery_Product__c = true OR Includes_SUSA_Product__c = true) AND First_Reminder_Date__c <= TODAY AND Renewal_Sales_Invoice__c = null AND Auto_Create_Sales_Invoice__c = true';
    
    global void execute(SchedulableContext SC) {
        
        // START: Update subscriptions that need need to be updates from "Current" to "Current - Renewing"
        System.debug('** Updating subscriptions from "Current" to "Current - Renewing" if needed');
        
        // Disable the Subscription account flag triggers. This is because the subscription
        // is still a current subscription so won't effect the flags.
        ApexCodePatrol.disable('AccountSubscriptionFlags');

        List<Subscription__c> subList = new List<Subscription__c>([SELECT 
                                        Id,
                                        Status__c, 
                                        First_Reminder_Date__c 
                                    FROM
                                        Subscription__c 
                                    WHERE 
                                        Status__c = 'Current'
                                        AND Create_Renewal_Objects_on__c <= TODAY]);

        for(Subscription__c sub : subList){
            sub.Status__c = 'Current - Renewing';
        }
        
        if (subList.size() > 0){
            update subList;
        }
        
        ApexCodePatrol.enable('AccountSubscriptionFlags');
        // END: Update subscriptions that need need to be updates from "Current" to "Current - Renewing"
        
        // START: Create new opps and cloned subscriptions
        System.debug('** running ScheduleSubscriptionRenewalBatch');
        System.debug('** subRenewalQuery: ' + subRenewalQuery);
        
        SubscriptionRenewalBatch subsRenewal = new SubscriptionRenewalBatch(subRenewalQuery); 
        ID batchprocessid = Database.executeBatch(subsRenewal, 1);
        
        // END: Create new opps and cloned subscriptions
        
        // START: Create invoice 
        System.debug('** running SubscriptionRenewalBatchInvoicesAndPacks');
        System.debug('** subRenewalQuery: ' + subRenewalInvoiceQuery);

        SubscriptionRenewalBatchInvoicesAndPacks subsInvRenewal = new SubscriptionRenewalBatchInvoicesAndPacks(subRenewalInvoiceQuery); 
        ID batchprocess2id = Database.executeBatch(subsInvRenewal, 1);
        
        // END: Create invoice
        
        
    }
    
    
}